### ISSUE TITLE
Search results: clarify "is-in" list

### ISSUE THREAD

**Issue by daganzdaanda** [openstreetmap/openstreetmap-website#1006]
A user opened this note https://www.openstreetmap.org/note/375269 because he was irritated by the way the search results are presented. He thought, the comma-seperated list of things that follow the result are nearby features (e.g. churches). 

Can we clarify the meaning of the list? 
```
Fußgängerzone Im Annahof, Innenstadt, St. Ulrich-Dom, Innenstadt, Augsburg, Schwaben, Bayern, 86150, Deutschland
```
The Nominatim result is here:
http://nominatim.openstreetmap.org/details.php?place_id=68417564

Possible solutions:

1) Add the words "Located in:" after the name of the search result and before the list of "is-ins".

2) Add the titles of the items, e.g. admin level 11: Innenstadt, St. Ulrich-Dom
This would make the list a lot longer. Using a descriptive title would be nicer, but adminlevels are not used consistently all over the world.

3) Link each part of the list to the object / relation it refers to. 
That might confuse people who mis-click when they want to follow the search result.

It would also make sense to optically separate the search result from the "tail". I would suggest to start a new line for the "is-ins" and maybe use a smaller font.

**Comment by HolgerJeromin** [comment]
The presented list is separated with comma. The name of the relation itself has an comma. IMO this is one of the main problems. What about this representation:

4) `Fußgängerzone 'Im Annahof', 'Innenstadt, St. Ulrich-Dom', 'Innenstadt, Augsburg', 'Schwaben', 'Bayern', '86150', 'Deutschland'`

**Comment by daganzdaanda** [comment]
Yes, that would make it clearer already.

**Comment by tomhughes** [comment]
It would help if you actually gave a link to the problem result...

**Comment by tomhughes** [comment]
This is a nominatim issue - we just show the "display_name" that it returns.

**Comment by daganzdaanda** [comment]
Thanks for pointing that out, I opened an issue there: https://github.com/twain47/Nominatim/issues/297
The search was https://www.openstreetmap.org/search?query=Im%20Annahof%20Augsburg#map=15/48.3675/10.8950

**Comment by daganzdaanda** [comment]
@lonvia at Nominatim sees it as a display problem (if any) and suggests

>  If the stock  display_name  is not good enough, then the website should request  addressdetails  and build it's own customized output.

I still think the results could be presented in a better way, but I don't know how to "code" it. So if someone thinks it's worth their time to figure something out, thank you :)

**Comment by tomhughes** [comment]
We're not going to start trying to write a multinational address formatter in the main web site code - that's just insane.

**Comment by lonvia** [comment]
Of course not, that wasn't the issue here. The issue was presenting the existing address list better. Things like adding links or optically separating the name from the tail can hardly be done in the text-only display_name response.

One thing that nominatim might be able to help with: if it would be useful to split the display_name into two separate field with name and address part, so that the name can be more easily optically separated, then that can be implemented. But in the end you still need to generate the actual HTML representation somewhere in the rails code.

**Comment by tomhughes** [comment]
Well (a) the suggestion as I understand it that we should take a list of address components and try and assemble them into a description (b) the Nominatim ticket referred to the need to be location sensitive to do it well and (c) isn't the whole issue here a component whose name contains a comma? So it would still fail if we just join the components with commas.

**Comment by lonvia** [comment]
`display_name` is nothing but a concatenation of the address parts with a bit of deduplication thrown in for convenience. This part the website can do by itself if it wants more fancy formatting, different delimiter etc.

I don't think the comma in the suburb was really the issue here. The original poster of the note just didn't know that there is a suburb called 'St. Ulrich Dom' (Saint Ulrich church) and assumed that the entry in the list referred to the church. No localized formatting could help with that. Well, except maybe solution 2 above but  I think we can agree that this would create a mess of overlong results that causes even more confusion. So, for what it's worth I do agree with your assessment of 'won't fix'.

**Comment by daganzdaanda** [comment]
I think solution 1) should be possible without too much hassle if Nominatim can return two fields instead of one. And with two fields, the second part could be presented in a new line with smaller font size, too. What do you think?

**Comment by HolgerJeromin** [comment]
IMO this could be done already with the parameter addressdetails=1. 
The first XML child of <place> is the main name, the rest can be concated with a comma (and stopped at country).
