### ISSUE TITLE
Improve UX for users landing /note/new directly from facebook

### ISSUE THREAD

**Issue by clkao** [openstreetmap/openstreetmap-website#1012]
Apparently facebook's map report link now goes directly to osm /note/new, without giving users much context besides this is 3rd party.  We should add some text about this being a community projects and where to learn more or start editing, for those angry people who never knew about OSM and just found their business on an incorrect map.

For referrer from facebook we can even show something about "we don't know when facebook will update their data even if it's correct here, and who they should bug"

**Comment by clkao** [comment]
Perhaps pointers to local OSM community as well.

**Comment by simonpoole** [comment]
We already have a page exactlly for that: http://www.openstreetmap.org/fixthemap FB just needs to point to it.

**Comment by tomhughes** [comment]
As @simonpoole says, the correct answer is to get Facebook to link to the correct location.

**Comment by clkao** [comment]
The links is to /note/new with the coordinates, which I think is for a good reason for users to create note at the right place, but gives user very little clue about OSM.  I don't think the fixthemap link is for such context with coordinates.

Please reopen.

**Comment by iandees** [comment]
I've reached out to a friend at Facebook that might be able to help and will update here with what I find out.

**Comment by simonpoole** [comment]
@clkao it does support lat lon so really FB simply has to point to that page see osm.ch for an example of how it works.

**Comment by clkao** [comment]
Can we add a link to https://www.openstreetmap.org/fixthemap on the /notes/new page with coordinates, if the referrer is external?

**Comment by clkao** [comment]
Thanks @simonpoole, i see that /fixthemap?lat=46.96947659374449&lon=8.369157314300537&zoom=10 works.

@landees, a friend noted that the mobile app map reporting is a completely different workflow.  we might need to make sure that links to the right place as well.

**Comment by iandees** [comment]
The Facebook team has been made aware of the /fixthemap page and they'll try to "hopefully fix [it] in the next week." :+1:

**Comment by clkao** [comment]
@landees++ :+1:

**Comment by SomeoneElseOSM** [comment]
FWIW, the location information FB are using seems to be "whatever they've currently got on file".  For example the location of this pub:

https://www.facebook.com/yorkshirepuddinghk?fref=ts

is off to the northwest of the actual location:

http://www.openstreetmap.org/node/1106670852

Presumably it's the group head office location - it looks like they own a bunch of businesses around there.  In this case "fixthemap" or an OSM note isn't appropriate, because our location's correct; it's the FB address that's "wrong" (in that it's a delivery address rather than one useful for customers).
