### ISSUE TITLE
Header too wide on small screens, in some locales

### ISSUE THREAD

**Issue by M1dgard** [openstreetmap/openstreetmap-website#1014]
Text in the header can overlap on certain screen sizes.

![toowide](https://cloud.githubusercontent.com/assets/4283376/8826508/3beab1b6-3087-11e5-86db-e990c0e12540.png)

Language shown: Belarusian (be)

May also happen when the display_name is too long (not tested).

**Comment by tomhughes** [comment]
This is well known, and there's a ticket for it somewhere (possibly in trac because I can't see it in github) but there's no really good fix.

If you make it collapse as soon as there isn't enough space for German then everybody else has it collapsing when half the width is still free. It really needs to be dynamic but nobody has ever come up with a way to do that.

**Comment by tomhughes** [comment]
The key issue here is https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/stylesheets/common.scss#L447 which controls when we collapse things to the compact view.

It's currently set to a screen width of 960px but that value unfortunately varies by language, and could change at any time as translations are updated... Sadly you can't use `calc()` in media queries to try and dynamically calculate the right value...

**Comment by M1dgard** [comment]
Maybe with some JavaScript?

It would involve getting the real width of the uncollapsed header and setting a resize event. The former seems to be an issue, as the header would have to be rendered unexpanded first. Or a dummy with all the same styles but without links could be created in the background, but that's an ugly fix.

**Comment by tomhughes** [comment]
I've put a possible fix (789195d43a3c1503d8c1444ed513521601dcc20b) up at http://tomh.apis.dev.openstreetmap.org/ if people could give it a go in different browsers and make sure it doesn't break anything...

**Comment by M1dgard** [comment]
It does.
![broken](https://cloud.githubusercontent.com/assets/4283376/8833346/43dd6f68-30ae-11e5-83ca-4e572f2b0fdb.png)

Pale Moon 25.4.1, like Firefox 31.9

**Comment by M1dgard** [comment]
In production we currently also have an intermediary state:
![intermediary](https://cloud.githubusercontent.com/assets/4283376/8833543/8ff4a974-30af-11e5-9014-82bfa3f0ff08.png)

**Comment by tomhughes** [comment]
It's the transition from full width to the intermediate state (the "compact" mode) that I have changed. The switch to the small or mobile view is unchanged.

**Comment by M1dgard** [comment]
Ah yes, that works great now. The mobile view has to be more dynamic as well though, and it actually also gets broken now. (Because the stylesheet gets overridden by the direct styling done by jQuery on lines 89 and 90.)

**Comment by tomhughes** [comment]
I've fixed it to stop the js interfering with the small view, but making the switch to the small view dynamic will be a lot more work because that's a whole style sheet full of changes selected by a media query on the link tag that loads it.

Probably we would need to do away with that and tie everything to a class on the body that can be changed by javascript to select the three modes.

**Comment by tomhughes** [comment]
Reworked it as 4dceacdeba42039a61f9bc9f56293f5652620e5b along the lines I mentioned so both transitions are now dynamic.

We may want to do something more sophisticated for the switch to small mode though as the idea there was to always use that mode on phone size devizes, though that was always hard due to modern phones having very high resolutions but physical device size media queries not actually being implemented anywhere...

**Comment by M1dgard** [comment]
Great work @tomhughes, it looks just the same as on production except that it switches just in time.
