### ISSUE TITLE
Search: I'm feeling lucky

### ISSUE THREAD

**Issue by simon04** [openstreetmap/openstreetmap-website#1039]
I often use the search to quickly pan to a specific location/city/region. Here's what I'm doing:
1. enter a search term, press enter
2. wait for the search results
3. click on the first entry
4. wait for the boundary to be loaded
5. close the sidebar

What I would like to be doing: Prefix the search term by a `!` to indicate that the first result should be displayed immediately. This is similar to Google's "I'm feeling lucky" button.

**Comment by tomhughes** [comment]
Oh come on, this is just silly.

**Comment by simon04** [comment]
If this feature were silly, why is it still placed on the Google start page?

Please don't kill a discussion just 2 minutes after a proposal not giving any kind of an objective argument! One can discuss on technical/UI/… issues, but it's hard to improve something when the discussion is stopped as a matter of you personal taste.

**Comment by tomhughes** [comment]
Well (a) we're not google and (b) as much as anything I was referring to your proposed trigger mechanism not the general idea.

To my mind this is an end user "feature" not a "mapper" feature and as such out of scope.

In any case triggering it with magic syntax is insane. If we were going to do it then it would have to be a separate button, but that has a high cost in screen real estate that I don't think we want to pay.

Yes of course I could just leave this open - it's not like anybody is actually going to anything about it anyway. But I'm really fed up with the hundreds of wishlist items in our bug tracker that nobody is ever going to implement. Leaving it open it doesn't help you (because nobody's going to magically implement it as a result) and it doesn't help us (because it reduces the signal to noise ratio).

**Comment by simon04** [comment]
"you"  vs. "us": I've been submitting a few pull requests in the past – among those, a few a still pending with or without comments. So in this case I wanted to check before putting efforts in an implementation  …

I find it discouraging that many small improvements are declined as nobody would use them or find them useful without giving them a try.

**Comment by tomhughes** [comment]
OK it's open again . Have a nice day.

**Comment by pnorman** [comment]
@simon04 How would this feature be evident to the users? They're not likely to figure it out with some hints.

**Comment by simon04** [comment]
For the UI, the following options come to my mind:
* from the search results, linking to a cheat sheet (example: https://github.com/search?utf8=%E2%9C%93&q=help, [screenshot](https://cloud.githubusercontent.com/assets/782446/9479108/04408050-4b7c-11e5-83fc-17c9ad4bde2f.png))
* show a hint ("do you know already?") in the search results (example: https://duckduckgo.com/?q=wiki+osm&ia=about, [screenshot](https://cloud.githubusercontent.com/assets/782446/9479139/2c17edca-4b7c-11e5-9f19-6ca6895d669b.png))
* show a tooltip in the search box (example: https://geizhals.eu/?cat=cpu1151, 
[screenshot](https://cloud.githubusercontent.com/assets/782446/9479158/40e716a4-4b7c-11e5-88af-2d2caf26c703.png))

**Comment by vincentdephily** [comment]
I think that implementing issue #919 (which is IMHO a good idea) would go a long way towards solving this issue (only the "close the tab" part is missing).

On its own I don't think that the ! syntax has much added value (less than on a generic search engine because we don't expect to leave osm.org). But if were were planning on extensions like "in viewport" and simple overpass-like searches, it could become interesting. I know, lots of ifs, sorry.

**Comment by gravitystorm** [comment]
I think with the fix in #919, the main purpose of this suggestion has been resolved.
