### ISSUE TITLE
user changeset atom feed lacks a title

### ISSUE THREAD

**Issue by vincentdephily** [openstreetmap/openstreetmap-website#1051]
The output of '/user/$SOME_USER/history/feed' doesn't have a title for the feed itself (the individual articles are fine), resulting in a blank name when adding the feed to (most ? all ?) feed readers :

    $ wget -qO- 'https://www.openstreetmap.org/user/Outdoor Escape/history/feed?bbox=undefined' | grep title
    <title/>
      <title type="html">Changeset 33780784 - Removed /?page_id=73 search from the URL, this search pointed to the homepage already</title>

The feed title should be something like "Changesets of $USERNAME" or even just "$USERNAME".

I'm only filing an issue now but this has bugged me for a while, having to manually set a name for each feed :)

**Comment by sonalkr132** [comment]
This is because `@title` for feed request is never set. [Here](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/changeset/list.atom.builder#L5) `@title` is nil:
```
 feed.title @title
```

On html request `@title` is set [here](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/changeset/history.html.erb#L8-L20):

```
  if params[:friends] and @user
     set_title(t 'changeset.list.title_friend')
     @heading = t 'changeset.list.title_friend'
   elsif params[:nearby] and @user
     set_title(t 'changeset.list.title_nearby')
     @heading = t 'changeset.list.title_nearby'
   elsif params[:display_name]
     set_title(t 'changeset.list.title_user', :user => params[:display_name])
     @heading = t('changeset.list.title_user', :user => link_to(params[:display_name], :controller => "user", :action => "view", :display_name => params[:display_name])).html_safe
   else
     set_title(t 'changeset.list.title')
     @heading = t 'changeset.list.title'
   end
```

Can't all that logic be moved to a helper function which can be called from both history.html.erb and list.atom.builder?

**Comment by polarbearing** [comment]
My Mozilla/Seamonkey complains that this feed is invalid because it lacks the title, and refuses to subscribe it. The Mozilla folks [refuse to fix it](https://bugzilla.mozilla.org/show_bug.cgi?id=1090207) as they say it's the publisher's fault.
