### ISSUE TITLE
OSRM: Zoom level 14 causes loss of precision for very close-by locations

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1077]
Please compare the following two OSRM routing results for the same start/end location:

* [OSRM routing result on OSRM project site](http://map.project-osrm.org/?z=18&center=51.859235%2C6.499635&loc=51.859563%2C6.500167&loc=51.859387%2C6.498863&hl=en&ly=&alt=&df=&srv=)

![d21](https://cloud.githubusercontent.com/assets/5842757/10711977/4518111c-7a8c-11e5-82b0-2d972dd82fd2.png)

* [OSRM routing result on OSM web site](http://www.openstreetmap.org/directions?engine=osrm_car&route=51.85956%2C6.50017%3B51.85939%2C6.49886#map=19/51.85923/6.49963)

![d22](https://cloud.githubusercontent.com/assets/5842757/10711978/499560f0-7a8c-11e5-9c65-a59aa84ffa85.png)

Issue: while the OSM website calls OSRM router with zoom level 14, the OSRM project site on map.project-osrm.org calls the OSRM router a second time with zoom level 18. By using zoom level 18, the routing results look more reasonable and in this specific case avoid a navigation right through a playground via car.

If you watch very closely, map.project-osrm.org actually triggers 2 routing calls: one with zoom level 14 and a second one with zoom level 18. I guess this additional step is somehow triggered if objects are very close to each other. I would assume that a similar logic needs to be put in to place on osm.org as well, to get similar results.

Just for clarification: when I talk about zoom level, I actually refer to the [parameter **z=** in the viaroute call](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#query-2), like in the following example: `/viaroute?z=14&output=json&instructions=true&loc=51.85956%2C6.50017&loc=51.85939%2C6.49886`

This topic was originally discussed on the [German OSM forum](http://forum.openstreetmap.org/viewtopic.php?id=52467)

**Comment by tomhughes** [comment]
They offer an API and we use it. We really shouldn't have to try and guess and re-call it with different parameters based on something that you can't even describe clearly.

This sounds like an issue that should be fixed upstream in OSRM.

**Comment by mmd-osm** [comment]
I'd like to ask you to reopen this ticket and further evaluate this topic for the following reasons:

* http://map.project-osrm.org already has some client side javascript code to deal with this situation. This code is just another consumer of the OSRM backend `viaroute` call, like the osm.org site, but it properly deals with the issue. If additional input is needed, I would suggest to contact the OSRM project for additional support.

* The OSRM server component works as expected here, providing the `z=` parameter is a feature rather than a bug.

To my understanding, this is not an upstream issue, but simply a not quite perfect implementation of `viaroute` calls on the osm.org part.

Thanks for considering this.

**Comment by tomhughes** [comment]
Well if you could actually explain what it is you want, and why you think it is the correct solution then we could consider it, but currently you proposal amounts to "if unspecified thing happens retry at higher zoom".

Before we can even consider it we need a definition of what the trigger condition is.

Even better would be to understand what the problem is and why retrying at high zoom fixes it so that we can consider if there is a better solution.

If we wanted to just copy what the OSRM site does then we would just have used their code in the first place rather than writing our own.

**Comment by mmd-osm** [comment]
Well, this issue has originally been raised by a newbie: in his words: when I calculate a route on osm.org from:
* 1, Mersmannstraße, Bocholt, Kreis Borken, Regierungsbezirk Münster, Nordrhein-Westfalen, 46399, Deutschland

to

* 6, Die Liene, Bocholt, Kreis Borken, Regierungsbezirk Münster, Nordrhein-Westfalen, 46399, Deutschland

OSRM will route me through a playground. [here's the link to osm.org](http://www.openstreetmap.org/directions?engine=osrm_car&route=51.85956%2C6.50017%3B51.85939%2C6.49886#map=19/51.85923/6.49963).

Next thing I did was to check the same route on the OSRM Project site: [here's the link](http://map.project-osrm.org/?z=18&center=51.859235%2C6.499635&loc=51.859563%2C6.500167&loc=51.859387%2C6.498863&hl=en&ly=&alt=&df=&srv=)

And then magic happens: osm.org did get it wrong: routoing right through the playground, while map.project-osrm.org avoided routing via the playground. See both screenshots I posted above.

BTW: it's really not a data issue as well - otherwise map.project-osrm.org would also produce incorrect results.

That's basically the issue. (let's start with that for the time being, without talking about possible solutions yet).

Do you buy this story so far? If not, what exactly is still unclear to you? Take the time to really visit both links and compare the results. That's really essential to understand the issue, imho.

**Comment by woodpeck** [comment]
[Way 374556245](http://www.openstreetmap.org/way/374556245) was last modified around the time you reported this issue. It is possible that not all routing graphs are updated to reflect the current situation; suggest to wait a while and check again. -- OSRM ignores smaller roads above a certain zoom level and goes bee-line to the next larger road so this "routing through a playground" you describe is not really routing through a playground but rather a route that starts a bit away from your desired starting point; on the Project-OSRM site these "connectors" are shown in a different line style.

**Comment by tomhughes** [comment]
It hasn't actually "routed through the playground" actually. The route, as described, is to follow "Die Liene" it's just that because that name continues around a right angled corner it regards it as a single segment and hence when it simplifies the graphical version of the route (as it does at lower z values) it treats that as a single segment in the graphical rendering.

So the real solution is that OSRM should realise that at a four way junction with three roads called "Die Liene" like that and a 90 degree turn that it really ought to treat that as a turn to be announced, which would also fix the rendering.

The solution for us is probably just to use a larger Z value - if that is supposed to be the zoom (what does the OSRM doco say?) then why are we always passing 14 there?

I don't see some attempt to refetch at higher Z as a sensible solution, especially as you still haven't managed to say what the criteria should be for making that decision...

**Comment by systemed** [comment]
osm.org specifies a constant zoom level of 14 because OSRM is more likely to find a route that way: https://github.com/Project-OSRM/osrm-backend/blob/develop/data_structures/static_rtree.hpp#L580

At z15 and above, OSRM will potentially snap onto a "tiny component", i.e. a small, unconnected piece of routing graph from which you can't route anywhere else. At z14 and below, tiny components are ignored.

You could take the view that tiny components are actually useful for debugging routing errors in OSM, of course, but weighed against that is the consistently worse user experience of routing when a significant proportion of queries fail.

I thought that there was a plan to break out the "tiny components" detection into a separate parameter, but looking at the OSRM source it still appears to be hardcoded to z<=14.

**Comment by danpat** [comment]
As usual with OSRM, things are more complicated than that :-)

Calls to `/viaroute` use this logic for tiny components:

https://github.com/Project-OSRM/osrm-backend/blob/develop/plugins/viaroute.hpp#L125-L155

That logic was added in Dec 2014, so it might be newer than osm.org's decision to use Z14.

Anyway, long story short, calls to `/viaroute` will attempt to select common connected networks for potential viapoint snapping, the `z=` parameter doesn't affect it at all.  There is no reason for `osm.org` to stick to `z=14` any more, except for the bandwidth savings achieved by line simplification that adding a `z=` parameter triggers.

The `/locate` plugin still uses the method that @systemed referred to, but `/viaroute` does not.

**Comment by systemed** [comment]
Aha, that's good.

> That logic was added in Dec 2014, so it might be newer than osm.org's decision to use Z14.

Indeed - the initial PR for routing on osm.org was in March 2014: https://github.com/openstreetmap/openstreetmap-website/pull/716 .

Thinking it through today, I'm still sceptical about rerequesting whenever the user zooms/pans, but I wonder if osm.org should perhaps select zoom level based on great-circle distance between start and end points: z14 is probably a reasonable default for a trans-America route, z18 is probably good for home-to-shops. A compromise, yes, but perhaps a reasonable one.

**Comment by mmd-osm** [comment]
Thanks everyone for your feedback on this issue! The proposal made by @systemed sounds indeed plausible to me. Maybe this is even better than constantly recalculating routes when zooming. The best threshold distance for switching between different z= levels might need a bit of trial and error, though.

Now that the ticket is still somehow  in status `closed`, I wonder how to proceed from here.

**Comment by tomhughes** [comment]
Personally I don't see a problem with rerequesting on zoom (other than that it's a bit of a pain to do) as OSRM is nice and fast.

**Comment by mmd-osm** [comment]
With the introduction of a new OSRM API version in August 2016, this issue no longer occurs. Closing.

**Comment by mmd-osm** [comment]
With the introduction of a new OSRM API version in August 2016, this issue no longer occurs. Closing.
