### ISSUE TITLE
Extract API to a separate gem

### ISSUE THREAD

**Issue by phlegx** [openstreetmap/openstreetmap-website#1097]
Hi! Would it make sense to extract the OSM API code to a separate gem?

**Comment by tomhughes** [comment]
General discussion normally takes place on the mailing list, but in any case https://github.com/zerebubuth/cgimap-ruby is a project to do exactly that.

**Comment by tomhughes** [comment]
To explain in a bit more detail, the API code here is not actually for all the calls on the production site - we have been gradually moving them to https://github.com/zerebubuth/openstreetmap-cgimap which currently runs as a separate service accessed via FCGI with the frontend web server deciding whether to send calls there or to rails.

The https://github.com/zerebubuth/cgimap-ruby project aims to give rails direct access to the code in cgimap rather than having it run as a separate service.

If you want to help with all this right now, then openstreetmap-cgimap is the place to go - we need help to move more API calls to that.

**Comment by phlegx** [comment]
Hi @tomhughes! Thank you for the reply. So, actually the production site of OSM uses cgimap?

**Comment by tomhughes** [comment]
For those queries which it supports, yes - basically https://github.com/openstreetmap/chef/blob/master/cookbooks/web/templates/default/apache.backend.erb#L59 is the relevant configuration that chooses which calls to send to cgimap.
