### ISSUE TITLE
Error 500 when clicking on Smart Bookmark

### ISSUE THREAD

**Issue by SarahTehCat** [openstreetmap/openstreetmap-website#1101]
I posted about this bug on the IRC channel `#osm` and was suggested to report it on `#osm-dev` as well as here. 

### Issue

You can bookmark the OSM search field as a search tag, and substituting `%s` with a search term or using the assigned keyword in the URL bar will work as expected. However, whilst on most other sites clicking on the bookmark itself will merely result in a search results (or equivalent) page with nothing but `%s` in the search field, doing so on OSM will yield an `HTTP 500` error.

(This feature is known as a *Smart Bookmark* (aka *Smart Keyword*). Basically, say if you designate the keyword `osmmap` for OSM's search function, if you type into the URL bar the string `osmmap toledo, ohio, usa`, it will automatically search the site itself through that. It's basically the `site:` operator minus the search engine being the one to show the results page.)<sup>1, 2</sup>

### What I've Tried

- Whitelisted OSM in NoScript. *Result*: Problem persists.
- Tried it in Safe Mode in Firefox. *Result*: Problem persists.
- Tried it in Incognito Mode in Chrome. *Result*: Problem persists.
- IRC user `@chippy` tried it on their computer. *Result*: Problem persists.

### Screenshots:

- *Firefox (Normal Mode)*: https://i.imgur.com/ISdkhu9.png
- *Firefox (Safe Mode)*: http://i.imgur.com/zg39S7l.png
- *Chrome (Incognito Mode)*: http://i.imgur.com/7WSe4L8.png

### Specs<sup>3</sup>

- *Make & Model*: Dell Inspiron N5010
- *Operating System*: Ubuntu 15.04
- *Firefox Info*: v42.0 ("Mozilla Firefox for Canonical – 1.0") (Stable Channel)
- *Chrome Info*: 46.0.2490.86 (Official Build) (64-bit)

### Notes

1. [Firefox Smart Bookmarks](https://support.mozilla.org/en-US/kb/how-search-from-address-bar)
2. [Wikipedia, *Smart Bookmarks*](https://en.wikipedia.org/wiki/Smart_Bookmarks)
3. I don't know the specs of `@Chippy`'s setup.

**Comment by tomhughes** [comment]
So the substance of what you're saying is that you invented a URL and it didn't work and you think that's a bug?

It's not like we have a search page we can send you to when you do a search with no query string... I mean you've given us a vast amount of redundant information but I don't think you've said what you think the site should do when asked to do a search for nothing?

**Comment by malenki** [comment]
I see no point whatsoever in adding a search URL without search string as a bookmark.

Since all modern browsers support user defined search engines you should add the OSM search this way to your browser. 
Just right-click into the search box, select "add search engine" (Chromium) or "add keyword for search (Firefox), select a matching shortkey (maybe osm) and be done. 
Now creating a new tab (ctrl-t) and typing "osm Çorovodë" will search at osm.org for Çorovodë and display the results.
No need to fiddle with a mouse. :)  
hth

**Comment by danstowell** [comment]
Possibly people are mis-reading @SarahTehCat's description? It's not about a "search with no query string". The OP describes it as a feature where the query string is filled in from user text in the location bar, in a similar way as @malenki's description. I'm not familiar with the functionality so I don't know if it's exactly the same.

**Comment by danstowell** [comment]
Actually I don't know if I've understood it right or not :/

**Comment by HolgerJeromin** [comment]
Long story short: 
If you want to define the search url by hand you (at least i got this a year ago) get the osm.org/search?... url which does not work. 
If you save the search with the tools of the browser the whole search works and interestingly chrome is showing me the same `http://www.openstreetmap.org/search?query=%s` query in the settings.

**Comment by openstreetmap-website** [comment]
I read it as a complaint that the error if the query term is omitted, is
somewhat unfriendly. Other sites do a search for "%s" (which probably
isn't that useful but it's a start) but OSM just returns a 500. 

On 2015-12-06 21:54, danstowell wrote

> Actually I don't know if I've understood it right or not :/ 
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> _______________________________________________
> rails-dev mailing list
> rails-dev@openstreetmap.org
> https://lists.openstreetmap.org/listinfo/rails-dev
 

Links:
------
[1]
https://github.com/openstreetmap/openstreetmap-website/issues/1101#issuecomment-162346651

**Comment by SarahTehCat** [comment]
@tomhughes: You misunderstood my post. I didn't invent anything. I created the bookmark in the exact same way as @malenki and @danstowell stated above. This is an issue that is definitely a bug because smart bookmarks are a basic feature that work with most other sites I've ever used them on (which has been a lot) and not once have I ever run into a site which gives a 500 error. 

You know, maybe I have you wrong, but I've noticed you being particularly nasty or rude to other users about features/thoughts/etc. that you disagree with. You did it with @emacsen on [2012-10-11](https://github.com/openstreetmap/openstreetmap-website/issues/130) (even @tmcw [called you out on it](https://github.com/openstreetmap/openstreetmap-website/issues/130#issuecomment-9362168), you did it with @simon04 both on [2012-11-12](https://github.com/openstreetmap/openstreetmap-website/issues/157) and [2015-08-24](https://github.com/openstreetmap/openstreetmap-website/issues/1039), and you did it with @welterkj on [2014-06-25](https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/50), and these are just the ones I've stumbled across when searching if there was a duplicate of this question!

Seriously, with all due respect, why don't you learn to be a bit nicer, or at least a bit less rude?

@malenki: That's exactly what I did. I right-clicked in the OSM search bar, selected "Add keyword for search", and boom, that's how the bookmark is created. 

@danstowell: Spot on, my friend. [nod] :)

**Comment by Zverik** [comment]
Not sure why do you need `%s` query string to show anything correct. The URL is incorrect (since `%s` is an incorrect sequence, it should be screened), hence the error. I presume using this bookmark with a search string yields correct page? I've been using custom searches with osm.org for two years now, in Opera and Firefox, with no issues.

**Comment by tomhughes** [comment]
@SarahTehCat I obviously misunderstood - like I said it wasn't entirely clear what exactly it was you had done.

**Comment by tomhughes** [comment]
So to get back to basics and understand what the problem is hear can you clarify exactly what you mean by "bookmark the search field" because I suspect different people here are understanding in different ways.

I think at least some people assume you mean that you used the OpenSearch support to select OSM from the browsers search drop down and "add it" as a permanent search engine but I suspect that probably isn't what you meant?

**Comment by tomhughes** [comment]
Incidentally my original thought was that you had manually added a keyword bookmark, which is why I thought you should get to keep the pieces if it broke. I've done that for various bits of the site but I know they break if I forget the argument.

I now see that Firefox at least offers to do it for you from the right click menu so I guess that is probably what you did? I'm not sure how it decides to offer that because it doesn't do it for every field and it can't know that it will work with no argument.

Anyway the only question now is, what should it do? I just tried it on one site and sent me to a search page, but we don't have that.

**Comment by tomhughes** [comment]
I'm even more confused now... I just used the right click menu to "add a keyword for this seach" and then typed the keyword into the URL bar with no argument.

I got taken to "http://www.openstreetmap.org/search?query=" which showed me the map, with the search bar open and a search done with some basically random results.

So it sounds like this really is something very odd!

**Comment by tomhughes** [comment]
So I can see that visiting "http://www.openstreetmap.org/search?query=%s" does error in the way you describe, but I can't get my browser (Firefox 42 on linux) to actually do that. My bookmark looks like:

![screenshot from 2015-12-07 07-31-44](https://cloud.githubusercontent.com/assets/147741/11621522/d4a9747a-9cb4-11e5-8557-feca0a6bbb46.png)

and typing "os" in the URL bar replaces the %s with the empty string.

**Comment by tomhughes** [comment]
Aha! Visiting the URL by clicking in the bookmark menu does it.

**Comment by Zverik** [comment]
I think this is more of a Firefox bug than ours.

**Comment by tomhughes** [comment]
Well you're probably right, but at least one other site I just tried somehow manages to search for "%s" when you do it.

**Comment by Zverik** [comment]
Maybe [this could help](https://github.com/cfabianski/rack-uri_sanitizer).

**Comment by tomhughes** [comment]
I think we have to use something like that yes because it seems that `Rack::Utils::InvalidParameterError (invalid %-encoding (%s))` is being thrown, likely in the rack stack before rails gets control.
