### ISSUE TITLE
blog: partly endless redirects

### ISSUE THREAD

**Issue by malenki** [openstreetmap/openstreetmap-website#1109]
When trying to look at several entries at blog.openstreetmap.org some cannot be shown due to "too many redirects" reported by the browser.
Examples:
https://blog.openstreetmap.org/2012/01/18/ulf-m%c3%b6ller-1973-2012/
https://blog.openstreetmap.org/2012/03/08/welcome-apple/
Tested with Chrome, Chromium and FF.

**Comment by tomhughes** [comment]
That's not the openstreetmap web site.

**Comment by malenki** [comment]
blog.openstreetmap.org looks to me like it belongs to openstreetmap.org.
If it doesn't, where should I beg for a fix then? The blog itself lacks any contact information.

**Comment by tomhughes** [comment]
If the issue can't be fixed by changing code in this repository then the issue doesn't belong here.

There isn't really an issue tracker for the blog any more than there is for most blogs. The "admin" component in trac is probably about the best bet, but as far as I can tell it's wordpress doing the redirection anyway, so it's not really in our control.

**Comment by malenki** [comment]
Thanks.
