### ISSUE TITLE
Export to PDF/PNG of Transport Layer shows Standard Tiles

### ISSUE THREAD

**Issue by petzlux** [openstreetmap/openstreetmap-website#1141]
when i try to use the export functionality to create a map of the transport layer , the resulting pdf/png shows the wrong basemap, ie the standard one, instead of the transport layer tiles.

**Comment by woodpeck** [comment]
This is a frequent misunderstanding on help.openstreetmap.org as well. Because only the standard layer is actually rendered on the OSM hosted system, only the standard layer can be exported; all other layers are rendered elsewhere and are not exportable. The export feature should be grayed out when any layer but the standard layer is selected.

**Comment by tomhughes** [comment]
It does say "Image will show standard layer" you know ;-)

**Comment by d1g** [comment]
@tomhughes, based on what woodpeck said, the best options would be to disable image export controls using simple JS code (with check for current layer) when layer isn't equal to standard

As bonus remove unnecessary text about "Standard" layer for simplicity (so only people with wrong layer are to read this warning)

There shouldn't be a warning if user does things right :)
