### ISSUE TITLE
german translation of "Relation"

### ISSUE THREAD

**Issue by Haikuch** [openstreetmap/openstreetmap-website#1142]
the english term "relation" has recently been translated to "Bezüge" in the german version of the osm.org changeset view. 
The original word "Relation" was perfectly fine and is also common in german, technical/mathematical, fields. The new word sounds horrible and will create misunderstandigs.

**Comment by polarbearing** [comment]
As I understand, the translations come from Translate wiki. It appears that there was a change from ```Relation``` to ```Bezug```, and grammatical variations, on [13 Dec 2015](https://translatewiki.net/w/i.php?title=Osm%3ABrowse.relation.title%2Fde&action=historysubmit&type=revision&diff=6589727&oldid=5176624). It appears to me that the translator [runs](https://translatewiki.net/w/i.php?title=Special:Contributions&offset=20151213230904&limit=500&contribs=user&target=Predatorix&namespace=) through a lot of quite heterogeneous projects, most far away from OSM, and does many changes without really understanding the context of his translations. Many of them I probed there were regressions.

**Comment by tomhughes** [comment]
As you have already discovered, this needs to be fixed on TranslateWiki, not here.

**Comment by tomhughes** [comment]
See http://wiki.openstreetmap.org/wiki/Website_Internationalization#How_to_translate for more information on how translation is handled.

**Comment by polarbearing** [comment]
Currently working on revising the translations of the mentioned translator.

**Comment by polarbearing** [comment]
@siebrand - it seems that you maintain the localisation updates from translatewiki. The bug reported above was part of a major regression in German translation, which was fixed in a [joint effort](https://translatewiki.net/w/i.php?namespace=1222&translations=only&users=&trailer=%2Fde&days=30&limit=500&title=Special%3ARecentChanges) last night, along with further consistency improvements.

Thus it would be good if you could import that soon. Thanks. 

@tomhughes - the link on the wiki page you mentioned to "See Committing to the rails port", redirecting to "Rails port/Development" is broken.

**Comment by siebrand** [comment]
Nice work, @polarbearing. Please have a look at the "Review" mode, so you can check all translations for OpenStreetMap. Many have already been checked and approved once, but some translations for German haven't been reviewed (could be those are your recent translations/updates): https://translatewiki.net/w/i.php?title=Special:Translate&group=out-osm-0-all&language=de&action=proofread

Running exports now, should be committed in a few minutes.
