### ISSUE TITLE
Map editor popup (tutorial / start editing) pops up every time

### ISSUE THREAD

**Issue by jancborchardt** [openstreetmap/openstreetmap-website#1162]
Currently every time I want to edit on OSM.org, this modal asking me if I’m interested in a tutorial (or just want to start editing) pops up every time. Yes, the new editor is awesome and no, I don’t need a tutorial. ;) At some point in the past I’m pretty sure I did the tutorial and it probably helped me. But now the popup is annoying – every time.

TL;DR: Only show this popup _once_ for a user. When I click »Edit« in the top bar, I want to directly edit. (I assume the tutorial can be accessed otherwise anyway if it’s needed later.)

**Comment by tomhughes** [comment]
So firstly, that's part of iD so you would need to raise it at https://github.com/openstreetmap/iD/issues rather than here.

But secondly, it does only show it once normally, so there's obviously something odd about your setup that is preventing that - as best I can see from the source it looks like it relies on storing a flag in HTML5 local storage so maybe you are blocking that?

**Comment by bhousel** [comment]
Yes, to echo what @tomhughes said, iD stores some settings in your browser's `localStorage` area.  If you have disabled this feature or are browsing in incognito mode, you might see the introductory popup every time you use iD.  

If you still have an issue with this, please open an issue on the iD project page with some details about which browser you are using.

**Comment by jancborchardt** [comment]
Thanks for pinting me in the right direction – wasn't sure which component this is part of. Opened https://github.com/openstreetmap/iD/issues/3002 as I think the issue still stands and there could be a better solution than using impermanent local storage.
