### ISSUE TITLE
auto-delete oauth tokens after X time

### ISSUE THREAD

**Issue by Haikuch** [openstreetmap/openstreetmap-website#1201]
oauth tokens are currently kept for ever, even when a fresh one has been created for an application. The data can be used to track my app using behavior. Since the data is technically not neccessary, it should be automatically deleted after X time and anyway when a fresh token is created for the same application.

**Comment by tomhughes** [comment]
We have no way of know when an application is the same. For example every installation of JOSM looks the same to us, so if you use JOSM from several different computers you will have several different JOSM tokens all of which are in use and none of which should be deleted.

So your theory that the data is "technically not necessary" unfortunately fails I'm afraid.

**Comment by Haikuch** [comment]
but why is it neccessary to keep 4 year old tokens?

**Comment by tomhughes** [comment]
Well to start with I don't believe we record when tokens are used, so we only know when they were created, not when they were last used.

Even if we did, how long should we wait? After how many months or years is it OK to make somebody reauthenticate? How many users will get annoyed and leave if we do that? How many will get annoyed and leave if we don't? These are all difficult questions with no good answer, but as there is little cost to keeping extra tokens around it seems better to err on the side of keeping them.

As tokens are associated with an account deleting them won't stop us tracking you, because we will still know when you create new tokens. Being able to track the edits you make is exactly why we make you authenticate after all!

**Comment by Haikuch** [comment]
of course, there is no doubt that using one account for several applications isnt free of tracking. Its just annoying to see, that I can read my behavior of using external applications since I registered to OSM. I can see, how I was using frequently different apps and at what daytime.

And thats because, and there is the problem with our different points of view, I keep cookies only for one browser session. That means, anytime I use the services I get a new token that will stay in my account until revolution, or I delete them manually. Oh, and the reason I delete all my cookies after session is because I dont like to be tracked by sites :) (and to train password typing by the way...)

Anyway, I see there are technical reasons to keep the tokens because users keep logged into the apps over days and weeks. Best way would be, to give users the opportunity to set token-lifetime and to choose how many tokens for a single app are allowed.

And at least, please add a button to revoke all tokens, because deleting tokens of 4 years one by one is a pain *** :)

**Comment by HolgerJeromin** [comment]
related to #1074
