### ISSUE TITLE
changesets API call with time range does not work as expected

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/openstreetmap-website#1204]
Again, I am not sure if this is a bug but I do not see a meaningful usecase for the current implementation of the following:

For the API call `changesets?time=date1,date2`, the parameters have the following meaning:
**`date1`**: closed after
**`date2`**: created before

So this reads as _"Find all changesets that have been created before X but closed after Y"_.
As someone already noticed in the [API 0.6 wiki documentation](http://wiki.openstreetmap.org/wiki/API_v0.6#Query:_GET_.2Fapi.2F0.6.2Fchangesets), this does not really make sense and certainly is not what one would expect.

What one would expect is that this selects a time range, i.e. _"Find all changesets that have been created after X and closed before Y"_ - 
**`date1`**: created after
**`date2`**: closed before

What makes sense and what does not make sense aside, this should only be changed if the current behavior is deemed to be a bug since the API should stay consistent in its behavior.

**Comment by tomhughes** [comment]
Are you sure that's what it means? If that is what it's doing then I think it's entirely an accident and not an official part of the API.

**Comment by tomhughes** [comment]
Hmm apparently that is what it means. I'm not sure we can change it now though, at least not without bumping the API version.

Certainly I don't think we can make the change you're suggesting as it would be inconsistent with the case where only one time is supplied, which currently selects everything closed after that time.

**Comment by tomhughes** [comment]
Looks like @zerebubuth introduced that in b875d14b7cd13432b0683ca548b341dcd8bddf80 so I'll leave him to comment on the logic behind it.

**Comment by zerebubuth** [comment]
The logic _should be_, although it's always possible that there are bugs, that changesets are time ranges; a changeset may contain edits with timestamps between its `created_at` and `closed_at` times. The query window is _also_ a time range, and the purpose of that clause was to find changesets overlapping the query window, so we need to test the maximum extent of the changeset time range, `closed_at`, against the minimum extent of the query window, `from`, and the minimum extent of the changeset time range, `created_at`, against the maximum extent of the query window, `to`.

As an example, consider:

1. Changeset 1, created at 1pm and closed at 2pm,
2. Changeset 2, created at 3pm and closed at 4pm.

Let's imagine we want to query for all changesets which might have been active between 1:30pm and 3:30pm, then we need to include both changesets 1 & 2.

All that being said, last time I checked usage stats, the changesets query API was hardly used. Partly, I suppose, because it was always a bit slow. But mainly that querying changesets rather than changes has turned out to be of limited usefulness. Instead we've got systems like overpass and OWL<sup>†</sup>, which query the changes directly. I think the changesets query API is a good candidate for removal at the next API revision.

†: for some values of "got".

**Comment by westnordost** [comment]
I had to read your explanation a few times to grasp the logic/use case you present, I find it very hard to understand.

So, the use case _"get all changesets that were open at some time between 1:30 PM and 3:30PM"_ translates to
_"created before 3:30PM but closed after 1:30PM"_ (-> `changesets?time=1:30PM,3:30PM`)

So the difference between the current implementation and the one that I expected is that the current implementation is "greedy", returning any changesets whose time being open merely overlap with the specified time range while the one I expected would only return changesets whose time being open were fully within the specified time range.

Okay, I get it. I think then we can establish that this is not a bug and indeed the current implementation returns a meaningful result - simply the documentation needs to be updated to explain it better.

**Comment by westnordost** [comment]
Which I will do now

**Comment by zerebubuth** [comment]
Thanks! And apologies for not having documented, commented or explained it better the first time around - the code is pretty opaque :confused:
