### ISSUE TITLE
Increase cachablility for individual OSM elements on the API

### ISSUE THREAD

**Issue by emacsen** [openstreetmap/openstreetmap-website#129]
Currently, OSM objects in the API appear at /api/.../{node|way|relation}/id

and there is /api/.../{node|way|relation}/id/version

A specific object version is immutable. Once an object is set, it cannot be modified under the same version.

This means that this url is completely cachable. I believe we specify that cacheablity now in the headers, if not- we should.

Unfortunately, most per-object calls do not include the version number, so they cannot be cached.

I suggest that the non-versioned call return a HTTP 303 (See Other) call which directs the http client to the current version.

This would also effect the .../full call, which would need to be modified sightly to support the new format.

**Comment by mmd-osm** [comment]
This issue is now 7 years old, we have > 6 billion objects in the database today (and even much more object versions).

Rather than requesting one object at a time (where in theory caching would still be an option), people should be using one of the available bulk interfaces to request many objects in a row. Even better, don't use the API at all, if you're not planning to use the data for editing purposes 

Let's close this issue. It's no longer relevant in 2019.
