### ISSUE TITLE
paginated browsing has disappeared from user changeset list

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/openstreetmap-website#1323]
I occassionally used to browse to older changesets of specific users. (osm.org/user/username ->edits).
Now I just discovered that it has become virtually impossible to browse older changesets when a user has performed more than a handful of edits, because the pagination has been replaced by a "load more" button. This is NOT an alternative. Have you ever tried to reach the first changesets of someone with 7000 changesets? This would now involve 350 times clicking on "load more" and waiting for the response. Also it will increase load on the server. Please do not remove features that "work".

**Comment by tomhughes** [comment]
Unfortunately they don't "work" for the poor server that in order to find page 7000 has to search through the preceding 6999*pagesize changesets.

Basically traditional paging is not sustainable on large datasets because each page is slower and slower to access as it has to read through the data for all the previous pages first and the simple fact is that no real person is actually going to browse through 7000 pages!

Presumably what you are really doing is binary searching by manually editing the URL to find the page which covers a particular date range you are interested in. Which puts you in the 0.001% of users that would have any idea how to do that.

The real solution, if I am right about what you are doing, is to add better methods to search for changesets by a given user in a given date range (which the server can do efficiently) not to bring back paging.

**Comment by dieterdreist** [comment]
2016-10-13 11:22 GMT+02:00 Tom Hughes <notifications@github.com>:

> Unfortunately they don't "work" for the poor server that in order to find
> page 7000 has to search through the preceding 6999*pagesize changesets.
>


ok, didn't know this, and it's likely a good reason to abandon the old way
(at least for the "default user", i.e. 99,999 % of all users)


> Basically traditional paging is not sustainable on large datasets because
> each page is slower and slower to access as it has to read through the data
> for all the previous pages first and the simple fact is that no real person
> is actually going to browse through 7000 pages!
>

yes, but this is what I would have to do now, because there is only one
"load more" button, while before I could have skipped the first 300 pages
in one go (by editing the url).


> The real solution, if I am right about what you are doing, is to add
> better methods to search for changesets by a given user in a given date
> range (which the server can do efficiently) not to bring back paging.
>

yes, this would be even better of course.

**Comment by tomhughes** [comment]
Yes, but the "Load More" button doesn't work using page counts - it passes a `max_id` parameter so that the next set can be loaded using the index on the ID without having to read through all the preceding records.

The problem is that is only loaded as a partial, so isn't something you can put in the main URL. You can see what I mean by hitting something like http://www.openstreetmap.org/user/TomH/history?list=1&max_id=1000000 which gives you just the HTML fragment that loads in the side bar.

**Comment by polarbearing** [comment]
The problem is being discussed in some other issues already, e.g. #568, see also #1089.

As for the time-range api call, is there a user interface for that? Is there already a URL format defined for that on this website? #1204 mentions an implementation in b875d14b7cd13432b0683ca548b341dcd8bddf80 - how is that being used?

**Comment by tomhughes** [comment]
@polarbearing that is just an API call - we don't provide any interface to it.

The web site should probably be recoded to use the API instead of loading partials (we'd need to add max_id style querying to the API call) and then it could expose the ability to search the axes the API supports.
