### ISSUE TITLE
"At the end of the street turn left" instruction provided in Russian

### ISSUE THREAD

**Issue by IknowJoseph** [openstreetmap/openstreetmap-website#1325]
As per title, the instruction "At the end of the street turn left" is being provided in Russian:

![screenshot from 2016-10-14 13-36-22](https://cloud.githubusercontent.com/assets/1896882/19390110/96239bc6-921e-11e6-91e7-2dce9b49d07c.png)

http://www.openstreetmap.org/directions?engine=osrm_car&route=38.25458%2C-76.96989%3B38.24909%2C-76.96200#map=17/38.25130/-76.96504

I previously assumed this was an OSRM issue, but am told that this is a problem with OSM's implementation: https://github.com/Project-OSRM/osrm-backend/issues/3057

**Comment by tomhughes** [comment]
This is a translation bug - you are using `en-GB` as your language rather than the base `en` translation and somebody has entered that string as the translation on TranslateWiki.

Please see http://wiki.openstreetmap.org/wiki/Translation#OpenStreetMap_website_interface for information on to correct the translation.

**Comment by IknowJoseph** [comment]
Thanks for the explanation - have provided correct translation via TranslateWiki.
