### ISSUE TITLE
How to deploy on DigitalOcean?

### ISSUE THREAD

**Issue by rikyperdana** [openstreetmap/openstreetmap-website#1385]
I have subscribed a $5 droplet on Digital Ocean
I followed to INSTALL.md and everything looks fine
But when i try to access my_ip_address:3000 from my browser
It only shows 'Problem Loading Page'
And when i access is through w3m http://localhost:3000 it works well
Could anybody tell me how to access it with my_ip_address:3000 ?

**Comment by zerebubuth** [comment]
That sounds like a problem caused by config or firewalling at Digital Ocean, and nothing specific to the OpenStreetMap website code.

I haven't used Digital Ocean myself, but a quick search led to https://www.digitalocean.com/community/questions/i-can-ping-my-droplet-but-cannot-connect-via-browser

If none of the solutions described there work, then I'm afraid I don't know how to help you further. I'd recommend asking Digital Ocean's support.

**Comment by rikyperdana** [comment]
I'm sorry, but i also install meteor project on the same droplet on port 3000 but it works well
I also tried to run this openstreetmap-website clone on port 4000, but nothing changed

**Comment by tomhughes** [comment]
Sorry, but you'll just have to debug it then and figure out what the problem is. There's no way we can help as we don't have access to your environment.

In any case it certainly isn't a bug with the software, it's an issue with the way you have set it up.

**Comment by tomhughes** [comment]
Actually by default rails only binds to the loopback interface if you're using the builtin server, which is designed for development use only.

You need to use `rails server --binding=0.0.0.0` if you want to bind to all interfaces, but it may not be a good idea to expose that server to the internet.

**Comment by rikyperdana** [comment]
It works, just like you told me to :)
