### ISSUE TITLE
Add changeset upload modifiers

### ISSUE THREAD

**Issue by woodpeck** [openstreetmap/openstreetmap-website#1389]
I would like to see more modifiers to the "modify" and "delete" sections in changeset uploads, along the lines of the existing "if-unused" modifier (or qualifier?) on the "delete" section (see http://wiki.openstreetmap.org/wiki/API_v0.6#Diff_upload:_POST_.2Fapi.2F0.6.2Fchangeset.2F.23id.2Fupload).

Reverting a large set of edits could be much more efficient if the following were supported:

1. "ignore-version" modifier on "delete" call to execute the deletion even if the object meanwhile has a different version. This would be used to delete e.g. a larger import where even if someone else had modified an object in the meantime, it still has to be deleted. 

2. "if-current" modifier on "delete" and "modify" calls to execute the deletion or modification only if the version transmitted is current (that is the default behaviour anyway) and silently ignore the deletion or modification if the version is not current (instead of cancelling the whole transaction which is the default behaviour). This could be used to revert a large mechanical edit where those objects that have meanwhile been touched by other mappers are exempt.

I'm happy to prototype these modifications but if possible I'd like some feedback on the ideas first.

A more ambitious way to improve the reverting of edits would be extending the changeset upload to allow a "revert" block that can revert objects to earlier versions without actually transmitting the full earlier version, like 

    <revert>
       <way id="1234" version="6" revert_to_version="2" />
    </revert>

but that's something for 0.7 I guess.

**Comment by dieterdreist** [comment]
2016-12-07 9:06 GMT+01:00 Frederik Ramm <notifications@github.com>:

> "ignore-version" modifier on "delete" call to execute the deletion even if
> the object meanwhile has a different version. This would be used to delete
> e.g. a larger import where even if someone else had modified an object in
> the meantime, it still has to be deleted.



if an object has been modified, it can have become whatever thing, not at
least connected to the original import. Although it might not happen too
frequently, you really will have to look at it (or accept some potential
data loss)

**Comment by mmd-osm** [comment]
> A more ambitious way to improve the reverting of edits would be extending the changeset upload to allow a "revert" block that can revert objects to earlier versions without actually transmitting the full earlier version

I'm not sure this is really an issue. On a decent internet connection, uploading large changesets only takes a rather small fraction of the total processing time, the rest is spent on processing Rails code.

This will significantly improve once changeset upload is available via cgimap (https://github.com/zerebubuth/openstreetmap-cgimap/issues/140). Mass downloading all of those objects to be reverted before uploading would be needed anyway to at least determine the current version numbers.

**Comment by mmd-osm** [comment]
> This will significantly improve once changeset upload is available via cgimap

New changeset upload is deployed for testing here now: https://upload.apis.dev.openstreetmap.org/user/mmd2/diary/1 

@woodpeck : https://github.com/woodpeck/osm-revert-scripts unfortunately doesn't have "Issues" enabled, that's why I'm adding a few comments here:

While reverting large changesets via JOSM reverter is very fast, I had mixed results with the osmtools reverter. Maybe I'm doing something wrong here, but it seemed that downloading objects took quite some time already. The upload process only improved after activating setting some $transaction = 1 flag.

Maybe it would make sense to investigate, if downloading multiple object versions at once might be an option (--> [multi fetch](https://wiki.openstreetmap.org/wiki/API_v0.6#Multi_fetch:_GET_.2Fapi.2F0.6.2F.5Bnodes.7Cways.7Crelations.5D.3F.23parameters)). If gathering old object version is fast, it would significantly reduce the risk for version conflicts.

My expectation is that a large changeset should be reverted in less than 1 minute, with the upload taking less than 10s.

Feel free to use the dev instance for testing and report back any concerns/issues or even success stories. Having strong reverter tooling support is essential, after all.

**Comment by woodpeck** [comment]
Is there a multi-fetch that, if one of the IDs mentioned has been deleted meanwhile, does *not* abort altogether but simply returns only the non-deleted objects?

**Comment by mmd-osm** [comment]
Ahem, the multi fetch doesn't abort in that case, it simply returns the element with a "visible=false" tag. Only in case you provide an object id that never existed on the database, you will get an HTTP 404. I believe for the use case of a reverter tool, that should never happen, right?

https://upload.apis.dev.openstreetmap.org/api/0.6/relations?relations=1396

https://upload.apis.dev.openstreetmap.org/relation/1396

**Comment by woodpeck** [comment]
Hm, ok. I'll have to check. I think the revert usually needs to know the previous version of everything, and sometimes even multiple previous versions, and there's no multi-fetch that allows you to access specific versions, but at least an initial pass could likely be made with multi-fetch.

**Comment by mmd-osm** [comment]
Multi fetch really allows you to access any version of any object, even multiple ones, as long as they fit into the URL, so that shouldn't be an issue...

**Comment by mmd-osm** [comment]
Ok, there's only one exception: redacted object versions are treated as if the object never existed in the first place, and result in an HTTP 404 for the whole call.  

https://www.openstreetmap.org/node/3006673214/history

https://api.openstreetmap.org/api/0.6/nodes?nodes=3006673214v4,3006673214v3

The API 0.6 documentation offers no real clarification how redacted object versions should be treated.

Rather than sending an HTTP 404, those object versions could also be omitted from the result without raising an error - like already done for the object history call: https://www.openstreetmap.org/api/0.6/node/3006673214/history

**Comment by mmd-osm** [comment]
By the way, as an immediate step to improve download speed, you should probably enable HTTP Keep-Alive in Undo.pl (`$ua = LWP::UserAgent->new(keep_alive => 1);`). Otherwise an SSL/TLS handshake is performed for every single node/way/rel you're downloading.

**Comment by mmd-osm** [comment]
@woodpeck : is this issue still relevant now that the new changeset upload is in place?

**Comment by mmd-osm** [comment]
No feedback since a few years. Please reopen if this is still relevant.
