### ISSUE TITLE
OAuth2 support?

### ISSUE THREAD

**Issue by HarelM** [openstreetmap/openstreetmap-website#1408]
Hi,

Any change to support OAuth 2 protocol. I currently have a security issue due to client side cuonsumer key vulnerability with OAuth 1. Also it's getting harder to support this old format in new packages (Mainly in .Net server side code).

P.S. I'm the co-founder and main maintener of https://israelhiking.osm.org.il and I have decided to use the OSM users as my site users to encourage people to contribute to OSM mapping.

**Comment by tomhughes** [comment]
Well the problem is OAuth2 isn't really a protocol, it's more of a toolkit that can you can use to design a protocol.

I've no objection to supporting it if somebody wants to do the work, but I don't really have the time or energy to do enough reading and research myself to come up with something.

I'm not sure what you mean by "client side consumer key vulnerability" though - if you just mean the fact that you need to have a key on the client side to identify the client then I'm not sure how OAuth2 is supposed to help as every OAuth2 system I'm ever seen still has that?

**Comment by HarelM** [comment]
Unfortunately I'm not a Ruby developer, so I can't help much in this area.
I guess that there are packages who offer this kind of support. googling it for a few second return this results:
https://github.com/doorkeeper-gem/doorkeeper
As I see it, it is so common that there must be a package that is debugged and production worthy that you can take and use out of the box.
Again, not a Ruby developer so this is just my experience with other languages talking...

**Comment by M1dgard** [comment]
Before you start considering OAuth 2, note that its lead developer called it bad before resigning from his role. He wrote about his reasons here: https://hueniverse.com/oauth-2-0-and-the-road-to-hell-8eec45921529

**Comment by tomhughes** [comment]
I am currently investigating this further - because the oauth-plugin gem we currently use is largely unmaintained I'm reluctant to use it's OAuth 2 support so am currently looking at https://github.com/doorkeeper-gem/doorkeeper instead.

That doesn't do OAuth 1 so the two will likely be largely separate though it may be possible to share the registered client list.

**Comment by mmd-osm** [comment]
It would be good to know if you expect some necessary changes on cgimap, which currently only supports OAuth 1.0a. zerebubuth has written that implementation, and we probably need to involve him, in case the plan is to run some mixed 1.0a/2.0 scenario for all API endpoints.

**Comment by tomhughes** [comment]
I guess so - certainly we won't be able to do a hard cutover. I've mostly just been reading so far though so not ready to offer any code or anything.

**Comment by mmd-osm** [comment]
It seems that cgimap would at least need to call an Introspection endpoint via HTTP(S) to validate a user-provided token and get further details such as user ids, scopes and whatnot (https://tools.ietf.org/html/rfc7662#section-2). 

As we share the same database anyway, there might be some way to directly query the respective doorkeeper tables, as we do today with OAuth 1.0a  (https://doorkeeper.gitbook.io/guides/internals/database-design).

Most of the work to get this up and running seems to be on the Rails side of the house this time.

**Comment by mmd-osm** [comment]
Quick heads up: the new JSON endpoint in #2839 returns an array of users as of now. While this works for  _jq_ ( `curl ... | jq '.users[0].user.display_name' `), array support was only added recently to the Discourse oauth2 plugin  (https://github.com/discourse/discourse-oauth2-basic/pull/22).

**Comment by mmd-osm** [comment]
For the sake of documenting my doorkeeper mini-proof of concept, I'm listing a few points that I thought might be worthwhile checking.

Gemfile:

```
+ gem "doorkeeper"
```

Beyond the default doorkeeper installation, I also installed:

- https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-views
- https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-PKCE-flow
- https://github.com/doorkeeper-gem/doorkeeper/wiki/Associate-users-to-OAuth-applications-(ownership)

Respective generate commands:

- rails generate doorkeeper:views
- rails generate doorkeeper:pkce
- rails generate doorkeeper:application_owner
- 

Some migrations need an additional `safety_assured` to pass.


app/controllers/api/users_controller.rb:

Enable OAuth token check with "read" scope for details endpoint:

```rails
   class UsersController < ApiController
     before_action :disable_terms_redirect, :only => [:details]
+
+    before_action -> { authorize_if_got_token! :read }, :only => [:details]
+
     before_action :authorize, :only => [:details, :gpx_files]
```

app/controllers/api_controller.rb:

Some ideas taken from https://github.com/tootsuite/mastodon/blob/master/app/controllers/api/base_controller.rb#L114. It's not clear if this a reasonable approach. Additional methods are only relevant for API endpoints.

```
+  # Find the user that owns the access token
+  def current_user
+    if doorkeeper_token
+      User.find(doorkeeper_token.resource_owner_id)
+    else
+      super
+    end
+  end
+
+  def current_resource_owner
+    @current_user ||= User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
+  end
+   
+  def authorize_if_got_token!(*scopes)
+    doorkeeper_authorize!(*scopes) if doorkeeper_token
+  end  
 end
```

app/models/user.rb:

(changes were described on some of the doorkeeper wiki pages mentioned earlier on)

```
   has_many :reports
+  
+  has_many  :access_grants, class_name:  "Doorkeeper::AccessGrant",
+                            foreign_key: :resource_owner_id,
+                            dependent:   :delete_all
+
+  has_many  :access_tokens, class_name:  "Doorkeeper::AccessToken",
+                            foreign_key: :resource_owner_id,
+                            dependent:   :delete_all  
+
+  has_many :oauth_applications, class_name: 'Doorkeeper::Application', as: :owner
```

config/routes.rb:

Use /oauth2/... to avoid interference with current oauth/ endpoints

```
 OpenStreetMap::Application.routes.draw do
+  use_doorkeeper :scope => 'oauth2'
+
   # API
```

doorkeeper.rb needs at least a custom implementation for:

* resource_owner_authenticator: 
* admin_authenticator

**Comment by tomhughes** [comment]
So basically you've been duplicating everything I've been doing?

**Comment by mmd-osm** [comment]
It was a good exercise to get some idea how doorkeeper works, a bit of duplication is perfectly fine for me. Your comment seems to suggest that this make at least some sense, which is a good start.

**Comment by mmd-osm** [comment]
I guess you've also got the discourse-oauth2-basic plugin up and running? I tried the new json user details endpoint along with Discourse, and that seems to be working ok'ish for my toy example.

**Comment by tomhughes** [comment]
No of course I haven't. I'm not doing anything with discourse, I'm just generally working on oauth2 support for the API.

**Comment by mmd-osm** [comment]
I've seen some issues with a user having to log in first at the rails port and then follow a redirect back to discourse (example: http://railsport.internal/login?referer=http://discourse.internal/auth/oauth2_basic/callback).

`safe_referer` in the app controller sanitises the referer url so that the redirect no longer works. When commenting out all that logic, discourse reports an csrf_detected error...

Long story short, I believe it would make sense to somehow include discourse in the tests. They offer a container image which is good enough for testing. https://hub.docker.com/r/bitnami/discourse/

Inside the discourse container, the oauth2-basic plugin needs to be installed:

git clone https://github.com/discourse/discourse-oauth2-basic.git /opt/bitnami/discourse/plugins/discourse-oauth2-basic
chown -R discourse:discourse /opt/bitnami/discourse/plugins/discourse-oauth2-basic

**Comment by tomhughes** [comment]
We are not going to include a test that uses a sodding discourse container.

Please just pipe down and let me get on with it which will include writing tests for the supported flows just as we already do for our existing oauth aupport.

**Comment by mmd-osm** [comment]
Sure, I didn’t really have any unit tests in mind, that would be a bit insane. The idea was more to give this a try in a standalone test, once all is done on the rails port, nothing else.

**Comment by gravitystorm** [comment]
> Please just pipe down and let me get on with it

@tomhughes that's a really unfair thing to say to someone who is a) interested in what is happening b) happily doing actual development work on it and c) a maintainer of cgimap. I don't understand why you are so anti-collaboration on this instead working with @mmd-osm together cooperatively.

**Comment by tomhughes** [comment]
I just don't understand why he's duplicating work that I've already said I'm doing, and I feel like he's trying to pressure me to go faster. I've said that this is a complex issue that is going to take time for me to address - there are a whole lot of challenging integration issues that need be resolved to get a production quality implementation and the fact that he can basically overtake me by taking shortcuts really just makes it feel like I'm being hounded to speedup.

**Comment by mmd-osm** [comment]
Apologies if this comes across that way, that’s not really my intention. It’s just that I want to get some first hands idea how this works.

**Comment by mmd-osm** [comment]
For anyone reading this and scratching their heads what this discussion is all about. 
I tried to work out the feasibility of an end-to-end sign up process using Discourse and the Rails port, i.e.
* installing discourse
* registering a new OAuth 2 client on Rails for Discourse application
* configuring the oauth2-basic plugin on Discourse
* Sign up as new user on Discourse, which includes logging in via the Rails port via OAuth2, and redirect back to Discourse
* make sure that Discourse can fetch all details for the new user from our new JSON format user/details endpoint (this includes user id and display_name + avatar image url).
* profit!

I added about 30 lines of code in Rails to the application controller, define a new CanCanCan capability, and add proper redirect to our login page for doorkeeper. That's all demo / throw away code anyway, so it doesn't really matter anyway if there's a bit of duplication here. 30 lines will never suffice for a production ready implementation, no doubt about that.

My focus was to find out if the end-to-end process will eventually work, and we're not missing any important bits nobody thought about before. Quite a different focus, after all. As the end-to-end demo turned out to successful, I'm confident to get this running at some point in the future.

**Comment by tomhughes** [comment]
I'll add that https://github.com/openstreetmap/openstreetmap-website/compare/master...tomhughes:doorkeeper is the current state of my work.

After some more work at the weekend I no have all the integration with CanCanCan working and have a bunch of tests demonstrating the necessary flows are able to authenticate successfully and then access resources.

There's a few more things I want to play with there, and a bunch of UI work around actually being able to add applications and customising authorisation etc.

**Comment by HarelM** [comment]
Sound great! Thanks for all the hard work!
Kindly let me know when there's something I can play with that is related to the OSM API. I would very much like to test it and try it out when something is available, even if it's only in the dev env or something.

**Comment by mmd-osm** [comment]
> I'll add that master...tomhughes:doorkeeper is the current state of my work.

I ran a quick test using Postman and Authorization Code (+optionally with PKCE) and that looked good. Due to the additional secret hashing, I had to register some new apps, but that's ok.

I was about to ask, if we would always keep permission and scopes names in sync, or if it would make sense to have some more fine granular scopes (for things like #2631). `includes_scope` and its mapping onto the existing allow_* fields looks like a clever trick to avoid some extra work (like defining a new capability, or inventing new scopes). I guess that implementation answers my question then.

**Comment by mmd-osm** [comment]
I couple of days back, I gave `tomhughes:doorkeeper` another try, and it seems it would be ready for deployment to dev anytime soon for some further testing. Auth.code + PKCE looked ok in Postman.

**Comment by tomhughes** [comment]
Yes I will probably be opening a PR soon as most issues are now resolved.

**Comment by mmd-osm** [comment]
One issue I'd like to report right away before I forget about it. I noticed that I can register a new application without any scopes, and then later successfully request a token for whatever scope I like. My expectation would be that "allow_api" shouldn't match an empty set of permitted scopes.

**Comment by tomhughes** [comment]
Yes if an application doesn't specify any scopes then all scopes are allowed - unfortunately it's not easy to change.

As best I could tell when looking at it yesterday we'd have to override the application model and add an extra validation to it that prevented creating applications with no scopes, which is possible but a bit of a pain so I guess it depends on how important we think it is.

**Comment by mmd-osm** [comment]
As an authenticated user, I can fetch secret values for my own applications via a json endpoint. Is this something we want?

![door1](https://user-images.githubusercontent.com/5842757/114607848-4f598f00-9c9d-11eb-85ea-b3425d214987.png)
![door2](https://user-images.githubusercontent.com/5842757/114607858-51bbe900-9c9d-11eb-8136-7f4f33abc3fd.png)
