### ISSUE TITLE
Upload trace fails on dev server

### ISSUE THREAD

**Issue by HarelM** [openstreetmap/openstreetmap-website#1412]
Hi,

I get an InternalServerError (500) when trying to upload a trace using the OSM API 0.6 to dev server.
When using the same code with the production server everything works as expected.
The error says something with rename failure on the server I think...
Server: ```http://api06.dev.openstreetmap.org/```
API Call: ```/api/0.6/gpx/create```

**Comment by tomhughes** [comment]
Trace uploads are not currently supported on the dev server. This is also the wrong place to report operational issues related to specific deployments - this tracker is only for issues in the code itself not for configuration issues related to specific deployments.

**Comment by HarelM** [comment]
> Trace uploads are not currently supported on the dev server.

Is it configuration issue or a statement? If this is a statement and not a bug then it means I can't fully test the API code against the Dev server which is problematic.
> This is also the wrong place to report operational issues related to specific deployments

I'm sorry, I did not know that.
I'm not sure where else I can post issues, please forward this to the relevant people.

**Comment by tomhughes** [comment]
It's a configuration issue in that we haven't configured any storage for traces on that server, mainly because if we did so we'd have to worry about cleaning it up somehow, which isn't an issue on the live server where we keep traces forever.

Either https://github.com/openstreetmap/operations/issues or https://github.com/openstreetmap/chef/issues would be better places in that it's an operational issue but at the end of the day the actual change would be to our chef recipes to make them configure storage for GPX traces on the dev instances.

As I say though, this isn't a simple issue, which is why it's never been done.
