### ISSUE TITLE
prevent copycats during registration

### ISSUE THREAD

**Issue by d1g** [openstreetmap/openstreetmap-website#1419]
In addition to #1083 

suppress fiddling with unicode to impersonate legit osm users 

[recent case](http://www.openstreetmap.org/user/%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%20%D0%9A/diary/40318)

**Comment by tomhughes** [comment]
That's just ridiculous. How on earth are we supposed to programatically determine what constitutes a "copycat" account? Or should we just send them all for your personal review?

**Comment by d1g** [comment]
first measure is to allow only one alphabet + numerals + (limited punctuation) in nicknames

**Comment by tomhughes** [comment]
Yes that will be very popular. Sorry, but we're not going to force the entire world to use the western alphabet.

**Comment by d1g** [comment]
...of course I meant `\P{Cyrillic}`|`\P{Arabic}` and [so on](https://en.wikipedia.org/wiki/Script_(Unicode)).

**Comment by zerebubuth** [comment]
There are a few possibilities which might work, but need further investigation to see if they are feasible, practical and effective. @pnorman and I were discussing a couple of ideas:

1. A [common defence](https://en.wikipedia.org/wiki/IDN_homograph_attack#Defending_against_the_attack) appears to be to only allow letters from a single language in the name. This doesn't prevent all homographs, but at least makes it much harder to find suitable glyphs. The first step here would be to implement something that checks to see how many existing display names would be affected by this, and whether there's any correlation with accounts used for impersonation.
2. A potentially very different approach would be to find the modal alphabet of all glyphs in the name and render any other alphabets differently. For example, in the name "zеrebubuth", one of the "e"s is a Cyrillic character, but the rest are Latin and so Latin is the "modal alphabet", and we might render the name as "z**е**rebubuth" or "z`е`rebubuth". This has the advantage of handling all existing display names, but the disadvantage that it would only be effective on the OSM website, where we can affect the rendering.

Of course, there are many other ideas as well, all vapourware at this point. The next step for any of them would be to make some concrete progress by showing proof of concept analysis, patches or other working code.

**Comment by gravitystorm** [comment]
> That's just ridiculous. How on earth are we supposed to programatically determine what constitutes a "copycat" account? Or should we just send them all for your personal review?

That's an unhelpful comment.

> suppress fiddling with unicode to impersonate legit osm users

We already support some measures to prevent copycat account names (specifically, you are no longer allowed a name which are case-insensitive duplicates, see https://github.com/openstreetmap/openstreetmap-website/blob/34d663f01af07033dfca697ad607cb473aa70e40/app/models/user.rb#L41-L42 . We can extend this idea to cover other unicode-based normalisation approaches, e.g. e-acute vs e-with-combining-acute, duplicated Unicode characters (see https://en.wikipedia.org/wiki/Duplicate_characters_in_Unicode) and homoglyphs or near-homoglyphs (see https://en.wikipedia.org/wiki/Homoglyph). 

The best approaches will be to work with whatever functions are available through PostgreSQL, e.g. [unaccent()](https://www.postgresql.org/docs/current/static/unaccent.html), or ruby, e.g. [unicode_normalize](https://ruby-doc.org/stdlib-2.2.1/libdoc/unicode_normalize/rdoc/String.html) or if there are suitable rubygems. We shouldn't attempt to build our own unicode normalisation rules!

Finally, the best long-term solution will be to include the account id in the URL, so that even the most creative of duplicate display names are easily distinguishable as separate accounts.
