### ISSUE TITLE
Add "show tile image" to right click menu

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/openstreetmap-website#1446]
As this page is to support the mappers opening the corresponding tile url would be helpful.

**Comment by tomhughes** [comment]
Sorry but I really don't see that at all. In what way is the tile URL useful?

**Comment by HolgerJeromin** [comment]
To refresh the tile without a browser cache. Shift f5 of the page often loads a cached tile. 
Or I can request a rerender.

**Comment by tomhughes** [comment]
That's a massively low level hack though and not something we would ever want to expose to a typical mapper or generally encourage. On top of which shift-reload does work fine in my experience.

**Comment by pnorman** [comment]
I have found myself frequently needing to open up a tile in its own window for one reason or another, but I'm not a typical user.

**Comment by tomhughes** [comment]
Yes I'm sure I'd find it useful sometimes but we're like the 0.001% here.

**Comment by Zverik** [comment]
But isn't our website for us, the mappers?

**Comment by pnorman** [comment]
We don't open tiles because we're mappers, we do that because we're style developers or server admins.

**Comment by tomhughes** [comment]
I think I already said it was for mappers. The point is that even most mappers don't need this, or if they do then this is not the right way to provide it.

If we really felt it was necessary we should add a "refresh tile" option to the menu, not an option to load the tile so the user can then a magic incantation to the URL bar.

**Comment by dieterdreist** [comment]
sent from a phone

> On 19 Feb 2017, at 09:19, Paul Norman <notifications@github.com> wrote:
> 
> I have found myself frequently needing to open up a tile in its own window for one reason or another, but I'm not a typical user.
> 


maybe I'm a more typical user, and I also need to access tile urls frequently. With the map aiming at mappers rather than users it should be considered exposing them in a convenient way. Maybe something like "re-render metatile" which would open the dirty url?

**Comment by tomhughes** [comment]
Firstly I don't believe mappers really "need" to force a refresh in most cases - they may like to see their work rendered immediately but it's certainly not essential in most cases.

But here's thing, you can do that with a shift-reload already. This is not hypothetical as I've been doing some mapping myself recently and I do a shift-reload and wait a few minutes and do it again and bingo my new edits have rendered.

**Comment by SomeoneElseOSM** [comment]
Like those above I may not be a typical mapper, but I also find getting a tile URL useful.  Usually this isn't as a way to dirty it, but as a way to share a tile, or view that same tile rendered with some other stylesheet.

**Comment by HolgerJeromin** [comment]
Tom you closed this issue with a no before discussion started and did not reopen it. That is why I understand Zverik that he built the PR.

**Comment by BushmanK** [comment]
I don't know about other browsers, but Shift-RightClick still works perfectly in Firefox for bringing up browser's context menu.
It is better to learn about your browser before complaining.

**Comment by HolgerJeromin** [comment]
@BushmanK 
Your perfect firefox gives you in the browser context menu the full tile url? 
What are you talking about?

**Comment by Zverik** [comment]
Just checked: Shift+Right Click works in the Firefox for macOS, does not work in Linux.

**Comment by HolgerJeromin** [comment]
#1447 fixes shift right click handling for all browsers but is still not deployed. 
But has **nothing to do** with this issue so please keep on topic!

**Comment by polarbearing** [comment]
My browser (mozilla/seamonkey), until some time last year, used to offer me "View image" in the browser's right-click menu, as long as I had not selected any additional layer such as data or notes. Since that does not work anymore, I have to go to the browser's debugging tools and wade through all images to find a specific tile.

**Comment by katpatuka** [comment]
Why not add it? An osm mapper knows that he could add a dirty or status parameter at the end of a tile url. A normal user doesn't know it so he would only think: what the hack is that for? But to get the tile's address is currently a pita.

**Comment by tomhughes** [comment]
No, a typical OSM mapper certainly doesn't know that at all, and shouldn't need to. You do, but you are in no way typical.

**Comment by HolgerJeromin** [comment]
@polarbearing 
The image is hidden from pointer interaction in leaflet
https://github.com/openstreetmap/openstreetmap-website/blob/5bcf82d8658d1d9ae389807362f542189d21ec56/vendor/assets/leaflet/leaflet.css#L225

Thats the reason the browser menu can not add "show image" as the rendered tile is not hit by the mouse.

**Comment by Zverik** [comment]
I still do not understand why not. We see a lot of questions here, there is an ongoing discussion filled with frustration in the Russian telegram channel, there are some puzzled tweets. We have a pull request, so now it is not the "please do the work" kind of issue, but "why you won't merge it" one.

Whom the "show tile image" menu item would hurt? It is not prominent, it does what it says. Outsiders will see that it opens an image and will close the extra tab with a shrug. They won't leave the website or argue that the website is not usable anymore.

Many mappers occasionaly need to get a tile URL. The most common usage is for /dirtying, programmers use it for testing downloaders and coordinate conversions, some copy the URL for the template to embed in their websites. It is not just ten or a hundred people.

As we learnt, shift+click does not work everywhere. The website is for mappers, so since we already have a popup menu, why not make a mapper's life a tiny bit easier by adding the extra menu item?

**Comment by BushmanK** [comment]
@HolgerJeromin, I've mentioned that since a lot of people are complaining about this new menu as about an obstacle to getting a tile URL. I don't have to know about their previous workflow, but the only thing that has changed after this new menu was added is that you can't call a context menu with RightClick. Personally, I've been always using built-in Code Inspector for that and nothing has changed for me.

By they way, wording like "your perfect Firefox" seems quite pathetic.

**Comment by Stalfur** [comment]
Another mapper here who is missing the show image tile option.

This is quality of life issue.

**Comment by simonpoole** [comment]
May be there is a way out of this with endangering the quality of life of anybody :-). I agree with @tomhughes that simply providing a link to a map tile on which you have to perform obscure stuff to get useful information, doesn't really make a lot of sense and is hopelessly implementation dependent.

So what about an entry that shows a popup that lists all the stuff we often get asked about: for example the cache you are being served from, the tile status and potentially a button to force re-render it.

**Comment by polarbearing** [comment]
... like the Show Tile Info in JOSM

**Comment by qeith** [comment]
I, also, would like to see a way to view individual tiles, and their corresponding url.

**Comment by tomhughes** [comment]
So obviously somebody has been canvassing for "support" for this. Getting a couple of dozen hard core mappers to agree with you doesn't change anything.

We're talking here about what makes good UX for the 99% not what will make the 1% a little happier.

If you want something to show tile status then fine. I might even agree to an option to get the tile URL or expire a tile (though the latter is perhaps unlikely) but it needs to be properly integrated, not just dumping the URL in another tab and letting the user fiddle with it.

By all means add a "show tile status" menu entry that opens a popup or the side bar with the tile coordinates and last refresh date etc though - that would be vaguely sensible from a UX/UI point of view.
