### ISSUE TITLE
Do not ask for application OAuth permissions repeatedly

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#1455]
Below is a screenshot of an excerpt from my OAuth authorized apps page. These three apps have the same id, and the website knows that I had granted some permissions to these apps before. Facebook, Google and most other OAuth providers do not ask for permissions the second time: a user chooses what they want to share only once. It would be great if osm.org did the same, and did not produce duplicate entries in that list as a result.

![2017-02-22 12 11 48](https://cloud.githubusercontent.com/assets/766031/23204627/c64866a8-f900-11e6-8d18-9e305ed414f4.png)

**Comment by tomhughes** [comment]
Well the client application is supposed to keep using the same token, not keep on reauthenticating new tokens!

**Comment by Zverik** [comment]
I agree, but the practive shows that our website keeps state much better than clients.

**Comment by simonpoole** [comment]
Doesn't guessing that it is the same device/app open up a security hole about as big as the whole universe plus some?

**Comment by Zverik** [comment]
Why? A user is authenticated and has granted permissions to an app. I often see Facebook remembering an app instead of asking for permissions again and again, and nobody has complained.

**Comment by tomhughes** [comment]
Do google, facebook etc really convert the new request token into the same access token? or do they just collapse multiple live access tokens to one line in the UI with the revoke button revoking all active tokens for that application?

**Comment by tomhughes** [comment]
Of course the other thing is that they're doing OAuth 2.0 so the details may be somewhat different anyway.

**Comment by Zverik** [comment]
An oauth2 provider must return a new token each time. Revoking an app removes all the tokens. With oauth2, tokens have a limited lifetime, so old ones are cleaned automatically. In our case we can limit the number of tokens and e.g. remove all but 20 newest.

The token list page presented above does not give a user an undestranding of what each token is for, so collapsing these is a reasonable first step.

**Comment by Zverik** [comment]
This is a screenshot of app management in Facebook. It is a simple list of apps with a visibility indicator. You can either remove an app, or adjust settings when you click an app's name.

**Comment by simonpoole** [comment]
Well we are not doing OAuth 2.0. 

In our case OAuth 1.0a each app only has the Consumer Key for identification, the association between user and the access token is established during the handshake. As a result there is no way I can see how you could go from the Consumer Key to the access token without re-authenticating the user and re-authorizing the app.

**Comment by HolgerJeromin** [comment]
Kind of related #1074

**Comment by Zverik** [comment]
> In our case OAuth 1.0a each app only has the Consumer Key for identification, the association between user and the access token is established during the handshake. As a result there is no way I can see how you could go from the Consumer Key to the access token without re-authenticating the user and re-authorizing the app.

I'm not sure I understand. I propose not to change OAuth implementation, but to make user UI for managing tokens more clear.

What I'm proposing (refined in this discussion) is:

1. Display to a user not a list of tokens, but a list of applications. A "revoke" button revokes all tokens for the application.
2. When an application makes a redirect to the oauth page, search for the last token and if found, use the permissions list from it, immediately redirecting user to the next step.
3. To simplify the last step, store granted permissions separately from tokens, and add an "edit" button to the app list from step 1, allowing a user to view and modify a list of permissions for the app.

**Comment by tomhughes** [comment]
But a lot of that involves either changing the oauth flows (mandated by the specs) or changing things which are part of the oauth gems and hence outside our control.

So what you're saying is that the flow would be that you get a new request token, then when you go to `/authorize` it would somehow find and return the existing access token rather than creating a new one. The problem with that is that `/authorize` is implemented by the oauth-plugin gem, not by us.

**Comment by simonpoole** [comment]
I suppose there is, in theory, some value in populating the permissions granted from what was granted last time. But I just don't see why the once in a blue moon reauthorizing is such a burden on the end user.

I added OAuth to vespucci 3 years ago. A user that authorised the app then and hasn't changed the phone, or hasn't deinstalled/reinstalled should not have had to re-authorize since (with other words likely the most common reason for reauthorizing is getting a new phone).

**Comment by Zverik** [comment]
This issue of course concerns users of web applications that change devices (e.g. access the same site from home, work and from a mobile phone), or have to cope with lost application state of some. JOSM / Vespucci / iD users will not be affected, since our tokens are eternal.

**Comment by Zverik** [comment]
> So what you're saying is that the flow would be that you get a new request token, then when you go to /authorize it would somehow find and return the existing access token rather than creating a new one? The problem with that is that /authorize is implemented by the oauth-plugin gem, not by us.

No, it should find the last granted token, and if found, use permissions from it for creating a new token. And we already override the `oauth1_authorize` that processes the request: this is a matter of adding an `else` block to the `if request.post?` clause.

**Comment by pnorman** [comment]
> I'm not sure we should be catering for apps (of any kind) that do not persist the access token properly.

👍 , a failure to persist the access token properly is not an issue with the rails port but an issue with the apps.

**Comment by zerebubuth** [comment]
> a failure to persist the access token properly is not an issue with the rails port but an issue with the apps.

I think what @Zverik is saying is not that the access token would be shared via the API, but that the user would accept a list of permissions on a per-app basis rather than a per-device / per-access-token basis. Accepting (or rejecting) a set of permissions is a part of the OAuth flow that we added, so we are able to skip that step if the user has previously authorised a token for this same app, and (I think) without impacting the security properties of OAuth.

Effectively, this would have two parts:

1. Where we currently [check token capability](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/application_controller.rb#L53-L68), we would instead look up a new type (say, `ClientPermissions`) which is unique per-user and per-`client_application`.
2. When authorising a new token, if a `ClientPermissions` object exists for the (`user`, `client_application`) pair, then use that instead of asking the user to approve the permissions.

The token UI would then be able to edit the `ClientPermissions` objects. This would mean the user loses the ability that they currently have to grant different permissions to different instances of the same app. I'm not sure if anyone is using that ability, so perhaps not a big loss.

**Comment by tomhughes** [comment]
It is, yes
