### ISSUE TITLE
Line breaks aren't working in user profiles

### ISSUE THREAD

**Issue by naoliv** [openstreetmap/openstreetmap-website#1503]
Have this example in the user profile description:

```
foo  
bar

foo  
bar
```

Both `foo` have two spaces at the end.
In preview we can see this:

![](https://cloud.githubusercontent.com/assets/982338/24388288/0fc6bfc8-1350-11e7-9ff8-dc44fbeb4fc0.png)

But after saving and taking a look at the profile (https://www.openstreetmap.org/user/username) we have this:

![](https://cloud.githubusercontent.com/assets/982338/24388293/19427a9c-1350-11e7-88ab-ea2bd9616bb9.png)

ie, there isn't a line break between the first `bar` and the second `foo`

**Comment by tomhughes** [comment]
A blank line is a paragraph break so is not preserved in the rendered output as such - the reason it appears to be in the preview is that paragraphs there have a 20 pixel bottom margin.

In the actual user description rendering the designer has chosen not to have that margin, likely because use descriptions are intended to be small and compact.

**Comment by gravitystorm** [comment]
This bug no longer occurs - the rendered version now has the same paragraph margins as the preview. So this is fixed.
