### ISSUE TITLE
Notes RSS feed is full screen height

### ISSUE THREAD

**Issue by DaveF63** [openstreetmap/openstreetmap-website#1522]
Hi

Maybe just me, but the Notes RSS feed length appears to be unset & the list is displaying my screen's full height. Is it possible to restrict the number of items? WhoDidIt's limit is 20.

**Comment by tomhughes** [comment]
I don't understand what you mean by "full screen height" or what the height of your screen or how your feed reader chooses to render the feed has to do with us...

I'm not sure which feed you are referring to either - the RSS version of the note list, or the comment feed.

Both respect the request result limit though as far as I can see, as set with the `limit` parameter on the URL and defaulting to 100 if not otherwise specified.

**Comment by DaveF63** [comment]
> I don't understand what you mean by "full screen height"
I think you do.

>  or what the height of your screen or how your feed reader chooses to render the feed has to do with us...
The example of WhoDidit limits its own feed. (server side?)

> I'm not sure which feed you are referring to either - the RSS version of the note list, or the comment feed.
As I never mentioned 'comment' but 'RSS' & 'notes' twice, I'm unsure why you fail to comprehend.

> Both respect the request result limit though as far as I can see, as set with the limit parameter on the URL and defaulting to 100 if not otherwise specified.
I was unaware of that parameter. Thanks. There is no mention of it in the wiki.
