### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by a01020304uk** [openstreetmap/openstreetmap-website#1565]
I have followed the instructions here
https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md
at the end everything works and does as its ays it shows OSM tiles
however i cannot understand or figure out how to import and use my own tiles on my own pc and not use OSM tiles
please can someone give me guidence??

I have looked at this page
https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md
the first part tells you to download london pdf file but i already have the pbf file I want to use so how can i use my own file and not download one mentioned?

**Comment by tomhughes** [comment]
This repository is just the web site - it doesn't deal with rendering tiles at all. Please see http://switch2osm.org/ for information on setting up a tile renderer.

**Comment by a01020304uk** [comment]
that website is out of date as many instructions dont work

**Comment by SomeoneElseOSM** [comment]
@a01020304uk I'd be surprised if https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ is out of date - I updated (and tested) it only a few days ago.

**Comment by a01020304uk** [comment]
when i try and install mapnik it says "unable to locate package libgall-dev"

**Comment by gravitystorm** [comment]
@a01020304uk If you want help with the instructions you find on switch2osm, then please see the "Getting Help" section of https://switch2osm.org/find-out-more/

**Comment by a01020304uk** [comment]
i dont want a slippy tile server only, i am wanting a complete clone of OSM

**Comment by tomhughes** [comment]
That is a major undertaking and this is not the correct venue in which to seek help with such a project.

**Comment by a01020304uk** [comment]
but i am follwoing instructions given as explained but after the initial page it makes njo sense and several commands do not work now you tell me to use switch which is a completly different thing. OSM is suppost to be open souce and can be installed everywhere and you say everyone is friendly and willing to help but when someone like me asks for help I get shut down.
all instructions seems to be writtenm by expets for experts so normal people do not uindesratdn a word thats written

**Comment by tomhughes** [comment]
Installing a complete openstreetmap stack is definitely not a job for an end-user and I don't believe we have every claimed that it is, not have we ever claimed it can be "installed everywhere" as you suggest.

In fact it has never really been the intention for the code in this repository to be used anywhere other than on www.openstreetmap.org although various people have done so.

Tile serving is something that we understand more people may want to do which is why resources like switch2osm.org attempt to explain how to do it - it is still really a job for a competent technical user though and not something somebody without some reasonable software development and/or system administration experience should be tackling.

Please, if you want to discuss this further take it to IRC or one of the mailing lists or https://help.openstreetmap.org/ or something - this discussion does not relate to any problem with the code in this repository as far as I can tell.

**Comment by a01020304uk** [comment]
i am wanting an exitable map to record 13th century stuff which i cannot do on a normal osm map or show on a osm map thats why want facility to do that myself

**Comment by a01020304uk** [comment]
OHM not suitable as i would need to delete someone elses work of their project to do what i want to do which defeats the purpoise.

**Comment by gravitystorm** [comment]
@a01020304uk If you have any questions about the code **in this repository** then please open a new ticket. 

For questions or support for anything else, including setting up tileservers, please see any of the following:

* https://help.openstreetmap.org/ 
* https://switch2osm.org/find-out-more/
* http://www.openstreetmap.org/help
