### ISSUE TITLE
Default view Eurocentric

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1586]
Users first visiting the site see a map centered on London.

Please chose five or more big cities, on different continents, and randomly center the map on them too.

Or even use location information from the user's browser, maybe.

Whatever you do, don't appear to always favor a certain country / continent, etc.

**Comment by tomhughes** [comment]
We use geoip - the default view you describe only happens if we don't get a geoip result for your IP address (and if you have no location cookie from a previous visit).

**Comment by jidanni** [comment]
Well, wouldn't you think of my ideas have a minimal degree of merit, in the case that the geoIP fails?

**Comment by jidanni** [comment]
Furthermore, I am only discussing the single case of people who have no cookie. Therefore I believe my comments are 100% relevant.

**Comment by jidanni** [comment]
What is your basis for believing that London should be the single default choice?

**Comment by tomhughes** [comment]
London isn't - the default view should be of the whole of western europe I believe. That is mostly because at the time it was chosen that was where the maps looked best!

The problem with browser location is that for many people it is just geoip and at the same time it's a horrible user experience because the first thing that happens when you visit what is probably a new site to you is that the browser shoves a permission box in your face.

We could do a randomisation thing but, and if somebody offered a pull request then we could consider it but it's not clear to me that it warrants a bug that will likely just sit here forever in the absence of anybody interested enough to implement it.

**Comment by woodpeck** [comment]
Selecting a random location is sure to confuse people. *If* a change is required for reasons of inclusivity then I'd simply zoom out to show the full planet, but frankly, with the project undeniably having its roots in the UK I don't mind that little reminder when you first visit the page AND have no GeoIP.

**Comment by jidanni** [comment]
Cc: diversity-talk@openstreetmap.org
https://github.com/openstreetmap/openstreetmap-website/issues/1586
Yes, please simply change the initial default coordinates for first time
visitors to show the whole world, not a map centered on London.

**Comment by jidanni** [comment]
Maybe use http://www.openstreetmap.org/#map=2/30.0/0.0 for the whole
world view.

Also looking at the https://www.google.com/search?q=geoip all the tests I did
could at least tell 114.41.39.166 is in Taiwan, alas
$ firefox --private-window http://www.openstreetmap.org/
still opens http://www.openstreetmap.org/#map=5/51.500/-0.100
Is the geoIP function still working for anybody?

**Comment by tomhughes** [comment]
Obviously it's tricky for me to test because I'm in the UK but I just changed the source to hardwire that address in place of using the real client address and loaded my dev site in a private window and this is what I saw:

![screenshot from 2017-07-16 18-30-16](https://user-images.githubusercontent.com/147741/28249818-14c431c0-6a55-11e7-9472-baeb40cd961d.png)

**Comment by tomhughes** [comment]
Hmm actually it looks like there might be an issue with the production servers...

**Comment by jidanni** [comment]
I suppose once your fix kicks in, users should only be staring at London 0.01 % percent of the time, thus no more Eurocentric.

**Comment by tomhughes** [comment]
It is deployed now if you want to try it again.

**Comment by jidanni** [comment]
OK good. I now get http://www.openstreetmap.org/#map=7/23.611/120.768 !

**Comment by jidanni** [comment]
Alas now showing London again. Today I'm coming from 114.26.47.27 .

**Comment by jidanni** [comment]
Oops. must have been cookie pollution from my last experiment. With a pristine browser the problem goes away.
