### ISSUE TITLE
Deprecated include of L.Mixin.Events: this property will be removed in future releases

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1598]
Please see https://github.com/openstreetmap/iD/issues/4199 ... which belongs here.

**Comment by tomhughes** [comment]
Please stop worrying about debug noise - there is always noise in the debug console!

In this case I believe it comes from third party components that are outside our immediate control. Obviously that may limit when we can update leaflet if those plugins are not updated but we are well aware of that.

**Comment by gravitystorm** [comment]
I'm going to reopen this, since the warnings appear dozens of times in each test run, and it's a needless distraction for our developers.

They originate from the [leaflet-locationfilter](https://github.com/kajic/leaflet-locationfilter) plugin that we include at [vendor/assets/leaflet-locationfilter.js](https://github.com/openstreetmap/openstreetmap-website/blob/master/vendor/assets/leaflet/leaflet.locationfilter.js). The plugin appears to be unmaintained, with the last update 4 years ago. We're running a patched version already (see https://github.com/kajic/leaflet-locationfilter/pull/23) so there's precedent for us patching the plugin further. 

However, it would be better to either get upstream to accept patches, or find a maintained fork, or find a replacement plugin. I'd like to reduce the amount of code we maintain, rather than adding further workarounds to other people's code, whenever possible.

**Comment by AntonKhorev** [comment]
`L.Mixin.Events` was removed in https://github.com/openstreetmap/openstreetmap-website/commit/fb53e2af4c2cb07176c54723affbf541dbac8bac. This of course doesn't change the unmaintained plugin use.
