### ISSUE TITLE
PUT on gpx_file in API does not remove old tags

### ISSUE THREAD

**Issue by HarelM** [openstreetmap/openstreetmap-website#1600]
I wanted to use the API in order to update a gpx_file details.
The following is my PUT command body:
```xml
<osm version='0.6' generator='OpenStreetMap server' copyright='OpenStreetMap and contributors' attribution='http://www.openstreetmap.org/copyright' license='http://opendatacommons.org/licenses/odbl/1-0/'>
      <gpx_file id='2466659' name='2014_02_15_1001_______________20140215_1001.gpx' lat='31.7165' lon='35.4505' visibility='private'>
          <description>2014-02-15 1001 עדינות צוקים__20140215_1001.gpx</description>
          <tag>tag0</tag>
      </gpx_file>
</osm>
```

When using the above on a gpx file that does not have tags everything works as expected but when the using it on a gpx file that already has a tag the previous tag is not removed.

The same effect can be achieved when running this command twice - `tag0` will be added twice.

**Comment by gravitystorm** [comment]
I can confirm this. The problem is around the building a [new_trace from the supplied xml](https://github.com/openstreetmap/openstreetmap-website/blob/9ed1fe2d781d50d2fb76124b488958f43b4c2f4e/app/controllers/trace_controller.rb#L266). The code for this sets the [id of the temporary trace to be the same as the existing trace](https://github.com/openstreetmap/openstreetmap-website/blob/9ed1fe2d781d50d2fb76124b488958f43b4c2f4e/app/models/trace.rb#L197), and then [builds the tags](https://github.com/openstreetmap/openstreetmap-website/blob/9ed1fe2d781d50d2fb76124b488958f43b4c2f4e/app/models/trace.rb#L212-L214). But the first call to trace.tags.build causes a load of the existing tags, before adding all the tags again from the xml.

To replicate in the rails console, using an existing trace:

```
irb(main):061:0> t
=> #<Trace id: 2, user_id: 1, visible: true, name: "trace 1", size: nil, latitude: nil, longitude: nil, timestamp: "2017-08-09 10:29:39", description: "2014-02-15 1001 עדינות צוקים__20140215_1001.gpx", inserted: false, visibility: "private">

irb(main):062:0> t.tags
  Tracetag Load (0.8ms)  SELECT "gpx_file_tags".* FROM "gpx_file_tags" WHERE "gpx_file_tags"."gpx_id" = $1  [["gpx_id", 2]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Tracetag gpx_id: 2, tag: "foo", id: 8>]>

irb(main):063:0> new = Trace.new
=> #<Trace id: nil, user_id: nil, visible: true, name: "", size: nil, latitude: nil, longitude: nil, timestamp: nil, description: "", inserted: nil, visibility: "public">

irb(main):064:0> new.id = 2
=> 2

irb(main):065:0> new.tags
  Tracetag Load (0.8ms)  SELECT "gpx_file_tags".* FROM "gpx_file_tags" WHERE "gpx_file_tags"."gpx_id" = $1  [["gpx_id", 2]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Tracetag gpx_id: 2, tag: "foo", id: 8>]>
```
So even though we haven't added any tags to `new` yet, it picks up the existing tags from `t`.


It seems a bit dangerous creating these trace objects from XML and setting the id of the temporary object to match an existing db record. We need to consider if there's a better approach.

For example, when updating a rails object normally, you load the existing one and update the attributes from the form data (e.g. `@diary_entry.update_attributes(entry_params)`), then run validations on the result. We don't normally create a temporary DiaryEntry object. The way the trace works currently is quite different, where we build a temporary Trace object, run validations as we parse the XML, and then copy the attributes over from the temporary object to the real one. I'm not sure if this approach has any benefits.

**Comment by HarelM** [comment]
Glad I'm not crazy :-)
Any time estimation on when I can expect a fix for this?
I'm guessing that the OSM site doesn't use this interface as I can see that when I edit a trace using the site it works well, I wonder if the code there can be used somehow...?

**Comment by gravitystorm** [comment]
@HarelM - sorry no estimates, I just do this as a hobby. But it's top of my priority list since it's clearly broken. You're correct that the website forms uses a different part of the code so it doesn't have the problem. I allude to the difference between the code for the forms and the code for the XML API in the final paragraph of my previous post (but I used the example of the `diary_entry` form to reduce confusion).

**Comment by HarelM** [comment]
Any updates on this issue? I'm hoping to open the ability to edit the tags from my site and this is currently a showstopper for this...

**Comment by gravitystorm** [comment]
I've created a pull request with one option to fix this, but I now need some feedback from other developers to see if it's the right approach.

**Comment by HarelM** [comment]
@gravitystorm Thanks!! keep me posted when a new version containing this fix will be published.

**Comment by HarelM** [comment]
When is this change going to be published?
Thanks for fixing this!

**Comment by tomhughes** [comment]
It should be live by now.
