### ISSUE TITLE
alias_method_chain deprecation

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#1602]
Currently we get warnings when running the tests:

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /home/andy/src/openstreetmap-website/config/application.rb:17)
```
As far as I can tell, this is being triggered by one or other of these two gems:

* [oauth](https://github.com/oauth-xx/oauth-ruby/blob/e397b3e2f540faaebd7912aeb2768835d151f795/lib/oauth/client/action_controller_request.rb#L21)
* [deadlock_retry](https://github.com/mperham/deadlock_retry/blob/874c80de92d9eb30405536916aff86f616649b01/lib/deadlock_retry.rb#L8)

In both cases there's not yet a newer version to upgrade to. The method [has been removed in rails 5.1](https://github.com/rails/rails/commit/7c848e6dd493ff236d33a0410a92f4c3e5cc3c7f) so I think this is blocking any upgrade.

**Comment by tomhughes** [comment]
Yes it's in the oauth gem. I did track it down and I'll probably monkey patch it when necessary though IIRC it's not very easy in this case which is why I haven't done it yet. In fact I think I decided I might need to fork the gem to do it sanely.

What we really need to do is move to oauth 2 and get rid of the oauth gem as it's basically unmaintained now.

**Comment by tomhughes** [comment]
Seems I remembered wrongly or I didn't actually identify the cause before - it's actually `deadlock_retry` that is the problem and it isn't monkey patchable because it is called at load time.

I have now published a fixed version as [openstreetmap-deadlock_retry](https://rubygems.org/gems/openstreetmap-deadlock_retry) which we use to work around this - the original has not been updated for five years and recent PRs have been closed on the grounds that it is no longer supported.

**Comment by mmd-osm** [comment]
@tomhughes : the PR is quite old...  `bundle exec rails test` seems to work without deadlock_retry Gem these days. Was there some other reason to add it back then? Can we retire it?
