### ISSUE TITLE
Don't play hide and seek with the marker

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1607]
Visit
http://www.openstreetmap.org/search?query=24.12475%2C120.87723#map=18/24.12475/120.87723

Move the pointer slowly over the side panel.

Notice a marker appears when the pointer crosses the words 24.12475, 120.87723, and then again when the pointer crosses the words "Taiwan , Taiwan".

Now attempt to take a screenshot with the marker.

To take a screenshot one must remove the pointer from the two magic lines that make the marker appear, in order to use the pointer to do the screenshot work.

See how frustrating this all is. 

Google would never dream of making a marker appear and disappear.

Please keep the marker there at all times.

**Comment by jidanni** [comment]
Yes, one can do everything above nicely from the SHARE panel.
I know that.
I am talking about the main window operations.

**Comment by mmd-osm** [comment]
Whatever tool you use to take screenshots, how about defining a keyboard shortcut. On Ubuntu, I just press Shift-Print and get this nice screenshot w/o any hassle.

![grafik](https://user-images.githubusercontent.com/5842757/28987180-7f95e3c6-796a-11e7-81b2-54e8f962a3ef.png)

**Comment by tomhughes** [comment]
It a deliberate design decision that I don't see any particular need to revisit - as @mmd-osm says most people use PrtScr or equivalent to take screenshots precisely because it's often impossible to move the pointer to a screenshot button. That is hardly unique to osm.

The alternative would be making people click on entries to highlight them on the map but that makes it much harder to scan through a list of results.

**Comment by jidanni** [comment]
I shouldn't have even mention screenshot. I'm just talking about it the general case of stability of the things on the screen.
