### ISSUE TITLE
The map on the iMac Retina 4K is not clear

### ISSUE THREAD

**Issue by hdd064** [openstreetmap/openstreetmap-website#1623]
The map on the iMac Retina 4K is not clear
<img width="2048" alt="screen shot 2017-08-29 at 9 32 18 am" src="https://user-images.githubusercontent.com/1020603/29819883-bfa5b11e-8cd7-11e7-9687-f0e0a94ff406.png">

**Comment by tomhughes** [comment]
This isn't an issue for this repository - as far as I know leaflet is quite capable of display retina tiles but there are no such tiles for us to display.

Realistically it's unlikely to happen until we move to vector tiles, which is an issue for the people working on the map rendering. We don't really have the resources to be rendering two sets of bitmap tiles.

**Comment by gravitystorm** [comment]
Is it worth trying it out first with the Cycle and Transport layers? Both are available as retina tiles, and this might help find any bugs in advance of retina tiles being available for the Standard layer.

Retina tiles are available for those layers by adding @2x just before the extension, e.g. `https://tile.thunderforest.com/cycle/14/8181/5450@2x.png?apikey=....`

![5450 2x](https://user-images.githubusercontent.com/360803/29821967-c150af16-8cc1-11e7-9eaf-633fe3ad8066.png)

**Comment by hdd064** [comment]
All Map layers have the same problem

**Comment by tomhughes** [comment]
@hdd064 yes we know, but the map layers themselves are not run by use (as in this repository) so we can only do anything about it where the map layer supports it.

@gravitystorm do you know how we get leaflet to do that? if not then I'll have a look, but I imagine it will need a change at https://github.com/jfirebaugh/leaflet-osm rather than here.

**Comment by tomhughes** [comment]
Looks like the answer is to extend the layer definitions with:

```
retina: '@2x',
detectRetina: true
```

I'll give it a try this evening when I'm at home and using my laptop that has a hidpi display...

**Comment by tomhughes** [comment]
So there are actually two different things you can do - you can add `{r}` to the URL template which will expand as `@2x` on hidpi displays, so that is what we need to do for @gravitystorm's layers.

You can also set `detectRetina: true` on a layer, which will cause it to fetch four tiles from the next higher zoom. That doesn't work very well though as you wind up with very thin roads and small text.

**Comment by tomhughes** [comment]
I've opened https://github.com/jfirebaugh/leaflet-osm/pull/17 to update leaflet-osm.
