### ISSUE TITLE
map page: unfocus search bar when pressing '-' or '+'

### ISSUE THREAD

**Issue by zepatrik** [openstreetmap/openstreetmap-website#1629]
I don't know about you but when I load the map page the first thing I do is zoom out to go to the desired location or search for it. The second use case is comfortably handled by the autofocused input, but for the first one the map has to be in focus. So why not make an exception when starting to type with a `-` or `+` so the zoom function of those buttons is conserved while still allowing to search right away? I don't think there is any use case you would want to start a search with those two symbols.

**Comment by tomhughes** [comment]
Seems like an extremely niche use case and extremely confusing behaviour if some keys cause the focus to change in mysterious ways instead of inputting into the field that has focus.

I don't know about you, but I basically never use use the +/- buttons, and I certainly never trigger them from the keyboard like that - in fact I didn't even know you could! I either zoom using the mouse wheel (or touchpad equivalent) or by shift-dragging to zoom in.

**Comment by HolgerJeromin** [comment]
My baby aged daughter showed me that i can use the cursor keys to move the map :-)

**Comment by zepatrik** [comment]
Actually, what would you expect to happen when you use the `-` or `+` keys? - zoom
Regardless of what's focused because your brain focuses the map and not the search bar. If you want to search for something you go to the input. Having the input focused on load is maybe convenient because some people might want that and something has to be focused, so why not the search bar. When you use the mouse to navigate the map the focus changes anyways, but the keys for navigating are not supported on load. And that behavior is unexpected, I think. Nobody pressing the zoom keys would even notice because in the brain the map is already focused.
