### ISSUE TITLE
How to get .osm or .pbf using local database

### ISSUE THREAD

**Issue by nafis042** [openstreetmap/openstreetmap-website#1636]
hello, I need help on how to generate .osm or .pbf file using my local database. So, what I have done so far 
I ran openstreetmap-website server and its running fine. I can add new road and the data is saved in my lcoal database named openstreetmap. Now I want to download the updated data in .osm or .pbf format.How can I do this?

Actually what I want is build a tile server. If I have the .osm or .pbf file then I can easily create tile server using osm2pgsql. Is there any way around?

**Comment by woodpeck** [comment]
You can use osm2pgsql to produce a data dump from your live database. With osm2pgsql you can also generate diffs (osc files) that represent the changes since the last run. The OSM website uses a different approach for full planet dumps nowadays, namely creating a database dump (backup) with pg_dump and then running https://github.com/zerebubuth/planet-dump-ng on that dump.

**Comment by tomhughes** [comment]
This is not a bug report.

**Comment by nafis042** [comment]
@woodpeck can you give me a detail walkthrough how to produce data dump from database?

**Comment by tomhughes** [comment]
Not here no - this is a topic for https://help.openstreetmap.org/ or for one of the mailing lists or IRC or frankly pretty much anywhere that isn't a bug tracker.
