### ISSUE TITLE
can't append osm data into database

### ISSUE THREAD

**Issue by nafis042** [openstreetmap/openstreetmap-website#1638]
at first I upload data into database using this command-
osmosis --read-pbf previous.osm.pbf \
  --write-apidb host="localhost" database="openstreetmap" \
  user="postgres" password="postgres" validateSchemaVersion="no"
and its working fine. Next I produce a diff.osc.gz using following command-
osmosis --read-pbf latest.osm.pbf --read-pbf previous.osm.pbf --derive-change --write-xml-change diff.osc.gz
Then I use the following command to append data into database-
osmosis --read-xml-change diff.osc.gz --write-pgsql-change user="postgres" database="openstreetmap" password="postgres" validateSchemaVersion="no"
It shows me following error:
SEVERE: Thread for task 1-read-xml-change failed
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT id, name FROM users WHERE id = ?]; nested exception is org.postgresql.util.PSQLException: ERROR: column "name" does not exist

Am I doing something wrong? what is the right procedure?

**Comment by tomhughes** [comment]
This is the openstreetmap-website issue tracker. Osmosis issues should be raised at https://trac.openstreetmap.org/newticket in the "osmosis" component.

**Comment by tomhughes** [comment]
I would just add that if your `users` table doesn't have a `name` column then something is very, very wrong with your rails port install.

This is not the place for support issues for the rails port install either  - this is a bug tracker. if you need help setting up an instance of the rails port then IRC or the mailing lists are better places to seek help.

**Comment by fazlerabbi37** [comment]
@tomhughes I followed the same process and got the same error. Yet I am writing here because you mentioned in the last comment that ' if your `users` table doesn't have a `name` column then something is very, very wrong with your rails port install'. I installed rails port twice but couldn't find any `name` column in `user` table. All the columns I could find on `user` table are `email`, `id`, `pass_crypt`, `creation_time`, `display_name`, `data_public`, `description`, `home_lat`, `home_lon`, `home_zoom`, `nearby`, `pass_salt`, `image_file_name`, `email_valid`, `new_email`, `creation_ip`, `languages`, `status`, `terms_agreed`, `consider_pd`, `auth_uid`, `preferred_editor`, `terms_seen`, `description_format`, `image_fingerprint`, `changesets_count`, `traces_count`, `diary_entries_count`, `image_use_gravatar`, `image_content_type` and `auth_provider`. Can you please help me out? Thanks in advance !

**Comment by tomhughes** [comment]
Sorry that was wrong, the column is called `display_name` not `name`.

So your osm2pgsql is obviously buggy and you need to talk to them not us.

**Comment by fazlerabbi37** [comment]
@tomhughes thanks !

**Comment by gravitystorm** [comment]
You’re using `—write-pgsql-change` which is for writing changes to the osmosis “simple” schema. Try `—write-apidb-change` instead.
