### ISSUE TITLE
Add note and comment counts too the user profile

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1643]
On Profile, one sees
```My Edits 508 My Notes My Traces 20 My Diary 0 My Comments My Settings```
this should be
```My Edits 508 My Notes 2 My Traces 20 My Diary 0 My Comments 0 My Settings```
else it looks broken.

**Comment by tomhughes** [comment]
Choosing not to show counts for some things isn't "broken" it's just a design decision and/or a sign that nobody has yet offered code to do it.

**Comment by gravitystorm** [comment]
I really don't think being inconsistent is a design decision (or if it is, it's not a good one). I think this is a valid issue and I'd be happy to see a pull request adding the notes and comments count.

**Comment by jidanni** [comment]
@gravitystorm Maybe group the items with counts together, then a divider, then the items without counts.
That way it wouldn't look so haphazard while it is waiting for a final solution.
But alas as this bug has been officially closed, that all doesn't matter anymore.

**Comment by tomhughes** [comment]
@gravitystorm Oh agreed and I would have no real problem with such a pull request, though it's not completely trivial, but this bug didn't say "please show counts for xxx" but instead started from an incorrect assumption that somehow they were meant to be there but just weren't showing up.

Basically this should be a phrased as a feature request rather than a bug report, so I will rephrase it as one and reopen.

To be honest I thought there was already a ticket for this but I can't see it right now.

**Comment by AntonKhorev** [comment]
Now we have an upper bound of notes count shown instead of the actual notes count. These numbers are different if the user interacted with any note more than once.
