### ISSUE TITLE
Italian translation error

### ISSUE THREAD

**Issue by NonnEmilia** [openstreetmap/openstreetmap-website#1646]
At [this line](https://github.com/openstreetmap/openstreetmap-website/blob/30392717b9095f6852a190dbc11f8bf4727bacdf/config/locales/it.yml#L2361) of the _it.yml_ file the `{distance}` and `{unit}` variables were translated in italian (becoming `{distanza}` and `{unità}`) breaking the location feature of the italian website with this error message:

> Error: No value provided for variable {distanza}

[I've already correct the italian translation in Translatewiki](https://translatewiki.net/w/i.php?title=Osm:Javascripts.map.locate.popup/it&oldid=7624706).

**Comment by tomhughes** [comment]
Well if you've made the correction in Translatewiki then there is nothing more to do - it will come through to the site next time they push changes.

**Comment by mmd-osm** [comment]
Looking through at the history for translation updates (https://github.com/openstreetmap/openstreetmap-website/commits/master/config/locales), this used to work fairly smoothly on a ~ weekly schedule until about end of May 2017, and then suddenly stopped. No more updates since about 4 months now. According to https://translatewiki.net/w/i.php?title=Special:RecentChanges&limit=500&namespace=1222&days=30&translations=only there were plenty of changes in the meantime.

@Nikerabbit is this expected, or did the automatic update maybe break for some reason?

**Comment by Nikerabbit** [comment]
I was going to ask to put a new public key in place since I stopped using my personal key and started using a dedicated key for translation updates. At some point I forgot that I need to do that and I am sorry about that. I will do an audit for all our projects to finish the migration. Where/to whom should I send the new key?

**Comment by tomhughes** [comment]
@Nikerabbit Just open a PR to changed https://github.com/openstreetmap/chef/blob/master/cookbooks/accounts/files/default/translatewiki/.ssh/authorized_keys I think?

**Comment by mmd-osm** [comment]
@Nikerabbit : great stuff, update seems to be working again 🚀

**Comment by Nikerabbit** [comment]
Thanks for poking me. You can expect approximately two updates per week from now onwards.
