### ISSUE TITLE
add ability to edit GPX tracks in the online editor

### ISSUE THREAD

**Issue by obama** [openstreetmap/openstreetmap-website#1649]
i would like an ability to edit the submitted GPX tracks right from the online editor. 
so you can remove very inaccurate portions for instance, or for privacy reasons.
because when you use mobile apps to submit tracks you can't edit them conveniently before upload.
(well you could export to PC before but its not convenient)

**Comment by tomhughes** [comment]
I don't think that's ever likely to happen because we keep the tracks exactly as they were uploaded - so if you upload a zip containing three gpx files then that is exactly what we have on disk.

So while we could in theory allow the imported version of the track to be edited the original raw files would still be available for download which would defeat the purpose of this if privacy was the issue.

So sadly I think we're going to have to say this is out of scope.
