### ISSUE TITLE
Allowed to contribute at Zoom Level 24, but enjoy the results at only 19

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1672]
User adds details to shopping centers using Zoom Level 24 in the editor.

Upon save he sees

```
Your changes should appear in the "Standard" layer in a few minutes.
Other layers, and certain features, may take longer.
View on OSM
```

Now he clicks "View on OSM" but is frustrated that all his hard work has
gone to naught, as he cannot zoom past Zoom Level 19. A whole five zoom
levels less than he was "cheated" into using in the editor.

"What is the point of me adding fine detail if nobody can see it?" He
thinks.

Turning to Google Maps he sees he can zoom all the way to zoom level 21.

Back at the OSM website he finds that indeed the Humanitarian Layer can
be zoomed to 20, but that is all.

**Comment by tomhughes** [comment]
Nothing to do with this repository.

**Comment by SomeoneElseOSM** [comment]
@ jidanni Still nothing to do with this repository, but zoom 24 works for me (see http://www.openstreetmap.org/user/SomeoneElse/diary/39423).  Rather more widely available are the mobile apps that most people actually use to view OSM data, many of which support higher effective zooms.

**Comment by gravitystorm** [comment]
> Nothing to do with this repository.

I think we can expand on that slightly, both so that @jidanni has more information and perhaps he can find a way forward. "Teach a man to fish", and all that.

 There are three aspects to increasing the max zoom shown on the main page:

* The style should support a particular zoom 
* The servers should support a particular zoom
* This repo should support a particular zoom

For example, the Thunderforest servers support zoom 22, but in all honesty above around 19 or 20 the cartography doesn't really work currently. This repo uses 18 for Thunderforest layers. It could be increased in [leaflet.osm.js](https://github.com/openstreetmap/openstreetmap-website/blob/33845759acf79dc9a0c8460e6363d767bcd86847/vendor/assets/leaflet/leaflet.osm.js).

With the standard layer, the style works reasonably well up to 19 or 20 (a rough rule of thumb is to check is with the maximum zoom levels handled by the [roads](https://github.com/gravitystorm/openstreetmap-carto/blob/master/roads.mss) layers), but the servers run by the OSMF are [limited to zoom 19](https://github.com/openstreetmap/chef/blob/79d28ce14b4c7cf3d964d07879928cd2811fd01c/roles/tile.rb#L94). It might seem straightforward to bump that up a few levels, but such a change would probably be rejected by the server admins. The currently used technology (mod_tile) stores all rendered tiles on disk before returning them to the client, so someone trying to download e.g. z24 for the UK could cause serious side effects! 

My feeling would be that for OSMF to support z20 or higher would need to wait on a more significant technology shift on the OSMF rendering servers, which would allow rendering ultra high zoom tiles on the fly. This is most likely through server-side rendering from vector tiles. If and when that's available, then this repo can be updated with a new maximum zoom.

I hope you find this a useful explanation.

**Comment by tomhughes** [comment]
Yes that's more or less correct (though actually there's nothing much to do in this repo bar updating a vendored library I think). The steps would be:

* Check that the style guys are happy it would render ok
* Get operations to provision sufficient hardware
* Update renderd config in chef
* Update leaflet-osm
* Updated vendored leafet-osm here

In reality the first two steps are the issue and if those were done the rest would get taken care of.

As @gravitystorm suggests however the real solution is likely to be some sort of vector tile based solution.

**Comment by woodpeck** [comment]
Not only does the currently used technology store all tiles on disk; the file names are generated from the x/y coordinates in a way that only works for zoom levels up to 20. If one wanted to support zoom 21, not only would the servers have to be configured to allow it, but the hashed file name structure used by renderd/mod_tile would have to be adapted (something that @SomeoneElseOSM had to do in order to make his example work).

**Comment by SomeoneElseOSM** [comment]
I'm happy to provide more info about what I did to add higher zoom level support to https://map.atownsend.org.uk/maps/map/map.html via https://github.com/SomeoneElseOSM/SomeoneElse-style/tree/master and https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT , both technically (including ensuring old tiles get removed, extra disk usage) and with the style (e.g. adding more gradual changes to road widths), but some other forum is likely to be the better place for it.  If you ask on the help site I can try and give a "chapter and verse" entry there.

**Comment by jidanni** [comment]
@SomeoneElseOSM  I am very happy mobile editing works for you from your mobile
devices. I prefer to enter my shopping center mapping from the comfort
of desktop.

You see each retailer in the shopping center has an "stall" address (number)
which would be great to have on OSM. Alas I will suspend my project for
now.

I suspect it all boils down to "OSM's goals in life."

Zoom levels of many years ago might no longer "be competitive".

Indeed, a fine level of detail is where OSM could "beat the
competition."

With the Suggestions at the bottom of
http://www.wolfpil.de/v3/deep-zoom.html we see that perhaps maybe a more
dynamic system could be used: different maximum zoom levels for
different areas. (I'm not sure of how this would work out with WMTS
`<ZoomLevel>int_value</ZoomLevel>`, etc.)

**Comment by jidanni** [comment]
See also https://developers.google.com/maps/documentation/static-maps/intro#Zoomlevels .

**Comment by tomhughes** [comment]
Well partly it boils down to our goals, but equally it boils down to whether anybody is stepping up to do the work to build a vector tile stack.

**Comment by jidanni** [comment]
2020 update: I'm always checking my mouse: why is it jammed at 19? Oh yeah, forgot...
