### ISSUE TITLE
layer control - zooming bug

### ISSUE THREAD

**Issue by obama** [openstreetmap/openstreetmap-website#1673]
after selecting a base layer and than using + or - key to zoom it zooms the minimap preview instead of the main view.

**Comment by tomhughes** [comment]
Eh? We don't have a minimap preview?

**Comment by tomhughes** [comment]
Confirmed that + and - work for me, and as I say we don't have any sort of minimap.

Are you sure this is www.openstreetmap.org that you're talking about?

**Comment by tomhughes** [comment]
Oh I see what you mean - you mean if you select a layer in the layer panel. Well I think that's really what I'd expect - the keys act on the map that has focus so just like you need to click on the main map before you can use keyboard controls (otherwise they go to the search box) if you click on a different map then that will get focus and will act on keyboard controls.

I mean we could (and possibly should) disable keyboard controls on those maps but the main map would still have lost focus and hence wouldn't see the keypresses.
