### ISSUE TITLE
Issue Installing Creating Function

### ISSUE THREAD

**Issue by ScottDWagner** [openstreetmap/openstreetmap-website#1709]
I am trying to use this command but getting error:
psql -d openstreetmap -c "CREATE FUNCTION maptile_for_point(int8, int8, int4) RETURNS int4 AS '`pwd`/db/functions/libpgosm', 'maptile_for_point' LANGUAGE C STRICT"

Error: 
ERROR:  could not access file "/openstreetmap-website/db/functions/libpgosm": No such file or directory

the file is there and is available.

**Comment by tomhughes** [comment]
So use the correct path then - the `pwd` in the fragment you quoted is supposed to be the current working directory as output by the `pwd` command.

**Comment by zerebubuth** [comment]
More detail, in case it's helpful: The `pwd` command stands for Print Working Directory, and the intention is to replace the `` `pwd` `` with the full path to the directory where `openstreetmap-website` is checked out. For example, when I check out the repository as `/home/matt/Programming/OSM/openstreetmap-website`, then I would run:

```
psql -d openstreetmap -c "CREATE FUNCTION maptile_for_point(int8, int8, int4) RETURNS int4 AS '/home/matt/Programming/OSM/openstreetmap-website/db/functions/libpgosm', 'maptile_for_point' LANGUAGE C STRICT"
```

Hope that helps.

**Comment by ScottDWagner** [comment]
I tried that as well even verified the pathway still the same error.

**Comment by gravitystorm** [comment]
The path looks strange to me - postgres is trying to find the code in a directory at the system root. I'd normally expect it to be in /home/username/ or /usr/local/src/ or something like that - rather than in '/openstreetmap-website'.

Assuming the code is actually in '/openstreetmap-website', then are you using encrypted partitions? The postgres system process needs to access the libpgosm.so file, and on my old laptop with an encrypted home drive, the postgres process didn't have access to the code. Instead I copied the .so file to /tmp and used that instead.

To debug further, I'd suggest doing `sudo su postgres` or whichever user your postgres runs as, and seeing if you can figure out why that user doesn't have access to the directory. Please note that it's the system user of the postgres server, not the user that you use to access postgres, that's important here.

Please let us know how you get on!

**Comment by ScottDWagner** [comment]
will do checking it now.

**Comment by gravitystorm** [comment]
@ScottDWagner Did you manage to get this problem resolved?

**Comment by gravitystorm** [comment]
Closing since there's no reply - @ScottDWagner feel free to comment if you still need help.
