### ISSUE TITLE
Why are some diff uploads slow?

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/openstreetmap-website#1710]
As pointed out in [this comment](https://github.com/openstreetmap/operations/issues/154#issuecomment-353475540) by @mmd-osm, diff uploads are buffered in memory before being processed. However, [another comment](https://github.com/openstreetmap/operations/issues/154#issuecomment-353289168) points out that some transactions can take up to 2 hours to process. This seems strange, given that it should just be parsing the XML (which is slow, but not that slow) and talking to the nearby database (which is also slow, but not that slow).

To investigate further, we need to find a recent diff upload that took a long time to process. That should give us some clues to start with.

**Comment by Komzpa** [comment]
Can we get a slowlog published?

```
shared_preload_libraries = 'auto_explain'
auto_explain.log_min_duration = '100ms'
auto_explain.log_nested_statements = on
auto_explain.log_analyze = on
```

It also seems we can have transactions up to 1M seconds, or 12 days: 
https://munin.openstreetmap.org/openstreetmap/karm.openstreetmap/postgres_querylength_openstreetmap_9_5_main.html

It can also be a reading transaction, say, a forgotten open psql on terminal.

`statement_timeout` and `idle_in_transaction_session_timeout` can help limit it, so it becomes application error traceable in application logs.

To get distribution of queries and keep sanity reading endless postgres logfiles: https://github.com/dalibo/pgbadger

**Comment by tomhughes** [comment]
Please don't confuse things @Komzpa - as you yourself admit there are lots of reasons for long postgres transactions that have nothing to do with changeset uploads.

A slow log isn't going to help unless the delay is down to a single statement and in any case trying to sanitise a slow log for publication is not a reasonable request.

I'm already working on @zerebubuth request so how about we cut out the back seat debugging long enough to let me investigate...

**Comment by tomhughes** [comment]
So to get back to the point, the longest upload I can see yesterday was about 503 seconds or just over 8 minutes.

That was changeset 54833679 and it had a total elapsed time of 503868ms and an activerecord time of 237165.8ms.

**Comment by tomhughes** [comment]
I've now gone back over all the logs we have, which is basically a week, and the longest I see is changeset 54716666 which has an elapsed time of 1028520ms or around 17 minutes and an activerecord time of 524142.0ms.

**Comment by mmd-osm** [comment]
My analysis last year (https://github.com/drolbr/Overpass-API/issues/346#issuecomment-266299854) was based on the number of minutely state.txt files, a particular transaction number appeared in the `txnActiveList` list of active transactions.

It could be that some other transaction that is unrelated to the upload process also shows up in that txnActiveList. I think it would probably to a good idea to cross check those results by going through all minutely diff file contents, to see how much of a delay we experience in the worst case. Let's see if I can get those figures.

**Comment by tomhughes** [comment]
Well every week you will get a day long transaction when the backup is running just as a start.

**Comment by tomhughes** [comment]
I think the background autovacuum jobs also cause random very long transactions as well.

**Comment by zerebubuth** [comment]
Thanks @tomhughes!

[Changeset 54833679](http://www.openstreetmap.org/changeset/54833679) has 1465 ways and 3103 nodes, which is large but doesn't seem excessive.

Do you know how the 237s in activerecord breaks down? Can we assume that's all database and network time, or is activerecord doing any significant processing?

It looks, from the timestamps of the nodes and ways in that changeset, that they span the whole 8 minutes. Which would seem to imply the other 266s is spent in per-element processing on the node. I'm not aware of any external requests that are happening (i.e: non activerecord ones), so the implication appears to be it's in the parsing code?

The next step will be for me, or anyone else who wants to help, to reproduce this locally as part of a test or other automated process so that we can analyse it more thoroughly.

**Comment by tomhughes** [comment]
There's no breakdown - rails just logs a value which I assume is the total time it spent executing statements.

I've just pushed https://github.com/openstreetmap/chef/commit/0d5f8536e0ddf09a6b923e1bc01f79f27e3ba05d to enable basic logging of any statement taking over a second. If that isn't too noisy we can think about reducing the time and if that isn't enough we can think about enabling `auto_explain` but I image the plan won't change much so we can probably just explain the statements later.

**Comment by mmd-osm** [comment]
I think It was a good idea to take a look at the minutely diff contents rather than just checking `txnActiveList`. I don't seem to find those extreme cases anymore with 2++ hours runtime anymore. These really seem to originate from unrelated processes like backup or vacuum.

However, we still have minutely diffs, where the first and last timestamp differs by as much as 32 minutes (one example: http://www.openstreetmap.org/changeset/43755443). Those should be good candidates for further performance analysis.

I'm processing all minutely diffs in directory `002/*/*` now, which will still take a while to complete. The list below is just a snapshot after an hour or so. Will be updated again once finished.

Filename | Earliest TS | Latest TS | Delta
-- | -- | -- | --
002/190/051.osc.gz  | 2016-11-18T06:47:49Z | 2016-11-18T07:20:00Z | 00:32:11
002/468/973.osc.gz  | 2017-05-31T02:18:07Z | 2017-05-31T02:48:59Z | 00:30:52
002/086/408.osc.gz  | 2016-09-06T23:33:52Z | 2016-09-07T00:03:06Z | 00:29:14
002/468/764.osc.gz  | 2017-05-30T22:51:51Z | 2017-05-30T23:20:08Z | 00:28:17
002/273/775.osc.gz  | 2017-01-15T11:20:48Z | 2017-01-15T11:47:02Z | 00:26:14
002/468/490.osc.gz  | 2017-05-30T18:20:03Z | 2017-05-30T18:46:14Z | 00:26:11
002/468/560.osc.gz  | 2017-05-30T19:32:07Z | 2017-05-30T19:56:12Z | 00:24:05
002/748/051.osc.gz  | 2017-12-11T00:08:20Z | 2017-12-11T00:31:53Z | 00:23:33
002/468/367.osc.gz  | 2017-05-30T16:21:53Z | 2017-05-30T16:43:15Z | 00:21:22
002/397/331.osc.gz  | 2017-04-11T08:11:43Z | 2017-04-11T08:32:02Z | 00:20:19
002/468/609.osc.gz  | 2017-05-30T20:26:06Z | 2017-05-30T20:45:10Z | 00:19:04
002/048/419.osc.gz  | 2016-08-11T13:40:17Z | 2016-08-11T13:59:00Z | 00:18:43

**Comment by mmd-osm** [comment]
I ran a very small local test based on [Changeset 53407241](http://www.openstreetmap.org/changeset/53407241), which took around 15 minutes via JOSM upload. Most CPU time was spent on _puma 001_ process (rails). On the console I noticed a rather large number of single row INSERT/DELETE/UPDATE operations:

  - Each single node (for current and old nodes)
  - Each single tag
  - Each single node in a way
  - Frequent checks for current changeset

Overall, I'm also suspecting shared/exclusive locks to contribute to the larger overall processing time on the server. With long running transactions, chances increase that other people start working on the same objects.

I think it's time for a bit out of the box thinking, and leaving the current implementation behind for a minute. That's why I gave [pyosmium](http://osmcode.org/pyosmium/) and some bulk SQL statements a short try.

The same 8MB diff file was completely parsed in 140ms. Based on this I generated some bulk insert statements, effectively creating all 4300+ nodes in one go:

```sql
BEGIN;
INSERT INTO "current_nodes" ("latitude", "longitude", "changeset_id", "visible", "timestamp", "tile", "version") VALUES
(423712730, -832172277, 19, 't', '2017-12-24 09:15:27.204641', 1234, 1),
(423712670, -834339064, 19, 't', '2017-12-24 09:15:27.204675', 1234, 1),
(423715247, -832172360, 19, 't', '2017-12-24 09:15:27.204684', 1234, 1),
(423715140, -834339084, 19, 't', '2017-12-24 09:15:27.204691', 1234, 1),
(423717479, -834339184, 19, 't', '2017-12-24 09:15:27.204697', 1234, 1),
(423672264, -832171144, 19, 't', '2017-12-24 09:15:27.204704', 1234, 1),
(423672601, -834336964, 19, 't', '2017-12-24 09:15:27.204710', 1234, 1),
(423674831, -832171161, 19, 't', '2017-12-24 09:15:27.204717', 1234, 1)
[...many more...]
 RETURNING (id);
COMMIT;
```

This query only took a few hundred ms on my local db (not much in there). The number of entries  (=package size) in one such INSERT statement could of course be made configurable, and the returned node ids used for later replacement operations. They could even be stored in a temporary table.

Regarding modify and delete operations, a huge part of the task is to pull data node by node, tag by tag out of the database, and INSERT it in the history table. I wonder, why we don't let the database do this job and only provide a list of object ids to do the copying in one go. This takes maybe a few seconds.

Here's a very rough idea:

```sql
insert into node_tags ( select node_id, version, k, v from current_node_tags t
inner join current_nodes n on t.node_id = n.id where id in (   19302,   19301,   19300,   
19299,   19298,   19297,   19296,   19295,   19294,   19293,   19292,   19291,   19290,   19289,   
19288,   19287,   19286,   19285,   19284,   19283,   19282,   19281,   19280,   19279,   19278,   
19277,   19276,   19275,   19274,   19273,   19272,   19271,   19270,   19269,   19268,   19267,   
19266));
```

I'm far away from understanding all of the details in the current implementation. Nevertheless, I think there's a lot of potential for improvement here, although it could mean that we can't reuse much of the current implementation. Wouldn't that be a good fit for cgimap?

**Comment by zerebubuth** [comment]
> Wouldn't that be a good fit for cgimap?

Possibly. I've added [an issue](https://github.com/zerebubuth/openstreetmap-cgimap/issues/140) so that we can track it there. If anyone would like to help out with the implementation, please do!

**Comment by mmd-osm** [comment]
BTW: There's a test version available on a dedicated server now, see this diary post for details: https://www.openstreetmap.org/user/mmd/diary/44318

**Comment by mmd-osm** [comment]
I think we can close this issue, I just merged changeset upload into cgimap-0.7.0-rc1.

**Comment by mmd-osm** [comment]
Code is also deployed on https://master.apis.dev.openstreetmap.org for further testing.

**Comment by mmd-osm** [comment]
Issue can be closed, see https://operations.osmfoundation.org/2019/05/31/may.html

**Comment by mmd-osm** [comment]
Overlapping minutely diffs (Delta Max Timestamp previous diff vs. Min Timestamp current diff)

Delta | Count | Percentage  | Percentage of Total
-- | -- | -- | --
No Overlap | 392301 | 86,67 % | 86,6690%
00:00:00 | 58086 | 12,83 % | 99,5016%
00:00:01 | 601 | 0,13 % | 99,6344%
00:00:02 | 138 | 0,03 % | 99,6649%
00:00:03 | 254 | 0,06 % | 99,7210%
00:00:04 | 181 | 0,04 % | 99,7610%
00:00:05 | 63 | 0,01 % | 99,7749%
00:00:06 | 121 | 0,03 % | 99,8016%
00:00:07 | 86 | 0,02 % | 99,8206%
00:00:08 | 39 | 0,01 % | 99,8292%
00:00:09 | 91 | 0,02 % | 99,8493%
00:00:10 | 28 | 0,01 % | 99,8555%
00:00:11 | 52 | 0,01 % | 99,8670%
00:00:12 | 45 | 0,01 % | 99,8769%
00:00:13 | 28 | 0,01 % | 99,8831%
00:00:14 | 54 | 0,01 % | 99,8951%
00:00:15 | 28 | 0,01 % | 99,9012%
00:00:16 | 11 | 0,00 % | 99,9037%
00:00:17 | 26 | 0,01 % | 99,9094%
00:00:18 | 19 | 0,00 % | 99,9136%
00:00:19 | 33 | 0,01 % | 99,9209%
00:00:20 | 18 | 0,00 % | 99,9249%
00:00:21 | 13 | 0,00 % | 99,9278%
00:00:22 | 21 | 0,00 % | 99,9324%
00:00:23 | 27 | 0,01 % | 99,9384%
00:00:24 | 10 | 0,00 % | 99,9406%
00:00:25 | 18 | 0,00 % | 99,9445%
00:00:26 | 9 | 0,00 % | 99,9465%
00:00:27 | 18 | 0,00 % | 99,9505%
00:00:28 | 11 | 0,00 % | 99,9529%
00:00:29 | 6 | 0,00 % | 99,9543%
00:00:30 | 16 | 0,00 % | 99,9578%
00:00:31 | 15 | 0,00 % | 99,9611%
00:00:32 | 7 | 0,00 % | 99,9627%
00:00:33 | 22 | 0,00 % | 99,9675%
00:00:34 | 3 | 0,00 % | 99,9682%
00:00:35 | 10 | 0,00 % | 99,9704%
00:00:36 | 11 | 0,00 % | 99,9728%
00:00:37 | 3 | 0,00 % | 99,9735%
00:00:38 | 13 | 0,00 % | 99,9764%
00:00:39 | 11 | 0,00 % | 99,9788%
00:00:40 | 3 | 0,00 % | 99,9795%
00:00:41 | 8 | 0,00 % | 99,9812%
00:00:42 | 4 | 0,00 % | 99,9821%
00:00:43 | 3 | 0,00 % | 99,9828%
00:00:44 | 2 | 0,00 % | 99,9832%
00:00:46 | 6 | 0,00 % | 99,9845%
00:00:47 | 5 | 0,00 % | 99,9856%
00:00:48 | 1 | 0,00 % | 99,9859%
00:00:49 | 2 | 0,00 % | 99,9863%
00:00:50 | 3 | 0,00 % | 99,9870%
00:00:51 | 2 | 0,00 % | 99,9874%
00:00:52 | 5 | 0,00 % | 99,9885%
00:00:53 | 1 | 0,00 % | 99,9887%
00:00:54 | 3 | 0,00 % | 99,9894%
00:00:55 | 1 | 0,00 % | 99,9896%
00:00:56 | 1 | 0,00 % | 99,9898%
00:00:57 | 2 | 0,00 % | 99,9903%
00:00:58 | 2 | 0,00 % | 99,9907%
00:00:59 | 2 | 0,00 % | 99,9912%
00:01:01 | 1 | 0,00 % | 99,9914%
00:01:03 | 1 | 0,00 % | 99,9916%
00:01:05 | 2 | 0,00 % | 99,9920%
00:01:06 | 2 | 0,00 % | 99,9925%
00:01:08 | 4 | 0,00 % | 99,9934%
00:01:10 | 1 | 0,00 % | 99,9936%
00:01:13 | 1 | 0,00 % | 99,9938%
00:01:15 | 1 | 0,00 % | 99,9940%
00:01:17 | 1 | 0,00 % | 99,9943%
00:01:23 | 1 | 0,00 % | 99,9945%
00:01:25 | 3 | 0,00 % | 99,9951%
00:01:27 | 2 | 0,00 % | 99,9956%
00:01:32 | 1 | 0,00 % | 99,9958%
00:01:35 | 1 | 0,00 % | 99,9960%
00:01:46 | 2 | 0,00 % | 99,9965%
00:01:48 | 1 | 0,00 % | 99,9967%
00:02:05 | 1 | 0,00 % | 99,9969%
00:02:39 | 1 | 0,00 % | 99,9971%
00:02:57 | 1 | 0,00 % | 99,9973%
00:03:06 | 1 | 0,00 % | 99,9976%
00:03:44 | 1 | 0,00 % | 99,9978%
00:06:01 | 1 | 0,00 % | 99,9980%
00:06:18 | 1 | 0,00 % | 99,9982%
00:06:20 | 1 | 0,00 % | 99,9985%
00:06:33 | 1 | 0,00 % | 99,9987%
00:06:34 | 1 | 0,00 % | 99,9989%
00:06:43 | 1 | 0,00 % | 99,9991%
00:07:30 | 1 | 0,00 % | 99,9993%
00:10:11 | 1 | 0,00 % | 99,9996%
00:20:08 | 1 | 0,00 % | 99,9998%
00:21:21 | 1 | 0,00 % | 100,0000%


Filename | Diff
-- | -- 
004/110/479.osc.gz | 00:21:21
004/235/753.osc.gz | 00:20:08
004/235/745.osc.gz | 00:10:11
004/110/492.osc.gz | 00:07:30
004/392/025.osc.gz | 00:06:43
004/267/357.osc.gz | 00:06:34
004/235/744.osc.gz | 00:06:33
004/071/016.osc.gz | 00:06:20
004/110/477.osc.gz | 00:06:18
004/071/125.osc.gz | 00:06:01
004/071/012.osc.gz | 00:03:44
004/380/692.osc.gz | 00:03:06
004/071/071.osc.gz | 00:02:57
004/235/746.osc.gz | 00:02:39
004/139/607.osc.gz | 00:02:05
004/069/950.osc.gz | 00:01:48
004/071/107.osc.gz | 00:01:46
004/069/945.osc.gz | 00:01:46
004/376/183.osc.gz | 00:01:35
004/277/670.osc.gz | 00:01:32
004/376/873.osc.gz | 00:01:27
004/264/037.osc.gz | 00:01:27
004/448/005.osc.gz | 00:01:25
004/264/036.osc.gz | 00:01:25
004/162/566.osc.gz | 00:01:25
004/235/742.osc.gz | 00:01:23
004/382/165.osc.gz | 00:01:17
004/164/862.osc.gz | 00:01:15
004/442/132.osc.gz | 00:01:13
004/105/931.osc.gz | 00:01:10
004/382/272.osc.gz | 00:01:08
004/234/113.osc.gz | 00:01:08
004/160/321.osc.gz | 00:01:08
004/128/673.osc.gz | 00:01:08
004/380/696.osc.gz | 00:01:06
004/286/010.osc.gz | 00:01:06
004/240/256.osc.gz | 00:01:05
004/235/747.osc.gz | 00:01:05
004/071/084.osc.gz | 00:01:03
004/436/934.osc.gz | 00:01:01
