### ISSUE TITLE
Favorite editor: add iD previews?

### ISSUE THREAD

**Issue by bagage** [openstreetmap/openstreetmap-website#1722]
Would it be possible to add iD previews ([stable](preview.ideditor.com/release) and [development](preview.ideditor.com/master)) as alternate choices in the user profile preferences? 
Releases are made every 6 months so it'd be cool if we could use preview instead to get new features quicker?

**Comment by gravitystorm** [comment]
It's certainly not 6 months between iD releases. You can see how often iD is updated in this codebase at https://github.com/openstreetmap/openstreetmap-website/commits/master/vendor/assets/iD

I would be against having development releases in the user preferences here, since I have no idea whether they are ready for mainstream use or not - perhaps they have bugs or similar. In order to tell which versions are stable enough, we wait for the maintainer to tag a release!

Overall, I feel like if you want to "get new features quicker" then you should instead persuade the iD developers to release more often. Or am I misunderstanding something?

**Comment by tomhughes** [comment]
I agree - the whole point of the iD making releases is to indicate when they think it's ready for the general population to use. In the meantime they provide external sites where you can use a preview version.

Adding preview versions to the main site would just confuse the majority of users who know nothing about the development process.

**Comment by bagage** [comment]
Yeah, I agree it wasn't sure it was a good idea either :).
