### ISSUE TITLE
Regarding GSOC 2018

### ISSUE THREAD

**Issue by biswesh456** [openstreetmap/openstreetmap-website#1729]
I am a second year computer science student. I have been looking into the organisation and want to contribute to it during GSOC 2018. I have knowledge of Ruby on rails, Java, C++ , Javascript, python and some other language. I was looking for some project to work in Ruby on rails. 

Here is a site built by me along with one of my friend. It uses Javascript and Rails(for backend):
https://circuitverse.org/ 
I have also worked on some other projects.

Can I be given some issues to solve so that I can get to know about the code well. I would also like to know if there are some good projects that I can take for GSOC 2018 and where should I start from so that I can prepare myself for the project.

I couldn't get any mean to communicate my doubts hence I have opened up this issue regarding the same. I would be grateful for any help!!!

**Comment by tomhughes** [comment]
This does not appear to be a bug report - if you wan't to discuss GSOC then please contact whoever is organising it this year, which isn't us.

**Comment by zerebubuth** [comment]
Hi @biswesh456,

Welcome!

We don't tend to assign issues to individuals in this repo. The best way to get started would be to look through the (rather large) [list of open issues](https://github.com/openstreetmap/openstreetmap-website/issues) and find one that you think you can solve. It's generally best, especially if the issue is not under active discussion, to add a comment laying out your approach to solving the issue. If you would like some help, feel free to mention either myself (@zerebubuth) or @gravitystorm and we'll do our best to explain the code that's already there, or give suggestions for how to approach new code.

A quick look suggests we have some issues that would be straightforward to solve:

* #1699 - The issue is that the "more" links to the same place as the name of the track. This should be a simple fix, although might need some shepherding through the PR stage if there are differences of opinion. The lack of discussion on the issue could mean it's uncontroversial, but doesn't guarantee that!
* #1689 - The issue is that email addresses in the tags for objects in the "browse pages" aren't linkified. It seems highly likely to me that either exists already as part of Rails, or someone has written a gem for it. The issue may be whether to only highlight links on `email` tags, or apply it more generally. As with anything linkified, it presents the potential for link farm abuse, but emails perhaps less so than arbitrary links.
* #1676 - The issue would be to link the GPX trace's start coordinate "map" link to one which has the marker enabled (see `mlat` & `mlon` query parameters). Seems like a useful addition, unlikely to be controversial.
* #1644 - The issue here is that sometimes we call GPX traces "traces" and sometimes "tracks" in the web interface. We don't want to change any of the URLs, so this should be a matter of reviewing all the instances of "track" in the translation text and changing them, where appropriate, to "trace".
* #1625 - This would mean making the delete link for traces visible to admins and moderators, and allowing them permission to run that action. At the moment, it's only visible and permitted for the user who originally uploaded the trace. As @tomhughes points out in the discussion, it wouldn't be a "power tool" for moderators, but it's a good addition for when small numbers of traces need to be deleted.


Some that are slightly more involved:

* #1702 - The issue is that we're not calling `set_locale` in enough places. This would require an audit of all the API calls to make sure that it's being called on every path. The best place to start would be to write tests which reproduce the issue reported, and check every API call route.
# 1663 - The issue is the placement of the "centre" of the map display on small / mobile screens. The behaviour appears to be different across different browsers, making it difficult and time-consuming to verify the fix, and the lack of regressions on other platforms.

That's just the first page of 12! Feel free to dig back further in the issue list to find things of more interest. Although beware that the older an issue is, the more likely it is for the the information in it to be out of date. It's always worth discussing a solution before implementing it, just in case it's no longer relevant, has already been fixed but the issue hasn't been updated, or there's more to it than meets the eye.

Good luck :smile:

**Comment by biswesh456** [comment]
Thanks @zerebubuth for taking out your time and giving me an idea about all the issues you have mentioned above. I would look into these issues and would try to solve them.
