### ISSUE TITLE
Quirk on changeset bbox calculation

### ISSUE THREAD

**Issue by TimSC** [openstreetmap/openstreetmap-website#1742]
I'm not sure this is a bug but there seems to be something strange when modifying a way to include an extra node. See TestInsertNodeIntoWay function in osmbbox.py https://gist.github.com/TimSC/2b22f9f41a4d86978501c7cc9b82b224

The changeset bbox seems to extend beyond any of the nodes that are used by the way. Any idea why this might be?

**Comment by mmd-osm** [comment]
Seems to be intentional as part of some optimization attempt: https://github.com/openstreetmap/openstreetmap-website/blob/2c52c91b393f087df60c3f6765905cbc8248e3e7/app/models/changeset.rb#L130-L140

**Comment by zerebubuth** [comment]
Yup, it is intentional behaviour. Whether it's still the best behaviour is a good question. Since the code now keeps a running count of the number of changes within the changeset itself: https://github.com/openstreetmap/openstreetmap-website/blob/b5ff4bfbe658fc21f2cf038809fd696d92b1f8f7/app/models/changeset.rb#L142-L148 then this behaviour is simply confusing.

It looks like we would get more predictable behaviour just by leaving the `EXPAND` parameter out and allowing `margin` to default to zero, although there'd probably need to be adjustments to the test suite. https://github.com/openstreetmap/openstreetmap-website/blob/b5ff4bfbe658fc21f2cf038809fd696d92b1f8f7/lib/bounding_box.rb#L35

**Comment by TimSC** [comment]
Thanks for the info!

**Comment by mmd-osm** [comment]
https://github.com/openstreetmap/openstreetmap-website/blob/161ce947c3b753f68f5c6b27fea369d2e2b8c7ea/test/controllers/changeset_controller_test.rb#L622

`cs.max_lat >= 90`  doesn't seem right and doesn't match the assert error message, probably a typo. Went unnoticed due the expansion logic.

I created a patch now to get rid of this logic altogether, including fixing the test suite issues.
