### ISSUE TITLE
Sort search results from GeoNames

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1881]
https://www.openstreetmap.org/search?query=南富村

```
Results from GeoNames
Nanfucun , China

Nanfu , Taiwan

Nanfu , Taiwan

Dananbu , Taiwan

Siwan , Taiwan

Shi’ergu , Taiwan

Shalao , Taiwan

Nanfu , Taiwan

Nanfu , Taiwan

Sheliao , Taiwan

Shezijiao , Taiwan

Nanfucun , China

Nanfucun , China

Nanfu , Taiwan

Xiaohushan , Taiwan

Haizikou , Taiwan

Waisiwan , Taiwan

Shatu Shan , Taiwan

Shangpingjiao , Taiwan

Houshixiao , Taiwan
```

1. Please sort the list, any way you like. But at least sort it.
2. No need for space before comma.
3. No need for empty lines after each line
4. Show a third component, when lines are the same. Don't just hope
the user will mouuseover to see the coordinates.

**Comment by tomhughes** [comment]
Frankly we should probably just get rid of the geonames results now.

**Comment by tomhughes** [comment]
There isn't a blank line by the way - there is a thing grey separator. That's the same for all search results and it would be inconsistent to make geonames different.

As to sorting I've always assumed geonames returns them in some sort of order of what it thinks is most likely - this is an unusual case because normally most of the results would start with the string you entered so sort wouldn't do much. I'm not sure how it's chinese search is working that it returns such diverse responses...

**Comment by gravitystorm** [comment]
I'd be happy to see Geonames removed too - OpenStreetMap has good enough placename coverage in most of the world nowadays.

**Comment by tomhughes** [comment]
Geonames support has now been removed by #3886 so this is no longer relevant.
