### ISSUE TITLE
Add address from the enclosing building to node information

### ISSUE THREAD

**Issue by SelfishSeahorse** [openstreetmap/openstreetmap-website#1901]
When querying POIs, it would be handy if the address from the enclosing building (and, if existing, from enclosing ZIP/place multipolygons) were displayed.

![untitled](https://user-images.githubusercontent.com/14875493/41456489-e645c0ba-7080-11e8-8060-0665724fe1c8.png)
![untitled2](https://user-images.githubusercontent.com/14875493/41456490-e67be546-7080-11e8-972b-b3a5b31ef386.png)

**Comment by tomhughes** [comment]
I don't think this is appropriate - those views are meant as views of the raw data and it would be confusing to mix in data from different objects.

On top of that there is no way to do it from the main database - we would have to call out to an external service like overpass to get that information.

If you want to know about enclosing features then we already have the query tool which can do that (by calling out to overpass) and I don't think it would be appropriate to make the data browser do it as well.

**Comment by Marc-marc-marc** [comment]
the website already propose it via a right click "show address" but it's not user-friendly.
in case of poi, it's maybe a good idea to have a least link "show addr" just under the tag of this poi.
it would avoid that many contributors duplicate the tag addr on the poi thinking to add a useful info that it is nevertheless present but not visible enough

**Comment by tomhughes** [comment]
Show address is slightly different - that does a reverse geocode using Nominatim and the result might actually be something nearby rather than anything that encloses the object.

**Comment by Marc-marc-marc** [comment]
you are right, it's slightly different.
it need another issue to talk about it ? or maybe a more generic one for all implicit addr tag for all poi and building objets

**Comment by das-g** [comment]
Related discussion on [[talk-ch] mailing list](http://lists.openstreetmap.ch/pipermail/talk-ch/2018-May/thread.html#9523) (continued [here](http://lists.openstreetmap.ch/pipermail/talk-ch/2018-June/thread.html#9576)).

(My) TL;DR summary: Some mappers feel that there should be a straight-forward way to get a POI's "address" (even for POIs that don't have one of their own, like most fountains) so that when one would like to direct someone there who has a navigation device that only takes addresses as destination inputs, you can give them that address.

(IMHO this should be fixed in those navigation devices and they should accept WGS84 coordinates, too.)

**Comment by Marc-marc-marc** [comment]
my idea was not to choose how people should or should not tag objects and how much duplicate info should or should not be added.
My idea was an ergonomic improvement. instead of the user having to guess that additional information is available with a right click on the object, add the link for the "show addr" feature to make it more user-friendly.

**Comment by SelfishSeahorse** [comment]
My idea wasn't to add the address tags from the enclosing building to the tags table of the POI, but rather to add them below 'Location', as this:

Edited 4 months ago by SelfishSeahorse
Version #3 · Changeset #56289965
Location: 46.3205660, 6.8761158
**Address: Rue de la Lanche 8, 1899 Vionnaz, Switzerland**

**Comment by das-g** [comment]
That changeset changes many objects. I guess you're referring to the [bakery "Boulangerie Guérin"](https://www.openstreetmap.org/node/4189254948/history)?

**Comment by SelfishSeahorse** [comment]
@das-g: Yes, I was referring to the first screenshot (https://www.openstreetmap.org/node/4189254948):

![untitled](https://user-images.githubusercontent.com/14875493/41456489-e645c0ba-7080-11e8-8060-0665724fe1c8.png)
