### ISSUE TITLE
OpenID sign in does not work due to CSP

### ISSUE THREAD

**Issue by miklcct** [openstreetmap/openstreetmap-website#1909]
I can't sign in OpenStreetMap website because when I try to type in my OpenID, the website refuses to send form data to the address I have typed in due to content security policy.

The only way I can sign in is to use a browser extension to temporary bypass the restriction.

**Comment by cweiske** [comment]
I have the same problem in Chromium 68. In Firefox 61, login via OpenID still works.

Error message in Chromium:

> Refused to send form data to 'http://id.cweiske.de/' because it violates the following Content Security Policy directive: "form-action 'self'".

**Comment by cweiske** [comment]
This still happens on Chromium 71.

**Comment by tomhughes** [comment]
In theory this should be fixable by sending the redirect as a `303 See Other` so that Chrome does it as a GET and doesn't resubmit the body but it still seems to complain.

I think the only other fix is to split the form in two so we can avoid the redirect :-(

**Comment by tomhughes** [comment]
Even that doesn't work because it sees a GET form to `/auth/openid` that redirects to the OpenID provider as sending form data to that provider and blocks it.

Note that firefox is fine with all of this because it treats redirected forms differently for CSP validation.

I'm a bit stuck for a solution at the moment, short of allowing that page to send form data to the entire internet.

**Comment by cweiske** [comment]
Thank you for the quick fix! OpenID login works fine now on Chromium 72.
