### ISSUE TITLE
Make straight line drawing an extra choice for Directions

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#1941]
Here's a great way to implement distance measurement:
In Directions, beside Grasshopper and OSRM choices, have also "Great Circle".

Finally users could draw constant path lines like Google Static Maps on https://wiki.debconf.org/wiki/DebConf18/121st_meridian_east .

**Comment by tomhughes** [comment]
As I have explained a number of times, the web site exists to support mapping activity and not to provide an end user replacement for google maps or qgis.

I don't see any significant use for this function as part of the everyday work of our users in mapping the world.

**Comment by jidanni** [comment]
https://www.bing.com/ has Measure Distance in the right context menu.

**Comment by jidanni** [comment]
https://maps.baidu.com/ has it in the upper right menu.

**Comment by jidanni** [comment]
https://support.google.com/maps/answer/1628031?co=GENIE.Platform%3DDesktop&hl=en

**Comment by gravitystorm** [comment]
@jidanni If you can show how this feature would help OpenStreetMap editors improve the data, then great. Otherwise it doesn't really matter that it's a feature used on other websites.

**Comment by jidanni** [comment]
(OK, but adding Directions doesn't help OpenStreetMap editors improve the data either.)

**Comment by HolgerJeromin** [comment]
> (OK, but adding Directions doesn't help OpenStreetMap editors improve the data either.)

Mapper can easy check if roads really connected or if a turn restriction is mapped.

**Comment by Adamant36** [comment]
@tomhughes, can you guys walk and chew bubble gum at the same time or something? Well I get that the website is "mostly" to aid mappers, it doesnt mean there arent people come there to view the map also once in a while. I know I do sometimes. Just because you impliment a few viewer centric features, like better viewing on mobile where you took the same stance for not implimenting that issue, doesnt automatically make you a competitor to Google. I dont get why there is such a phobia about it anyway, even if it did. Plus, you would think making it more user friendly, whatever end its on, would inharently bring in more editors. Which would be a good thing. Being openly hostile toward a segement of the websites users by discounting every feature they might benefit from off hand definitely isnt going to help bring in more editors though. Especially not those people you refuse to catter to for no other reason then that you don't feel like it.

**Comment by jidanni** [comment]
Yeah. Maybe the site should just be mappers only -- login if you want to
use it. Like Facebook. That way nobody would ask for the ability to draw
a line from A to B.

**Comment by Adamant36** [comment]
@jidanni, I do think if there is going to be a map viewable map before people login that it should be friendly to people viewing it. Otherwise, yeah it should behind a login screen and only accessible to mappers. Not everyone that comes along to the site. Then knowone would want to edit the map because they couldnt see what they might be editing before creating an account. So yeah I totally agree, if thats what your getting at.
