### ISSUE TITLE
Retire irc.openstreetmap.org from links, use webchat.oftc.net

### ISSUE THREAD

**Issue by grischard** [openstreetmap/openstreetmap-website#1981]
@dwfreed who helps run OFTC recently came onto #osm to ask us to stop running our own irc webchat:

04:54:41                     dwfreed hey guys, please don't host your own webchat
04:54:52                     dwfreed it makes managing abuse a lot harder
04:55:10                     dwfreed (I help run OFTC)
04:56:32                     dwfreed use https://webchat.oftc.net/?channels=osm
05:01:12                     dwfreed if somebody encounters that and decides to start abusing it, I'll have to kill everybody using it
05:01:36                     dwfreed because it looks like everybody connecting through it uses the same host
05:01:55                     dwfreed our webchat will show the user's real IP address

AFAICT, the main place where people find out about the irc webchat is the 'help' tab. The difference between cgiirc and webchat.oftc.net is that we would no longer [prepopulate the channel list with all local channels](https://github.com/openstreetmap/chef/blob/bff262debe7a3c7fb831433066c17028bb5d9e06/cookbooks/cgiirc/templates/default/cgiirc.config.erb), but on the other hand we could link to e.g. https://webchat.oftc.net/?channels=osm-dk directly from the Danish locale and it would work.

People do use the cgiirc page to get onto #osm-dev often, #openrailwaymap sometimes, #osm-de rarely, #osm-fr and #osm-ie never.

**Comment by simonpoole** [comment]
IMHO even toughing the current setup makes no sense, if we want to revamp things I would just getting rid of the web ui and running our own (not necessarily meaning that this needs to be run on osmf hw and by the sys admins) matrix home server with a riot install. While this is clearly more resource intensive in more that one way, it would remove arguments for slack and so on.

**Comment by tomhughes** [comment]
This is mostly an operations issue rather than a web site issue so this would probably be better opened there - yes there will a few minor edits needed to the web site but killing or replacing irc.osm.org is an ops job.

**Comment by gravitystorm** [comment]
The cgiirc instance was removed in March 2020, and replaced by a small static website that allows users to pick a channel from a list, and then uses webchat.oftc.net from there. 

https://github.com/openstreetmap/chef/commit/5844c5bc2edf22e4d6a4316f887adf758584a008

While this doesn't cover the topic of direct connection to specific channels based on locale, that's a different can of worms entirely (we run location-based channels, not language-based ones!). 

So I'm happy to close this issue since the original problem - running our own cgiirc instance - is resolved.
