### ISSUE TITLE
Usernames of deleted users are visible on /changeset/ID

### ISSUE THREAD

**Issue by Nakaner** [openstreetmap/openstreetmap-website#2024]
The original username of a suspended account is visible on the website. See the bottom of the sidebar in the following screenshot.

![username-visible](https://user-images.githubusercontent.com/3611273/46789351-7fc2ba00-cd3c-11e8-89f3-57261152cba8.png)

https://www.openstreetmap.org/changeset/62984233

**Comment by dieterdreist** [comment]
And we should redact names, phonenumbers and email adresses from such
account names. Someone might set up an account "Dieterdreist is a bitch" or
"call 123 for first class peanuts in Zanzibar". Admittedly this becomes
difficult if we don't have admins that understand the language of the
account name.

**Comment by tomhughes** [comment]
I'm not entirely sure what you're suggesting, and it doesn't really appear to relate to this ticket, but we're not going to get into to trying to blacklist certain words from account names!

**Comment by Nakaner** [comment]
@tomhughes In the past, changeset pagination was possible for those users but their username was replaced by `user_{{uid}}`. It was helpful to review changesets by a deleted account (sometimes vandals or users who cannot get along with valid criticism delete their account before their damage has been cleaned up completely). Now you disabled pagination at all.

I don't know when the username became visible but a few months ago user_uid was visible only. I assume that the visibility of the username was a side-effect of some other change (refactoring?).

**Comment by tomhughes** [comment]
No that replacement was never done at display time, but I can understand why you thought it was. There are in effect three possible states:

* Suspended, where the user state is set to `suspended` either automatically by the spam score or manually by an administrator.
* Hidden, where the user state is set to `deleted` by an administrator.
* Deleted, where the user state is set to `deleted` and personal information is cleared from the user record by an administrator.

The last case is where `user_XXX` will appear, because that is what the display name is changed to when a user is deleted.

For spammers I normally use hide so as to preserve details while account closure requests use delete instead so that personal information is removed.

**Comment by mmd-osm** [comment]
> In the past, changeset pagination was possible for those users but their username was replaced by user_{{uid}}

@Nakaner : as [some old comments suggest](https://github.com/openstreetmap/openstreetmap-website/issues/1311#issuecomment-264628206), even though it looked like pagination worked for those users, it wasn't really the case. Following the link took you to some error page instead.
