### ISSUE TITLE
Redaction title can be blank.

### ISSUE THREAD

**Issue by RoyallDesigns** [openstreetmap/openstreetmap-website#2033]
@1v0ryh4t and I found that when creating a new redaction under `/redactions/new`, the redaction title is allowed to be blank. When attempting to view said redactions under `/redactions`, the new redaction is not present or viewable under the list as its title or name is an empty string. I would like to add a validation to a `redaction` so that when creating or editing the `redaction`, the name can never be blank. (This seems like a decent `good-first-issue` for myself.)

Please see the attached images.

![notitleredactioncreation](https://user-images.githubusercontent.com/41215187/47397923-97684e00-d6ff-11e8-8e0c-b1267067f9a8.png)
![redactionsscreen](https://user-images.githubusercontent.com/41215187/47397929-9b946b80-d6ff-11e8-9e90-46f08170ace2.png)

All redactions (`/redactions`):

![redactions_list](https://user-images.githubusercontent.com/41215187/47398054-3a20cc80-d700-11e8-97ca-7b6729bb9671.png)

**Comment by gravitystorm** [comment]
I think it's reasonable to require a title, should we also consider making the description required too?

I checked the [original pull request](https://github.com/openstreetmap/openstreetmap-website/pull/39) for adding redactions, and I couldn't find any discussion as to whether titles and/or descriptions should be optional. I'd be interested in feedback from any openstreetmap.org moderators, who have the most experience with creating redactions. Personally I think it would be fine to require both attributes to be present.

**Comment by tomhughes** [comment]
I think it's clear a title should be required and I'd be inclined to say a description should be as well.

I'm surprised I didn't insist on it at the time - it must have slipped by me when I was reviewing this.

**Comment by rileythomp** [comment]
Does this still need to be worked on?

**Comment by SomeoneElseOSM** [comment]
> I'd be interested in feedback from any openstreetmap.org moderators

Creating new redactions isn't something that we need to do that often, thankfully -the last one I did was a couple of years ago I think - https://www.openstreetmap.org/redactions/102 .  I'd always expect to use a title and description.

**Comment by sonukushwaha403** [comment]
is this issue open can i work on it

**Comment by gravitystorm** [comment]
> is this issue open can i work on it

Yes, the issue is open and can be worked on. Please also read through the [previous pull request](https://github.com/openstreetmap/openstreetmap-website/pull/2034) for more information.

**Comment by BLSowmya** [comment]
is this issue open  and can i work on it ???

**Comment by gravitystorm** [comment]
@BLSowmya Yes, the issue is open and you are welcome to work on it.

**Comment by IshmeetSingh06** [comment]
Hey @gravitystorm If this issue has not been picked up by anyone, I'm going to work on it, after reading the previous PR comments I want confirmation about some things:
1. We want ensure the presence of Title and Description both,
2. For missing titles and description we need fill them up with the id of the redaction?
3. In a single migration we have to backfill our data and change the column null to false right?
4. Since we are using strong migrations do we need to change null first and then Validate it inside a seperate migration as stated by the strong migration documentation?

**Comment by gravitystorm** [comment]
> We want ensure the presence of Title and Description both,

Yes please

> For missing titles and description we need fill them up with the id of the redaction?

I would suggest "Redaction #{id}" (i.e. the word "Redaction" followed by the id number) as the title, and "No description" as the description. But it's not super important since I don't think there are many (any?) on the osm.org servers. It might affect other deployments though.

> In a single migration we have to backfill our data and change the column null to false right?
> Since we are using strong migrations do we need to change null first and then Validate it inside a seperate migration as stated by the strong migration documentation?

Yes, whichever approach works best with strong migrations. See https://github.com/ankane/strong_migrations?tab=readme-ov-file#setting-not-null-on-an-existing-column

Thanks for looking into this!

**Comment by IshmeetSingh06** [comment]
@gravitystorm Thanks for the clarification's I'll start working on it

**Comment by tomhughes** [comment]
Model validations were added in 873ac155cabfb1aab8d887d07bc8389617d3f843 without realising that they fixed this.
