### ISSUE TITLE
Adjust testing instructions for change from rcov to simplecov

### ISSUE THREAD

**Issue by krubokrubo** [openstreetmap/openstreetmap-website#2066]
The [testing instructions in Contributing.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md) say you can generate test coverage stats with: `sudo gem install rcov; rcov -x gems test/*/*.rb`

However, [rcov does not work with Ruby 1.9+](https://github.com/relevance/rcov/issues/99) and says to use simplecov instead.  Ideally, Contributing.md should be updated with the best practice for how to do so.  I figured out [one way to do it](https://github.com/lemurheavy/coveralls-public/issues/881) but I'm not sure if it's the best practice.

**Comment by tomhughes** [comment]
I'm not sure who even put that in there to be honest - the coverage stuff is only really in there for travis and I never expected anybody to run it locally. I certainly don't.

**Comment by gravitystorm** [comment]
I think I've figured out a way to get both to work at the same time. Reading through the coveralls code, it [sets its own formatter](https://github.com/lemurheavy/coveralls-ruby/blob/8121b40c691821b919846bf17346511459caee57/lib/coveralls.rb#L50) when you run `Coveralls.wear!`. So the multiformatter stuff needs to come after that point.

Here's my proposed solution:

https://github.com/gravitystorm/openstreetmap-website/commit/d43315f738a415823c42e4b7d3df83c1d3aa9263

@krubokrubo does this also work for you?

If so, then I propose that we run both local simplecov generation, and the coveralls stuff, by default. 

However, since local code coverage statistics are not of much interest to most people, I would like to try to silence the simplecov summary output when the tests are run (probably by making a custom formatter and/or overriding the [output_message](https://github.com/colszowka/simplecov-html/blob/a9fe0369d62e95fb9cc838c912346e483b4f4a30/lib/simplecov-html.rb#L28-L30) method). If there's a simple way to suppress this message, then I can make a pull request.

**Comment by tomhughes** [comment]
The [coveralls suggestion](https://docs.coveralls.io/ruby-on-rails#simplecov-customization) seems to be to just setup the formatters yourself and then call `start` instead of `wear!`.

**Comment by tomhughes** [comment]
I have to say I'm not sure how that would work though...

**Comment by krubokrubo** [comment]
@gravitystorm @tomhughes So far I didn't understand the difference between `start` and `wear!`, but the proposed solution gravitystorm@d43315f is working fine for me, and I appreciate how it makes the instructions simpler in Contributing.md.

(For what it's worth, I don't see a need to suppress the "Coverage report generated" message...from my perspective, this message actually helps clarify the next message about "Outside the CI environment, not sending data".)
