### ISSUE TITLE
Allow more zoom in the standard view

### ISSUE THREAD

**Issue by tsdgeos** [openstreetmap/openstreetmap-website#2094]
For some reason the humanitarian layer allows for more zoom which means you can see shops that are closer together, e.g. compare
https://www.openstreetmap.org/#map=19/41.37363/2.10585
with
https://www.openstreetmap.org/#map=20/41.37370/2.10547&layers=H

In the second you can see both Merca Cama and La Bona Gent while in the first you can only see La Bona Gent.

**Comment by simonpoole** [comment]
This is an attribute of the layer being displayed: the maximum zoom level supported by the tile server operator, and yes for the "Humanitarian" layer that is more than for the the standard style. 

So this would be both an operational (because of increased resources required for rendering) and rendering issue (because the style would need some adaptions for another zoom level) and would need to be discussed in the corresponding issue trackers. 

That said, I wouldn't hold my breath for that as vector tiles are a better approach for very high zoom rendering and I would suspect that most people would want to defer any such change till that is in place.

**Comment by tsdgeos** [comment]
@simonpoole "That said, I wouldn't hold my breath for that as vector tiles are a better approach for very high zoom rendering and I would suspect that most people would want to defer any such change till that is in place."

Is there an issue tracking that?

**Comment by tomhughes** [comment]
Well there is https://github.com/openstreetmap/operations/issues/214 but basically it's a big project not a simple "issue" with a quick fix.

**Comment by tsdgeos** [comment]
This is github, these things are called issues, i understand it's not fixed by adding a ; somewhere. Don't get upset. Happy 2019
