### ISSUE TITLE
truncate will remove users

### ISSUE THREAD

**Issue by perosoft** [openstreetmap/openstreetmap-website#2112]
I have an imported openstreetmap for my local network, and working great.
Now problem for updates.
With truncate&populate i lost accounts for edit maps.

How can i have this:
1. save accounts
2. truncate database
3. populate database
4. restore accounts

**Comment by mmd-osm** [comment]
it's not clear what you're trying to achieve. It sounds a bit like you want to run `truncate table changesets cascade;` before running a backup/restore of your database?

Maybe you could try adding more details in your mother tongue if that's easier for you.

**Comment by tomhughes** [comment]
Why remove the accounts in the first place. If you want to keep them then don't remove them and you won't need to restore them.

If whatever tool you are using to populate the database requires you to remove them then this is something you would need to ask the author of that tool about - why do they not allow you to keep them in place?

Otherwise you will need to make your own arrangements to save and restore those users as what you are doing is not something that is supported by us because it is not required for our use of the code.

**Comment by mmd-osm** [comment]
FWIW, I frequently use `truncate table changesets cascade;` to clean up my local changesets, [old] nodes, ways, relations,. It keeps all user accounts around, but removes any "mapping related" data.
