### ISSUE TITLE
Vagrant: cannot find bundler executable

### ISSUE THREAD

**Issue by mvexel** [openstreetmap/openstreetmap-website#2149]
`vagrant up` fails because the `bundle` executable cannot be found:

```
    default: /usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe'
    default: :
    default: can't find gem bundler (>= 0.a) with executable bundle
    default:  (
    default: Gem::GemNotFoundException
    default: )
    default: 	from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
    default: 	from /usr/local/bin/bundle:23:in `<main>'
```

I think this is because the `Gemfile.lock` has 

```
BUNDLED WITH
   1.16.2
```

which is not the version that is installed by default. manually installing that specific bundler gem version seems to remedy the situation.

I'm filing as an issue because I don't know enough about ruby packaging to suggest a fix.

**Comment by tomhughes** [comment]
No idea I'm afraid. Pretty sure it's not what you think though but there's not enough context in that error to say any more.

**Comment by mvexel** [comment]
I'm going by someone else having the [exact same problem](https://stackoverflow.com/a/54038218) and noting that as the culprit.

**Comment by tomhughes** [comment]
Well maybe, but if that is the problem then there is no realistic solution - we need to install the bundle to get the right version but we also need to know the right version to install the bundle? See the problem...

So unless we update `Vagrantfile` every time we update the bundle with the correct version, which we're never going to remember to do, then I don't see a solution.

Plus, you know, we do this all the time when deploying and it works fine, as it does when I am developing.

**Comment by tomhughes** [comment]
The real problem is https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html I think and is because the rubygems version is too old to support the logic in bundler 2.x that tries to handle bundle 1.x generated bundles.

So installing an old bundler without that logic fixes it as does a newer rubygems that fixes that, but our `Vagrantfile` is used the system rubygems but installing bundler itself.

A temporary workaround is likely to force bundler 1.x without actually specifying an exact version.

This also explains why I haven't seen it, because this is all quite new with the bundler 2.x release.
