### ISSUE TITLE
The meaning of "Reply to this entry" is not clear

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/openstreetmap-website#2166]
Its not really clear what "reply to this entry" does. It sounds like its replying to diary entry, but its sending the person a private message. So it would be clearer if it if said something like "Write user message" or something similar that explicitly says your sending them a message. Instead of just leaving one on the diary entry like "comment on this entry" does. 

Also, the usage of "reply" is kind of ambiguous in this situation because the communication hasn't actually been initiated yet. So your not really "replying" to anything in the traditional sense.

**Comment by mmd-osm** [comment]
Ok, so you're talking about https://www.openstreetmap.org/diary 

How about  "Contact the author"?

**Comment by Adamant36** [comment]
Yep. "Contact the author" would totally work.

**Comment by ConSou** [comment]
Hello, I can make this adjustment if no one has started on it already.

**Comment by gravitystorm** [comment]
I would prefer "Send a message to the author" or even "Send a message to %{display_name}", since that makes it even clearer what the link does. We use the phrasing "send a message" and similar elsewhere on the site when referring to messages, so it would be good to promote consistency. As far as I can see when we say "contact" it's in documentation not specifically referring to the messaging system.

There's also two places this should be changed. The first is on the diary pages (`app/views/diary_entries/_diary_entry.html.erb`) and the second is on the diary comment notification emails.
