### ISSUE TITLE
Link secondary WIkipedia tags - brand:wikipedia, operator:wikipedia, subject:wikipedia etc

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#2184]
Currently wikipedia article specified in `wikipedia` tag is linked in tag list.

But there are also secondary Wikipedia tags like `subject:wikipedia` that are not linked. It would be desirable to create link for both cases.

![Selection_006](https://user-images.githubusercontent.com/899988/54638391-3e70cc00-4a8b-11e9-9406-4d9127cfbc80.png)

![Selection_007](https://user-images.githubusercontent.com/899988/54638430-4cbee800-4a8b-11e9-823a-910631fa9b4a.png)

See https://www.openstreetmap.org/node/5167698292 and https://www.openstreetmap.org/node/1350073645

See https://wiki.openstreetmap.org/wiki/Key:wikipedia#Secondary_Wikipedia_links

See https://taginfo.openstreetmap.org//search?q=%3Awikipedia

`brand:wikipedia`, `operator:wikipedia`, `species:wikipedia`, `subject:wikipedia`, `name:wikipedia`, `architect:wikipedia`, `artist:wikipedia`, `name:etymology:wikipedia` are probably ones worth linking

**Comment by HolgerJeromin** [comment]
Ref #788

**Comment by nachanon** [comment]
This bug is still reproducible.

I have recently added an OpenStreetMap node-type POI representing a memorial statue ([`historic=memorial`](https://wiki.openstreetmap.org/wiki/Tag:historic=memorial),[`memorial=statue`](https://wiki.openstreetmap.org/wiki/Tag:memorial=statue)) with information on the person statue represents in the  in the [`subject:wikipedia`](https://wiki.openstreetmap.org/wiki/Key:subject:wikipedia) key, using the same format as [`wikipedia`](https://wiki.openstreetmap.org/wiki/Key:wikipedia) tag.

But as soon as I tried to verify the entered entry on main OpenStreetMap interface, I found that the [`subject:wikipedia`](https://wiki.openstreetmap.org/wiki/Key:subject:wikipedia) key's name was properly linked to its OSM Wiki description, **but the key's value is not linked to Wikipedia article in question**...

* [Field Marshall Bhanurangsi Savangwongse statue](https://www.openstreetmap.org/node/6567173391):
	
	![](https://u.cubeupload.com/xwindows/giEvia.png)
	
	^ You would see that while `subject:wikipedia` _key_ is linked, **its value is not**.

Other similar examples could be found via an Overpass query <sup>([Turbo](https://overpass-turbo.eu/?Q=node[historic%3Dmemorial][memorial%3Dstatue][%22subject%3Awikipedia%22]%3Bout%3B%28way[historic%3Dmemorial][memorial%3Dstatue][%22subject%3Awikipedia%22]%3Brelation[historic%3Dmemorial][memorial%3Dstatue][%22subject%3Awikipedia%22]%3B%29-%3E._%3Bout%3B%3E%3Bout+skel%3B&R), [Raw](https://overpass-api.de/api/interpreter?data=node[historic%3Dmemorial][memorial%3Dstatue][%22subject%3Awikipedia%22]%3Bout%3B%28way[historic%3Dmemorial][memorial%3Dstatue][%22subject%3Awikipedia%22]%3Brelation[historic%3Dmemorial][memorial%3Dstatue][%22subject%3Awikipedia%22]%3B%29-%3E._%3Bout%3B%3E%3Bout+skel%3B))</sup> (139 nodes, 10 ways, 1 relation POIs at the time of this writing). I have picked several samples of them at random, and found the same problem when viewed on main OpenStreetMap interface.

The [`subject:wikipedia`](https://wiki.openstreetmap.org/wiki/Key:subject:wikipedia) is quite important for statue POI, since statue often not having its own Wikipedia entry, while the person/subject it represents usually has one.

While some people would argue that one could find associated Wikipedia entries via Wikidata link anyway; doing it this way can be time-consuming where there is a lot of linkage information (large _Statements_ section) on the Wikidata page in question&mdash; which is also the case for the POI shown in my screenshot.

Notes:

* This problem is not specific to memorial/statue POI type.
* There are currently 2874 POIs (1586 nodes, 1256 ways, 32 relations) on OSM with `subject:wikipedia` key in general. ([Taginfo](https://taginfo.openstreetmap.org/keys/subject%3Awikipedia), Overpass [Turbo](https://overpass-turbo.eu/?Q=node[%22subject%3Awikipedia%22]%3Bout%3B%28way[%22subject%3Awikipedia%22]%3Brelation[%22subject%3Awikipedia%22]%3B%29-%3E._%3Bout%3B%3E%3Bout+skel%3B&R)/[Raw](https://overpass-api.de/api/interpreter?data=node[%22subject%3Awikipedia%22]%3Bout%3B%28way[%22subject%3Awikipedia%22]%3Brelation[%22subject%3Awikipedia%22]%3B%29-%3E._%3Bout%3B%3E%3Bout+skel%3B))
* This problem shows up the same whether JavaScript is enabled or not.

Browser: Pale Moon 25.8.1 (binary)  
System: Debian GNU/Linux 7.0 Wheezy i386

**Comment by matkoniecz** [comment]
> This bug is still reproducible.

Note that it is not a bug, it is a request for a new feature. Also "is still reproducible" is already known given that this issue is open.

**Comment by alesarrett** [comment]
I'm also supporting this enhancement request, given also the issue #834 recently solved.

**Comment by boothym** [comment]
Would be good if this was implemented - seems strange to have brand:wikidata linked but not brand:wikipedia.

**Comment by matkoniecz** [comment]
This issue is open, it means that it is waiting for someone to implement it (or review a submited pull request). In general, in open source projects you can either implement it by yourself or wait for someone else to do this.

There are ways to increase chance for someone working on it. All of them are either not too effective or require noticeable effort. Note that comments with complaints or +1 comments usually have an effect of making someone interested in fixing this less likely.

For people interested in just signalling interest in a fix there are often features allowing to note this, without sending notifications to all involved. Developers may look at open issues and may be more interested or motivated in fixing ones with multiple votes/

In GitHub it is called reactions allowing to add +1 without triggering notification send to every single person who enabled notifications in this issue or in repository in general (in this case - about 100 people).

See https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/ for guide how you can add your +1 without sending flood of notifications.

**Comment by 1ec5** [comment]
#788 added linking for `architect:wikidata`, `artist:wikidata`, `brand:wikidata`, `operator:wikidata`, and `subject:wikidata`. openstreetmap/openstreetmap-website@36a382bb43c81847b9463066a57cc7986d7cd731 added linking for `name:etymology:wikidata` and `network:wikidata`. #2812 would add linking for `species:wikidata`.

At a glance, it looks like this case:

https://github.com/openstreetmap/openstreetmap-website/blob/70d7d8d850148f714b70a3297c02a8203214dec6/app/helpers/browse_tags_helper.rb#L63-L64

needs to be consistent with this conditional:

https://github.com/openstreetmap/openstreetmap-website/blob/70d7d8d850148f714b70a3297c02a8203214dec6/app/helpers/browse_tags_helper.rb#L107-L108
