### ISSUE TITLE
User IDs have inconsistent types in the database

### ISSUE THREAD

**Issue by ststeiger** [openstreetmap/openstreetmap-website#2211]
https://raw.githubusercontent.com/openstreetmap/openstreetmap-website/master/db/structure.sql

> Error 1750
> The column "users.id" doesn't have the same data-type as the "client_applications.user_id"-column
> The constraint or index couldn't be created. See above error. 

users.id is bigint, but the references to users.id are int. 
This is wrong ! 
Same thing with note_comments.

```
ALTER TABLE client_applications ADD CONSTRAINT client_applications_user_id_fkey FOREIGN KEY ("user_id") REFERENCES users(id);
ALTER TABLE issue_comments ADD CONSTRAINT issue_comments_user_id_fkey FOREIGN KEY ("user_id") REFERENCES users(id);
ALTER TABLE issues ADD CONSTRAINT issues_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES users(id);
ALTER TABLE issues ADD CONSTRAINT issues_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES users(id);
ALTER TABLE issues ADD CONSTRAINT issues_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES users(id);
ALTER TABLE oauth_tokens ADD CONSTRAINT oauth_tokens_user_id_fkey FOREIGN KEY ("user_id") REFERENCES users(id);
ALTER TABLE reports ADD CONSTRAINT reports_user_id_fkey FOREIGN KEY ("user_id") REFERENCES users(id);

ALTER TABLE note_comments ADD CONSTRAINT note_comments_note_id_fkey FOREIGN KEY (note_id) REFERENCES notes(id);
```

**Comment by tomhughes** [comment]
The `structure.sql` file is basically just rough documentation (personally I would get rid of it but people insist on having it) and should not be treated as gospel truth as it often picks up random bis of breakage from people's development databases which have complex histories.

The migrations are the one and only way that you should create a database and they will do the right thing.

**Comment by tomhughes** [comment]
It does appear that there really are some mismatches (only on users - nothing on notes that I can see) which obviously might eventually become a problem once we have two billion users. That is probably a little way off however.

In the fact the real error is probably on the users table unless we're expecting a very rapid growth in user numbers ;-) It's probably easier to fix the references though.

That said there is no need for the two sides of a foreign key constraint to have the same type as far as I know, and I have never seen Postgres complain about it like that. What version are you using?

**Comment by ststeiger** [comment]
@tomhughes: I ported it to MS-SQL, that's why, and it requires the foreign key to be of the same type. 
Quite franky, I don't see why postgre doesn't require this, because if I have a user-id > int32.maxValue, there will be an error, because you can't insert a 64-bit number into a 32-bit number. 

This seems to be more like an overlooked bug than a feature - courtesy of PostgreSQL.

**Comment by ststeiger** [comment]
@tomhughes:: the bug with note is in note_comments, it states note_comments.note_id is a bigint, and references note.id, which is an integer. 

While this would work, I don't see the point in wasting storage. 
Probably notes was expected to switch to bigint, and therefore it uses a bigint. 
Here you can argue if it's a bug or a feature.

**Comment by tomhughes** [comment]
Well MS-SQL is entirely unsupported by us and there are other things in our schema that are almost certainly not going to work, not least the 3GL functions!

Obviously you're right that there would be values that couldn't be represented on one side but that is no barrier to validating that the values which are present and can be represented exist in the other table.

**Comment by gravitystorm** [comment]
> The `structure.sql` file is basically just rough documentation (personally I would get rid of it but people insist on having it) and should not be treated as gospel truth as it often picks up random bits of breakage from people's development databases which have complex histories.

I disagree. The structure.sql should exactly mirror the database structure, and eventually we should  the oldest migrations (e.g. when they are more than 3-4 years old). There's a good explanation of why in the [rails documentation](https://edgeguides.rubyonrails.org/active_record_migrations.html#schema-dumping-and-you) and elsewhere in blog posts. There are migrations written more than a decade ago, for different versions of postgres and different assumptions in active_record and trying to revisit them over and over every few years is unnecessary when we have a structure file that explicitly states the end result.

But of course, it doesn't matter if @tomhughes and I disagree on this topic, so long as we have both the migrations, and the schema, and that they both match the real database! Any discrepancies between the production database and the schema.sql are bugs and definitely need to be fixed. Old migrations can also be changed (e.g. for bigint/integer changes as rails has evolved) but this is a bit more hard work.

**Comment by tomhughes** [comment]
Well of course it *should* it's just not really possible in a practice because of the way it is created and maintained.

**Comment by ststeiger** [comment]
Well, that shouldn't be difficult in practice. 
All you need to do is run the migrations on the database, (continuous integration), and fetch the table-create script from the database after the migrations have run. 

All that's possible then is that the script is not the latest version (or that the table-create-algorithm doesn't account for some new features). 
And then, when you need to fix mismatching data-types, you'll just need to create a migration, up-and-down, for it, and run the table-create-algorithm on the updated integration db.

**Comment by tomhughes** [comment]
That's exactly what rails does - whenever you run a migration if dumps the schema to that file afterwards - the problem is that different developers have different minor variations in their databases that then get reflected in the SQL file.

All it takes is one minor change to a migration that somebody doesn't rerun against their local database and they wind up with a schema locally that is different to other people and which is reflected in future whenever they make another change. Sometimes I think it even comes down to changes in rails defaults and how old your database is (ie what version of rails was used when running certain migrations).

At the very least you wind up with pathnames in the SQL which are tied to where the user happens to have their 3GL libraries installed.

Yes we could do what you suggest and make travis constantly add new commits to bring the SQL back to a clean version but that will produce horrible churn in the git history unless we can somehow also prevent user changes making it through so that we only get the clean versions.

All this is why rails does not generate that file by default - we had to opt in to that.

**Comment by ststeiger** [comment]
> The `structure.sql` file is basically just rough documentation (personally I would get rid of it but people insist on having it) 

This is 
A) Because they don't know the rails migration exists, or where (with a google search, you land on the structure.sql on github), neither do I (now just the where)
B) because the rails package manager is atrocious, and if you don't manage versions carefully, it breaks or creates hours of joy, so using the structure.sql is a lot easier, especially for portation to another rdbms.

**Comment by tomhughes** [comment]
Like I say as far as we are concerned we don't support any other databases and there are a number of things in our schema and our code that rely on Postgres specific features that are unlikely to work on other databases.

**Comment by ststeiger** [comment]
> Like I say as far as we are concerned we don't support any other databases and there are a number of things in our schema and our code that rely on Postgres specific features that are unlikely to work on other databases.

It's not that I didn't notice that. 
Varchar without length, for example, apart from the native functions.
I need to import the data from the xml dumps, and I need to know the schema for that.

**Comment by woodpeck** [comment]
I think one feature that we depend on is an auto-increment of the version when we insert something with an already-existing id (i.e. the unique constraint is on the id,version tuple and we want the second part of the tuple to auto-increment). Details such as this, however, should not be relevant to someone who wants to process our XML dumps (which only cover a fraction of the database tables anyway). @ststeiger, could you perhaps explain more about your concrete use case - where do you want to import the data to and what do you want to do with the resulting database once you have managed the import? Perhaps we can then come up with recommendations to help you achieve your goal instead of squabbling over petty details.

**Comment by tomhughes** [comment]
@ststeiger also things like `inet` types which I don't think many databases support.

**Comment by ststeiger** [comment]
I noticed that, too. 
I replaced it with varchar for the time being. 
SQL-Server does support CLR-datatypes, though - so I should be able to create a type inet.

**Comment by ststeiger** [comment]
@woodpeck: I'm basically trying to extract the list of all cities/towns/villages, along with administrative regions level X, including translations (where they exist). Along with coordinates, zip-codes, and whatever else of use that I can find.

**Comment by tomhughes** [comment]
I've attempted @gravitystorm's idea in https://github.com/tomhughes/openstreetmap-website/commit/8a5aca62bf1a8aa076e982416c0767165356d85c and you can see the results at https://travis-ci.org/tomhughes/openstreetmap-website/builds/523928627.

The failing difference is.. interesting... Those tables do not specify a type for the `id` column in our schema. The default changed in rails 5.1 from `integer` to `bigint` but those tables are being created using either the 4.2 or 5.0 compatibility rules so should use the old default (you can see in the migrate output that it set `:id => :integer` to force it) but there seems to be a bug in rails that stops it happening.

Note that although the production database does have `integer` for the column it has `bigint` for the sequence, while my own database had `integer` for both!

There is a second related issue in the production database which is not visible here because I have fixed my own database, which is that prior to rails 4.2 any `string` column without an explicit limit was created as `character varying(255)` by the postgres driver while since rails 4.2 that has defaulted to `character varying` instead. So which you have will depend on which version of rails you were using when the migration was done. There are no backwards compatibility rules in rails for versions before 4.2 so it doesn't even try to fix that.

**Comment by tomhughes** [comment]
Further investigation revealed that `notes` and `note_comments` where in fact changing the id column type to bigint later - no idea why production didn't have that change but I have now applied it.

As to `acls` then seems to be because it adds the column manually as type `primary_key` and the back compatibility seems to miss that. Again I have corrected production.

So I have now pushed a structure update and the travis check to the main repo.
