### ISSUE TITLE
Block repeated identical GPX uploads

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#2259]
This user https://www.openstreetmap.org/user/jojkuhiuwer/traces uploads identical traces every minute. Can we add a simple check to prevent broken upload scripts?

E.g.: before inserting a new trace, check table `gpx_files` for an existing trace where visible = true, inserted = true and new trace has identical user_id,  size, latitude, longitude, description and visibility. If matching, reject the upload with an error message.

**Comment by tomhughes** [comment]
Well that algorithm clearly won't work as some of those attributes are only known after doing the import!

**Comment by tomhughes** [comment]
If you wanted to do it then a checksum is the proper approach.

In the mean time I have suspended that user.

**Comment by mmd-osm** [comment]
Agree, checksum would be better, maybe as a new calc_checksum method lin lib/gpx.rb?

I think the gpx import has no check for the current user status, as new gpx files keep appearing in the list.

**Comment by tomhughes** [comment]
Huh, they have to authenticate and a suspended user can't authenticate.

**Comment by mmd-osm** [comment]
Closing for now due to low impact.

**Comment by Rub21** [comment]
The issue is still there!!  
<img width="951" height="189" alt="Image" src="https://github.com/user-attachments/assets/70e3e965-e824-4ffe-be12-6ef0a4b67ecb" />

e.g:  this user upload two similar traces after 2 minutes
25 March 2026 at 17:49 https://www.openstreetmap.org/user/rwblake/traces/12260113
25 March 2026 at 17:51 https://www.openstreetmap.org/user/rwblake/traces/12260117
