### ISSUE TITLE
Including the smooth-zoom of the Qwant-map

### ISSUE THREAD

**Issue by theuserbl** [openstreetmap/openstreetmap-website#2283]
Including the smooth-zoom of the Qwant-map, which using parts of OSM
https://github.com/QwantResearch/qwantmaps
https://www.qwant.com/maps/

And yes, I have seen the closed issue
https://github.com/openstreetmap/openstreetmap-website/issues/1153
but if the Qwant-code is better, then the Leaflet-code, then using the Qwant one.

**Comment by tomhughes** [comment]
Qwant maps uses vector tiles and client side rendering with mapbox-gl-js so is not in any way relevant or useful to us right now.

As and when we are ready and able to move to vector tiles it might be (though we might just as well use mapbox-gl-js directly - the QwantMaps frontend is a full feature "map site" built on top of that).

**Comment by gy-mate** [comment]
> is not in any way relevant or useful to us right now.
> 
> As and when we are ready and able to move to vector tiles it might be

We now have not one but two kinds of vector tiles, hooray!! 🎉

It looks like this issue became relevant more than ever. If this is the case, @tomhughes, could you please reopen this issue? (Due to the suggestion of smooth zoom, not Qwant-map.)

Many thanks in advance! :)

**Comment by gy-mate** [comment]
_Related: #5481_

**Comment by 1ec5** [comment]
As explained in https://github.com/openstreetmap/openstreetmap-website/issues/2283#issuecomment-506391221, the lack of smooth zooming is just a symptom of using Leaflet. We’re still using Leaflet, only with MapLibre GL JS drawing off-screen behind the scenes and relying on the [maplibre-gl-leaflet](https://github.com/maplibre/maplibre-gl-leaflet/) plugin as a compatibility shim. #2686 and gravitystorm/openstreetmap-website#289 discuss migrating to MapLibre GL JS for real. We aren’t going to migrate to [Erdapfel](https://github.com/Qwant/erdapfel/) as implied by the original post, so we should track any migration to GL JS in a separate issue rather than this one.

**Comment by gy-mate** [comment]
My bad—thanks for the info! :)

**Comment by tomhughes** [comment]
Migrating to GLJS natively probably isn't possible until it's a bit more developed - it just doesn't have all the features we need at the moment.
