### ISSUE TITLE
security audit on openstreetmap-website?

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/openstreetmap-website#2306]
Has a security audit ever been performed on the openstreetmap-website? 

Mozilla has a program to undertake security audits and do remedial work on open source projects.
https://www.mozilla.org/en-US/moss/secure-open-source/

If this might be interesting, we could apply.

**Comment by tomhughes** [comment]
Not as far as I know but it doesn't really sound like a matter for the issue tracker anyway.

If you saw the two alerts github is reporting on the repo (not sure if you can see those) then please ignore them - neither has a fix and one of them doesn't apply to the way we use the gem in question and as for the other nobody (not even the author of the gem in question) has been able to find out what the problem is as a CVE was reserved but no details were ever provided.

**Comment by mmd-osm** [comment]
It would be great to not only include osm-website, but also other user facing endpoints in such an audit, e.g. cgimap and Nominatim.

By the way, #2229 includes some security related checks for this repo.
