### ISSUE TITLE
INSTALL.md has minor quirks

### ISSUE THREAD

**Issue by YuriiNskyi** [openstreetmap/openstreetmap-website#2345]
I'm trying to install `openstreetmap-website` on clean `Ubuntu 18.04 LTS`.

After spending some time on solving [this issue](https://github.com/openstreetmap/openstreetmap-website/issues/2295), by executing these commands:

```
sudo apt-get -y install npm
sudo npm install yarn -g
```

here are the new problems:

First has occurred when executing `bundle install`:

>Traceback (most recent call last):
	1: from /usr/local/bin/bundle:23:in `<main>'
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/share/rubygems-integration/all/gems/bundler-1.16.1/exe/bundle (LoadError)

After googling, this problem is simply resolves:

```
sudo gem update --system
sudo gem uninstall bundler
sudo gem install bundle
```

The next steps works as needed, until we stops at `bundle exec rails server`:

> couldn't find file 'settings.local.yml'

This is happily resolved by executing `cp config/settings.yml config/settings.local.yml`.

Finally, the site works.

There are multiple proposed solutions:

1. Add section with Yarn installation into [INSTALL.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md).
2. Do something with bundler (it's up to you, I'm not a professional Ruby developer)
3. Do not require `settings.local.yml` file as, I think, it is only needed to override `settings.yml`. What if I don't need any overrides and totally agreed with a default? 
4. Do something with these errors, while running the server:

>pngcrush worker: `pngcrush` not found; please provide proper binary or disable this worker (--no-pngcrush argument or `:pngcrush => false` through options)
advpng worker: `advpng` not found; please provide proper binary or disable this worker (--no-advpng argument or `:advpng => false` through options)
optipng worker: `optipng` not found; please provide proper binary or disable this worker (--no-optipng argument or `:optipng => false` through options)
pngquant worker: `pngquant` not found; please provide proper binary or disable this worker (--no-pngquant argument or `:pngquant => false` through options)
jhead worker: `jhead` not found, `jpegtran` not found; please provide proper binary or disable this worker (--no-jhead argument or `:jhead => false` through options)
jpegoptim worker: `jpegoptim` not found; please provide proper binary or disable this worker (--no-jpegoptim argument or `:jpegoptim => false` through options)
jpegtran worker: `jpegtran` not found; please provide proper binary or disable this worker (--no-jpegtran argument or `:jpegtran => false` through options)
gifsicle worker: `gifsicle` not found; please provide proper binary or disable this worker (--no-gifsicle argument or `:gifsicle => false` through options)
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)

Seems that they are just warnings, anyway, they looks scary.

After all, it is really not so hard to install `openstreetmap-website`, except those quirks which are quite confusing for those who didn't professionally work with Linux or Ruby.

**Comment by tomhughes** [comment]
To answer your points:

* We haven't documented yarn yet because we don't have a good solution for Ubuntu but what you did is probably the least worst approach for now.
* I don't think you needed that bundle stuff at all and I wouldn't advise it - the real error there was the settings thing I think. It's a bad idea to overwrite the apt installed bundler with a gem installed one like that anyway - we should either use one of the other.
* As I said, the settings thing is known about - there's a ticket somewhere I think though I couldn't find it - it's not clear what is best to do but copying is certainly not required or advisable as it will stop you getting any updates to defaults. An empty file is better.
* Yes the image optimiser things are warnings but there is no way to get rid of them.

**Comment by tomhughes** [comment]
Note that I don't think you actually need yarn at the moment unless you want to run the eslint tasks?

**Comment by YuriiNskyi** [comment]
@tomhughes 

So, why not document it? People will search and find similar solution, there is unnecessary complication here.

So, the error was because of the `settings.local.yml` file? It's not obvious at all.
What should we do with [Ruby gems](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md#ruby-gems) then? 

Yes, I don't want to run eslint tasks, but without installing Yarn, I can't pass [Node.js modules](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md#nodejs-modules) step. Am I right that this step is don't even needed, when you have no goal to run eslint tasks?

Ok, let's ignore those warnings!

IMHO, section FAQ in [INSTALL.md](https://github.com/openstreetmap/openstreetmap-website/blob/master/INSTALL.md) with such quirks, will be a great support for those who want to install `openstreetmap-website` from scratch.

**Comment by tomhughes** [comment]
I'm not saying there aren't problems that we should fix, just that it's hard to come up with good instructions that won't run the risk of breaking people's systems.

We can certainly document the settings thing, but the whole idea is that you shouldn't need that file unless you want to override a setting - the problem is that we wanted the assets to rebuild if it changed so we added a dependency on it which causes the error. Ideally we want a dependency that is optional so that if the file exists and is changed the assets are rebuilt.

Yes I realise the instructions advise running yarn, and it's likely to be more important at some point, but sadly Ubuntu has not packaged yarn yet which makes it tricky. That's quite new and we're still working out the best solution. Maybe we should just document that step as optional for now.

**Comment by YuriiNskyi** [comment]
Ok, your point of view is clear, except that I can't understand where is the risk of breaking people's systems, if provided installation instructions are for new people, they don't have any systems.

I'm closing this issue, it is all clear now.
