### ISSUE TITLE
Search or Directions doesn't prioritise nearby locations

### ISSUE THREAD

**Issue by eliotb** [openstreetmap/openstreetmap-website#2356]
In my experience, neither Search nor Directions prioritise nearby places.

## Search
Example: I start here Christchurch City, New Zealand. https://www.openstreetmap.org/#map=12/-43.5315/172.5830
Search for "cashmere high school", which is in the view.  The map jumps to Washington, USA.

Desired result:  Select the closest, order by distance.

## Directions
Then select the correct (2nd) entry,  click Directions arrow button, and put pin on the school.christchurch   Enter "airport" into the destination box, click GO.

Result: Destination filled in with "Airport, Access to Metro 'Aeroporto', Olivais, Santa Maria de Olivais, Lisbon, Grande Lisboa, Área Metropolitana de Lisboa, 1700-008, Portugal"
Routing displays:"Couldn't find a route between those two places."

Change destination to "Christchurch Airport",
Result: Destination="Spence, B4234, Lydbrook, Forest of Dean, Gloucestershire, South West England, England, GL17 9NS, United Kingdom".
Routing displays:"Couldn't find a route between those two places."

Unlike the Search results, there is no list of found places to select from, the first one is always used.

Desired result: Closest reachable destination used(?) or at least a selection of found places to choose from.

**Comment by tomhughes** [comment]
Search bugs need to be reported to https://github.com/openstreetmap/Nominatim/issues which is the tracker for our geocoding engine.

We do prioritise nearby places though, or at least we pass the search engine the current viewport so that it can do so. I believe it doubles the size of that box and considers anything in that area as "near" rather than doing a full global sort by distance which may be the issue you are seeing.

**Comment by eliotb** [comment]
OK, it is hard to tell whether the problem is with the front or back end.

The 2nd part of my issue, about directions  (always get first item, don't see other search results) could be a front-end (enhancement or bug, if you like)

**Comment by systemed** [comment]
The intention (certainly from my POV when I did the initial coding on the directions feature) was ultimately for the JS client to call the geocoding sources directly, rather than having geocoder_controller.rb call and agglomerate them. This would then enable refactoring so that the directions could use the same code as the standard placename search. It'd be a good project for a JS developer to work on.

**Comment by tomhughes** [comment]
I was looking to move the geocoding search to the client side but @gravitystorm was against it I think.

**Comment by eliotb** [comment]
Any chance of opening this issue again. Change title to "Directions doesn't allow choosing from search results" or something.  I think this is a web UI issue rather than Nominatim.

I've opened a separate Nominatim issue about the actual search results.
