### ISSUE TITLE
"Zoom in to query features" -- that disappear when one zooms in!

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2357]
One sees "Zoom in to query features."
However often those features one wants to query disappear when one zooms in!
Therefore consider always allowing the user to query any item he can see.

**Comment by tomhughes** [comment]
That limitation is not there for fun, it's there because too many things would be found, or more likely the overpass query that drives it would just time out.

You need to be zoomed in far enough that there are likely to only be a relatively small number of features within the search radius. Sorry if that is sometimes annoying, but it's the best we can do I'm afraid.

**Comment by jidanni** [comment]
Actually one would think a workaround would be just a  select a different layer . However different layers , other than the standard layer,  don't have those features in the first place. Example: https://www.openstreetmap.org/#map=9/24.2932/121.1177

Anyway, sometimes one really does want to find out what is causing a certain item to appear at lower Zoom values, but there's no way to find out.

**Comment by HolgerJeromin** [comment]
> Anyway, sometimes one really does want to find out what is causing a certain item to appear at lower Zoom values, but there's no way to find out.

This is a problem, but that could be a large osm landuse which is nowhere near the label point you want to analyse.

**Comment by jidanni** [comment]
OK.
https://help.openstreetmap.org/questions/70512/how-to-query-features-without-zooming has some workarounds.
