### ISSUE TITLE
GET User's current ratelimit quota

### ISSUE THREAD

**Issue by blackboxlogic** [openstreetmap/openstreetmap-website#2363]
Just a nice to have...
There is no way to know how much is left in your API rate-limit quota. There could be an endpoint /user/quota or every response from the API could have a quota header.
Would be nice to know:
- if the quota is by account or by IP
- how much has been used
- how much is remaining
- rate that the quota regenerates

**Comment by tomhughes** [comment]
With one exception there is no quota - that exception is the download of existing data.

The quota is set at a level where nobody is expected to hit it in normal use, and we don't like to advertise the details too much because it will just encourage people to find ways to game it.

It's nothing to do with this repository anyway - the quota is implemented in [cgimap](https://github.com/zerebubuth/openstreetmap-cgimap) and configured by our [chef](https://github.com/openstreetmap/chef/) recipes. The rails implementation of the API doesn't actually enforce any quotas at all.

**Comment by tomhughes** [comment]
Oh to answer one of your questions it is by account if you authenticate the request (which is optional when fetching map data) and by IP if you do not.
