### ISSUE TITLE
Time to finally make an openstreetmap official app

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2414]
I think openstreetmap needs an official app,  iOS and Android. Wikipedia has a official app. Google maps has an official app. Yep, every website that is for real also has an official app.

Okay, so what should the openstreetmap official app look like? Well, it should look pretty much just like the website looks like.

Well, what great Improvement would that be? Well it might be a little more efficient then going indirectly through a browser. And also it would be an official implementation so people could be sure that there's no browser bug causing something weird that they're seeing.

**Comment by jidanni** [comment]
Sure, there's plenty of apps that use openstreetmap data. However there is still no official openstreetmap app.

**Comment by jidanni** [comment]
I'm not saying it it needs to compete with anybody oh, I just saying it should be an official reference version.

**Comment by HolgerJeromin** [comment]
What would be the benefit?
Who should do it?
Why should someone invest the time to make this happen?

**Comment by HolgerJeromin** [comment]
The best way (less coding needed) would be an progressive web app #2361 but the benefits are not existing.

**Comment by tomhughes** [comment]
This is the repository for the web site so is not the place to discuss a hypothetical mobile app.

The team here develop the web site - if you want an official app then start a project to create one and persuade the OSMF to bless it as "official" presumably by allowing use of the trademark.

**Comment by julian-fairfax** [comment]
Hi,
I'm just dropping in here to give my thoughts on this issue as someone who's been on a quest to switch to as many open-source privacy-respecting apps as possible. While I agree that OpenStreetMap doesn't *need* an official app, I think it would go a long way in making the switch for users easier. People who use Google Maps on their computer and want to use it on their phone can just go to the app store and install the Google Maps app. It's a frictionless experience because Google Maps looks the same on all platforms. In comparison, if you want to use the OpenStreetMap *service* on your phone they can't just download the OpenStreetMap *app*, they have to download a third-party *client* that relies on the OpenStreetMap *service*.

Obviously we can all agree that this doesn't really matter if you're already familiar with OpenStreetMap but it makes things more difficult to understand for the average person. I'm also not suggesting that the OpenStreetMap team work on an entirely new app, as there are already multiple good contenders for an official app. I'd also like to note that this decision would hinge on two parties, possibly even three: the OpenStreetMap Foundation, the developers of one of those apps, and possibly the users. As for what would need to be done: once the app to become official is chosen, it would just need it's name and icon changed in accordance with the OpenStreetMap trademark.

The other solution is to simply add PWA support to the website as suggested in #2361 (although as mentioned, the benefits are not that obvious). The problem is that while the website does *scale* for mobile devices, it's clearly not made for them. So in my opinion, assuming an official app were to be made, it'd be better to just use an existing third-party app. As part of my quest, I not only wanted to find open-source apps, but also apps that were cross-platform. OpenStreetMap doesn't officially fulfil this criteria because there's no official app. (In practice however, through one of the multiple third-party mobile apps and the website, it is.) Thank you so much for making this wonderful service and I'll hope you'll consider this at some point!

**Comment by gravitystorm** [comment]
As @tomhughes already said - This is the repository for the web site so is not the place to discuss a hypothetical mobile app.
