### ISSUE TITLE
Remind anonymous users that they can login to get notified of changes to their note

### ISSUE THREAD

**Issue by iandees** [openstreetmap/openstreetmap-website#244]
I've seen several anonymous notes that I think came from OSM users or people at least willing to log in; it would be great to provide a link to the login page and remind them that if they want to receive updates for their note they should complete the login or registration process.

**Comment by donaldrnoble** [comment]
+1 on this, I often have to comment a second time because I am not logged in, usually on mobile phone or tablet (and also see quite a few instances of this happening for others)

Would it be possible to have some text above the comment button that says "log in to receive updates" or something similar
