### ISSUE TITLE
Batch uploaded GPX-files in a zip-file, trace not showing up in iD or Potlatch 2

### ISSUE THREAD

**Issue by magu01** [openstreetmap/openstreetmap-website#2455]
I zipped a bunch of gpx-files as mentioned in this link.
https://wiki.openstreetmap.org/wiki/Batch_Upload_of_GPX_(various_tools)

But when i try to load the trace in iD or Potlatch 2 I can't see the trace. iD shows only one trace from one gpx. Potlatch is not showing any trace.

This is the trace.
https://www.openstreetmap.org/user/magu01/traces/3161726

Uploaded as private and then changed to Identifiable.

**Comment by tomhughes** [comment]
The question is, is the problem with the API or is it with the editors...

**Comment by magu01** [comment]
I would bet my money on the editors. Is this the wrong place to report in that case? 
How do we decide?

**Comment by tomhughes** [comment]
I've been looking and I think you're right.

I'm not actually seeing anything in iD either although looking at the network traffic the API appears to be returning all the data.

I suspect the problem is that editors don't cope with the slightly odd way we return the data, which is basically by concatenating all the files, and they are at best only parsing the first XML document they see.

Probably best to report it separately against [iD](https://github.com/openstreetmap/iD/issues) and [potlatch](https://github.com/systemed/potlatch2/issues).

**Comment by magu01** [comment]
Thanks! I will report the issue there.
