### ISSUE TITLE
Imagery_used custom background link broken

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#2493]
Originally posted at https://github.com/openstreetmap/iD/issues/7207

I used a custom background in iD and after saving, the changeset's imagery_used field had "Bing" included as part of the hyperlink for the custom url:

`<td class="browse-tag-v">﷐Custom (<a href="https://anygis.ru/api/v1/Tracks_Strava_All/{x}/{y}/{z});Bing" rel="nofollow">https://anygis.ru/api/v1/Tracks_Strava_All/{x}/{y}/{z});Bing</a> aerial imagery;OS OpenData StreetView;Esri World Imagery﷯</td>`

![Screenshot_2020-01-03 Changesets OpenStreetMap](https://user-images.githubusercontent.com/16965772/71753075-4f06fd00-2e79-11ea-82cf-b6a1fcae443d.png)

**Comment by tomhughes** [comment]
Parsing links out out of text is not an exact science - it's heuristic and there will always be cases that go wrong.

In any case we use a third party tool (https://github.com/vmg/rinku) to do the linking so it's outside our control.

**Comment by tomhughes** [comment]
Also as @bhousel pointed out on the other ticket this is not really a valid link anyway, so it's never going to work, but there is no way for a link parser to know that.

**Comment by boothym** [comment]
The same thing happens with valid links though (assume you mean those with a file extension).
![Screenshot_2020-01-04 Way 488123069 OpenStreetMap](https://user-images.githubusercontent.com/16965772/71765122-95e00b80-2ee8-11ea-8a21-160f28152fe0.png)

There isn't a problem when the custom url is the final item in the list. I wonder if spaces after the semi-colon would help? 

Or does the custom url need to be turned into a hyperlink at all?

**Comment by tomhughes** [comment]
Well that's still not a valid link - it's a template for a link (into which the tile coordinates have to be substituted).

A space might help, but that's something for iD not us.

Obviously it doesn't need to be turned into a link, and indeed shouldn't be because it's a not a real link, but there's no way for us to know that - we just run a general linkifier on all tag values when displaying them to try and make anything that looks like a link into an active link.
