### ISSUE TITLE
Bad redirect for new user URL

### ISSUE THREAD

**Issue by flyingpimonster** [openstreetmap/openstreetmap-website#2555]
In GNOME Maps, there's a link in the login dialog to https://www.openstreetmap.org/user/new?referer=gnome-maps, so a user can create an account. However, this URL redirects to https://www.openstreetmap.orggnome-maps/, which is obviously not the expected behavior. (Note there is no slash between .org and gnome-maps--this is a completely invalid URL).

Is the URL in GNOME Maps wrong, or is openstreetmap.org not handling it properly?

**Comment by tomhughes** [comment]
The URL is wrong. I assume they added the `referer` parameter for some sort of statistical tracking purposes but that is a valid parameter for `/user/new` that has a meaning and the value they have given is not valid.

That said, the redirect you are seeing only happens because you are already logged in - if you weren't logged in you would get sent to the signup page. Once you completed signup you might get sent to a bogus redirect though.
