### ISSUE TITLE
Strip non-numeric characters from end of url

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#2568]
On mailing lists and elsewhere, I've seen OSM urls linking to nodes, ways, relations and changeset which have accidentally included a dot or other character on the end of the url.

When clicked these go to the "file not found" page, which is confusing until you realise the extra character is there at the end.

Would it be possible to remove any non-numeric characters from the end of the url and redirect to the correct page?

**Comment by tomhughes** [comment]
No, that way lies madness. Seriously, once we start trying to guess what the client really meant by a URL where do we stop? With the insanity that is mod_spelling?

**Comment by boothym** [comment]
Why is it madness to make this broken url - [https://www.openstreetmap.org/node/107775. ](https://www.openstreetmap.org/node/107775.) - display the correct page? 

I'm not asking to check the url for spelling. But the part after node/way/relation/changeset should be numeric, so surely osm.org can remove anything that isn't?

**Comment by tomhughes** [comment]
Bacause fundamentally you are trying to guess what the user meant when they provided malformed input.

Presumably the real problem is not people mistyping URLs but things like email clients that try to heuristically extract URLs from text?

Anyway this seems like a ridiculously trivial problem to spend time trying to correct on the server for the one URL in a million that has this particular sort of error.
