### ISSUE TITLE
Nominatim: "Hearing aids" is not translated

### ISSUE THREAD

**Issue by caugner** [openstreetmap/openstreetmap-website#2589]
Example: https://www.openstreetmap.org/search?query=h%C3%B6rger%C3%A4te%2C%20berlin#map=19/52.46610/13.48738

![image](https://user-images.githubusercontent.com/495429/79279929-6d848780-7eaf-11ea-9d2e-c46590c14330.png)

How can I fix this? (I didn't find it on translatewiki.)

**Comment by tomhughes** [comment]
Probably in nominatim then, though it might also rely on @lonvia doing a sync from nominatim to here.

**Comment by caugner** [comment]
Hm, weirdly the Nominatim FAQ in the OSM Wiki refers to this repository specifically and Translatewiki for the translations.

**Comment by tomhughes** [comment]
You use TW to update the translations yes, but messages are not translatable until the english version is added, which hasn't been done for several years by the looks of it - the last one I can see is de10143dea2bef3fc7fecdec012bf86503cce68e.

That is done by synchronising the keys in our translation list with those generated by Nominatim which @lonvia normally takes care of.

**Comment by mikini** [comment]
Could we help bring on that synchronisation? I regularly annoy myself of this too, most recently I found building=office and boundary=public_transport in English (from [this query](https://www.openstreetmap.org/query?lat=55.67459&lon=12.58479)) using Danish language.

I reckon it would always be a subset of Nominatim's full list that is added to en.yml to be localisable on osm-website?

Maybe it would be an idea to have a wishlist somewhere to which people could add entries they want to be translatable? Or if it is automated the selection is maybe based on pure usage statistics?

I see from https://github.com/osm-search/Nominatim/issues/292 that Nominatim itself (at least 5 years ago) didn't contain any translations and the discussion pans out with some good thoughts about an independent project containing translateable descriptions of key/value pairs. I guess that hasn't been brought any further, yet?

**Comment by lonvia** [comment]
I'll do another sync as soon(ish). I'm quite sure though that boundary=public_transport won't make the list. It is simply to rare and I've always tried to keep the list to a managable size covering the most used key/value combinations.

**Comment by mikini** [comment]
@lonvia Thanks. Yeah, I understand that when sync. is done manually and translated for the website only it can't have the full list (and honestly, this is maybe not the most prominent and important functionality of the site). But the idea of having a generic description of key/value pairs seems nice and usable to OSM data consumers universally.

**Comment by mikini** [comment]
@lonvia Thanks for the update in 987977363bc47d99161600c3730df36c0470d502, it included both [shop=hearing_aids](https://github.com/openstreetmap/openstreetmap-website/commit/987977363bc47d99161600c3730df36c0470d502#diff-37c9b835927e3c363588f172de9bb6faR1110) and  [building=office](https://github.com/openstreetmap/openstreetmap-website/commit/987977363bc47d99161600c3730df36c0470d502#diff-37c9b835927e3c363588f172de9bb6faR645). The latter must have been exposed previously, because an [old Danish translation existed](https://translatewiki.net/w/i.php?title=Osm:Geocoder.search_osm_nominatim.prefix.building.office/da&action=history) making the feature [show up translated](https://www.openstreetmap.org/query?lat=55.67459&lon=12.58479) immediately.
