### ISSUE TITLE
Replace blogs.osm.org with blog.osm.org

### ISSUE THREAD

**Issue by Zverik** [openstreetmap/openstreetmap-website#260]
Right now there is a link to blogs.openstreetmap.org on the frontpage. Since we now have an "official" (?) blog, I don't think it's reasonable anymore to link to that aggregator, which often has spam posts at the top. On the other hand, blog.osm.org cannot be called a community blog, but there is diary link as well, so I guess that isn't a problem.

**Comment by gravitystorm** [comment]
Time has moved on, and as mentioned in #1042 these links are no longer on the front page.

I don't think it's a good idea to remove the link to the aggregator entirely, since there is relevant content there that is of interest to the community and not found elsewhere.

I do think the text on the about page could be reworked, and the posts on the main blog highlighted. So I've made a PR to this effect - see #1686
