### ISSUE TITLE
Diary editor Edit and Preview buttons wrongly greyed-out

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#2607]
Those Edit and Preview buttons are valid buttons. They should not be greyed out.

They are currently greyed out unless the mouse is upon them.
Sure, if the user has entered 0 bytes, they can be greyed out, but not otherwise please.

![image](https://cloud.githubusercontent.com/assets/1190866/24242521/33062fde-0f75-11e7-8580-714159a254ae.png)

The edit/preview button is on the right, like other places where Markdown is used. This might not be the clearest UI, but functionality exists.

_Originally posted by @pnorman in https://github.com/openstreetmap/openstreetmap-website/issues/1497#issuecomment-288671249_

**Comment by mmd-osm** [comment]
Only one of the two buttons is greyed out here, so a user can toggle between edit and preview mode. Enabling both of them at the same time isn't a good idea, as a user typically wouldn't want to switch from a Preview mode to the same Preview mode they're already in.

Note that by removing _deemphasized_ (that's what you called greyed out), the Preview button will look like two other buttons "Save" and "Subscribe" we have on that same screen. 

![deem](https://user-images.githubusercontent.com/5842757/80864891-02e09380-8c86-11ea-81bb-87a25728c541.png)


https://github.com/openstreetmap/openstreetmap-website/blob/master/app/helpers/application_helper.rb#L33-L34

**Comment by gravitystorm** [comment]
I expect all of these buttons to be redesigned when we move to using bootstrap buttons - they give much more flexibility in terms of button types, button groups and so on.

I also think this whole zone should be redesigned, since the subscribe button is nothing to do with writing a comment, the preview button seems unrelated to the text area, "Save" is not a clear description of the action, and so on. I also like the github approach of having "write" and "preview" as tabs containing the text area, rather than buttons on a side panel.

**Comment by jidanni** [comment]
Yeah, it almost makes one want to import the whole thing to some diary.openstreetmap.github.com .
Maybe the "GitHub modules"(?) could be used instead of the current modules... (but they probably aren't even open source.)

**Comment by AntonKhorev** [comment]
Edit and Preview buttons are not greyed out now.

**Comment by mmd-osm** [comment]
Issue was resolved as per previous comment.
