### ISSUE TITLE
GPX traces - Application error

### ISSUE THREAD

**Issue by kudlav** [openstreetmap/openstreetmap-website#2645]
Unable to load https://www.openstreetmap.org/traces

Got following error page:

> ### Application error
> The OpenStreetMap server encountered an unexpected condition that prevented it from fulfilling the request (HTTP 500)
> 
> Feel free to contact the OpenStreetMap community if your problem persists. Make a note of the exact URL / post data of your request.
> 
> This may be a problem in our Ruby On Rails code. 500 occurs with exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code)

Browser: 3.0.1874.38 (Stable channel) (64bit)
User: kudlav
Language: cs_CZ

**Comment by kudlav** [comment]
Also discussed here:
https://help.openstreetmap.org/questions/71118/httpswwwopenstreetmaporgtraces-application-error

**Comment by mmd-osm** [comment]
Seems like key "others" is missing for ".count_points" in cs.yml. This needs to be fixed on translatewiki.

ActionView::Template::Error at /traces

translation data {:one=>"1 bod", :few=>"%{count} body", :many=>"%{count} bodů"} can not be used with :count => 3427. **key 'other' is missing.**

**Comment by tomhughes** [comment]
That file seems to be very inconsistent - lots of the pluralizable messages have a `many` key which isn't actually valid. Some have `other` but none have both.

The valid keys are `zero`, `one`, `few` and `other` where `few` is for 2, 3 or 4 and `other` for anything greater than 4.

**Comment by tomhughes** [comment]
On the assumption that the `many` keys are actually the `other` keys I have renamed them.

Hopefully @Nikerabbit can make sure that doesn't cause issues with @translatewiki on the next merge...

**Comment by Nikerabbit** [comment]
Umm, what plural rule data are you using? Because our data says:

    "version": {
      "_number": "$Revision: 14885 $",
      "_unicodeVersion": "12.1.0",
      "_cldrVersion": "35.1"
    },

      "cs": {
        "pluralRule-count-one": "i = 1 and v = 0 @integer 1",
        "pluralRule-count-few": "i = 2..4 and v = 0 @integer 2~4",
        "pluralRule-count-many": "v != 0   @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …",
        "pluralRule-count-other": " @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …"
      },

The question is, how can we make sure our plural rule data are in sync?

In this case, the additional form many should case no issues for you, right?

This is how it currently looks to our translators:
![image](https://user-images.githubusercontent.com/1109395/84002992-01d00f80-a972-11ea-8456-ff7cfe9adee1.png)

This currently just a warning, but I think we should make it an error so that no new translations with missing forms can be made. Do you agree?

**Comment by tomhughes** [comment]
The pluralization rules are defined by https://github.com/svenfuchs/rails-i18n/tree/master/rails/pluralization and specifically in this case by https://github.com/svenfuchs/rails-i18n/blob/master/rails/pluralization/cs.rb which shows it is driven by the `RailsI18n::Pluralization::WestSlavic` class which is defined by https://github.com/svenfuchs/rails-i18n/blob/master/lib/rails_i18n/common_pluralizations/west_slavic.rb which uses `one`, `few` and `other`.

It does in fact also support `zero` because they all support that as it's processed separately before any locale specific pluralizer is invoked.

So the difference seems to be that you have an additional rule for non-integer values? But still the result was to accept a translation without the `other` key which you do also have?

I do plan to try and write a test to at least check that all languages have `other` for all pluralizable translations as I believe that is used as a fallback so it's presence will at least avoid exceptions.

**Comment by tomhughes** [comment]
Ah no your `few` is for powers of ten actually. Rails does have that in https://github.com/svenfuchs/rails-i18n/blob/master/lib/rails_i18n/common_pluralizations/east_slavic.rb for locales driven by the `EastSlavic` class but not in `WestSlavic` like this.

**Comment by tomhughes** [comment]
There seem to have a handful of other cases where `other` is missing:

```
# Running:

............F

Failure:
I18nTest#test_ko [/home/tom/src/osm/rails/test/lib/i18n_test.rb:43]:
traces.create.traces_waiting.other plural key missing


rails test test/lib/i18n_test.rb:5

...................................................F

Failure:
I18nTest#test_be_tarask [/home/tom/src/osm/rails/test/lib/i18n_test.rb:43]:
notifier.gpx_notification.success.loaded_successfully.other plural key missing


rails test test/lib/i18n_test.rb:5

.F

Failure:
I18nTest#test_pl [/home/tom/src/osm/rails/test/lib/i18n_test.rb:43]:
datetime.distance_in_words_ago.about_x_hours.other plural key missing


rails test test/lib/i18n_test.rb:5

.............................F

Failure:
I18nTest#test_ru [/home/tom/src/osm/rails/test/lib/i18n_test.rb:43]:
notifier.gpx_notification.success.loaded_successfully.other plural key missing


rails test test/lib/i18n_test.rb:5

............................F

Failure:
I18nTest#test_ce [/home/tom/src/osm/rails/test/lib/i18n_test.rb:43]:
diary_entries.diary_entry.comment_count.other plural key missing


rails test test/lib/i18n_test.rb:5

.....

Finished in 7.435667s, 17.6178 runs/s, 56744.8744 assertions/s.
131 runs, 421936 assertions, 5 failures, 0 errors, 0 skips
```

**Comment by Nikerabbit** [comment]
> It does in fact also support zero because they all support that as it's processed separately before any locale specific pluralizer is invoked.

Which is wrong, because for example for Latvian the rule `zero` is:
> 0, 10~20, 30, 40, 50, 60, 100, 1000, 10000, 100000, 1000000, …
> 0.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, 

Regardless, my short term plan is as follows:
* Promote the warning to error so that no new translations can be made with missing forms (according to CLDR rules)
* Make sure our exporter fills in the missing forms for currently broken translations by copying the last available form to the rest. This may not be 100% correct, but usually it works quite well, and translators need to update check them anyway.

**Comment by tomhughes** [comment]
There's nothing stopping a locale returning `zero` for other values, although Latvian doesn't seem to at the moment. It's just the actual zero value that is hardcoded to return it (https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/backend/pluralization.rb#L36).

**Comment by Nikerabbit** [comment]
Hmm you are right. There doesn't seem to have any language with `zero` rule that doesn't include zero. In MediaWiki support it as well, but it's used by using 0 as they key (or any other number respectively to match variable value).

**Comment by Nikerabbit** [comment]
To clarify why I think that shortcut is not a good idea in my opinion: You often use it in English to write a message such as _You have no items_. For languages where the zero form actually exists, if they follow the example of the source language, then the translation would incorrectly display _You have no items_ (translated), even if you have for example 15 items, in Latvian language.
