### ISSUE TITLE
Add support for logging in with Instagram

### ISSUE THREAD

**Issue by subinze** [openstreetmap/openstreetmap-website#2653]
People can login from websites like facebook,github,google.
https://www.openstreetmap.org/login
It would be nice to add more social login format.
In 2020 World SNS popularity ranking, Youtube and Instargram are among the top 10.

so, How about adding login method like Youtube and Instargram?

**Comment by suuubbb** [comment]
Looking at it, youtube the same as google.

However, Instagram can log in any other way than Facebook.
Instargram can also create other accounts.

**Comment by tomhughes** [comment]
Yeah I wasn't sure about instagram as I don't use it but I was pretty sure google and youtube accounts got unified long ago.

There is an [omniauth plugin for instagram](https://github.com/omniauth/omniauth-instagram) so it could be done but I would suggest that nobody spend any time on it until we have legal clearance given the time I wasted on the twitter one that was never used because of their terms of use.

**Comment by suuubbb** [comment]
You mean you're going to postpone adding Instagram, right?

**Comment by tomhughes** [comment]
Well opening a ticket here is just a request - code doesn't magically appear and we don't have paid staff who get told what to work on.

So this ticket sits here until somebody is interested in working on it and submitting a pull request with actual code to add this feature.

I am just warning anybody thinking about doing that to make sure that our legal team are happy before spending time on it because to integrate a service like this requires us to sign up for an application ID with the service which requires agreeing to some terms and sometimes we find those include things we can't agree to.

**Comment by mmd-osm** [comment]
Latest published Gem version on https://rubygems.org/gems/omniauth-instagram/ still depends on omniauth 1.x, newer changes haven't been published as a new Gem yet. https://github.com/omniauth/omniauth-instagram seems unmaintained and somewhat dead at the moment.

So unless someone is going to fix this gem, there's not much we can do here.
