### ISSUE TITLE
Default diary to user's language

### ISSUE THREAD

**Issue by boothym** [openstreetmap/openstreetmap-website#2657]
I clicked on User Diaries link to see what diaries had been posted recently, but the first 10 or so (this was yesterday) were not in a language I could read.

The only way currently to see the latest English language entries is to append "/en" to the url, or keep scrolling to find a post in English and then click on the "English (English)" link. 

Of course, this is also a problem when those who read other languages encounter lots of posts in English.

Would it be possible to add a link saying "| Show only English* language diary entries" next to the RSS | New Diary Entry | My Diary links? (* this would change to the preferred language of each user)

Even better would be if users could tick a box to in their settings, which would make the diary page default to their preferred language url ("diary/en"), and a "| Show all diary entries" link appear on the diary page.

**Comment by MateoGreil** [comment]
I think you're right : all of this is not user-friendly.

> Would it be possible to add a link saying "| Show only English* language diary entries" next to the RSS | New Diary Entry | My Diary links? (* this would change to the preferred language of each user)

I can do it, I could even add a dropdown button to select among the preferred languages.

I think to select all of ours preferred languages could be better, but to do this, I need to edit the controller, and the routes, so I think I shall wait to get the confirmation of the main maintainers :
We could add a route `get "preferred_languages", :preferred_languages => true`.

Waiting for confirmations from the main maintainers.

**Comment by tomhughes** [comment]
Why on earth would you need a route, never mind a global one.

There's no need to export the preferred languages to the browser to be able to return a filtered view.

**Comment by MateoGreil** [comment]
Sorry, I misspoke, I wanted to say add a route `diary/preferred_languages`, of course not a global one.
Only accessible by authentified users and with preferred languages filled.

**Comment by gravitystorm** [comment]
> this would change to the preferred language of each user

An important thing to note here is that we don't have "one preferred language" for each user. The preferred languages is a list of languages, so that needs to be taken into consideration.

Furthermore, I don't think we should hide large parts of the community from each other by default. I often see diary entries in languages that I can't read, but sometimes the pictures are enough (or mentions of something that I recognise, like 'JOSM') to make me want to translate them to find out what's going on. 

> Only accessible by authentified users and with preferred languages filled.

The preferred language setting should only be seen as an override to browser-specified defaults. So even for non-logged-in users we can detect the preferred languages. It's only that they don't have the opportunity to set a preference, not that we should ignore their preferred languages entirely.

**Comment by MateoGreil** [comment]
Hi back, after many months, I remind me this issue.
I'm not sure to get you about one important thing :
Are you ok to add this feature ? (I guess yes, else, you should probably close it ?)
And are you ok with my method to add a route `/diary/preferred_languages` ?
I think I should be more precise : I just want to be inspired by `/diary/nearby` / `/diary/friends` : just to create a param `preferred_languages`, in the `diary#index`. By consequent, also accessible via `/diary?preferred_languages=true`.

**Comment by mmd-osm** [comment]
I think this was fixed in #4451. You should see a link in the header that would return diary entries in your preferred language only:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/5d26e0b9-0227-4964-91bc-d0ab99cb4254)
