### ISSUE TITLE
Login is not a verb

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#2703]
I think that a word "login" should be changed in some places to "log in" because "login" is not a verb:
http://www.notaverb.com/login

The places where it should be changed:
- Osm:Messages.reply.wrong user - "Please login as the correct user in order to reply."
- Osm:Messages.show.wrong user - "Please login as the correct user in order to read it."
- Osm:Users.login.with username - "Please login with your username and password"
- Osm:Users.new.use external auth - "Alternatively, use a third party to login"
- Osm:Users.auth association.option 2 - "If you already have an account, you can login to your account
using your username and password and then associate the account with your ID in your user settings."

Other messages with "login" but in these cases it can be either a verb or a noun (as "the process of logging in") but I think they should be changed too.
- Osm:Users.login.title - "Login"
- Osm:Users.login.login button - "Login"
- Osm:Users.login.auth providers.openid.title - "Login with OpenID"
- Osm:Users.login.auth providers.google.title - "Login with Google"
- Osm:Users.login.auth providers.facebook.title - "Login with Facebook"
- Osm:Users.login.auth providers.windowslive.title - "Login with Windows Live"
- Osm:Users.login.auth providers.github.title - "Login with GitHub"
- Osm:Users.login.auth providers.wikipedia.title - "Login with Wikipedia"
- Osm:Users.login.auth providers.yahoo.title - "Login with Yahoo"
- Osm:Users.login.auth providers.wordpress.title - "Login with Wordpress"
- Osm:Users.login.auth providers.aol.title - "Login with AOL"

**Comment by tomhughes** [comment]
Thanks, but I think the boat has long since sailed on this and those are clearly representative of modern common english usage.

**Comment by maro-21** [comment]
Why did you close the issue?

**Comment by Contributor2230** [comment]
I'm also wondering why this was closed. While it might be common to use "login" as a verb in many contexts, it doesn't appear to be the convention for buttons in user interfaces such as [/login](https://www.openstreetmap.org/login), where I'd expect the submit button to use two words:
<img width="76" alt="login" src="https://user-images.githubusercontent.com/110362694/182057873-b9c30e93-71ab-4cd1-a152-46b68981d06a.png">

*Examples of common usage in user interfaces*

**OpenStreetMap**
This usage is not consistent with OpenStreetMap itself: The header uses the two-word verb form "Log In."
<img width="651" src="https://user-images.githubusercontent.com/110362694/182057547-2a5be78b-720a-4de5-9ac9-57cab922f7d5.png">

This usage is also not consistent with [/user/new](https://www.openstreetmap.org/user/new), which uses a "Sign up" button instead of "Signup."
<img width="95" src="https://user-images.githubusercontent.com/110362694/182057691-51a5b9ec-9636-44a4-af8a-526a4ea98b3e.png">

This usage is not common amongst the third party authentication providers supported by OpenStreetMap, none of which use "Login" or "Signup" as the action on the authentication form.

**OpenID**
N/A. It's a protocol, not an identity provider itself.

**Google**
Somewhat N/A as the submit button is "Next," but like the OpenStreetMap header, the link to the auth page is "Sign in."
<img width="105" src="https://user-images.githubusercontent.com/110362694/182058975-43225337-86c2-4d5f-ab0a-088af1031271.png">

**Facebook**
"Log In"
<img width="313" src="https://user-images.githubusercontent.com/110362694/182059345-47d0aa12-1958-447d-a5fa-99618cc16ec6.png">

**Microsoft**
"Sign in"
<img width="361" src="https://user-images.githubusercontent.com/110362694/182059616-ce901203-f8b3-488b-a0d1-0ff13a3a90f9.png">

**GitHub**
"Sign in"
<img width="289" src="https://user-images.githubusercontent.com/110362694/182059684-bc0e8aeb-93b6-4576-bf5e-5e3b045dbc87.png">

**Wikimedia**
"Log in"
<img width="303" src="https://user-images.githubusercontent.com/110362694/182060236-cfa41d9c-0781-43d3-8337-32d15e4f3fde.png">

I looked at a few other authentication forms on popular sites (WordPress.org, Flickr, Waze) and was not able to find any examples of "Login" as the text for the submit button.

This is of course a nitpick, and it's perhaps impossible to argue that any language usage is incorrect when there isn't a list of rules that the community has agreed on. However, I notice that button _every_ time I log in. :)

**Comment by maro-21** [comment]
This was corrected in March 2024, so the topic can be closed.

**Comment by maro-21** [comment]
I'm not opening a new issue but I hope someone will see my message here.

There is one new string again with "login" as a verb, even though all the other "Log in with Google, Wikipedia, etc" are spelled "Log in":

<img width="807" height="495" alt="Image" src="https://github.com/user-attachments/assets/1a0a81a1-e7af-4f49-b802-b8a711479236" />

It is a string "Login with Apple":
https://translatewiki.net/wiki/Osm:Application.auth_providers.apple.title/en
used on https://www.openstreetmap.org/user/new at the bottom.
