### ISSUE TITLE
Dynamic configuration for tile server 

### ISSUE THREAD

**Issue by galta95** [openstreetmap/openstreetmap-website#2733]
After running a local opnstreetmap environment that includes openstreetmap-website, tile server e.t.c, 
when configuring a local tile server it requires you to change the source code. 
I would like to be able to configure a different tile server from the configuration file or some place else. 
The alternative is to search in the project the url of *.tile.openstreetmap.org and change it to our own tile server, and it's uncomfortable.
If you are open minded to that change, i can help with that.

**Comment by mmd-osm** [comment]
It's not only this project, leaflet.osm.js is even in another repository: https://github.com/openstreetmap/leaflet-osm

Not sure how you would make this more dynamic.

**Comment by galta95** [comment]
I ment that to change the requests to my local tile server it requires a change in the source code, because it is hard coded. look at lines 5, 17: 
![Screenshot from 2020-07-27 13-00-15](https://user-images.githubusercontent.com/48960890/88529943-5bb39400-d009-11ea-8f12-6c36d804a3fa.png)

**Comment by mmd-osm** [comment]
Right, the file on your screenshot comes from another repository, like I mentioned before. You cannot change it in this repository, as any changes would be overwritten next time the Gem gets updated.

**Comment by tomhughes** [comment]
Plus we support five different layers, each of which has a number of things that would need configuring.

Essentially doing this would require abandoning use of the leaflet-osm plugin and just configuring the layers dynamically from the a YAML file or something.

I understand that this is a common request but at the end of the day the prime goal of this repository is to provide the osm.org interface and third parties wanting to reuse it are almost always going to need to maintain some sort of light fork because while we try to make things configurable where we easily can we're not going to go out of our way to make this a portable project because that's not really it's goal.

**Comment by mmd-osm** [comment]
(Closing based on previous explanation)

**Comment by AntonKhorev** [comment]
> Essentially doing this would require abandoning use of the leaflet-osm plugin and just configuring the layers dynamically from the a YAML file or something.

Why do we need the leaflet-osm plugin, an external dependency that became unmaintained right after its first release?

**Comment by AntonKhorev** [comment]
> the prime goal of this repository is to provide the osm.org interface ... while we try to make things configurable where we easily can we're not going to go out of our way to make this a portable project because that's not really it's goal.

We're not making it easy for ourselves by keeping parts of layer configuration in two different repositories.

**Comment by mmd-osm** [comment]
Yes, agree. I wanted to change the processing in leaflet-osm to JSON format, and consolidate it with what displaying query results is doing. Having an abandoned addon with relatively small amounts of code in there does not really help performing such changes.
