### ISSUE TITLE
Learn why people visit the Copyright page

### ISSUE THREAD

**Issue by migurski** [openstreetmap/openstreetmap-website#2736]
[Grant says](https://github.com/openstreetmap/openstreetmap-website/pull/2735#issuecomment-664703858):

> The top page on OpenStreetMap.org is https://www.openstreetmap.org/copyright, it unsurprisingly also has the highest bounce rate. It would be good to also have a think about how we could improve that page and get move people who arrive on /copyright converted into mappers.

A high bounce rate is not necessarily a bad thing, since people might have gotten what they need from it and left happy. We learned at Code for America that traditional user metrics could often be interpreted backwards for government services on the web.

I suggest we add an [Ethnio web intercept prompt](https://ethn.io/intercepts) for a limited time to that page so we can do some non-invasive user research, learn what people were looking for when they got there, and hopefully determine whether it needs work.

**Comment by tomhughes** [comment]
There's no secret why people visit it - lots of big downstream sites link to it in their attribution.

**Comment by tomhughes** [comment]
So 74% of them are actually direct entries which is a little surprising - maybe that is people coming from mobile apps that have a link in the attribution?

Another 25% are from other websites, again likely people following links from attribution. Few sites stand out in that - even the largest only have a couple of percent of that 25% portion.

Everything else is basically a rounding error.

**Comment by migurski** [comment]
Would we be interested in knowing anything more about why those visitors clicked through to the copyright page? If not, we can close out this issue.

**Comment by woodpeck** [comment]
My $0.02: Interested in knowing more, yes; willing to display a popup that attempts to "engage" users, no; using a proprietary third-party software to do that, hell no.

**Comment by simonpoole** [comment]
...
> I suggest we add an [Ethnio web intercept prompt](https://ethn.io/intercepts) for a limited time to that page so we can do some non-invasive user research, learn what people were looking for when they got there, and hopefully determine whether it needs work.
...
There is currently no legal way we could use Ethnio since the data transfers would rely on the, now defunct, privacy shield agreement (and SCCs are not likely to survive either), not even considering the tsunami of outrage this would cause (which is not my problem, but worth mentioning).

**Comment by migurski** [comment]
Thanks Simon, that’s useful feedback! Perhaps we should leave this issue open to determine if the outrage tsunami is real or just an illusion? 

Frederik, do you have any alternative suggestions for learning from our users?

**Comment by simonpoole** [comment]
There seem to be numerous rails gems that provide survey functionality so not being able to use a 3rd party service isn't a blocker.

But I'm not sure that there is really anything big to be learned to start with, as the copyright page is the page our attribution guidance requires to be linked to. I can faintly remember a discussion way back which touched exactly on the topic of if it wouldn't be preferable to link to openstreetmap.org directly because that might work better from a recruiting pov. In any case I can't make an argument against adding some text at the top of the page for people that are not interested in the legal aspects.

**Comment by mmd-osm** [comment]
OT: What most people would rather know is how many users never get to see this copyright page because the app/website they're using does not properly attribute OSM.

**Comment by migurski** [comment]
MMD, can you share any data to expand on that?

**Comment by mmd-osm** [comment]
Sure. Although, it's probably off topic for this particular issue, this may offer a different perspective on the overarching topic that community member frequently raise as an issue.

As an example take a look at what people on https://t.me/OpenStreetMapOrg have to say on the topic "attribution", and how frequently this topic pops up in the discussion. Or maybe Twitter: https://twitter.com/search?q=attribution%20openstreetmap&src=typed_query&f=live

**Comment by migurski** [comment]
You’re right, that is completely off-topic.

**Comment by migurski** [comment]
I’m going to go ahead and close this issue since I’m not seeing a lot of support for the idea of learning about these inbound users or suggestions on productive ways to do it.

**Comment by Firefishy** [comment]
@migurski I think the reason is known why many people reach the /copyright page is particularly known, it is people clicking on the OpenStreetMap attribution link on maps which use OpenStreetMap data... Although we could likely know more eg: are they clicking the link to find out about what is OpenStreetMap or are they clicking the link because they've seen some error or something missing on the map....

It would be good to see if we could improve the /copyright page. We could use existing piwik analytics to measure the number of people arriving on /copyright and then successfully creating an account.

**Comment by grischard** [comment]
> So 74% of them are actually direct entries which is a little surprising 

Linking to the http URL [like this](http://openstreetmap.org/copyright), instead of https, will strip the referrer in most browsers.
