### ISSUE TITLE
Add banner to notify about "active contributor membership program" in website

### ISSUE THREAD

**Issue by naveenpf** [openstreetmap/openstreetmap-website#2789]
![image](https://user-images.githubusercontent.com/12662835/90973944-541dd700-e544-11ea-9538-ed15edbab2f5.png)

@dorotheakazazi

**Comment by dorotheakazazi** [comment]
@naveenpf Thanks for the ping. I will probably submit a PR once the Spanish translation of the announcement is ready, so that _(if the PR is approved by the OWG)_ it will have a bit wider reach than just community members who know English. The image will be a different one, most likely without much text.

**Comment by tomhughes** [comment]
Can you add this to the agenda for the OWG call this week please @dorotheakazazi?

**Comment by naveenpf** [comment]
@dorotheakazazi  Thanks

**Comment by gravitystorm** [comment]
I'm going to close this as there hasn't been any activity here for a year. If there's a pull request to implement it that of course would be welcome.
