### ISSUE TITLE
Avoid flickering in export

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#2791]
See comments in: https://github.com/openstreetmap/openstreetmap-website/commit/30122011609aa02c32cfef6a31d3f28c1d0207e4

>I'm seeing a yellow warning box for "export_osm_too_large" for a fraction of a second, only to disappear again immediately. I don't recall seeing this kind of flickering before.
> Is there some way to tell the export_osm_too_large id to start out with "display: none" as default?

**Comment by gravitystorm** [comment]
This turns out to be harder than I thought. :smile: 

The jQuery `.toggle` works by applying a `style="display: none"` to the element, but I can't use an inline style to hide it by default (due to CSP) and the bootstrap `d-none` class sets `display: none !important` and that overrides the toggling. This means that we need to change the javascript slightly, to use `.toggleClass` instead of .`toggle`, e.g. `.toggleClass("d-none", getBounds().getSize() < OSM.MAX_REQUEST_AREA);`

The bigger issue is choosing what to show by default, since we need to consider both the message and the button. If I hide the message and show the button by default, that looks fine when the initial state is zoomed in, but flickers when the initial state is zoomed out. If show the message and hide the button, it looks fine when zoomed out but flickers when zoomed in.

I'm not sure what the best approach is. Maybe we need to hide the entire panel by default, let the calculations run once to show either the message or the button, and then show the entire panel after that calculation has run?

**Comment by mmd-osm** [comment]
Hmm, if this minor inconvenience turns out to be a major time sink, I would opt for leaving it as is for the time being.
