### ISSUE TITLE
Flickering of map layer labels on Safari

### ISSUE THREAD

**Issue by hikemaniac** [openstreetmap/openstreetmap-website#2807]
When I open the map layer pane and scroll on my iPhone, their labels start flickering arbitrarily. I am using **iOS 13.6.1**.

![map labels flickering](https://user-images.githubusercontent.com/31667811/92025083-51e72400-ed5f-11ea-85ee-5e1885b3607d.gif)

**Comment by gravitystorm** [comment]
I can confirm that I see the same on iOS 13.

However, I've just upgraded to iOS 14 and I don't see the problem any more. Can you confirm if it's fixed for you too?

**Comment by hikemaniac** [comment]
@gravitystorm I updated my phone to iOS 14.0.1 today and I can confirm that the flickering has disappeared. Should this issue be closed now or should we still try to fix it for older Safari versions?

**Comment by gravitystorm** [comment]
I'd love to fix it, but I no longer have a device running the affected version ( :smile: ) and I wouldn't know where to start or how to debug on iOS anyway. And unless anyone explains otherwise, it might well be a pure Safari problem that we can't fix.

So I'm going to close this issue, but if anyone has any insights or suggestions, I'm happy to reopen it.
