### ISSUE TITLE
Spurious Bulgarian in query tool result

### ISSUE THREAD

**Issue by eehpcm** [openstreetmap/openstreetmap-website#2852]
I used the query tool on [this building](https://www.openstreetmap.org/?mlat=52.08112&mlon=-4.65761#map=19/52.08112/-4.65761) and this is what came back.

![query_bug](https://user-images.githubusercontent.com/3224921/94369042-5b09ad80-00df-11eb-9c25-cc8e4e2b8bdb.png)

It should say "Industrial building" not  "Индустриална сграда" (Google Translate tells me that is Bulgarian for "Industrial building").

My browser is configured to default to English and Bulgarian is not in the list of languages I want it to accept.  Most other things I've queried come back in English.

**Comment by gravitystorm** [comment]
There's some bulgarian translations in the en-GB.yml file that we received from Translatewiki. 

It would be good if someone can investigate on Translatewiki to see if there's a pattern of this happening or if it's just a one-off, since we had something similar happen recently (see https://github.com/openstreetmap/openstreetmap-website/issues/2841 and links)

**Comment by tomhughes** [comment]
I likely missed some as I only did the one block when I fixed the previous issue.

**Comment by tomhughes** [comment]
Looks like https://github.com/openstreetmap/openstreetmap-website/commit/0aab333adb#diff-63ce76535a96f7acb5e8e66cea31936b was the original source.

I think I've fixed all the remaining issues on TW now.

**Comment by gravitystorm** [comment]
> I think I've fixed all the remaining issues on TW now.

Thanks! Looking at that commit, and the authors contributions to other files, I think we can file this as most likely a single honest mistake.
