### ISSUE TITLE
Still problems with yarn in INSTALL.md

### ISSUE THREAD

**Issue by zanguian** [openstreetmap/openstreetmap-website#2968]
(On my ubuntu machine 20.04.1) After the most recent commit to INSTALL.md regarding yarn, I am still getting several errors after running 
`bundle exec rake test:db`

It seems that the addition of `sudo apt-get install yarnpkg` in INSTALL.md didn't fix the problem. However, when I manually install yarn via instructions of the official website (https://classic.yarnpkg.com/en/docs/install/#debian-stable), I get no errors after running `bundle exec rake test:db`

Are we able to add this into the markdown file?

**Comment by tomhughes** [comment]
No, we are not going to recommend that people install software outside of the OS packaging system because it's a terrible idea.

If you want us to help you then you have to actually tell us what you problem is - that means telling us what error you get in detail not just "it didn't work".

**Comment by gravitystorm** [comment]
I took some time today to spin up a fresh vagrant/virtualbox (by hand, not using the Vagrantfile in this repo) and worked through the installation instructions manually. I didn't encounter any problem involving yarn, so I can't investigate this report further without more information.

At the least, we need to see the error messages to know what to do next. And ideally, we need some set of instructions to follow to trigger the error, since I couldn't trigger it using the INSTALL.md instructions.

I'm going to close this issue now, but I'll reopen it if/when we get more information.
