### ISSUE TITLE
performance reduced when updating/migrating

### ISSUE THREAD

**Issue by caleb87** [openstreetmap/openstreetmap-website#2980]
I tried to migrate and update to a different server, but the read/write performance has went drastically down even though it should have went up.

**Old Setup**: Ubuntu 16, AWS with 32gb ram, 4 threads, 2.5ghz, EBS SSD, postgresql 9.5
Loads the bbox in 18 seconds: /api/0.6/map?bbox=-97.58167,35.385,-97.51833,35.44833

**New Setup:** Ubuntu 20, 128gb ram, 128 threads, 3.8ghz, m.2 500k IOPS read/write, postgresql 12
Loads the bbox in 144 seconds

Postgresql config is the same, but shared_buffers was changed from 10GB to 90GB.

The production server fetches the bbox in 2.5 seconds. 

 Any idea what could be causing the performance issue?

**Comment by tomhughes** [comment]
This is a bug tracker for the web site code, not a forum for help with postgresql tuning...

We don't even use the code in this repository for the production API because it is known to have poor performance but obviously if you are seeing a difference where the only thing you have changed is the hardware and the database then that is what you need to look at, not any of our code.

Clearly there is something drastically wrong which should be fairly obvious from comparing the execution plans - most likely you need to analyse the new database or something.

**Comment by caleb87** [comment]
When running
SELECT COUNT(*) FROM current_nodes; 

the old database did it in 7m 30s, and the new one did it in 3 minutes. That seems like postgres is running fine, but OSM is doing something wrong.

**Comment by tomhughes** [comment]
Yes that's definitely a valid test - of how fast your database can table scan `current_nodes` but it says absolutely nothing about the kind of queries involved in running the map call which involves joining a number of tables and (hopefully) choosing to use indexes instead of table scanning.

Please, looking at your log, see what queries are slow, and try analysing them.

Also, seek help from postgres experts if you need help with postgres.

If you really want to claim it's our code then run the same version on both machines so the results are comparable.

First rule of debugging - change one thing at a time. You have apparently changed hardware, database and rails code all in one go and you're now guessing which of those variables is the problem. Try and eliminate some of those variables to see where the problem is. A good start is to run the older rails code on the new machine or the new rails code on the old machine because that's easy to do.

That said, the API code in this repository hasn't changed significantly in years because, as I say, we don't actually use it!

**Comment by caleb87** [comment]
I agree on running it the same, though it's been a pain trying to clone the AWS server to a local machine. 

The version I previously had is drastically different than the current version. The old one I had is from 2017 or so. The logs show what's happening, and it's just way more queries than it used to be. 

[slow.log](https://github.com/openstreetmap/openstreetmap-website/files/5593752/slow.log)
[fast.txt](https://github.com/openstreetmap/openstreetmap-website/files/5593751/fast.txt)

**Comment by gravitystorm** [comment]
All the lines in the "slow" log with CACHE are not actual queries to the database, so you can ignore them. You can also see that they take 0ms to run. 

But even if you take the first "Node Load" query, the queries are identical and your "slow" one takes 7.7ms and your "fast" one takes 4.3ms. For the same query. I echo Tom's suggestions of looking into your database to find out why these identical queries are taking much longer to run.

There are also plenty of things we can improve in the map call performance, when it comes to preloading data. But as Tom has also explained, this is a low priority since OSMF uses cgimap in production.

**Comment by tomhughes** [comment]
Yes what you want to do now is to analyse that query on both databases, do in the postgres console run this:

```
explain analyze SELECT  "current_nodes".* FROM "current_nodes" WHERE (( tile BETWEEN 1334380527 AND 1334380543 OR tile BETWEEN 1334381903 AND 1334381919 OR tile BETWEEN 1334381935 AND 1334381951 OR tile BETWEEN 1334382032 AND 1334382033 OR tile BETWEEN 1334382036 AND 1334382037 OR tile BETWEEN 1334383264 AND 1334383295 OR tile BETWEEN 1334383328 AND 1334383359 OR tile BETWEEN 1334383520 AND 1334383535 OR tile BETWEEN 1334384640 AND 1334384769 OR tile BETWEEN 1334384772 AND 1334384773 OR tile BETWEEN 1334384784 AND 1334384785 OR tile BETWEEN 1334384788 AND 1334384789 OR tile BETWEEN 1334384832 AND 1334384833 OR tile BETWEEN 1334384836 AND 1334384837 OR tile BETWEEN 1334384848 AND 1334384849 OR tile BETWEEN 1334384852 AND 1334384853 OR tile BETWEEN 1334384896 AND 1334384911 OR tile BETWEEN 1334384928 AND 1334384943 OR tile BETWEEN 1334385024 AND 1334385025 OR tile BETWEEN 1334385028 AND 1334385029 OR tile IN (1334380517,1334380519,1334380525,1334381893,1334381895,1334381901,1334381925,1334381927,1334381933,1334382021) ) AND latitude BETWEEN 346183300.0 AND 346816700.00000006 AND longitude BETWEEN -982816700.0 AND -982183300.0) AND "current_nodes"."visible" = true limit 15501;
```

and then paster the output into something like https://explain.depesz.com/ to visualise it better, for example https://explain.depesz.com/s/GWGc is the plan for that query on our production database.

What you're looking for in the first instance is the scan types on the stats tab - you want to see index scans or bitmap heap scans and definitely not any sort of seq scan.

**Comment by caleb87** [comment]
I rsync'ed my old openstreetmap-website folder, ran it, and it finished the same area in 547ms on the new "slow" machine. On the same machine, I went back to latest OSM website folder, ran it, and it comes back 3800ms. They are both using the same database, but the latest git clone is slow. Is it possible that the latest osm website requires a configuration that's slowing it down that wasn't there before? I'm just using a default git clone on both.

@gravitystorm there are dozens of log rows that show 5-6ms. I didn't add them up. They probably don't total 3800ms though. 
`Node Load (6.2ms)[0m  [1m[34mSELECT "current_nodes".* FR.....


```
New OSM website clone on new machine
Rendered api/map/index.xml.builder (Duration: 3489.9ms | Allocations: 3999549)
Completed 200 OK in 3806ms (Views: 2738.0ms | ActiveRecord: 806.8ms | Allocations: 4342985)
```

```
Old OSM website clone on new machine
Completed 200 OK in 547ms (Views: 0.1ms | ActiveRecord: 77.8ms)
```




```
OLD SERVER
About your application's environment
Rails version             5.1.5
Ruby version              2.3.1-p112 (x86_64-linux-gnu)
RubyGems version          2.5.2.1
Rack version              2.0.4
JavaScript Runtime        therubyracer (V8)
Middleware                SecureHeaders::Middleware, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::Local                                                                                                                    :Middleware, ActionDispatch::RemoteIp, Sprockets::Rails::QuietAssets, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions,                                                                                                                     , ActionDispatch::Cookies, ActionDispatch::Session::CacheStore, ActionDispatch::Flash, Rack::Head, Rack::ConditionalGet, Rack::ETag, HttpAcceptLanguage::Mid
Application root          /home/ubuntu/openstreetmap-website
Environment               development
Database adapter          postgresql
Database schema version   20180204153242
```

```
NEW SERVER, OLD OSM CLONE THAT I RSYNC
About your application's environment
Rails version             5.1.5
Ruby version              2.7.0-p0 (x86_64-linux-gnu)
RubyGems version          3.1.2
Rack version              2.0.4
JavaScript Runtime        therubyracer (V8)
Middleware                SecureHeaders::Middleware, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, Ac:Middleware, ActionDispatch::RemoteIp, Sprockets::Rails::QuietAssets, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::Cookies, ActionDispatch::Session::CacheStore, ActionDispatch::Flash, Rack::Head, Rack::ConditionalGet,
Application root          /home/ubuntu/openstreetmap-website
Environment               development
Database adapter          postgresql
Database schema version   20201006220807
```


```
NEW SERVER, LATEST OSM WEBSITE CLONE
About your application's environment
Rails version             6.0.3.4
Ruby version              ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
RubyGems version          3.1.2
Rack version              2.2.3
JavaScript Runtime        Node.js (V8)
Middleware                OpenStreetMap::Cors, SecureHeaders::Middleware, ActionDispatch::HostAuthorization, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::URISanitizer, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, ActionDispatch::RemoteIp, Sprockets::Rails::QuietAssets, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, BetterErrors::Middleware, ActionDispatch::ActionableExceptions, ActionDispatch::Reloader, ActionDispatch::Callbacks, ActiveRecord::Migration::CheckPending, ActionDispatch::Cookies, ActionDispatch::Session::CacheStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper, I18n::JS::Middleware, HttpAcceptLanguage::Middleware, OpenStreetMap::CompressedRequests, OAuth::Rack::OAuthFilter, OmniAuth::Builder
Application root          /home/osmserver/openstreetmap-websiteNEW
Environment               development
Database adapter          postgresql
Database schema version   20201006220807
```
