### ISSUE TITLE
Move export tab to right hand tool pane

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#3040]
The `Export` button to the right of the `Edit` and `History` buttons is rarely-used.

The majority usage population of the OSM website are mappers like me. 
I never have used the `Export` feature and probably never will because other file export options such as from the Overpass API and JOSM's import are much more convenient. 
Also, the pane does not even explain that it's exporting in the `.osm` format, offer to export in other formats say through a dropdown menu, and only has links to other sites.

It does not make sense to have it as a top-level heading link.

**I think it's pane contents should be either:**
- Moved to the `Share` button on the options pane right of the map and the hover text be renamed to `Share/Export`.
![ink](https://user-images.githubusercontent.com/22477298/103845057-e5f42f80-5060-11eb-9904-8dd977f1a566.png)
- Be added as a new dedicated Export button on the options pane right of the map.

**Here is what the site would look like without it:**
![image](https://user-images.githubusercontent.com/22477298/103846404-9ebb6e00-5063-11eb-91a8-e071f9a4df5a.png)

**Comment by HolgerJeromin** [comment]
I also never use the export. But this option is one of the mayor difference to other mapping data sources.
You can download the raw data...

**Comment by dieterdreist** [comment]
I find the export button a bit confusing, because the API is reserved for editing purposes. Maybe it should be renamed to "get the data" or something like this, with links to the planet and extracts, it is already there and shows when you select an area that is too big: "This area is too large to be exported as OpenStreetMap XML Data. Please zoom in or select a smaller area, or use one of the sources listed below for bulk data downloads."

**Comment by lectrician1** [comment]
Just for clarification _I am not asking to remove the button_, just move it's view to another button that is less-prominent.

**Comment by tomhughes** [comment]
Yes we're well aware that this is really just a trojan horse because you didn't think you'd be able to persuade us to add a Wiki tab unless you first removed something else - it would probably have helped your case here if you had been up front about that when opening this.

Personally I would be quite happy to remove the export button because I can't see that it gets any significant use because it's not really very useful. It's one of those things that seems reasonable on the surface but because it relies on an API that is only designed to deliver up small areas it's hard to see that it has much practical use, as the fact that we've had to add lots of hints on how to get larger areas to the panel!

**Comment by lectrician1** [comment]
> you didn't think you'd be able to persuade us to add a Wiki tab unless you first removed something else

This was not my intent at all. I just thought of the 2 improvements when thinking about improving the heading in-general.
Please do not assume that I have passive-aggressive intentions Tom.

**Comment by mmd-osm** [comment]
>  it relies on an API that is only designed to deliver up small areas 

Current limit of 50'000 nodes is only in place for compatibility reasons with the Rails port, most likely to have sane limits for memory and cpu consumption im place.

I don't think the current cgimap implementation was specifically _designed_ to only serve up small areas. I'm not aware of any technical limits that would break it when exceeding 50k nodes.

**Comment by tomhughes** [comment]
Well no but it's never going to scale to downloading the sort of size of area most practical uses would require nor do we particularly want it to when extracts are a much better solution.

**Comment by tomhughes** [comment]
Apologies if that was not your intention @lectrician1 it just seems like an extraordinary coincidence that the two were opened at the same time.

I was actually under the impression that they were pull requests, and it seemed implausible that somebody would have done the large amount of work that moving this would involve on a whim but I see that they are actually just issues.

**Comment by natrius** [comment]
Well, do not think somebody wants to do something bad. Maybe he just thought about the UI as a whole and stumbled upon this. it seems like he thought about it as well, because the issues were made close to another, timewise. If he would have made this issue after you declared you do not want to change this, maybe. But even then, that does not change anything - he is correct, this button should not be that porminent up there, it should be in the sidebar.

**Comment by AntonKhorev** [comment]
*Export* was moved in #5151, therefore this issue may no longer be relevant. If you still want to move *Export* elsewhere or rename it, it's better to open a new issue.
