### ISSUE TITLE
Add Wiki Link to Heading

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#3041]
The Wiki is a major resource used by the OSM community. Having a dedicated link to it in the heading would be useful.

Here's a suggested placement:
![image](https://user-images.githubusercontent.com/22477298/103848396-e6dc8f80-5067-11eb-9454-79bdff9bfd24.png)

**Comment by gravitystorm** [comment]
The wiki is already linked to from as part of the Help pages. I prefer this approach, since it is more flexible and easier to expand with multiple (and future) useful external links.

We can't add everything to the menu, so we draw the line somewhere. 

And I'm not in favour of linking to external sites in the menu bar either.

**Comment by lectrician1** [comment]
The Wiki is not _really_ an external site. It is hosted by OSMF and the root of the OSM community. No mapper should have to figure out that the Wiki is in box at the _bottom_ of the help page. 

Also, I've found the Wiki to be my **most-used OSM resource** as a mapper other than the site itself (for iD and carto). There should be immediate access for anyone who does or doesn't know about it.

The Wiki also acts as a community hub. Currently, we have OSMcal, regional mapping projects, links to other communication channels, and of course, tag pages - where mappers can learn more and discuss on talk pages about tags. **All** of these things are nonexistent on the main site itself and are vital to holding together the community.

I'm also a bit frustrated that you closed this based on your opinion alone, when the feature request clearly has support by numerous others.

**Comment by gravitystorm** [comment]
> The Wiki is not _really_ an external site. It is hosted by OSMF and the root of the OSM community.

I'm not debating who hosts it, or whether it's part of the community. I mean that it's an external site in that you click the link and you end up on a different site. You can notice this when the top bar changes and all the links change and it everything looks different. The other links in that menu are not external sites, since you click on them and you are still on the same site, with the same menu and it looks the same and so on.

It's great that you find the wiki useful, but that doesn't mean that it should automatically get a link in that menu - there are more things to consider than that.

And as for closing the issue - I've explained my reasoning, and I'm happy to explain my reasoning in more detail if you want. Or you can offer alternative considerations to persuade me otherwise. But please don't complain about a decision based on 'clear support by numerous others' since that ignores my reasoning entirely. One of the burdens of a maintainer is to make decisions, sometimes unpopular ones - but that's why I always explain things.

**Comment by lectrician1** [comment]
Yes, then please explain.

**Comment by gravitystorm** [comment]
> Yes, then please explain.

I've explained my reasoning twice already. You need to tell me which bit of my explanation is unclear or needs to be explained in more detail.

**Comment by lectrician1** [comment]
> there are more things to consider than that.

What are the more things?

**My further explanation**
I completely understand the argument that you wouldn't want another site to be linked as a heading, but I personally feel really strongly about the Wiki and think it should have a much better place on the main site than what it currently has. I also think the pros outweigh the cons.

I feel it's okay in this situation for it to link to another site. I've been told _time and time again_ that `openstreetmap.org` is mean for _contributors_. Many times [I've suggested features or simplifications of the site](https://docs.google.com/presentation/d/1Qlp8_f01oRq3ZslJpCuuy-ef-gCD22LpJwAwDtwOPSU/edit?usp=sharing) that make it more like a map product rather than a tool (I want it to look nicer). Community members tell me that should remain as a tool/editor.

Therefore, if the site is meant for contributors, then shouldn't we accommodate that population to the fullest extent? The Wiki as I noted has quite the importance to the community. It itself is also used as a tool. I see little conflicts between the Wiki and the main site when each offer important, but separate features to the community. Contributors should _know_ that the Wiki links to an external site. This is no shock for them. The link will of course open in a new tab, meaning that they won't navigate from the site itself.

Another comparable situation are websites that also have wikis eternally sourced. For example, software projects that use ReadTheDocs for documentation, or even MediaWiki too. 
They link the documentation for their product in the heading of their website. Why can't we?

**Other options**
Another option could be making a "Community" page and heading. This could replace and combine the functions of the "User Diaries" and potential "Wiki" Heading.

If you have any other ideas about a better placement, please share.

**Comment by mxxcon** [comment]
> I mean that it's an external site in that you click the link and you end up on a different site. You can notice this when the top bar changes and all the links change and it everything looks different. The other links in that menu are not external sites, since you click on them and you are still on the same site, with the same menu and it looks the same and so on.
> 
You don't think OSM's wiki, probably the de-facto source of documentation for all the mappers doesn't deserve the top-level navigation simply because it doesn't look the same?
If that's the criteria then https://www.openstreetmap.org/about shouldn't be there either since it looks completely different from all the other pages.
And does MediaWiki really doesn't have any option to customize the way header looks? There are no plugins/add-ons to add such functionality if it's missing?

> It's great that you find the wiki useful, but that doesn't mean that it should automatically get a link in that menu - there are more things to consider than that.

What's more important for day-to-day user of OSM: the primary reference source of the documentation and tags or links to "About" and "Copyright" pages?
How often when you map some area do you need to reference the copyright page?

Yes, copyright and proper attribution information is important, but such pages can be minimized/condensed/combined to free up space in the header for a wiki link. If you are already contributing to OSM that you means you already read those pages and know what's there.

**Comment by tuckerrc** [comment]
I think the current navigation is fine. It might be worth adding a link to the wiki somewhere on the https://www.openstreetmap.org/about page though. If users follow the "Learn More" link in the initial dialog it goes to the about page where we can introduce new users to the wiki.

![image](https://user-images.githubusercontent.com/4624530/106367628-0a66c300-6312-11eb-9661-930708f7740d.png)

As it stands there are plenty of other ways to get to the wiki. Any page on www.openstreetmap.org is only two clicks away ("Help" > "OpenStreetMap Wiki"). When using the iD editor every single field has an "i" icon that opens more info and a link to the wiki page related to that field.

**Comment by SomeoneElseOSM** [comment]
> Any page on www.openstreetmap.org is only two clicks away ("Help" > "OpenStreetMap Wiki")

... and the keys and values on any OSM object being viewed also link straight through to the wiki.  Try clicking on any of the links at the left of https://www.openstreetmap.org/way/631675997 , for example.

**Comment by mxxcon** [comment]
> When using the iD editor every single field has an "i" icon that opens more info and a link to the wiki page related to that field.
There's no "i" icon when you are not sure how to map something and need to documentation to reference how to do it.

Ultimately, you consider "copyright" page to be more useful to mappers than a documentation site.

**Comment by tuckerrc** [comment]
> Ultimately, you consider "copyright" page to be more useful to mappers than a documentation site.

I think the "copyright" page is more important for mappers to be aware of.

Anyplace the wiki is useful it is already linked (and directly to the relevant page).

**Comment by tuckerrc** [comment]
> There's no "i" icon when you are not sure how to map something and need to documentation to reference how to do it.

I just noticed this comment. In this case the "Help" link is better. Like @gravitystorm mentioned this gives us the opportunity to present several options for help. We don't know if the mapper is a beginner, maybe they have a question, or they want to switch from another mapping service. With one link we can provide answers to all these types of inquiries.

**Comment by dieterdreist** [comment]
sent from a phone

> On 31 Jan 2021, at 01:49, Tucker Chapman <notifications@github.com> wrote:
> 
> With one link we can provide answers to all these types of inquiries.
> 


the wiki should move up in the help list, from the very bottom to a place before “mailing lists” (and after beginner’s guide)

**Comment by lectrician1** [comment]
> I think the current navigation is fine.

And what's _not_ fine about adding the Wiki link to the heading? I would like for this issue to remain on-topic with the request at hand of placing the Wiki in the heading. Stalling out of stubborness for needed change and the thought that the "site is fine how it is" is disappointing.

Reordering its position on another part of the site will _barely_ help the visibility issue compared to if it were in the heading. There will basically be no change.

I think the previous arguments for doing so made by @mxxcon and I are strong and have not been directly addressed still.

**Comment by SomeoneElseOSM** [comment]
> And what's not fine about adding the Wiki link to the heading? 

It can be already pretty crowded, depending on font and screen size etc.  On the PC that I'm using now (a laptop with a 14" screen with Windows' "recommended" magnification level in place) the heading collapses to display only "More" if the browser window is less than about 80% of screen width, and that's with English as the language, which isn't one of the more verbose ones.  I certainly wouldn't want to see extra links up there (especially not extra links that are already accessible just 1 more click away).

**Comment by tuckerrc** [comment]
I cannot think of a website that has more links than the wiki. Sure it is not in the header but there are links to it everywhere, especially when you are mapping with iD (JOSM users will probably already have the wiki open on another tab). The links even go directly to the most relevant page. When looking at a way all the tag names are direct links to the wiki as well. If we add a link to the header you can only link to the main page of the wiki which might be confusing because it is a different website and not very helpful other than the user is now on the wiki.

The question to ask is what problem is linking to the wiki in the header going to solve and is the space it uses and possible confusion to user worth making that change.

> If you have any other ideas about a better placement, please share.

Higher placement on the "Help" page or a dedicated section on the "About" page would better serve new mappers by introducing them to the wiki. Once they know about it it is only a click away when they are mapping.

> Reordering its position on another part of the site will barely help the visibility issue compared to if it were in the heading. There will basically be no change.

What visibility issue? Links to the wiki are everywhere. 

> There will basically be no change.

Maybe in English but other locals already have longer secondary navs. Adding 25-30px may not seem like much but on smaller screens that adds up.  (a few examples)

| lang | width |
| --- | --- |
| en | ~500px |
| de | ~530px |
| es | ~625px |
| fr | ~625px |
| ru | ~660px |
| cy | ~660px |

The arguments against adding it to the header are already posted by @gravitystorm above and multiple users have pointed out how prominent the wiki is in the rest of the site. I do not see how adding a link to the header will improve visibility.

**Comment by mxxcon** [comment]
If the width of the header is the issue, then that's even more incentive to make it shorter. When the header collapses into "More", now your rule of "_Any page on www.openstreetmap.org is only two clicks away_" is broken.
Why not combine "copyright" and "about" into a unified page? "Wiki" is a shorter word than both of those words in English and probably all the listed languages.
And even beyond that, the site uses piwik for stats and analytics. Why not use it to see which of those links are the least used and consider combining or moving or even removing them?
For example, does "Export" get used so often that it deserves to be 1 of the 3 main buttons on the site? Does "GPS Traces" get used so often that it deserves to be the first of the secondary navigation links?
Wiki is more than just for beginners.

**Comment by lectrician1** [comment]
## Here are some views of the site I compiled
### Current Site
Test them on your own and compare to with Wiki heading views below. 
### Site with Wiki heading
#### Main
![image](https://user-images.githubusercontent.com/22477298/106510082-15e1f780-6494-11eb-924d-81113f6874a5.png)
####  Collapsed heading
![image](https://user-images.githubusercontent.com/22477298/106510212-40cc4b80-6494-11eb-93d7-6c6dec10c7a4.png)
#### More expanded 
![image](https://user-images.githubusercontent.com/22477298/106510372-74a77100-6494-11eb-901c-ee90a0167009.png)
#### Fully-collapsed heading
![image](https://user-images.githubusercontent.com/22477298/106510273-53468500-6494-11eb-87e4-7abec5163f09.png)
### Alternate headings
#### Copyright removed
![image](https://user-images.githubusercontent.com/22477298/106510822-0d3df100-6495-11eb-844a-2b16912993b3.png)
#### Copyright removed. GPS Traces and User Diaries Replaced with Community
![image](https://user-images.githubusercontent.com/22477298/106511225-8f2e1a00-6495-11eb-8083-bbb17a75aaa7.png)
#### Copyright removed. GPS Traces, User Diaries, and Wiki replaced with Community (my favorite)
![image](https://user-images.githubusercontent.com/22477298/106511432-d4eae280-6495-11eb-96fe-2f3f6eae9c50.png)
#### Copyright remains. GPS Traces, User Diaries, and Wiki replaced with Community.
![image](https://user-images.githubusercontent.com/22477298/106511717-3612b600-6496-11eb-8954-d4b7010ed477.png)
### Current Russian site (largest heading)
![image](https://user-images.githubusercontent.com/22477298/106518388-6f035880-649f-11eb-9191-5a6453601889.png)
### Russian site with Wiki heading
Wiki is a 4-letter word in Russian (Вики), so the same amount of change as English.
![image](https://user-images.githubusercontent.com/22477298/106518301-4a0ee580-649f-11eb-8251-555e794aa8bf.png)
### Other Page Views
#### Current help page
![image](https://user-images.githubusercontent.com/22477298/106513674-dff34200-6498-11eb-8f31-d78507e631d7.png)
#### OSM Wiki at the top of the help page
![image](https://user-images.githubusercontent.com/22477298/106513616-d073f900-6498-11eb-91ff-d10e2a8f00dd.png)
#### OPTION: Direct Help to OSM wiki help page (we would probably have to clean it up a bit)
![image](https://user-images.githubusercontent.com/22477298/106513755-f9948980-6498-11eb-8239-1904b0ebc81f.png)
#### OPTION: Community page 
I can't figure out ruby routing, but basically there could be a card style like on the Help page that has links to User Diaries, GPS Traces, and the Wiki.
#### OPTION (Extreme)
Use the Wiki instead of the main site to organize all external links. The site would just be used for the map viewer and editor.

For example:
* The **About** heading would lead to [Wiki About](https://wiki.openstreetmap.org/wiki/About_OpenStreetMap)
* The **Help** heading would lead to [Wiki Help](https://wiki.openstreetmap.org/wiki/Get_help)
* The **Copyright** heading would lead to [Wiki Copyright](https://wiki.openstreetmap.org/wiki/Copyright)

This might inspire some people to clean up the look of the Wiki :stuck_out_tongue: 

## Conclusion
The current heading takes up a lot of space to begin with. Maybe cutting down on some of the links will help.

If we were to add the Wiki link today, it would have little impact. "Wiki" is only 4 letters long. 

Everything still fits with all views of the site.

**Comment by cliffordsnow** [comment]
While I use the wiki often, having it on the main page isn't all that helpful. If you don't know what a wiki is just having a menu item wiki isn't all that helpful. Using DuckDuckGo, I just type !osmw with my search. Simple and quick.

I know that there are other projects close to being completed that in my opinion are more beneficial to OSM and should be on the main page. Microcosms and information on Local Chapters. The later just in the conceptual phase. 

One last point - there have been discussions about the appearance of the OSM main page. I'd like to see more thought what, if anything, changes are needed for osm.org.

**Comment by kathleenlu09** [comment]
I don't think it's appropriate to remove Copyright from the menu. The license is something very important for more casual visitors to be aware of. 

I agree that User Diaries and GPS Traces don't require such prominent placement, and could fall under a Community heading along with Wiki (along with Local Chapters and possibly other topics).

**Comment by lectrician1** [comment]
@cliffordsnow Yes, any OSM resource is "easily accessible" with a search engine, however I'd like to orient the argument to "importance" rather than "accessibility" when it comes to its presence on the header.

The Wiki is much more than the current "GPS Traces" and "User Diaries".

Also, newer contributors should know that the Wiki is an accessible resource from the moment they first arrive to contribute. When I first contributed, I simply used iD presets and had no idea a community existed behind OSM. I did not find out about the Wiki until a week later when I thought a preset was missing in iD. 
Like I noted, the Wiki acts as a community hub, which would be useful to new and experienced contributors alike.

**Comment by ZeLonewolf** [comment]
I echo the sentiment that "Community" needs to be a top-level link.  In particular, there isn't really a good way to learn where all of the local user communities are active.  If you went to the forums and looked at the United States forum, you'd assume that the US didn't have an active community (but we surely do).  "User Diaries" should be _within_ the Community section, not at the top level.

GPS Traces doesn't belong at the top level and I don't really see the benefit of giving it such a prominent heading.

I dislike that we bury the Wiki in "help" as if it is one of a number of equally-considered resources.  The Wiki is effectively the project's documentation and deserves top billing.

If I had it my way, I'd remove "User Diaries" and "GPS Traces" and replace them with a link "Documentation" that goes to the Wiki.  "Help" and "Documentation" are really different concepts here.

**Comment by matkoniecz** [comment]
> In particular, there isn't really a good way to learn where all of the local user communities are active.

What about listing appearing on saving any edit in iD? (Maybe JOSM would benefit from something similar, but that is a separate topic...)

**Comment by natrius** [comment]
I want to add, i never thought about pressing "help" to get to the wiki. Someone else linked it to me in the forum. I found the forum through google when i started, if i remember correctly. And, i started with osm 2013 with less activity. Did way more later. But i just stumbled by 'mistake' on help on September 2020 because it never occured to me to click on "help" to search there for a wiki or anything. Help is for me a FAQ and maybe a contact-formular to get support, but not where all the information about the community is. 


The top bar should be like that in my opinion:

`Community | Documentation | Help | About` 
Where 
Community contains: Forum, , local chapters, Help, Mailinglists, IRC.
Help contains: Welcome, Tutorial, Switch2osm, Organisations, Wiki
Documentation: A link to the wiki. Because it does not matter.
About contains: All the stuff thats there right now, copyright

GPS Tracks should be buried somewhere in a submenu, maybe somewhere in community, but not top level, same as use diaries. This is stuff that simply does not matter when tagging, its just there, because there is (was) no better place for that. Its not ideal, but for sure better than the current one in my opinion.

**Comment by gravitystorm** [comment]
Thank you to everyone who commented on this issue. I read through every comment last Wednesday, and then took more time since to consider all the comments made.

This issue was originally "Add Wiki Link to Heading" and I remain unconvinced that this is a good idea. Please see my earlier comments at https://github.com/openstreetmap/openstreetmap-website/issues/3041#issuecomment-763722664 and https://github.com/openstreetmap/openstreetmap-website/issues/3041#issuecomment-769873636 . I'm not planning on making detailed responses to every pro and con raised thereafter, but I do appreciate the time that everyone put in, I did read everything, and there were many valid points made.

So I'm going to close this issue again. And I will follow up with a comment on the wider topic of the menus in general.

**Comment by gravitystorm** [comment]
There have been many different options proposed here for a much wider rearrangement of the menus. I would be happy to see future proposals along these lines. If you are thinking about doing so, let me give some guidance, that I hope will help your proposal succeed:

* Rearranging all the menus is a big project, not the work of ten minutes adding a comment to this tracker.
* Your proposal should be carefully thought through. We don't want to just 'try it out' and then spend 3 months rearranging things when we realise something is wrong.
* The proposal should be comprehensive - every feature and external link that we have already should be included. No forgetting about traces or export or whatever and then finding there's nowhere to put it.
* The proposal should be extensible - including options for features that are under development or are reasonably conceivable in the near future, such as microcosms or integrating osm-community-index or QA tools. Show that you have considered these king of things, because I'll be considering them when reviewing your suggestion. 
* The proposal should be logical - you'll need to explain the basis for your thinking and reasons for your categorisation. There are 10,000 different ways to arrange the menus, and personal preferences are not a sufficient basis for categorisation.
* Consider the different users of the website and their different purposes. Just because one group don't use feature X doesn't mean it can be hidden in a submenu.
* Try it out before you propose it. What works on paper might not work in reality, and in trying to implement it you might discover other problems. If you don't want to edit this codebase, at least use some other UI prototyping technology to demonstrate to yourself that it works.

I hope this guidance can help lead to a good proposal that will be easily agreed on!

**Comment by natrius** [comment]
Thank you @gravitystorm . Is it possible to get kind of an user statistik? How often were the buttons pressed in the menu and the submenu above in the last 2 months, for example. You are using piwik and these might be available? I understand if this is nothing you want to provide.

**Comment by gravitystorm** [comment]
> Thank you @gravitystorm . Is it possible to get kind of an user statistik? How often were the buttons pressed in the menu and the submenu above in the last 2 months, for example. You are using piwik and these might be available? I understand if this is nothing you want to provide.

That's something for the OSMF (probably the OWG) to look into - I don't have access to the OSMF piwik stats or any other access to their production environment!

**Comment by tomhughes** [comment]
We don't explicitly track any sort of events or clicks within the site other than account signups, editor launches and map layer selections.

Things which lead to a server side action by loading a URL might be identifiable in the statistics based on URL transitions but anything which happens client side won't be.
