### ISSUE TITLE
Current Labels (and notes) and suggested new ones

### ISSUE THREAD

**Issue by tuckerrc** [openstreetmap/openstreetmap-website#3043]
## Current Labels

I've documented the usage of the labels in this repository (as of about a week ago). I can see a few that could probably be deleted and a few that are used. I have been adding the "bug", "i18n", and "enhancement" labels to a few issues.

| Issue Labels      | Open Issues | Closed Issues | Notes |
| ----------------- | ----------- | ------------- | ----- |
| api               | 4           | 2             | I was under the impression that the API should not be used anymore. Is that true? |
| awaiting upstream | 2           | 0             | Useful for documenting issues related to upstream code |
| bug               | 1           | 12            | Something is broken or not working as expected (default GitHub label) |
| cleanup           | 0           | 8             | Refactoring issues. Good for labeling deprecated issues or things that work but could be done better |
| dx                | 3           | 0             | Developer experience issues (Vagrant, Docker, Rake, Setup, etc.) |
| enhancement       | 17          | 13            | Improvements and new feature requests |
| good first issue  | 3           | 3             | Issues that require little knowledge of the codebase |
| help wanted       | 1           | 0             | Default GitHub label |
| i18n              | 4           | 4             | International issue (translations, languages, etc.) |
| osrm              | 2           | 1             | Open Source Routing Machine |
| spam              | 0           | 0             | Canned cooked pork popular in Hawaii |
| support           | 1           | 22            | Issues where a user needs help with development environment or other issues |
| ui                | 8           | 11            | User Interface issues |

| PR Labels         | Open PR  | Closed PR | Notes |
| ----------------- | ----------- | ------------- | ----- |
| work-in-progress  | 1           | 14            | (PR) PR is not ready to be merged |
| ruby              | 0           | 123           | (PR) Dependabot changed Ruby code |
| javascript        | 0           | 23            | (PR) Dependabot changed JavaScript code |
| changes requested | 10          | 13            | (PR) Changes are needed before the PR will be merged or reviewed again |
| dependencies      | 0           | 147           | (PR) Dependabot wants to update dependencies |

## New Labels

| Label | Documentation |
| ----- | ------------- |
| notes | Issue with the notes |
| moderation | Issue with moderation or administration |
| diaries | Issue with the diaries |
| mapview | Issue with the mapview (legend, tiles, search, etc.) |
| changesets | Issue with changesets |
| meta | Issue that relates to the repository or workflows (like this issue) |

Are there any more that we might want to include?

**Comment by gravitystorm** [comment]
Thanks for working through these! I'm happy with the descriptions you have here. Do you have enough Github permissions to change them for the labels, or is that something that I need to do?

Beyond that:

* I don't think it's worth separating out "Issue" and "PR" tags, since they can be used interchangeably (e.g. "spam" or "dx" easily apply to both). By splitting them in the table, some of the numbers are slightly off (e.g. "dx" has been used on a few PRs).
* I would not use the definition for "spam" given here :smile: Not everyone has English as their first language, and we should avoid in-jokes in order to be as inclusive as practicable
* I'm not sure the definition for Moderation quite hits the spot - it's not clear if that is intended just for Issues and Reports, or also User Blocks? Or is it just anything that needs moderator/administrator rights on the site?
* I propose changing the "osrm" label, or removing it. It's too niche to be useful, particularly without a more wideranging 'routing' tag to cover the other routing engines. But maybe it should be treated the same as geocoding and folded into the 'mapview' tag.

Let me know if you need me to update the label descriptions in Github.

**Comment by tuckerrc** [comment]
No problem!

- I think "Write" permission is required to edit labels so if you could update them that would be great.
- The separation by "Issue" and "PR" was just for counting. I was not planning on labeling Pull Requests but I might do that if it would be useful.
- I am unfamiliar with the moderation aspects of the website. If there are better ways to split those components that would be great.
- Removing "osrm" or changing it to "routing" would be good. I know there are a couple routing engines that are used and I have seen some issues mentioning them.
- For the "spam" label :smile: a more helpful description would be "Unhelpful or irrelevant". Does this repository get much spam? I did not find any issues or pull requests that were labeled "spam"

**Comment by gravitystorm** [comment]
I've added descriptions to all the labels, and I've added the new ones too. I've also added a "geocoding" label which I think sits nicely alongside the renamed 'routing' label.

Let me know if you spot any mistakes, or if anything else needs changing.

**Comment by tuckerrc** [comment]
> Let me know if you spot any mistakes, or if anything else needs changing.

Will do! Thanks for adding the new labels. The new colors look great too!

**Comment by gravitystorm** [comment]
> The new colors look great too!

Ah, I was wondering if anyone would notice those!

By the time I had added the extra labels, the colours were quite a cacophony. So I changed them all to be from the github default palette, which is eight colours and eight pale variants. Then I made all the "related to ... feature" labels the same colour, picked some more colours at random, and then used the full colour labels for some of the more "action-orientated" labels like "changes needed" so that they stand out. It's a bit arbitrary but at least much better than before.
