### ISSUE TITLE
Reverse direction moves the blue query button in the navigation menu when language set to Polish

### ISSUE THREAD

**Issue by mateuszmp** [openstreetmap/openstreetmap-website#3052]
Steps for reproduction:

1. Ensure you are viewing OSM in Polish
2. Select any two points to query a path between them
3. Click on "Odwróć kierunki" (Polish for Reverse direction)
4. Observe blue left-arrow button drop a line when clicking the blue button back and forth.

![normal](https://user-images.githubusercontent.com/19210834/104812257-5b01fa80-5801-11eb-8711-5f792c06ce54.jpg)
![reversed](https://user-images.githubusercontent.com/19210834/104812267-67865300-5801-11eb-81d6-bdc7f627f245.jpg)
https://user-images.githubusercontent.com/19210834/104812278-74a34200-5801-11eb-89ca-8a0fe8c31334.mp4

**Comment by gravitystorm** [comment]
I think this has been fixed. I refactored the directions form in https://github.com/openstreetmap/openstreetmap-website/pull/3109 (about a month after this issue was reported) and I've tried to reproduce it today and everything looks fine to me.

If you are still having problems with the button moving around, please reopen and let me know which browser.
