### ISSUE TITLE
Improve HTTPS security

### ISSUE THREAD

**Issue by nukeador** [openstreetmap/openstreetmap-website#3108]
Hi,

According to the Mozilla Observatory, openstreetmaps.org has some misconfigurations that can degrade the HTTPS security on the site:

https://observatory.mozilla.org/analyze/openstreetmap.org 

![image](https://user-images.githubusercontent.com/531906/108499923-5670ac00-72af-11eb-8865-a1f5364d07c2.png)

Cheers.

**Comment by tomhughes** [comment]
They're all wrong though, or deliberate decisions.

The first is wrong, or at least irrelevant, because we redirect to https and have HSTS enabled and preloaded. We just don't forbid http loading in the CSP because we don't have control over what resources we might need to load from third party sites - for example if somebody uses an http link for an image in a diary post.

The second (as they even admit) is again largely irrelevant because redirect to https and have HSTS enabled and preloaded. We probably should set it but virtually nobody will ever load a page over http with a session cookie because of HSTS.

The third is entirely deliberate so that third parties can use the API!

**Comment by tomhughes** [comment]
In fact I think the first point is referring to the fact that we allow http://127.0.0.1:8111 for remote control but that is entirely deliberate and necessary and 127.0.0.1 is a special case - the browsers even recognise that and allow insecure loads from localhost that would not be allowed otherwise so that's really just a bit in the observatory analysis.

**Comment by nukeador** [comment]
Thanks for the reply Tom. Some additional thoughts:

- Is "somebody using loading a http resource" considered a risk? My understanding is that this is something that should be avoided, specially when allowing user-generated-content.
- Is the API loading from the base domain or using a different one? (where I assume external queries are desired)

[Mozilla InfoSec](https://infosec.mozilla.org/guidelines/web_security#cross-origin-resource-sharing)
> For example, if your server provides both a website and an API intended for XMLHttpRequest access on a remote websites, only the API resources should return the Access-Control-Allow-Origin header. Failure to do so will allow foreign origins to read the contents of any page on your origin.

Thanks for your time.

**Comment by tomhughes** [comment]
At the moment loading of insecure passive content in secure pages is still generally allowed (active content isn't which makes the complaint more weird as the browser will deny that anyway even without CSP with the exception of localhost which is a special case) and we have no control over what our users are doing, and more importantly, what they did in the past.

Should we break a 10 year old diary entry because it's no longer considered "good" to load images over http?

Note that the actual page you analysed isn't allowing that but some like the diaries do.

We do only allow cross origin access to selected endpoints (https://github.com/openstreetmap/openstreetmap-website/blob/master/config/initializers/cors.rb#L21) but it's a bit more than just the API as it has to include OAuth for site that want to authenticate and the RSS feeds so that third part sites can load those.
