### ISSUE TITLE
Add an option to select open / close notes

### ISSUE THREAD

**Issue by letypequividelespoubelles** [openstreetmap/openstreetmap-website#3111]
In "my profile" clicking on "My notes" lists all the note you've participated in (created, closed, commented, etc...). It would be good to have a filter to select shown note depending on the status of the note : open or closed (or both, like it's now).

Thanks a lot for maintaining OSM !

**Comment by danielmizrachi** [comment]
Just came here looking for this, would definitely be nice to have! It'd make it much easier to find notes that are more likely to need attention.
I'm not a Rails dev but it looks like it'd be added in [/app/views/notes/_notes_paging_nav.html.erb](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/notes/_notes_paging_nav.html.erb). Maybe a "Show only open notes" checkbox that just filters the list.

**Comment by mnalis** [comment]
Showing just your open notes would definitely be most useful - it was suggested few years ago in https://github.com/openstreetmap/openstreetmap-website/issues/832. Unfortunately it never happened, so in the meantime I've written 3rd party workaround at http://my-notes.osm-hr.org/ in order to cope - while not perfect (most notably, it can update just once in 24 hours) everyone is welcome to use it until this issue gets deserved attention and is implemented in OSM website itself.

**Comment by gravitystorm** [comment]
This is very similar to #832, so I'm closing this issue as a duplicate.
