### ISSUE TITLE
Go button collapses wrongly at medium width

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#3119]
![Screenshot 2021-03-03 at 3 52 34 PM](https://user-images.githubusercontent.com/22477298/109877373-8ff2d100-7c38-11eb-86c5-7d15d0035c6a.png)

This is probably caused by one of the new bootstrap/css updates.

**Comment by gravitystorm** [comment]
Thanks @lectrician1 - great catch!

**Comment by tomhughes** [comment]
What width does this happen at? Only I can't reproduce it...

**Comment by gravitystorm** [comment]
On my screen, it's between 653 and 768px. But it depends on the size of your menus (e.g. length of username) whether you see the bug at all. From the smallest width, it happens from the `small-nav / compact-nav` cutover, up until the sidebar becomes full width (at 768px). You might not see it if your own `small-nav / compact-nav` cutover is above 768 px (e.g. you have a long username, many unread messages, or something like that).

Less than 768px screen width, the sidebar is 300px:

https://github.com/openstreetmap/openstreetmap-website/blob/dfeb93c9f8e39323d72c147dc80b6c28971026b8/app/assets/stylesheets/small.scss#L110

Greater than 768px screen width, the sidebar is 350px:

https://github.com/openstreetmap/openstreetmap-website/blob/1c2d0ba92d4fad53b3abb09b90c72a00a018f0db/app/assets/stylesheets/common.scss#L358

In all honesty I'm not sure we need the two-stage sidebar width change, and it's not something that I've been conscious of before. It changes from 300 to 350px which isn't all that significant. So I might remove this 'narrower sidebar' changeover at some point too. I also think the presence of the sidebar should be based on screen width rather than the menu width, but that's further work!
