### ISSUE TITLE
Unable to log in via OpenID

### ISSUE THREAD

**Issue by osmpaws** [openstreetmap/openstreetmap-website#3131]
Hello, for some time I was not able to login into OSM.org not knowing the reason. Originally it was error 500 and now it just do nothing else than disable Login button when pressed. Since I mainly use mobile device it was not clear what happens. On desktop there is finally some info in browser console saying that _Refused to send form data to 'https://mojeid.cz/' because it violates the following Content Security Policy directive: "form-action 'self' accounts.google.com *.facebook.com login.live.com github.com meta.wikimedia.org"_. I do not understand why you have decided to cut off my OpenID provider that is by the way run by our national domain registry organization cz.nic that is doubtly worse provider than facebook is. The worse than that is the message is not showed up on login screen and you have to dig it yourself.

**Comment by tomhughes** [comment]
Nobody has decided to cut anybody off. You appear to have stumbled on a bug and rather than report it as such have jumped to the conclusion that somebody is out to get you have deliberately blocked your chosen identity provider.

**Comment by osmpaws** [comment]
The concluson was clear. Based on the filter you have just changed. Someone had to set it up. Years before it worked well. Let me say last year I was not able to log in not knowing why. But anyways thank you for the fix.

**Comment by tomhughes** [comment]
Yes the filter was correct when it was added but there was a recent change in a third party component to address a security issue which means that the authentication is now done as POST instead of GET which changes the behaviour of the filter.

Importantly it only changes the behaviour in some browsers - there was no problem in Firefox for example because that only applies the form-action rule to the original URL on the form but Chrome also applies it to any redirect and hence was refusing the redirection to the OpenID provider.
