### ISSUE TITLE
Adding users via script (appending Configure.md#managing-users)

### ISSUE THREAD

**Issue by kallejre** [openstreetmap/openstreetmap-website#3136]
Hello,
I was trying to create script for setting up local copy of the website and noticed that tutorial's (configure.md) user management chapter needed manual actions to be made via website and ruby console. That got me wondering if there's way to automate it, but luckily there's pull request #3030 which covers populating database. I understand why such PR can't be merged due to cybersecurity concerns, but i believe some code snippets featured there, namely user creation, are worth mentioning or at least linking in tutorial.

Suggesting to add following bash command as automated alternative to adding dev-server admin/moderator:
```ruby
bundle exec rails runner 'admin = User.find_or_initialize_by(:email => "superadmin@osm.dev")
admin.update_attributes(
  :email => "superadmin@osm.dev",
  :email_valid => true,
  :display_name => "My New User Name",
  :description => "User description",
  :home_lat => "52.5170365",
  :home_lon => "13.3888599",
  :status => "confirmed",
  :terms_seen => true,
  :terms_agreed => Time.now.getutc,
  :data_public => true,
  :pass_crypt => "Str0ng_P4sSword",
  :pass_crypt_confirmation => "Str0ng_P4sSword",
)
admin.roles.create(:role => "administrator", :granter_id => admin.id )
admin.roles.create(:role => "moderator", :granter_id => admin.id)
admin.save!'
```
PS. As a person, who has never used Ruby before, I think at some point user should be informed, that in order to access webpage from other devices, `-b 0.0.0.0` needs to be added to regular `bundle exec rails server` command. Figuring it out myself took me several hours of reading repo's code and stackoverflow. This is useful in scenario when someone sets up website on server OS, not desktop Linux.

**Comment by tomhughes** [comment]
Well you probably shouldn't be using `bundle exec rails server` in production - that's a toy server for development use.

Then again you probably shouldn't be running this code in production without some familiarity with ruby and rails - this really is not a polished product that a non-technical end user should be trying to run. It exists to run `www.openstreetmap.org` and anything else is really at your own risk.

**Comment by gravitystorm** [comment]
> Well you probably shouldn't be using `bundle exec rails server` in production - that's a toy server for development use.

Some people prefer to develop on remote machines, e.g. VMs, when collaborating with other people like designers or managers, or if they have low-end personal hardware without enough disk-space for what they are working on.

But in any case, our policy is to help developers set up their local development environments. We don't provide instructions for more than that, since there are an infinite variety of options, whether for development or deployment. So I don't intend to add the binding configuration to our setup instructions.

As for the original part of this issue - we need to be careful about instructions for setting up administrative users. If we set it up in the way that you suggest, then nobody can log in as that user since the password is unknown ("Str0ng_P4sSword" would be the crypt, not the password itself). If we set a specific crypt and state the password needed, then that's a security issue for when someone either opens their dev environment to the internet, or copies the database contents into their production environment. So I'd rather have the developer create an account through the web interface, choosing their own password, and then instructions for upgrading that account into an admin account. Since that's what we have now, I don't think there's anything to change. 

In any case, thank you @kallejre for your suggestion! If there are other aspects of setting up a development environment that you think we can improve, please let us know.
