### ISSUE TITLE
Expired blocks do not show for how long they were crafted

### ISSUE THREAD

**Issue by polarbearing** [openstreetmap/openstreetmap-website#3143]
An expired block shows when it was created, and in the status when it ended. 
When the user reads the message after the expiry date, the block shows the reading date as its end. 

For example, block 3168 started 2019-09-19 and ended 2021-01-25 (visible only after hovering manually over the dates #907) which is about 16 months. Thus it probably ended when the user read the message, since block cannot be crafted for this span. 

Looking at blocks retrospectively, it makes a difference if a user read a 0h-block after a year, or a 1y-block just expired.

**Comment by tomhughes** [comment]
Can you give an actual link to the block rather than just a number? It's hard to see what you mean otherwise...

**Comment by tomhughes** [comment]
I've found it now (https://www.openstreetmap.org/user_blocks/907) but it appears to still be active so I'm not sure why you think it has ended?

**Comment by tomhughes** [comment]
Ah sorry that's an irrelevant issue number - https://www.openstreetmap.org/user_blocks/3168 is the block.

**Comment by tomhughes** [comment]
This appears to be deliberate (described in the comment at https://github.com/openstreetmap/openstreetmap-website/blob/master/app/helpers/user_blocks_helper.rb#L20) on the basis that the block didn't actually end until the user read it.

**Comment by polarbearing** [comment]
Yes that's fine and should not be changed. We just lack the information for which original time the block was intended for. 
My suggestion is to append the "Created" line with the difference ```duration = (ends_at - created_at)```, so it would read e.g.
```Created: over 1 year ago (4 hours)``` avoiding a new text string, or
```Created: over 1 year ago, for 4 hours```

(BTW, codewise, isn't the variable ```updated_at``` is a bit of a misnomer? It appears to be unrelated to the ```update``` function of a block, which appears to influence the ```ends_at``` time. Thus easier to understand would be ```read_at```)

**Comment by woodpeck** [comment]
`updated_at` is a Rails thing. It is largely useless but Rails likes to update that, well, whenever it updates a record in any way.

**Comment by polarbearing** [comment]
Thanks. Thus ```duration = (ends_at - created_at)``` is the correct description of the manually intended block duration.

**Comment by gravitystorm** [comment]
> (BTW, codewise, isn't the variable `updated_at` is a bit of a misnomer? It appears to be unrelated to the `update` function of a block, which appears to influence the `ends_at` time. Thus easier to understand would be `read_at`)

I've been looking at this today, and I think there's a few oddities with the user blocks. For example, the `updated_at` is indeed a rails thing, so as well as updating the model when it is viewed by the recipient, it's also updated if the block is ever edited e.g. by a moderator editing the block_reason at any point. So I think it's unwise to rely on that, and I think we should move to having a `viewed_at` or `acknowledged_at`, and only update that when it's the user viewing it, rather than (potentially) side effects of other things. At the moment it (just about) works, since moderators can't edit the block after it has finished, and the `show` method implicitly relies on rails' "dirty" handling to avoid updating it each time it's viewed - but still :frowning_face:
