### ISSUE TITLE
Glitch with text failing to cross the street

### ISSUE THREAD

**Issue by vivia** [openstreetmap/openstreetmap-website#3145]
At this link: https://www.openstreetmap.org/search?whereami=1&query=40.5709%2C22.9861#map=14/40.5709/22.9861

The text "Κόμβος Φοίνικα" is split across the two sides of the street, but at different heights.

![image](https://user-images.githubusercontent.com/28337/111970132-e003db80-8af2-11eb-85ce-89774c9ebce5.png)

**Comment by gravitystorm** [comment]
Issues with the map layers are not dealt with in this repository - all of the map layers are taken from external projects.

The OSMF OWG runs the tileservers used to generate these images, and run an issue tracker at https://github.com/openstreetmap/operations

The OpenStreetMap-Carto project creates the map stylesheets used to generate these images, and run an issue tracker at https://github.com/gravitystorm/openstreetmap-carto

Please note that broken labels like this are relatively common, since each image is generated separately, often on different servers, and each image is cached separately too. The occasional broken label is to be expected, and everyone involved in running the tileservers and developing the stylesheets is already aware that it happens from time to time. I don't think there's much point in opening a fresh issue on this topic, since having one more example is unlikely to help develop a solution.
