### ISSUE TITLE
Don't require a message to report spam diary entries

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/openstreetmap-website#3154]
It should be really easy to tell what diary entry has spam or not and having to write a message about it just creates a hurdle to it being reported. Most of the time when I report it I just put something like "Spam!!" as the message or I don't report it at all because I don't feel like bothering. I probably would report it if it was more of a "one click" process. I imagine a lot of other people treat spammy diary entries the same way. So, it would be better not to require a message in order to report them in the first place.

**Comment by matkoniecz** [comment]
I just copy paste segment of spam message

**Comment by gravitystorm** [comment]
> having to write a message about it just creates a hurdle to it being reported.

I think the hurdle is pretty small here. You even say that you only type 6 characters, and I'm surprised that you say you "don't feel like bothering" due to this small amount of typing.

I suspect a things, without providing evidence:

* First, that this isn't causing any great difference in the fight against spam, since there is usually at least one other person willing to put in the effort to type in a few characters for each spam entry. So even if you aren't reporting things personally, other people are.
* Second, that there are times when having descriptions in the reports helps share the burden of work with the moderators (e.g. to avoid them having to use google translate). So I'm happy to put in small explanations in my reports, in the hope that it makes their lives that little bit easier.
* Third, that working on making report descriptions optional for certain types of report on certain objects is far more developer time than the payoff in (potential) increased spam reporting from making the easy process a tiny bit easier than it already is.

So I'm going to close this issue, and nudge you gently to continue reporting spam for the benefit of the whole community, even if you just continue to press just 6 characters at a time (compared to your 531 character complaint about having to do so! :smile: )

If anyone from the moderation team wants to reject any of my points above, or to say that they collectively would prefer the situation changed, then of course I will reopen this.
