### ISSUE TITLE
Page for suggestions for tags and schemas

### ISSUE THREAD

**Issue by Sowa1980** [openstreetmap/openstreetmap-website#3163]
сделайте Страницу для предложений по тегам и схемам на сайте OSM. В этом же нет ни чего трудного по аналогии с дневником. также голосование

**Comment by tomhughes** [comment]
Translation from google:

> make a Tag and Schema Suggestion Page on the OSM website. In this there is nothing difficult by analogy with a diary. also vote

**Comment by tomhughes** [comment]
I think this is probably out of scope, not to mention being our of line with our free form approach to tagging.

**Comment by mmd-osm** [comment]
So how does this differ from the wiki? Or the tagging mailing list? What’s the benefit of this proposal?

**Comment by Sowa1980** [comment]
Нет вы не поняли меня я предлагаю, эту страницу вести для упрощения процедуры внесения тегов на обсуждение и голосования, и что бы как раз упорядочить ее. С этой страницы можно было бы отправлять в рассылку .

**Comment by mmd-osm** [comment]
Deepl translates this to:

_No you do not understand me I suggest, this page is to simplify the procedure of entering tags for discussion and voting, and what would just streamline it. From this page could be sent to the mailing list. The benefit is significant. any participant can easily make a suggestion and it would be immediately available here to all participants on their pages for example in the news tab._

**Comment by Sowa1980** [comment]
еще не маловажный факт, что многие участники проекта, даже не знают как это сделать и куда надо написать и что нужно вообще для этого.

**Comment by gravitystorm** [comment]
Thank you for the suggestion. I can see the benefits of moving the tag proposal and voting system into a structured system, rather than a free-form wiki. But I can see disadvantages too.

I would encourage you to discuss this within the wider tagging community, to explain your proposal and see if it is welcome or not, and whether a majority of people would use any new system. Without such buy-in, there is little point in implementing it, and even with buy-in, that might not be enough to find the developer capacity for the implementation.
