### ISSUE TITLE
Update Bootstrap 4 to 5

### ISSUE THREAD

**Issue by vanillajonathan** [openstreetmap/openstreetmap-website#3230]

**Comment by tomhughes** [comment]
Do you have some reason for wanting this? Opening a ticket with a bald statement as title and no body giving any sort of reasoning is not really very helpful...

**Comment by vanillajonathan** [comment]
To give the website a slightly more modern look-and-feel, and give the developers more tools for delivering a better experience, such as [offcanvas](https://getbootstrap.com/docs/5.0/components/offcanvas/) which can be used for menus in mobile experience or for tools or map features in the iD editor.

**Comment by tomhughes** [comment]
Right, but we're still kind of migrating to bootstrap so we probably don't want to rush into an upgrade for the sake of it.

Doubtless @gravitystorm will have some thoughts anyway given he's the one that has been working on moving us to bootstrap.

**Comment by gravitystorm** [comment]
@tomhughes is right that we're still migrating to using bootstrap 4, so the easiest wins are by continuing that migration first. This will make the upgrade to bootstrap 5 easier, but it's not a blocker.

What is a blocker is that [bootstrap_form](https://github.com/bootstrap-ruby/bootstrap_form) does not yet have a v5 release. So that needs to come first.

The main thing that I'm looking forward to is better RTL support, since I know that's a bit ropey in some places in bootstrap 4. Moving away from left/right padding and margin utilities in particular is useful, but perhaps not the biggest impact on us since I've tried hard to avoid them wherever possible.

Overall, I don't have this as a high priority, and certainly not before bootstrap_form is available.

**Comment by gravitystorm** [comment]
bootstrap_form is now available for bootstrap 5, so that's no longer a blocker.

However, the list of changes in bootstrap 5 is long and complex, so it's not going to be a trivial upgrade. There are guides for both bootstrap_form v5 and also bootstrap v5.

* https://github.com/bootstrap-ruby/bootstrap_form/blob/main/UPGRADE-5.0.md
* https://getbootstrap.com/docs/5.0/migration/
