### ISSUE TITLE
OAuth 1.0a issue

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#3241]
(redacted)

**Comment by tomhughes** [comment]
So you discover a security issue and decide to raise a public ticket for it?

Thanks for royally fucking over my day.

**Comment by mmd-osm** [comment]
Apologies, it didn't look like really critical, but ok, I removed all relevant details now.

**Comment by tomhughes** [comment]
I don't think it's a new issue. The granted token does have the permission which is what worried me because that code was touched on as part of the OAuth 2 work.

My guess is that it's a bug when authorising an OAuth 1 application - mostly likely if you uncheck every permission so that it gets an empty permission list then it copies all the permissions from the application definition.

**Comment by tomhughes** [comment]
Argh... Is there some way to stop this damned thing using a popup so I can debug it?

**Comment by tomhughes** [comment]
Found a way to do it - the form submission is actually sending two contradictory parameters:

```
allow_read_prefs=0&allow_read_prefs=1
```

**Comment by tomhughes** [comment]
I think it's something to do with https://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-check_box but I'm struggling to get osm-auth working in my dev environment.

**Comment by mmd-osm** [comment]
Hmm, the instructions on the Github repo https://github.com/osmlab/osm-auth worked for me. Where exactly do you experience some issues?

**Comment by tomhughes** [comment]
Well the problem was working out which file to change to put the tokens and URL in but I got it working now.

**Comment by mmd-osm** [comment]
Thanks a lot for the quick fix. As far as I understand the change, those fields used to be boolean, and are now numeric. I'm still wondering a bit where this change has been introduced originally. My guess would be it's doorkeeper related, but i'm not really sure.

**Comment by tomhughes** [comment]
No doorkeeper is not involved in OAuth 1 at all.

The issue relates to that rails doco I linked to and the fact it deliberately sends each flag twice and we were essentially checking if the parameter existed rather than if it was non-zero.

We think, but haven't proved yet, that the trigger was the switch to bootstrap for the worm - it may have been using `check_box_tag` before for example which doesn't cause the duplicate values.

**Comment by tomhughes** [comment]
Yes that is exactly what happened in 9e75b8472ff066ba98d5f2af07fa12f7c11df55f.

**Comment by mmd-osm** [comment]
(change had some side effect on JOSM's fully automated mode, see https://github.com/openstreetmap/openstreetmap-website/pull/3177#issuecomment-876154928)
