### ISSUE TITLE
CSP issue with Safari 14

### ISSUE THREAD

**Issue by sluukkonen** [openstreetmap/openstreetmap-website#3261]
I hope this is the correct place to report this issue. I'm seeing the following kind of error when using openstreetmap.org on Safari 14.1.1. 

```
Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.
send — application-a8df84636f8cf8b2fde8f3bbf45bf57017fd817b335995864ab863bd92096052.js:3:18672
```

**Comment by tomhughes** [comment]
Unfortunately there's not a lot I can do based on that alone.

Does it happen as soon as you load the page? or when you take a particular action?

**Comment by Firefishy** [comment]
I have tested using Safari 14.1.1 but I cannot get the same error.
Only error I get in the console is:
```
Unrecognized Content-Security-Policy directive 'worker-src'.
```

But, the Layer, Map Key, Share and Query Feature buttons on right do not work (not action). Zoom, Show My Location and Add Note work as expected.

**Comment by tomhughes** [comment]
The error doesn't seem to make much sense - it appears to be complaining about an inline script but we don't use those (which is why the policy disallows them) and yet it refers to `application.js` which is loaded from the server and should match the `'self'` rule. The line number given is just the end of the file so isn't helpful.

My guess is maybe this is a case of a toolbar or browser extension or similar trying to inject code into the page and rightly being defeated by our security policy?

The thing with the buttons is #2811 and is a separate issue.

**Comment by Firefishy** [comment]
@sluukkonen Would you mind testing with Extensions disabled? You can do this by Safari -> Preferences -> Advanced -> Check "Show Develop menu in menu bar", close. Develop menu in menu bar -> Check the Disable Extensions item.

Some extensions (eg: Password managers) modify website behaviour and could be causing the problem.

**Comment by sluukkonen** [comment]
You're correct, the CSP error seems to be caused by AdGuard. The original issue I had with Safari was #2811. I saw the CSP errors in the console and hastily assumed that they were related.
