### ISSUE TITLE
application logger problem

### ISSUE THREAD

**Issue by alenigrelli** [openstreetmap/openstreetmap-website#3273]
I registered my application in my openstreetmap website, when I try to log in from my application it gives me an error 500 (Internal Server Error)
 I have attached some screenshots ... how should I solve this problem?
![Captura de pantalla de 2021-07-27 17-52-36](https://user-images.githubusercontent.com/15861031/127226343-aa9f0f58-30c2-4843-aa0f-3fb215937e44.png)
![Captura de pantalla de 2021-07-27 17-52-33](https://user-images.githubusercontent.com/15861031/127226351-51d89f05-b3b3-4eae-bee8-e5eb64d0ec73.png)

**Comment by tomhughes** [comment]
By following the instructions and registering the necessary OAuth applications.

**Comment by gravitystorm** [comment]
I think the instructions might be slightly out of date, now that we've moved iD and the website to use OAuth 2. For example, they say 'Click on "oauth settings" on the My settings page' but that link no longer exists, and it's not clear from reading just the instructions whether to pick "OAuth 1 settings" or "OAuth 2 applications" or "OAuth 2 authorizations".

I'm also interested to see if we can make things clearer, e.g. providing a decent error message (rather than a 500 error) if a developer tries accessing a part of the site that relies on an OAuth token, without that token being configured in the settings.yml. Even if it's just a message to say "`id_key` not set, please read CONFIGURE.md for more information" or something like that.

**Comment by alenigrelli** [comment]
I managed to register the app. But I got the following problem, did it ever happen to you?
![Captura de pantalla de 2021-07-28 15-51-51](https://user-images.githubusercontent.com/15861031/127383947-286e3938-babb-4713-8772-861a63a6cb77.png)
![Captura de pantalla de 2021-07-28 15-44-22](https://user-images.githubusercontent.com/15861031/127383954-c73d283e-d95d-48e9-9514-240271d056a0.png)
