### ISSUE TITLE
the text on about page isn't mobile friendly.

### ISSUE THREAD

**Issue by shubhangi013** [openstreetmap/openstreetmap-website#3302]
On the 'https://www.openstreetmap.org/about' :
(Here I've also  attached the relevant screenshot of the issue.)
![Screenshot from 2021-08-26 13-51-01](https://user-images.githubusercontent.com/78342516/130928647-655807b3-9ddd-4e8e-8d07-54bf01347b83.png)

- The text 'OpenStreetMap ' isn't mobile-friendly.

- I think there should be space between Ⓒ and 'OpenStreetMap contributors'

**Comment by gravitystorm** [comment]
Hmm, this is strange, since I couldn't recreate the issue quite as you see it. Here's my own firefox, with the display set to the same Galaxy S9 as you used for your screenshot:

![Screenshot from 2021-10-20 17-18-53](https://user-images.githubusercontent.com/360803/138133456-10b7001c-cdac-4efb-abbb-1816fa30737e.png)

So mine shows the gap and the fonts are noticeably smaller. Could you send me the "fonts" tab of your Firefox inspector window, like this please?:

![Screenshot from 2021-10-20 17-31-29](https://user-images.githubusercontent.com/360803/138133983-1e31f824-3028-46d8-9e2a-d656fe094fd1.png)

I'm curious as to which font it has ended up using, since I couldn't recreate it even by removing Roboto from my font list. The font you are using has a distinctive sloping left-hand corner to the lower case "t", so maybe that will help someone figure it out.

**Comment by gravitystorm** [comment]
On the more general point:

* I'm going to update the positioning of the copyright symbol to be based on the font size, rather than a fixed width. This means it will automatically adapt to any future changes in font sizes.
* For the large header fonts on small screen sizes - there's not much we can do about that at the moment. However, the next version of bootstrap (v5) has [responsive font sizes enabled by default](https://getbootstrap.com/docs/5.0/getting-started/rfs/), i.e. the font sizes will get smaller as the window width narrows. So when we move to that, this will be taken care of automatically. See #3230
