### ISSUE TITLE
Allow uploading new version of traces

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3333]
On the "Edit this trace" page, offer "Upload new version".
That way one needn't delete the trace, and upload it again.
P.S., @tomhughes You are blocking **my** notifications!
Also if you say "No I'm not" I won't be notified, so I probably won't remember to respond "Yes you are", which of course you won't be notified about. But that's how blocking works on GitHub, alas.

**Comment by tomhughes** [comment]
Do you think I'm not aware that I'm blocking you? I'm perfectly well aware - it was a deliberate decision on my part!

Traces are immutable by design - allowing them to be changed would break things like the rendered trace maps at https://gps-tile.openstreetmap.org/ which would not know to go back and redo them when they changed and which is not able to remove the old version once it has been rendered.

**Comment by tomhughes** [comment]
No I am well aware of that because you've told me multiple times.

Your mistake is thinking that I am bothered by that.

**Comment by jidanni** [comment]
Yes, but don't you think it is bad that you are also zapping *my* notifications.
In an ideal world, each person should only zap their own notifications, correct?
If it was easy for you, that is what you would choose too, correct?
But OK, it is not easy for you to only zap your own notifications,
But if their was an easy way, that is what you would do, no?
OK, maybe one day they will invent an easy way.
