### ISSUE TITLE
Mention Overpass_API/status page when printing errors

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3346]
When printing
```
Error contacting https://overpass-api.de/api/interpreter: Too Many Requests
```
be sure to also mention
"Check status on https://wiki.openstreetmap.org/wiki/Overpass_API/status "!

**Comment by jidanni** [comment]
The user does one search in his entire life and gets this message.

The page should give some hint on how to report/solve the problem.

**Comment by lectrician1** [comment]
I added enhancement because some explanation for the error should definitely be printed as requested. 

You can't just leave a user hanging with an error message and provide no explanation of a potential cause.

**Comment by SomeoneElseOSM** [comment]
> ... some explanation for the error ...

Agreed, but specifically not https://wiki.openstreetmap.org/wiki/Overpass_API/status , as that is completely irrelevant to the likely problem, as @mmd-osm as said here (and elsewhere previously).

**Comment by tomhughes** [comment]
This is redundant as we are no longer using the overloaded public overpass servers - that also means that the wiki page wouldn't be relevant as it describes the status of the public servers.

In any case because the overpass URL is configurable in the rails code it wouldn't make sense to point to a wiki page that relates to a specific set of servers.
