### ISSUE TITLE
Bug while log in

### ISSUE THREAD

**Issue by Anjiru98** [openstreetmap/openstreetmap-website#3405]
### How to reproduce the issue?

If I click on https://www.openstreetmap.org/user/forgot-password , and than typong the email address and confirming, it appears a green banner. But in this green banner the tag <code>:-(</code> isn't read.

### Screenshot(s) or anything else?

https://cdn.discordapp.com/attachments/923570986681516112/923572896675299348/unknown.png

**Comment by gravitystorm** [comment]
The french translation contains the html `<code>` tags, which are not present in the original:

```
en.passwords.lost_password.notice email on way: "Sorry you lost it :-( but an email is on its way so you can reset it soon."
fr.passwords.lost_password.notice email on way: "Désolé que vous ayez perdu votre mot de passe <code>:-(</code>
        Un courriel vous a été envoyé pour que vous puissiez vite le réinitialiser."
```

I think we need to mark the french translation as needing retranslated on translatewiki. And perhaps change the original, since I'm not sure that the ascii smiley is good text anyway.

And perhaps we need to figure out some kind of validation to prevent translators from changing the html in the first place, e.g. detecting when html is introduced into non-html translations. 

I'll also continue to work on removing more html tags from the translations - we have around 260 html tags in there, including multiple times where the html class is defined in the translation, and I don't see any great reason to let translators change the html elements used on the site.

**Comment by gravitystorm** [comment]
@Anjiru98 Thank you for the bug report!

**Comment by Anjiru98** [comment]
@gravitystorm I fixed the error https://translatewiki.net/w/i.php?title=Osm%3APasswords.lost_password.notice_email_on_way%2Ffr&type=revision&diff=10463709&oldid=9991996

**Comment by gravitystorm** [comment]
@Anjiru98 Thank you!

**Comment by gravitystorm** [comment]
The validations to prevent people adding html tags into translations (e.g. `<code>:-(</code>`) were added in #4007 so this issue can be closed.
