### ISSUE TITLE
Dropdown menu does not go away by clicking on the map

### ISSUE THREAD

**Issue by d-e-v-esh** [openstreetmap/openstreetmap-website#3464]
### URL

https://www.openstreetmap.org/edit

### How to reproduce the issue?

1.  Click on the edit dropdown menu
2.  Then click away on the map

The dropdown menu should disappear as we are now interacting with the map but it does not go away. We need to click on the dropdown button again to make it disappear. This bug is not available on the normal website.

### Screenshot(s) or anything else?

https://user-images.githubusercontent.com/59534570/155006492-2c764ba7-de94-4753-81e2-2b38ca916840.mp4

### Which iD Editor versions do you see the issue on?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Chrome

**Comment by tomhughes** [comment]
That's probably hard to fix because the "map" as you refer to it is actually the iD editor which is a separate project that we don't directly control.

The menu is also managed by bootstrap an not directly by us and bootstrap normally takes care of getting rid of it.

My guess is that iD is grabbing the events and stopping them bubbling up to the top which is why bootstrap isn't seeing them.

**Comment by mmd-osm** [comment]
Oh well, I sent @d-e-v-esh to this repo, as I believe this needs to be handled by the website code.

**Comment by tomhughes** [comment]
Well like I say I don't believe we actually do anything to implement those menus other than mark them up with the right classes - the implementation is all down to bootstrap. That strongly suggests that bootstrap is not seeing the normal events, either because the body of that page is a frame or because of something iD is doing.

**Comment by mmd-osm** [comment]
I think this is a minor inconvenience only, and somewhat a niche requirement. You can click somewhere on the header bar to get rid of the popup again, or as mentioned in the initial post on dropdown menu icon. I suspect that this need some additional work on iD. Closing for now.
