### ISSUE TITLE
API /gpx/#id/data documentation and behaviour

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/openstreetmap-website#3487]
### Description

I'm in the process of refactoring the GPX support in Vespucci see https://github.com/MarcusWolschon/osmeditor4android/projects/1#column-15955445 and one of the potential enhancements is downloading tracks for the user (logged in, as there is no reasonable way to retrieve public traces currently via the API). 

The /gpx/#id/data API call is documented here https://wiki.openstreetmap.org/wiki/API_v0.6#Download_Data:_GET_.2Fapi.2F0.6.2Fgpx.2F.23id.2Fdata If the behaviour was as described, this would be fairly painful as it would require handling a (undocumented) multitude of archive formats. However inspection of the code https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/api/traces_controller.rb#L53 shows that the returned format can actually be forced to GPX (and XML, however that is supposed to be useful in this context).

This is insofar helpful as it makes things easy on the client side. There is however a lingering question wrt multi file archives, experimentation shows that the contained files are simply concated together in the output, a slightly original solution (https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7.2 would likely be 'correct'), but completely parseable ignoring nitpicking. 

The question is if this is intended behaviour that will be maintained going forward and can be documented, or if this is simply an unintended implementation consequence that cannot be relied on?

**Comment by tomhughes** [comment]
So the original change to support XML output was in https://github.com/openstreetmap/openstreetmap-website/commit/07e84496255ebd1d53108894e0fb8ce98b55ccee in order to fix https://github.com/openstreetmap/trac-tickets/issues/534 which was then extended to the API method in https://github.com/openstreetmap/openstreetmap-website/commit/2ce394118da72186ed0ca4594c1833c3579bb2a6.

There was then a further extension in https://github.com/openstreetmap/openstreetmap-website/commit/7e896d758d33d9bccb36ace4e11b0d795b5e700b to allow requests for the GPX type.

**Comment by simonpoole** [comment]
Current behaviour documented in https://wiki.openstreetmap.org/wiki/API_v0.6#Download_Data%3A_GET_.2Fapi.2F0.6.2Fgpx.2F.23id.2Fdata

**Comment by simonpoole** [comment]
@gravitystorm as far as I could see the format options are not tested for download (there is a test that routing exists for .xml).

**Comment by mmd-osm** [comment]
I believe there's some tests covering downloads: https://github.com/openstreetmap/openstreetmap-website/blob/master/test/controllers/traces_controller_test.rb#L366-L408
