### ISSUE TITLE
Only standard carto layer renders on iPad

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#3527]
With iPad 9.3.6, all the other layers (transport, cycle...) are just gray empty. Safari browser. (This is the newest iOS version for the particular hardware.)

**Comment by tomhughes** [comment]
That seems implausible but as I don't have such an iPad there's not much I can do to help.

**Comment by SomeoneElseOSM** [comment]
It's a real enough problem - the issue is that an antique version of iOS won't trust certificates that old by default (you have to explicitly trust the osm.org cert what you browse there).  Try explicitly browsing to

https://b.tile-cyclosm.openstreetmap.fr/cyclosm/13/6720/4720.png
https://a.tile.thunderforest.com/cycle/13/6719/4720.png?apikey=6170aad10dfd42a38d4d8c709a536f38
https://c.tile.thunderforest.com/transport/13/6719/4719.png?apikey=6170aad10dfd42a38d4d8c709a536f38
https://tileserver.memomaps.de/tilegen/13/6725/4720.png
https://tile-a.openstreetmap.fr/hot/13/6725/4720.png

and see if you can persuade iOS to let you trust those certifiicates

**Comment by jidanni** [comment]
Who would have ever guessed! Too bad there's no way to make a set of instructions for a workaround that could be done without a special list of links. For instance touching a layer and then that would take us to the tile site where we can approve the site. But that's not possible with the iPad. So we'll just have to use your workaround. Thanks!

**Comment by jidanni** [comment]
Oh maybe Apple could make another tiny update release...

**Comment by mmd-osm** [comment]
https://discussions.apple.com/thread/253219776 suggests:

Go to https://letsencrypt.org/certs/isrgrootx1.pem in Safari on your iPad. It should prompt you to install the certificate.

**Comment by tomhughes** [comment]
Well "newest iOS version for the particular hardware" was rather burying the lede!

I assumed that meant it was a modern iOS version or I would have suggested it was an out of date root store...

**Comment by jidanni** [comment]
> Go to https://letsencrypt.org/certs/isrgrootx1.pem in Safari on your iPad. It should prompt you to install the certificate.

The medicine pill worked!

**Comment by SomeoneElseOSM** [comment]
> Go to https://letsencrypt.org/certs/isrgrootx1.pem in Safari on your iPad. It should prompt you to install the certificate.

For completeness, where that probably won't work is if the iPad is managed by someone else (perhaps issued by work or school).  In that case you'll need to talk to whoever manages it and ask them to push that certificate out to devices that need it (and how to do that will depend on whatever it is they are using to manage the devices).
