### ISSUE TITLE
define security policy

### ISSUE THREAD

**Issue by mnalis** [openstreetmap/openstreetmap-website#3553]
### Description

it would be nice if there were `Security policy` defined at https://github.com/openstreetmap/openstreetmap-website/security with instructions how one can report security problems (without exposing it to the public via default issue tracker)

**Comment by tomhughes** [comment]
This is somewhat duplicative of https://github.com/openstreetmap/operations/issues/623 though it does depend on the nature of the security issue which is the correct place to raise it.

There isn't really a good way to raise issues in the web site code other than mailing me and @gravitystorm because we don't really have any infrastructure for the project other than this repository.
