### ISSUE TITLE
 Yarn install broken - INSTALL.md out of date?

### ISSUE THREAD

**Issue by joelsgp** [openstreetmap/openstreetmap-website#3579]
I followed the instructions in INSTALL.md with a fresh virtualbox of ubuntu server 20.04. In the yarn step I get this result:
```
user@hostname:~/openstreetmap-website$ bundle exec rake yarn:install
/usr/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/usr/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/usr/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/var/lib/gems/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
yarn install failed to execute.
Ensure yarn is installed and `yarn --version` runs without errors.
user@hostname:~/openstreetmap-website$
```
I also found this line in the dockerfile that says this is expected to not work. Seems the INSTALL.md needs updating to match the Dockerfile.
https://github.com/openstreetmap/openstreetmap-website/blob/master/Dockerfile#L47

**Comment by tomhughes** [comment]
Well our production servers run Ubuntu 20.04 and `bundle exec rake yarn:install` works fine for them.

As I believe I explained before what the dockerfile does is just wrong.

**Comment by joelsgp** [comment]
After using `yarnpkg --ignore-engines install`, the other `bundle exec` steps had warnings too, but the tests passed

**Comment by tomhughes** [comment]
The `bin/yarn` in this repository used to do that job but I don't think rails uses that anymore.

**Comment by mmd-osm** [comment]
Interesting. Although we're only processing some JSON files from osm-community-index, we're inheriting a Node 16 dependency here. I'm wondering if there's a good way to avoid this.

**Comment by tomhughes** [comment]
No there isn't because yarn got rid of the switch that allowed you to tell it to ignore engine version constraints.

**Comment by bhousel** [comment]
Why not add osm-community-index to the vendorfile?  It doesn't make sense to build that project from scratch, the output is just some .json files.

**Comment by tomhughes** [comment]
Well we were trying to move away from Vendorfile really - aside from anything else upstream for vendorer hasn't touched it in four years.

**Comment by gravitystorm** [comment]
There's two different issues discussed here, and while they are related they are not the same. `bundle exec rails yarn:install` failing to find yarn on Ubuntu is not the same issue as `The engine "node" is incompatible with this module.` for osm-community-index. The first is to do with package naming on Ubuntu, the second is to do with passing flags to yarn.

The behaviour of `bundle exec rails yarn:install` [changed in Rails 7](https://github.com/rails/rails/pull/43641), to directly call `yarn` instead of `bin/yarn`. 

This is important for two reasons, the first being that `bin/yarn` [detects whether to call `yarn` or `yarnpkg`](https://github.com/openstreetmap/openstreetmap-website/blob/52078b5d764b867c643728ed5839a2cfbd9c5a2c/bin/yarn#L6). 

The second reason is that `bin/yarn` passes the `--ignore-engines` flag, and without that yarn will fail on osm-community-index or js-cookie, which [has an existing discussion](https://github.com/openstreetmap/openstreetmap-website/issues/3275).

It's interesting to investigate why this didn't break anything in CI (both tests and for Docker) or elsewhere, since it indicates inconsistencies between our installation instructions and what CI is actually doing.

* For the CI tests - It calls [`bundle exec rails yarn:install`](https://github.com/openstreetmap/openstreetmap-website/blob/52078b5d764b867c643728ed5839a2cfbd9c5a2c/.github/workflows/tests.yml#L57), so I would expect it to fail! However, the GithubCI version of Ubuntu [has newer versions of node](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#installed-software) installed, and presumably has a binary called `yarn` too. So although we are trying to test on "Ubuntu" it's more like "Github flavoured Ubuntu" rather than "actual Ubuntu" or "vagrant ubuntu/focal64 flavoured Ubuntu". Hence the discrepancies between CI and INSTALL.md.
* For the Docker tests, this is more straightforward. The Dockerfile contains an explicit [`yarnpkg --ignore-engines install`](https://github.com/openstreetmap/openstreetmap-website/blob/52078b5d764b867c643728ed5839a2cfbd9c5a2c/Dockerfile#L50), which still works (but is Ubuntu specific). I think that should be changed to line up with our installation instructions.
* For production, OSMF [used to have a shim](https://github.com/openstreetmap/chef/blob/4e4da59c36d7727b244fedda27e97b11ae1e9a9e/cookbooks/nodejs/templates/default/yarn.erb) so that `yarn` worked and `--ignore-engines` was always passed to yarn, but [are now using nodesource packages](https://github.com/openstreetmap/chef/commit/cfa0fe92774c9dfcf0a0085d7772319550066ed7) to get both a binary called `yarn` and a new enough version of node that there are no engine warnings.

**Comment by tomhughes** [comment]
I think that newer versions of yarn have dropped support for `--ignore-engines` haven't they, which is the main reason our old approach of using a wrapper no longer worked and we had to switch to using nodesource.

**Comment by gravitystorm** [comment]
> I think that newer versions of yarn have dropped support for `--ignore-engines` haven't they, which is the main reason our old approach of using a wrapper no longer worked and we had to switch to using nodesource.

No, I think that's a separate thing related to any potential upgrade to yarn2/3, see https://github.com/openstreetmap/openstreetmap-website/pull/3515 . All the discussion here assumes continuing use of yarn 1 - the latest yarn 1 release still has the `--ignore-engines` flag, but if you are running a new enough version of node (e.g. from nodesource packages) then you aren't affected by the aforementioned rails7 change that means the flag is no longer passed to yarn.

OSMF servers install yarn from https://dl.yarnpkg.com/debian, which is yarn 1.

**Comment by gravitystorm** [comment]
So thinking about this, there's two main options:

* Change the installation so that both a) a new enough version of node and b) a non-Ubuntu package of yarn is installed. For example, use nodesource for node 16+ and https://dl.yarnpkg.com/debian apt repository for yarn. This would resolve both the engines and the yarnpkg binary naming issues, and `bundle exec rails yarn:install` would then work.
* Alternatively, change the installation instructions to run `bundle exec bin/yarn install` instead. This way we can keep using the package name detection and keep ignoring the engines.

I lean towards the second option. This is to keep the installation as simple as possible. Since we can actually run everything we need for the site just fine with the versions of node and yarn that Ubuntu supply, even on 20.04, it seems unnecessary to make new developers jump through hoops of adding additional apt repositories. If they already have newer versions of node and/or yarn on their system, bin/yarn will still work fine for them too.

We would need to revisit this if/when we genuinely need a newer node engine, or at some point the stars will align and some future Ubuntu LTS release will have a `yarn` binary plus a new enough version of node for all of our packages. And at that point `bin/yarn` will be obsolete and we can go back to `bundle exec rails yarn:install`.

The one small wrinkle here is that one of our dev node packages, eslint, genuinely requires node 12+. It [was mentioned](https://github.com/openstreetmap/openstreetmap-website/issues/3275#issuecomment-1106929281) in April 2022, and was broken by the [upgrade to eslint 8.x](https://github.com/openstreetmap/openstreetmap-website/pull/3339) in October 2021. It wasn't picked up at the time, due to the whole "Github flavoured Ubuntu" thing which means that eslint still passes on Ubuntu 20.04 in CI. eslint will work with standard packages on Ubuntu 22.04, but not on Ubuntu 20.04. To fix this particular issue, a followup task will be to upgrade all our installations (INSTALL.md, Dockerfile, vagrant, etc) to 22.04.
