### ISSUE TITLE
Globe projection update: Mapbox now supports globe projections

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#3619]
### Description

I don't know why #2604 was locked as it's clearly not resolved, but I just wanted to give an update that Mapbox now supports a globe projection:

https://docs.mapbox.com/mapbox-gl-js/guides/globe/

**Comment by tomhughes** [comment]
But we don't use mapbox-gl-js and will never be able to use it for licensing reasons.

**Comment by lectrician1** [comment]
Can you at least unlock the former issue in case any other alternatives are available in the future to share and discuss?

**Comment by gravitystorm** [comment]
I'm happy to leave the original issue locked, since there's a low chance of any *productive* conversation coming out of it, and a very high chance of *unproductive* comments ("me too!", "Yes please!", "Why haven't you done this yet?", "Here's a suggestion which is not practical and ignores what the maintainers have already said" etc). The last few comments in the thread demonstrates this clearly already so that's not a hypothetical concern.

Please see [my original comment](https://github.com/openstreetmap/openstreetmap-website/issues/2604#issuecomment-653914831) as to why the issue was originally closed. We don't need issues open for every conceivable feature request, particularly when there are several major changes that would be needed before any work could be considered.
