### ISSUE TITLE
Reimagining the OSM.org

### ISSUE THREAD

**Issue by Playzinho** [openstreetmap/openstreetmap-website#3785]
One of the big problems with OSM.org today is its dated design, which is not very flexible for new changes and doesn't take any care with the user experience. OSM is a social platform where you connect with your local community because you believe that a map should be made by the community for the community. 
 The goal is to bring more mordenity to the OSM.org website without losing its personality and simplicity I made some proposed changes in my project submitted for the OSS4SDG 2022 like a new profile and a profile dedicated to communities and organizations active in OSM.

### New user profile

With more information and statics it is easy for you to identify the mapper region and if it is an active mapper.
Bringing a more familiar experience with other social networks, the new OSM profile has enormous potential for those who are looking for new mappers to add to their team.

[![User-1.png](https://i.postimg.cc/7YQrjzf5/User-1.png)](https://postimg.cc/dLdfyLRF)

### organization profile

In the same way that Github has specific pages for organizations, OSM will have it to facilitate who are the organizations that work directly mapping, who participates and where they participate, the intention is to better centralize the information directly on OSM.org without having to search the Wiki .
Today if we are going to see each OSM application has a different way of dividing its teams and monitoring its performance, what I propose is that teams be created directly in OSM and made available via API to other applications.
Another point for organizations is the addition of events directly on the platform so that mappers can discover new training and Mapathonas

[![organizations.png](https://i.postimg.cc/bvxMYSNH/organizations.png)](https://postimg.cc/qt7QjRKz)

### Welcome popup
A way to explain to first-timers what OSM is and how they can get in touch with their local community

[![main-1-1.png](https://i.postimg.cc/DySMJMwz/main-1-1.png)](https://postimg.cc/PPk40KZG)

Currently the development of OSM.org is being maintained by volunteer developers who are doing a great job but since it is a big change it would be important to create a Working Group focused on Design and a full-time dev.

The first step would be to create a design system that can be used on OSM.org to guide independent developers in creating their applications
    
Examples:    
- [GNOME Human Interface Guidelines](https://developer.gnome.org/hig/)   
- [Wikimedia Design Style Guide](https://design.wikimedia.org/style-guide/)   
- [Firefox](https://design.firefox.com/)    
 
## Steps   
- WG Design Creation   
- User Surveys   
- Create a Design System
- Presentation   
- Implementation    
   
Link to project  repo: https://github.com/Playzinho/gaia

**Comment by kauevestena** [comment]
Amazing suggestions!!

**Comment by mmd-osm** [comment]
Linking to an earlier version of this proposal which includes a bit of user feedback: https://www.openstreetmap.org/user/PlayzinhoAgro/diary/397900

**Comment by tomhughes** [comment]
I'm not really clear what is actually being proposed here, or whether this is any way concrete or actionable.

It seems that this overlaps with ongoing microcosms work at least.

Perhaps you could also provide some support for the assertion that "OSM is a social platform where you connect with your local community because you believe that a map should be made by the community for the community" beyond that simply being your personal opinion of what OSM should be?

Maybe you also shouldn't introduce yourself to the maintainers of this repository by proposing to replace them by a paid developer, and without even explaining how you propose to fund that?

**Comment by gendy54** [comment]
Not even a thank you @tomhughes for the work done by @Playzinho? Really?
We don't want that kind of behaviour anymore. This is what kills the goodwill for our project. If we don't move forward, we will die.
The first question that beginners ask us in France is: how do I meet people around me?

**Comment by LaoshuBaby** [comment]
**looks beautiful and modern**, but will it bring more loading time? In those picture I can see many icon assets were used. 

And truly looks more like a social media website, not a map database, so I also understand those more conservative opinion. Let mapper accepting a new profile style is not easy

Another problem is should those calender statistic and heat map offered by OSM official,  or call neis-one.org's API? Those still need to be discussed.

(Besides, do we have organization account verify?)

**Comment by pyrog** [comment]
> how you propose to fund that?

This question is addressed to the OSM Foundation… 😉 
After the Foundation and/or the community have discussed the substantive issue.

**Comment by tomhughes** [comment]
This project is not actually run by the OSM Foundation as strange as that may seem.

**Comment by Playzinho** [comment]
@LaoshuBaby LaoshuBaby I can't tell you if the loading time will change.
The same conservative view has made OSM a pariah and the best kept secret of the bigtechs, who cares to keep OSM as a database only? I don't think even the bigtechs themselves want that.
@tomhughes  is an open proposal to be discussed I am not trying to impose anything but changes can be difficult but we can not stand still in time, OSM is a project made of communities and communities are social organizations.
I don't intend to adopt anything as definitive without finding a direct survey with OSM users so if you look in the steps there are "User Surveys" for that.

**Comment by Playzinho** [comment]
@LaoshuBaby I think you could reuse theneis-one.org implementation and also add the possibility to have a private profile without sharing statistics

**Comment by gravitystorm** [comment]
@Playzinho Thank you for your proposals.

I have a lot of questions that I could ask, but before I do so I want to know whether this is something that you are planning to work on yourself over the long-term? Or was this concept development a project mainly focussed on the Hackathon event that you mentioned?

**Comment by Playzinho** [comment]
@gravitystorm is a project I've been working on for a few months not just for the event as you can see in my OSM diary from October 2021, I intend to continue to take the project long term.
https://www.openstreetmap.org/user/PlayzinhoAgro/diary/397900
I also posted other UI/UX projects in my diary ;)

**Comment by overflorian** [comment]
Thank you for this refreshing design.
Our [Projet du Mois](https://github.com/vdct/ProjetDuMois) (project of the month) team already designed such a user-profile page (for example https://projetdumois.fr/users/overflorian) so I love the idea of having badges.

Nevertheless I feel like we miss a "contact" button on the user page.

Also the heatmap could use some more options such as a time-selection.
I can think of 2 ways:
1. simple buttons "last week / last month / last year / all contributions"
2. a slider

Other topic: the "last edits" is useful but we need, on one way or the other, a link to all edits.

The "mapathon" badge is useful, and the system behind it is potentially huge to develop.

**Comment by pyrog** [comment]
> This project is not actually run by the OSM Foundation as strange as that may seem.

Yes, really strange.
Which organisation is behind openstreetmap.org website ?

**Comment by wzbartczak** [comment]
Amazing Job! I've been wanting to propose something like this myself for a while! Did you do it in Figma?

**Comment by woodpeck** [comment]
I would advise maximum caution with anything that goes in the direction of "gamification" - anything that comes close to leaderboards, badges and so on, for three reasons:

1. Gamification is a proven motivator but it is very difficult to reward behaviour that is actually helpful to OSM, rather than just tweaked to "earn rewards". For example, if you look at the current OSM user pages there will be some users with 10,000 and mre "edits" and others with just 500 - which might well be 500 valuable, well-surveyed changesets reach representing hours of good work, while the 10,000 changesets could be mini-changesets made by a bot that corrected the spelling of a name and added little value to OSM. Introducing badges that actually reward good behaviour rather than just mindless button clicking is a challenge in itself, and a badly designed reward system can hurt much more that it helps.
2. Any form of "I am better than you" status symbols on OSM should be avoided, they will only lead to new people being disheartened by those with higher status.
3. Some people feel treated condescendingly when you give them worthless badges that some developer thought would entice them to work (even) harder. There were quite a few people complaining about the "Congratulations"-Messages they got from the new Discourse forum after engaging in what they felt was everyday activity.

Not saying "don't do it", but it would have to be thought out very well since changes to the reward and status system could  prove difficult once it's running.

**Comment by Playzinho** [comment]
@overflorian I watched your presentation at SOTM22 and I really agree with you, the project of the Month would be a great way to add badges to OSM just like MissingMaps. I apologize but I forgot to put the direct message button. About the heatmap I believe yes we can look at that, maybe with the option to expand the view we can add more options to it.

**Comment by Playzinho** [comment]
@wzbartczak I did not use Figma, prefer to use the https://penpot.app/ that is opensource if you want to help the whole project is published on github https://github.com/Playzinho/gaia

**Comment by Playzinho** [comment]
Yes, I agree that a gamification system should be very well discussed and well elaborated, I think a good example to follow would be the Project of Mouth and Missing Maps and also #30DayMapChallenge. 

It would be interesting to discuss a third profile category for profiles of automatic edits and imports to be ignored in any kind of rank or gamification, an example is that in OSMstats my import profile is in 2nd place and its reversal profile is in 4th.
I also do not agree that gamification should be done using only the number of edits because it is very easy to increase this number, I have a huge number of edits that were only changing an item by using the maproulette with the ID.

> Any form of "I am better than you" status symbols on OSM should be avoided, they will only lead to new people being disheartened by those with higher status.

 This says more about the person than the function, I imagine something closer to the ranking made in HDYC, is a way to recognize the most active and experienced mappers far beyond the numbers edits.

**Comment by wzbartczak** [comment]
> Yes, I agree that a gamification system should be very well discussed and well elaborated, I think a good example to follow would be the Project of Mouth and Missing Maps and also #30DayMapChallenge.

Gamification system is only part of the system. There is no need to start with it.

Your proposal solves a lot of problems that have been talked about for years.

For me, the most needed part of this proposal are the profiles of the organizations and their logos next to the profile. Especially if we change the procedure of organized/coorporate editions. This would be an excellent step towards transparency, not to mention promoting local communities.

**Comment by mmd-osm** [comment]
> It seems that this overlaps with ongoing microcosms work at least.

Agree, I also see quite a bit of overlap here, in particular around the organisation / community profile topic. Microcosm has a stronger focus on community and community events, not so much performance management (I'm not sure, if that concept makes even sense on osm.org?). And then there's lots of overlap with what Pascal Neis is already offering for the new user profile.

I think, in order to avoid duplicating efforts, it would be good to see a bit more collaboration across projects here.

( looping in @openbrian )

**Comment by wzbartczak** [comment]
>  And then there's lots of overlap with what Pascal Neis is already offering for the new user profile.

For me, integration is important. Especially for new users. They don't have to search for information, everything is integrated. We make it easier for newcomers to find their way in the community.

**Comment by gravitystorm** [comment]
> I intend to continue to take the project long term.

Great, that's good to hear.

I'm going to set aside your specific proposals for the moment, and we can come back to them at some point later. First I want to focus on some of the more general points that you have made.

My advice would be to not try to do too many things at once! In your first ever involvement with the project, you proposed:

* Creating a new design system
* Changing the organisational structure
* Creating a new working group
* Hiring a paid developer
* Introducing gamification
* Undertaking user surveys

... and that wasn't even everything! I admire the ambition, but I would recommend that if you want to see tangible progress in a reasonable amount of time, then you will need to focus fewer things, otherwise there's a real risk that these won't happen at all, or that you will see lots of unfocussed discussion and little overall progress and might get discouraged or frustrated.

The second thing that I would encourage is to ask more questions, and make some investigations, before proposing large changes. For example, you say that we should hire a developer full-time to work on design, but would that be the most important thing for our first full time developer to work on? You suggest gamification badges, but have you researched any history of gamification in OpenStreetMap? Have you asked the maintainers about the existing organisational structure, before proposing a new one? Are you aware of what our current design system is, what its limitations are, and why we have chosen it? And so on and so forth. By taking more time to understand the current situations, your proposals (and their likelihood of success) will be greatly improved.

Overall, It's great to have a large goal in mind. But to achieve your "reimagining", we need to break it down into smaller parts. We're all volunteers here so I'm not going to tell you what to do next, the choice is yours. But please let me know if I can help with anything.

**Comment by Playzinho** [comment]
Thanks for the comment @gravitystorm Yes, I understand the conversation is getting a bit noisy here but it's good to hear other ideas, As suggested by [nukeador](https://www.openstreetmap.org/user/nukeador) in the OSM [diario](https://www.openstreetmap.org/user/PlayzinhoAgro/diary/397900) I plan to open a forum thread discussing each step.

I think we should first discuss the creation of a Design System for the OSM ecosystem and then go through the rest calmly as suggested. 

I did some research before and did not find a documentation about the current design process if you can send it I would appreciate it, from what I think it is used only H1,H2,H3 tags and some bootstrap buttons without any personality reminding us of 2000's sites and simple HTML pages

**Comment by Adamant36** [comment]
> And then there's lots of overlap with what Pascal Neis is already offering for the new user profile.

Personally, I'd love to see elements from what Pascal Neis is offering added to the main site. Things like a chart of how many days of the year someone has contributed or a heat map of their edits just seem like obvious, modern improvements to the "My Edits" page. Which really loses it's usefulness after loading more then the first list of edits. 

Even if that wasn't the case though it would still be good to have more fine grained ways for people to get information about their edits when they are logged in. Really, it's kind of weird that people get essentially the same data/interface regardless of if they are logged into their accounts or not. There should really be a more "premium" experience for logged in account holders compared to random visitors of the website. The more personalization the better to. As things currently are the "My Dashboard" page seems really impersonal.  

> Any form of "I am better than you" status symbols on OSM should be avoided, they will only lead to new people being disheartened by those with higher status.

Totally agree with that. People already act like they are better then each other based on the number of edits they have or how long they have had their accounts for. Adding "gamification" would just exacerbate things. At least if it was part of the person's public profile. There's no reason it couldn't be private though. Really, number of edits and account age shouldn't be public information either. 

Making the "gamification" private would probably also negate the issue of people mindlessly clicking for badges. I don't really see people mindlessly making edits on MapRoulette or StreetComplete just to rack up achievements, which I assume is because they aren't shared publicly. 

(As an addendum to that, people do mindlessly edit on MapRoulette for points. Points are a separate thing then badges though and OSM already has a point system going with the number of edits a person has anyway. But either way, 👍 for badges.)

**Comment by raphaelpe** [comment]
Boa Tarde @Playzinho para começar esse projeto quanto custaria ? teria programadores já pronto para começar esse trabalho, como pesquisa, teste e outros.... ou isso seria feito em contato com a fundação OSM ? já que recurso a Fundação deveria ter para iniciar e contratar programadores de tempo integral para começar o projeto...

**Comment by gravitystorm** [comment]
> I think we should first discuss the creation of a Design System for the OSM ecosystem and then go through the rest calmly as suggested.

> I did some research before and did not find a documentation about the current design process if you can send it I would appreciate it, from what I think it is used only H1,H2,H3 tags and some bootstrap buttons without any personality reminding us of 2000's sites and simple HTML pages

There's no specific documentation about the current design process that I can send to you, but I'm happy to discuss our approach. 

For many (10 ish?) years we had a custom set of CSS stylesheets which defined our site design. However, they only had extremely limited responsive capabilities, and few generally reusable design rules, and so a lot of the website was styled on an ad-hoc basis. We introduced Bootstrap in late 2019 and started the long process of refactoring our site to remove the use of custom CSS, adopt Bootstrap and use components and other features from there.

The main principle of our design is to "use Bootstrap defaults wherever possible". In particular, this covers things like using responsive layout grids, spacing between elements, typography, meaning through colour, form layouts and spacing, etc. This principle is because we are a small team, and history shows that we simply do not have the resources to maintain our own bespoke site design. Similar to all of our code (e.g. rubygems, node modules), if we can build on top of someone else's existing work, so much the better. If we are just reinventing the wheel, then we must avoid that. In particular, by using Bootstrap and updating to new versions as they are produced, we have gained improvements like responsive font sizing, without having to design, develop and maintain such features ourselves.

You say that we only use h1, h2, h3 tags and some bootstrap buttons, and I have to strongly disagree. Perhaps it's because Bootstrap is so ubiquitous and familiar that you haven't noticed things like form layouts, tabbed navbars, alerts and other components. But trust me, you would notice if we were not using them and were still making up our own design ourselves!

I don't have a clear idea of what a "design system" would mean to you, in contrast to what we are doing already. In my limited experience "design systems" are mostly used as a way to ensure consistency between multiple designers on very large projects, and given our situation we have little need for such coordination. If you are thinking of a design system being a higher level set of abstractions, like how we could combine multiple Bootstrap components consistently for similar website features, then that sounds like it can be useful. If you mean to coordinate design across multiple different OSM projects in the wider "ecosystem", then that could be challenging. Or if you mean something significantly different, then let's clarify the topic further.

So I hope this gives you some background. Feel free to ask questions or ask me to elaborate on any of these points.

**Comment by Playzinho** [comment]
@gravitystorm Thanks for responding,
So, I think it's important to have OSM's own documentation to allow other designers to help.
The intention is that other apps in the ecosystem have a guide for other devs developing apps for the OSM ecosystem.
If what is being used is bootstrap then I don't see why we should change it, maybe make a copy with modifications that are more representative of our style.
What do you think?
Which icon packs are used?
Do you have a default font?

**Comment by Playzinho** [comment]
thanks @gravitystorm  the bootstrap documentation helped a lot to improve my proposal.
I also noticed that in the folder that has the images there is also the color palette that is outdated and analyzing the colors currently used on the site we have a contrast problem that can affect people with color blindness and other vision conditions. here is the link from MDN for those who want to read more about [(MDN color contrast)](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast).

[![photo-2023-02-09-10-45-59.jpg](https://i.postimg.cc/9FgVBV1d/photo-2023-02-09-10-45-59.jpg)](https://postimg.cc/Vdt3Yxxv)
[![Captura-de-tela-de-2023-02-08-16-09-34.png](https://i.postimg.cc/4dcbWJzm/Captura-de-tela-de-2023-02-08-16-09-34.png)](https://postimg.cc/YGpW9BDH)
[![Captura-de-tela-de-2023-02-08-16-13-11.png](https://i.postimg.cc/J4ZvsLv7/Captura-de-tela-de-2023-02-08-16-13-11.png)](https://postimg.cc/HVWBNfTF)
[![Captura-de-tela-de-2023-02-09-12-06-47.png](https://i.postimg.cc/bvtthmd5/Captura-de-tela-de-2023-02-09-12-06-47.png)](https://postimg.cc/GBb2PJFP)

We also have some UX issues in case the user makes a mistake on his password or login, it's not shown which of the two he made, as well as on the sign up page the same happens, but in the sign up page it could be validated directly without the user having to submit (at least in some fields). 
https://www.checklist.design/flows/submitting-a-form

[![Captura-de-tela-de-2023-02-09-11-07-34.png](https://i.postimg.cc/mD6fyyyb/Captura-de-tela-de-2023-02-09-11-07-34.png)](https://postimg.cc/XGFzVFPh)

so I made some corrections in the color palette and some adjustments in the UI but trying to keep the identity already established in OSM.org, I think this is the first mockup ready to be implemented and fully responsive, I also used the 8pt grid system. 

https://design.penpot.app/#/view/55d48600-1ee8-11ec-9b4d-b2702b3a67d1?page-id=ae6e99f0-489e-11ed-ba98-8351b9a013d4&section=interactions&index=0&share-id=2eb76e7e-3bb3-81ac-8002-06ac11576817

[![login-desktop-1.png](https://i.postimg.cc/mrj0kQdy/login-desktop-1.png)](https://postimg.cc/677H1Gx8)

some things are still missing in the sign up page like illustrations and texts, that's why I didn't adapt it to other screen sizes, sometimes the penpot can break the spacing of the objects.

**Comment by mxdanger** [comment]
Hi @Playzinho that's a cool mockup but I would recommend you also try making your designs with Bootstrap 5. Concept design is nice but creating static test pages with Bootstrap means you can make responsive UI that would behave exactly the same in production. It's even better that way since it allows for easier changes by others and once it gets finalized its easy to commit.

**Comment by Playzinho** [comment]
Yes, I have created a static page for login and copyright page you can try https://playzinho.github.io/gaia/index.html

the repository: https://github.com/Playzinho/gaia

the mockups in penpot: https://github.com/Playzinho/gaia

**Comment by Zaczero** [comment]
@Playzinho Great stuff! Some of your ideas have already been implemented[^1](https://www.openstreetmap.org/user/NorthCrab/diary/404335) in [openstreetmap-ng](https://github.com/Zaczero/openstreetmap-ng) and we look forward for integrating more of your work! We want to keep it familiar looking without too drastic changes so not everything is possible (for now). Keep up the good work friend :+1: It's great to see such passion

**Comment by Playzinho** [comment]
Thanks @Zaczero I'm going to close this discussion and take it to the [openstreetmap-ng](https://github.com/Zaczero/openstreetmap-ng) repo
