### ISSUE TITLE
Remove "The Rails Port" terminology

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/openstreetmap-website#3796]
"The Rails Port" being the very first heading and mentioned other times in the README always confused me. Now thinking about it, I think it's a historical artifact of when the site originally was rewrote in Ruby on Rails from PHP. 

Since the rewrite happened years ago and most contributors nowadays don't even know that there was a different site previous to this one, I think we should remove the terminology and just describe the application on its own and avoid confusion.

**Comment by systemed** [comment]
The site has never been in PHP. It was in Plain Old Ruby before, not Rails.

**Comment by gravitystorm** [comment]
I agree that "The Rails Port" is unhelpful, and it's surprising that the term has stuck around for so long. 

I'm also not super keen on "openstreetmap-website" since it's a bit misleading - it's not just the website that this code controls, but also the API, the database structure behind both of them, etc etc. It would also be nice to have a term for this codebase, which is clearly distinct from the primary deployment of it - like Wikipedia has "Mediawiki", whereas we have "The OpenStreetMap website" and "openstreetmap-website" which are a bit too similar.

I'm open to suggestions for new names for the codebase. I've personally toyed with "openstreetmap-core" as the name for this codebase, but I'm sure there are better suggestions.

In the meantime, I'm happy to remove mentions of "The Rails Port" from the documentation.

**Comment by mmd-osm** [comment]
As an FYI, I'm also unhappy with the name "CGImap", as "CGI" is technically incorrect, and "map" doesn't really describe its current scope.

I think I will rename it to "API accelerator" next year, inspired by [this post](https://news.ycombinator.com/item?id=32484803). So maybe rename "Rails port" to "OSM website & API", and CGImap will then be the accelerator. Works for me.
