### ISSUE TITLE
Avoid using `to_sentence` to create map key entries

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#3816]
In https://github.com/openstreetmap/openstreetmap-website/pull/3731 it was shown that the map key isn't displayed correctly for certain languages.

The underlying cause of the problem is that we are using `.to_sentence` to join individually translated words, which is [unnecessary](https://github.com/openstreetmap/openstreetmap-website/pull/3731#issuecomment-1269667154) and causes this bug.

This issue is here since the original PR was closed, and an alternative PR hasn't yet been created, and we need to ensure that we don't forget about this problem in the meantime.

**Comment by AntonKhorev** [comment]
Some map keys are now assembled from parts. The result looks like this:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/42ac5112-4122-42eb-9010-576093f53e32)

Are there any reasons to do this? Maybe we want to link individual parts to wiki pages like this:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/22ca1925-7c5b-4879-828d-3161816319cf)

But even if we do, we don't have to assemble sentences. We can do something like this:
![image](https://github.com/openstreetmap/openstreetmap-website/assets/4158490/38c4139f-6fc6-4b03-827d-d69b5d3de67f)

What would you like locale entries like this one to be converted to?
```
summit:
  - Summit
  - peak
```

- option A:
  ```
  summit: "Summit"
  peak: "Peak"
  ```

- option B:
  ```
  summit: "Summit and peak"
  ```

This issue [suggests B](https://github.com/openstreetmap/openstreetmap-website/pull/3731#issuecomment-1269667154). I think A is better because they are shared between different map layers where they may get [combined in a different manner](https://github.com/openstreetmap/openstreetmap-website/pull/4371#issuecomment-1827223460).
