### ISSUE TITLE
documentation: add more info about translating

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#3894]
Because not all of the messages on osm.org can be translated on Translatewiki, I suggest to add this information to the documentation.

https://github.com/openstreetmap/openstreetmap-website/blob/master/README.md

```
* Translation is managed by [Translatewiki](https://translatewiki.net/wiki/Translating:OpenStreetMap). Most of the messages can be translated there. However, some translations come from external sources:
   * GraphHopper: https://github.com/graphhopper/graphhopper/blob/master/docs/core/translations.md
   * Time and date format: https://github.com/svenfuchs/rails-i18n
```

**Comment by Vel-12** [comment]
Which section do you want me to add the above text @maro-21?

**Comment by maro-21** [comment]
> Which section do you want me to add the above text @maro-21?

There is "Development" section where you have a line "Translation is managed by ..." - so over there below.

**Comment by mmd-osm** [comment]
I believe this is opening up a can of worms. We have many more places where translations are managed in some different repo, eg. the community index, etc… Including rails platform specifics like svenfuchs/rails-i18n makes this even more a never ending story. 

Rather than proactively trying to keep such a list up to date, translators could raise an issue instead, if they can’t work out where a translation originated from.
