### ISSUE TITLE
Pushing Cursor Coordinates to Clipboard as Soon as Possible

### ISSUE THREAD

**Issue by dusko23** [openstreetmap/openstreetmap-website#3900]
### Problem

I am using OSM to get cursor coordinates in Clipboard. Doing it quite often takes a lot of **time (Clicks)**.

### Description

Here is OSM Process:

- Right Mouse Click On MAP to open Context Menu,
- The option Show address is given,
- Clicking it opens the Right Panel with Search Results,
- Move the Cursor over the lat/long,
- Click it using the Right Mouse button,
- Context Menu opens,
- Click Copy Link Address.

The link is finally in the Clipboard.

It would be great (and probably not too hard to implement) if Copy Link Address is available in the Context menu after the first Right Mouse Button Click

**Comment by tomhughes** [comment]
Interacting with the clipboard from javascript is (deliberately) very hard for security reasons.

**Comment by tomhughes** [comment]
I think it probably is possible to use `navigator.clipboard.writeText` here (for modern browsers that support it) as it would be in response to a user interaction which is the main restriction.

**Comment by dusko23** [comment]
Thanks, Tom for your response.
However, I am referring to the existing osm map webpage.
I am not constructing a new web page based on OSM technology.
Just using [the existing one](https://www.openstreetmap.org/#map=18/52.17802/0.15049).

Please have a look at the document to check if we are on the same page.
[GetCoordinateProtokol.pdf](https://github.com/openstreetmap/openstreetmap-website/files/10449011/GetCoordinateProtokol.pdf)

My suggestion is to add this simple but powerful feature to Context Menu at the OSM end.

**Comment by tomhughes** [comment]
Yes I understand what you wanted. I was adding some notes on the technical difficulties with implementing what you asked for and how we might be able to do it.

**Comment by tomhughes** [comment]
It shouldn't be called "copy link" of course because that is meaningless in the context of the menu - it would have to be "copy coordinates" or something.

**Comment by dusko23** [comment]
Hi Tom, I am just referring to what **already exists** in the OSM map portal.
When I get a link in Clipboard (after several clicks and mouse moves) I parse it to get pure coordinates.
Therefore my suggestion is to just use **the same variable** that is already in place on the OSM map portal.
Just show/create it in the Context menu much earlier. After first Right Mouse Click on the map.
Sure I have nothing against changing First Right Mouse Click Context Menu to **Copy Coordinate** and finding pure LAT/LON in the Clipboard. :-)

**Comment by dusko23** [comment]
Thanks, I understand that. I think I do. Unfortunately, I am not a javascript programmer but c#/vb.net.
I have implemented the Chromium WevView2  component inside the windows form.
Inside I open a normal osm mapping application.

Right Click on the map creates a coordinate variable. Right?
And variable, wherever it is, is remembered (saved).
It appears later in the Left Panel where javascript opens the Context menu.

Is there anything I could do at my end to get coordinates when the map is right-clicked?
No need to be a clipboard. Just a variable. Just not sure how to get access to it.

**Comment by tomhughes** [comment]
So @gravitystorm has raised in his review of #3903 the question of what the use case is for this - how does this help you map?

**Comment by SomeoneElseOSM** [comment]
@dusko23 (unrelated to https://github.com/openstreetmap/openstreetmap-website/pull/3903 but may actually be relevant here) - just to be clear, you do know that you can just download OSM data and create a website that shows it that also has any functionality you want?  It's not like Google where "the only way to get to the data is via an API".

If you'd like help with solving the problem that way I'd suggest asking a question over at the help site or the forum; it wouldn't need any changes to the "mappers' website" openstreetmap.org as all.

**Comment by dusko23** [comment]
Thanks for the suggestion. We already use SHP extracts from Geofabrik.  We have pushed our mapping system a bit further.  It is not always about finding and tuning existing options but reaching the target as efficiently as possible. OSM map coordinate in this case. OSM is a great piece of software, data, attitudes, people, and knowledge. The reason for my suggestion was the idea to provide a similar user experience to Google Maps and Bing Maps. I hope you agree that adding a simple **Copy** option beside the coordinates displayed in the left panel is actually "a piece of cake" and takes just a fraction of the time. However, finding a zillion of reasons why not to implement it is easy too. But it takes a lot of time.

![image](https://user-images.githubusercontent.com/26789352/214807646-bba34800-6306-417d-b44b-89bd4524e85d.png)

**Comment by gravitystorm** [comment]
@dusko23 Thanks for the additional explanation of how your application works, which you provided in the associated pull request. In short, your have an application to show maps to search and rescue personnel, and to achieve this you've created a web component that includes the entire openstreetmap.org website within that application.

I'm happy that this use case (embedding the entire website within a third-party application) is not something that we support, and I'm happy to decline features based on this use-case. Our primary focus is on our community of mapping volunteers, and that is the primary use-case for our site. However, unlike other mapping solutions, we also make available both the underlying map data, and also various map services (like map tiles from the OSMF tile server) available for third-party use. There are various ways that you could achieve the result that you are looking for, such as:

* Use a mapping library within your application, and load map tiles from the OSMF tileservers. See the [OSMF tile usage policy](https://operations.osmfoundation.org/policies/tiles/). You can then implement menus, links etc in your application.
* Create your own website, even just a static page with a Leaflet map, that shows map tiles. You can then add your own context menu, links, or whatever you need, and embed that site within your application. 
* Either of the above, [using tiles from another provider](https://switch2osm.org/providers/)

There's no need to embed the whole openstreetmap.org website in your application and then ask for features to be added to our site to support your application.

(I should note here that I'm not recommending any particular solution to you, since your activities might be prohibited by the [OSMF Terms of Use](https://wiki.osmfoundation.org/wiki/Terms_of_Use) ("Dangerous businesses such as emergency services"))

Despite the fact that I'm not supporting this feature request based on your own use case, it's still worth considering whether the feature is useful enough for volunteer mappers to include it anyway. However, given the responses that I've seen, I'm also happy that there's no significant use case here.

So thank you for your feature request, but based on the above I'm going to decline it.

**Comment by dusko23** [comment]
Hi Andy,
I'm sorry to say that, but you have completely missed my final proposal.
Some of your statements are wrong, irrelevant, or make no sense.
Regards,
Dusan
