### ISSUE TITLE
RTL UI has some reversed features

### ISSUE THREAD

**Issue by yarons** [openstreetmap/openstreetmap-website#3910]
### How to reproduce the issue?

Simply login and switch to any RTL language, you'll see that the search box has overlapping words and that the buttons on the top right are clipped on the wrong side (due to hard coded left/right style arguments).

### Screenshot(s) or anything else?

![image](https://user-images.githubusercontent.com/406826/213380301-561567e5-944f-4cee-a77a-9b73871dcead.png)

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit

### Which browsers are you seeing this problem on?

Firefox

**Comment by biswajit-k** [comment]
I think it can be resolved by adding styles for placeholder for RTL language, @gravitystorm could you please let me know if this is correct? I can work on this.

**Comment by yarons** [comment]
CSS supports such behavior:
https://stackoverflow.com/questions/22511460/css-dir-rtl-vs-style-directionrtl (The resolving answer)

I can try and tinker with the CSS in my browser and take a screenshot of it if it helps.
Thanks!

**Comment by tomhughes** [comment]
It can be fixed yes, my draft fix is to replace https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/stylesheets/common.scss#L29 with:

```css
[dir=rtl] {
  /* no-r2 */ text-align: right;

  ::placeholder {
    /* no-r2 */ text-align: right;
  }
}

[dir=ltr] {
  /* no-r2 */ text-align: left;

  ::placeholder {
    /* no-r2 */ text-align: left;
  }
}
```

That works, though in my (english) browser the cursor winds up at the wrong end but I'm guessing that won't be the case if your browser is configured for an RTL language?

**Comment by biswajit-k** [comment]
For me, it still shows the placeholder text on the left, I think it is because `dir => "auto"` attribute is set on the input field. Also, `dir` set to `auto` always displays placeholder text on the left irrespective of the language. So, I think we should remove the `dir` attribute for the input fields and let the input and placeholder text be left or right-aligned based on the language selected.
I referred below-
[A similar issue](https://github.com/whatwg/html/issues/4903) and [an attempted fix](https://github.com/wikimedia/codex/commit/a25d22fd8d93a18a2259b297ba62e7556c542131)

**Comment by yarons** [comment]
I'm not sure if we can do it but we can use CSS vars but it may solve this issue, we just simply need to avoid the "auto" configuration and set the style for this field instead.
If I'm adding `direction: rtl` to the CSS it looks great, not sure why is doesn't inherit that from the HTML property.
Thanks :)

**Comment by yarons** [comment]
You're absolutely right, usually I'm using `[dir="rtl"]` to make sure it won't affect the LTR variant.
