### ISSUE TITLE
Could not find mini_portile2-2.8.1 in any of the sources

### ISSUE THREAD

**Issue by aryansa** [openstreetmap/openstreetmap-website#4032]
after running project docker-compose I try to pre-compile assets as it's mentioned [here](https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md#production-deployment) but it raises an error :
`Could not find mini_portile2-2.8.1 in any of the sources
`
Something like this `gem 'mini_portile2', '~> 2.8', '>= 2.8.1'` should be added to the gem file.

**Comment by tomhughes** [comment]
It's not something we make use of directly so there should be no need to list it - if something else needs it and isn't requesting it then that is a bug that should be taken up with the gem that uses it.

That said, it is already [listed](https://github.com/openstreetmap/openstreetmap-website/blob/486e87301f16222aa5060b98950cf4df544db23a/Gemfile.lock#L301) in our `Gemfile.lock` because it's a dependency of `nokogiri` so if you have done a `bundle install` and don't have it then your bundler installation is buggy.
