### ISSUE TITLE
Smoothness: inconsistency between old value and new ones proposed by schema

### ISSUE THREAD

**Issue by icegood** [openstreetmap/openstreetmap-website#4072]
### How to reproduce the issue?

1. Open iD editor and choose 'old dirt road' with smoothess field. 
2. Normally value of such filed was 'Thin rollers, Wheels, Offroad...'. And it is not mapped to any newly proposed ones

====
Good idea is once schema is changed,  old values MUST be converted to one of the new ones by default.

**Comment by icegood** [comment]
[smoothness doc](https://wiki.openstreetmap.org/wiki/Key:smoothness)

**Comment by tomhughes** [comment]
As the new issue page for this repository explained issues with iD should be reported at  https://github.com/openstreetmap/iD/issues rather than here as we do not develop iD.

That said in this it seems you want to change the editor presets in which case https://github.com/openstreetmap/id-tagging-schema/issues is probably the best place
