### ISSUE TITLE
High Largest Contentful Paint (LCP) in Google Core web vitals

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/openstreetmap-website#4084]
[Core web vitals](https://web.dev/vitals/#core-web-vitals) are Google's site performance measurement metrics for site performance.

The Core web vitals are used as a ranking factor in Google's results since May 2021.

Since 9th May 2023 Google Search Console reports an increase in the [Largest Contentful Paint (LCP)](https://web.dev/lcp/) for Mobile pages scoring poorly. The increase can also be due to Google changing the thresholds.

Google provide a guide on [optimising LCP](https://web.dev/optimize-lcp/).

Attached are the Google Search Console screenshots:

LCP Mobile details:
<img width="938" alt="Screenshot 2023-07-11 at 16 12 36" src="https://github.com/openstreetmap/openstreetmap-website/assets/248188/18f51d27-888f-4073-8b41-4a1a907fb8cb">

Core Web Vitals details:
<img width="947" alt="Screenshot 2023-07-11 at 16 13 33" src="https://github.com/openstreetmap/openstreetmap-website/assets/248188/879a1ae1-ffd3-42c1-999f-4439d417a7d7">

**Comment by tomhughes** [comment]
Without concrete suggestions this is pretty much useless - it's a complex page so it takes a few seconds to load.

**Comment by tomhughes** [comment]
Frankly this seems like SEO nonsense to me and I'm not interested in pandering to that.

**Comment by gravitystorm** [comment]
I've had a quick look at one of the example URLs in their dashboard, and it's the background tiles that it's complaining about most:

> This is the largest contentful element painted within the viewport. [Learn more about the Largest Contentful Paint element](https://developer.chrome.com/docs/lighthouse/performance/lighthouse-largest-contentful-paint/?utm_source=lighthouse&utm_medium=lr)LCP
Element
div.leaflet-pane > div.leaflet-layer > div.leaflet-tile-container > img.leaflet-tile
<img alt="" src="https://tile.openstreetmap.org/19/283653/182345.png" class="leaflet-tile leaflet-tile-loaded" style="width: 256px; height: 256px; transform: translate3d(1px, 137px, 0px);">

|Phase | % of LCP | Timing|
|---|---|---|
|TTFB|17%| 610 ms |
|Load Delay|72%|2,500 ms|
|Load Time|3%|100 ms|
|Render Delay|8%|290 ms|

The difference between mobile and desktop performance seems to be because they throttle bandwidth and add extra latency to the mobile requests. That means the above figures need to be taken with a pinch of salt, I reckon, since they are probably a mixture of real latencies plus emulated ones.

Overall though, this might be something for the OSMF operations team to have a look at, since map tiles are out of scope here :smile:

The other topic appears to be the large size of our application.js bundle, so maybe that's something we can check on here.

> Frankly this seems like SEO nonsense to me and I'm not interested in pandering to that.

Well, it's an approximation of how people in the real world experience the site, so I'm receptive to warnings about that and suggestions for improvements. 

I'm also (mildly) receptive to maintaining OSM.org ranking in search results, since I don't want us to end up with a "stackoverflow" situation where other copy+paste sites end up ranking higher by simply serving the same content faster than we do. But that's a minor concern.

**Comment by gravitystorm** [comment]
I've gone through the list of recommendations again, to see if there's anything else that applies to this repo. As before, it's mostly about the amount and size of the images, although the amount and size of our CSS and Javascript gets a mention too.

There's some other accessibility stuff mentioned that I've reviewed (see e.g. #4131), but I don't think there's anything else actionable here.
