### ISSUE TITLE
Block mapy.cz as non-approved imagery

### ISSUE THREAD

**Issue by Jakuje** [openstreetmap/openstreetmap-website#4085]
### Problem

Some users in Czechia are using mapy.cz satellite imagery which is not approved for mapping.

### Description

This was originally reported in openstreetmap/iD#9708 but it looks like they do not have a way to fix it on their side and it should be done here.

**Comment by tomhughes** [comment]
We do have the ability to add things to a [block list](https://github.com/openstreetmap/openstreetmap-website/blob/17b18fcb816f26953a05742d2101cef99df87d30/config/settings.yml#L84) but we'd need to know the URL pattern and I'm not sure who usually authorises that - past requests have likely come in from LWG I think (see #2777 and #2779 for examples).

Probably we shouldn't really put them in this repo at all, but instead have no defaults here and have OWG configure the settings OSM wants in the production deployment.

**Comment by Jakuje** [comment]
The url should be anything under `mapy.cz` domain as proposed in openstreetmap/iD#9709

**Comment by zbycz** [comment]
@tomhughes - thanks, it would be of course better to have it configurable in DB instead of config file. Could we perhaps prepare a PR for this still using config file and add new issue which will tackle the move out of config?

btw, the original issue is here: https://github.com/openstreetmap/iD/issues/9708, in OSM db there is more then 1000 violating edits, and the number is rising. We (czech comunity) would be glad if this could be blocked somehow.

**Comment by tomhughes** [comment]
I didn't say configurable in the database - that would be massive overkill..

It's already configurable in the site settings - all I was suggesting was that instead of shipping defaults in this repository we leave the defaults blank and have OWG configure values for the openstreetmap.org instance via chef.

**Comment by tomhughes** [comment]
If you have a thousand dodgy edits you are presumably already talking to DWG about this? They would then normally ask us to block the site if they were concerned.

**Comment by simonpoole** [comment]
@zbycz I would suggest simply making a PR against https://github.com/openstreetmap/openstreetmap-website/blob/master/config/settings.yml#L85 as @tomhughes says there are not enough entries nor do they change often enough to make a more refined solution necessary. In any case I don't quite see why we are already more than 3 weeks in to this (and the problem getting worse) without actual action.

**Comment by tomhughes** [comment]
Resolved by #4093.
