### ISSUE TITLE
"application could not be found" message for most of oauth2 apps

### ISSUE THREAD

**Issue by AntonKhorev** [openstreetmap/openstreetmap-website#4103]
### URL

https://www.openstreetmap.org/oauth2/authorized_applications

### How to reproduce the issue?

- open oauth2 authorizations list https://www.openstreetmap.org/oauth2/authorized_applications
- likely you have some, so you'll see a list of apps, that will include, for example [OpenStreetMap Web Site](https://www.openstreetmap.org/oauth2/applications/100)
- click the link, and you'll get the message "Sorry, that application could not be found."

The only links that are going to work are those for the apps registered by you. What's the point of other links then?

Maybe there shouldn't be links for apps registered from other accounts. Maybe the message should be different, that the app actually exists but you're not allowed to look at its details. Maybe the details should be shown, there aren't any secrets in them (client secret is only shown right after app registration).

**Comment by gravitystorm** [comment]
> Maybe the details should be shown, there aren't any secrets in them (client secret is only shown right after app registration).

In general I think there should be a link, and it should work, but I'm not sure what it needs to show or if anything should be hidden. I think there's a (niche) amount of value in allowing users to have links to specific oauth applications, in case they are discussing the app behaviour, permissions its requested or some reason like that.

At the moment, the controller restricts which applications can be shown in the `:show` method, to be the same as for `:edit` etc. Perhaps this restriction can be removed for `:show`?

**https://github.com/openstreetmap/openstreetmap-website/blob/db8e193d712db007d67ce5f9ea821a1756f425aa/app/controllers/oauth2_applications_controller.rb#L16-L17**

**Comment by tomhughes** [comment]
I don't think there's anything sensitive on that page given we use hashed secrets which are only shown when an application is first created.

The edit and delete buttons should obviously be hidden in that case.

**Comment by tomhughes** [comment]
Thinking about this some more I think the real question is whether it is actually useful for people to have access to that page.

There are basically three ways we could fix this issue:

1. Make the links work, with edit and delete removed
2. Suppress the links for applications the user doesn't own
3. Suppress the links for everybody

I'm inclined to say that should hide the links rather than make them work. Indeed I'm inclined to say we just hide them all for everybody - the normal way for an application owner to manage it is via the applications tab not the authorizations tab.

**Comment by tomhughes** [comment]
Fixed by #4110.
