### ISSUE TITLE
Map controls are inaccessible on short screens

### ISSUE THREAD

**Issue by fgnievinski** [openstreetmap/openstreetmap-website#4121]
### URL

https://openstreetmap.org/#map=17/-30.08792/-51.21842

### How to reproduce the issue?

1. open url above in a smartphone
2. notice the share button is visible 
3. now turn smartphone from portrait to landscape view
4. notice the share button is missing

### Screenshot(s) or anything else?

![Screenshot_20230730-005608](https://github.com/openstreetmap/openstreetmap-website/assets/5018500/23359d70-890c-4e06-b893-721d8a36fd4c)

**Comment by gravitystorm** [comment]
I've changed the title of this issue, since I misunderstood the report. Hopefully it's a bit clearer now.

The problem is that we don't have a good way to handle the map buttons when the vertical size of the screen is too short. The features that appear at the bottom of the map are still anchored to the bottom, and so they are visible, but the buttons on the right (e.g. share button, notes button and query tool button) are off-screen and there's no way to get them to show or to interact with them.

This happens regardless of the orientation and regardless of platform, it's just a function of screen height. So it's not specific to mobiles in landscape orientation - although that's an obvious use-case.
