### ISSUE TITLE
Using URL schemes of google Maps - Libredirect

### ISSUE THREAD

**Issue by IkelAtomig** [openstreetmap/openstreetmap-website#4219]
### Problem

Hello. I am Ikel, One of the members from Team @Libredirect. We redirect from big tech sites to private frontends.

We have OpenStreetmaps on the extension for long time. But OSM has its own URL schemes. We tried to manually scrap it from Gmaps and adapt to OSM but it went more trickier and eventually removed support for it.

### Description

We would like you to follow the URL schemes of google maps, so it is easier for us to integrate and intituitive for the end user. It will also promote OSM more as the URL being same and just changing domain will give privacy mindset makes reach more audience.

**Comment by gravitystorm** [comment]
Hi @IkelAtomig thank you for your feature request. I am going to close this request, because we are unlikely to implement this.

We have very limited resources, and providing url-compatibility to a commercial provider like Google is not something we want to attempt. Our site is not an end-user replacement for Google Maps, it is designed for our mapping community, and them alone.

Google Maps has a huge amount of end-user functionality that we don't offer, including things like StreetView, aerial imagery, terrain layers, traffic, "my maps" and so on. So beyond just positioning the map correctly, showing icon markers or search results, showing route overlays etc, we would need to add support for all of the things we can't offer, even if only to say "sorry we can't convert that url". The extra work for us would again simply not be a priority, and will prevent us from doing things that are more important to our goals.

You have already tried to implement a Google Maps URL -> OpenStreetMap URL conversion, and if you want to do so then that is your choice. But you say it "went more trickier" and it sounds like you simply want us to do the work for you instead!

**Comment by IkelAtomig** [comment]
> it sounds like you simply want us to do the work for you instead!

Kinda true. And asked it cuz most frontends do so. That is why. It is understandable. I hope we could look back on this in future.

Good luck on the project.
