### ISSUE TITLE
Guidelines for Spanish translation

### ISSUE THREAD

**Issue by angoca** [openstreetmap/openstreetmap-website#4238]
I have already verified or translated all entries in https://translatewiki.net. However, I see other Spanish translators arrive and change some entries that affect the entries' structure, which creates an uncomfortable reading.

Let me give you some examples:
* Some sentences are changed from "tu" to "usted." But most of the translations are already with "tu." This makes an incoherent reading and creates a sense of a low-quality project.
* They change to false-friends words. For example, redaction in OSM is to censor, but it is changed to "redacción," which in Spanish means Drafting. This new word completely changes the meaning of the text.

I have already created a set of words to use on the OSM website: https://translatewiki.net/wiki/Translating_talk:OpenStreetMap#Spanish_words, but it seems the translators do not read it. Also, I created a Communities thread to read what people think: https://community.openstreetmap.org/t/spanish-osm-website-translation-mensajes-en-la-pagina-de-osm-deben-tutear-o-ustear/103509

Translations lack a government, creating a revert war.

What is the best way to solve this issue and prevent the website from importing a set of invalid translations?

* Create an entry on this page for the guidelines. Probably, following the guidelines from wiki - https://wiki.openstreetmap.org/wiki/ES:Wikiproyecto_Traducci%C3%B3n_en_espa%C3%B1ol
* Have a group of people review the entries, not everyone.

**Comment by tomhughes** [comment]
This is a question for Translatewiki, not us. We know nothing about how it works or what tools it provides.

**Comment by gravitystorm** [comment]
We currently outsource everything about the content of our translations to Translatewiki. (We are still in charge of certain technical details about making sure the whole site is translatable, and certain other aspects).

This has advantages and disadvantages, of course. The main one is that the team here doesn't have any capacity to manage translators, conflicts between translators, subtleties in each language etc. Another advantage is that translatewiki has a big community of translators since they host multiple projects. This is important since we might otherwise struggle to find volunteers to translate some languages - perhaps less so nowadays as more people get involved in OpenStreetMap itself.

The main disadvantages are just the mirror images of those advantages. We don't have any oversight of the translators, who are entirely self-organising. Even things like using the qqq language for guidance is something we don't have any insight into (but a big thank-you to whoever it is who is adding such guidance). And the other thing is that most of the translators come from a background of cross-project translations (i.e. they translate for all the different projects hosted on translatewiki), so they might have no OSM-specific knowledge to help them with some of the OSM-specific terminology.

The short answer to your problem is a variation on what Tom said - our translators are self-organising, and so any revert wars or similar need to be sorted out among the translators, and with the Translatewiki admins if appropriate. There's nothing we can do to help here, unfortunately.

The long answer is that if there are unsolvable problems with Translatewiki, we could consider other translation platforms, but that in itself would be a lot of work so any changes would have to be carefully planned and also bring significant benefits.

**Comment by tomhughes** [comment]
As far specific issues go trying to get to the bottom of why particular types of mistake are being made may help with finding the best way to try and stop them.

I'm not familiar with Spanish myself but I assume tu vs usted is an informal vs formal thing which is obviously just a project style question and hard to avoid if people aren't going to try and understand the project style before working on it.

The censor vs redacción is obviously a bit weirder. I can only assume that people not familiar with the english word redaction are essentially guessing at the translation based on the textual similarity to redacción?

**Comment by mmd-osm** [comment]
Perhaps @Nikerabbit could share some insights on how to best avoid 'revert wars' on Translatewiki.

**Comment by Nikerabbit** [comment]
I do have a couple of suggestions:

First, to further increase the visibility of your style guide:
* Try adding the words to https://translatewiki.net/wiki/Project:Terminology_gadget
* Mention it in https://translatewiki.net/wiki/Terminology and https://translatewiki.net/wiki/Portal_talk:Es and maybe even on the OSM project main page instead of the talk page

In case someone doesn't follow the style:
* Leave a message to the translator to inform them
* If the user doesn't cooperate after leaving a message, you can leave a message for the admins on https://translatewiki.net/wiki/Support. They can remove translation rights if they are misused.
