### ISSUE TITLE
provide alternate edit experiences for mobile users

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/openstreetmap-website#428]
perhaps the edit button could have a PushpinApp like experience. something like http://yuvi.in/POSM/. 

and for notes, http://osmlab.github.io/osm-note/

**Comment by gravitystorm** [comment]
Thank you for this feature suggestion. It's been a while without anyone developing this into a pull request, and I don't think any of our developers will work on this in the near future either.

In order to help us manage our backlog, I'm closing this issue. If anyone would like to work on this in the future, we can reopen.
