### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [openstreetmap/openstreetmap-website#4453]
### Problem

GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

### Description

It would be nice if the project's code were moved to GitLab or Codeberg.

**Comment by tomhughes** [comment]
There is no "danger" because git is distributed so everybody who has a copy of the repository has a full history and even if github disappears in a puff of smoke we can just push a copy somewhere else - there is already a copy at git.openstreetmap.org to start with.

I have absolutely no interest in political debates and prefer to spend my time on meaningful development than moving things around to meet some arbitrary definition of what is open.

It's not like the public gitlab site is really open anyway as it has a number of non-free extensions and we don't have the time or capacity to run a self-hosted copy of the open source subset.
