### ISSUE TITLE
old user preferences containing "%" break PUT on /api/0.6/user/preferences

### ISSUE THREAD

**Issue by mnalis** [openstreetmap/openstreetmap-website#4467]
### URL

https://www.openstreetmap.org/api/0.6/user/preferences

### How to reproduce the issue?

- find an old user who has lone percent sign (`%`) somewhere in preferences. For [me](https://www.openstreetmap.org/user/Matija%20Nalis), it was some preferences put by [Merkaartor](https://wiki.openstreetmap.org/wiki/Merkaartor) app some number of years ago, in the following format:

 ```
 <preference k="MerkaartorTmsServer003" v="OSM Mapnik;tile.openstreetmap.org;/%1/%2/%3.png;256;0;17"/>
 ```

  (you need to use an old user, as it is impossible to recreate preferences with lone `%` even for testing)

- you do `GET /api/0.6/user/preferences` and read those preferences just fine
- however, when you try to `PUT /api/0.6/user/preferences` them back again (with some or no changes), you get `400 Bad Request` HTTP error (without any more informative `error` header/text (like one might get for trying to e.g. upload duplicate key or other errors).

That is quite unfortunate, at it means (among other things) that people who have used Merkaartor (or other apps which might use `%` in preferences) in the past are (among other things, but as an example) [unable to save overpass-turbo queries to OSM](https://github.com/tyrasd/overpass-turbo/issues/666#issuecomment-1883698962) any more (note that overpass-turbo had another unrelated but there, but fixing it only fixed the issue for some people, not all).

### Screenshot(s) or anything else?

Possible solutions (from more preferred to less preferred)

- Allow lone `%` in the preferences again, as they were allowed in the past (i.e. undo the regression that introduced this change). That would fix this, and likely related issue: https://github.com/openstreetmap/openstreetmap-website/issues/4001. The advantage is that nothing else needs to be changed and everything starts working automagically.
- replace lone `%` (i.e. not followed by 2 hexadecimal characters) in the OSM preferences database by [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding) `%25`, as it seems to be what OSM API expects nowdays (at least the error is gone and preference is uploaded when one does that). The disadvantage is that any app which uses such values need to be informed that they need to parse percent-encoded values now. 
 E.g. example above would become:
 ```
 <preference k="MerkaartorTmsServer003" v="OSM Mapnik;tile.openstreetmap.org;/%251/%252/%253.png;256;0;17"/>
 ```
- delete (after backing up) all keys in preferences database that contain lone `%`. That would at least allow preferences to be changed / saved again and avoid user frustration (but original data would be lost -- hopefully it is only old historical preferences of little value).
- add an explanatory error header/body (e.g. `lone percent-sign is not allowed with key MerkaartorTmsServer003`) as other errors do (e.g. duplicate keys return `Duplicate preferences with key diary.default_language0`)  
- at least [document on the wiki](https://wiki.openstreetmap.org/wiki/API_v0.6#Preferences_of_the_logged-in_user:_GET_/api/0.6/user/preferences) this `%` behaviour (and possible remedy for affected users)

**Comment by mmd-osm** [comment]
I cannot reproduce your issue locally:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/ebd53ac2-56fd-4ff8-b7e3-d369afe5a0f4)

Verifying the previous request:

![image](https://github.com/openstreetmap/openstreetmap-website/assets/5842757/c49a3b75-f3fe-4398-b1c4-3a6181c298a8)

I also checked the exact same requests on https://master.apis.dev.openstreetmap.org/, and it's also working as shown above.

Presumably, you're sending your request with a Content-Type application/x-www-form-urlencoded or something similar, in which case the request fails with HTTP 400.

**Comment by mmd-osm** [comment]
Also, the issue in #4001 is a completely different one. There's a missing "force string to be treated as UTF-8" in the character validation rules.


```
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)

API threw unexpected Encoding::CompatibilityError exception: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
openstreetmap-website/app/validators/characters_validator.rb:6:in `match?'
openstreetmap-website/app/validators/characters_validator.rb:6:in `validate_each'

```

**Comment by gravitystorm** [comment]
> Presumably, you're sending your request with a Content-Type application/x-www-form-urlencoded or something similar, in which case the request fails with HTTP 400.

I was investigating this yesterday, and came to the same conclusion. In fact, it's easily reproduced in our test suite, since the put requests fail with the same 400 response if you add a % character:

```diff
       xml = "<osm><changeset>" \
-            "<tag k='created_by' v='osm test suite checking changesets'/>" \
+            "<tag k='created_by' v='osm test suite checking changesets%'/>" \
             "</changeset></osm>"
```

```
Failure:
Api::ChangesetsControllerTest#test_create [/home/andy/src/openstreetmap-website/test/controllers/api/changesets_controller_test.rb:82]:
Creation of changeset did not return success status
```

```
Started PUT "/api/0.6/changeset/create" for 127.0.0.1 at 2024-01-11 09:52:24 +0000
  
Rack::QueryParser::InvalidParameterError (invalid %-encoding ('created_by' v='osm test suite checking changesets%'/></changeset></osm>))
```

If we add a "Content-Type: application/xml" header to the `put` request in the test suite, then that stops Rack from treating it as url-encoded payload, and correctly treats it as XML.

So the first step is as @mmd-osm explains - the client application should set the correct content-type header, and then it will hopefully work fine.

The second step is to open the discussion about whether we should set a default content-type for the API. This is one of these things were someone has built their client application, and it's worked fine without it, until someone hits an edge case and it breaks. Should we treat all requests to the XML api as application/xml by default, to avoid this from happening? Or should we start throwing errors for incorrect content types, so that developers find this out during testing rather than user reports year(s) later?

**Comment by mmd-osm** [comment]
So in this particular case, overpass turbo is indeed sending a request with Content-Type application/x-www-form-urlencoded, although the code explicitly requested Content-Type text/xml earlier on. I haven't investigated in more detail why this is happening. I'd say the issue would have to be fixed on overpass turbo side.

> Should we treat all requests to the XML api as application/xml by default, to avoid this from happening? Or should we start throwing errors for incorrect content types, so that developers find this out during testing rather than user reports year(s) later?

Throwing errors for unsupported content types sounds like the better approach. I'm a bit worried that such a change might cause too much breakage. Since we're not mentioning the Content-Type header even once on the OSM API 0.6 wiki page, people might use whatever value that happens to work somehow.

An aggregated log with e.g. User-Agent and Content-Type for a given endpoint might be useful to better understand how much of a problem this really is.

**Comment by tyrasd** [comment]
Thanks for looking into this! It was in fact simply a bug in overpass turbo, which is now fixed with https://github.com/tyrasd/overpass-turbo/commit/8db5c4379844908491d8ce7a68c24646134b00d7.  :bow:

**Comment by mnalis** [comment]
Thanks everybody, you are indeed correct -- I was only using `copy as cURL` as produced by overpass-turbo trying to determine why it worked for everybody else but not me, so I was also using incorrect `Content-Type: application/x-www-form-urlencoded`. 

I can confirm that the overpass-turbo fix [above](https://github.com/openstreetmap/openstreetmap-website/issues/4467#issuecomment-1892839847) inspired by your comments works fine and solves overpass-turbo issue, so I'm closing this.
