### ISSUE TITLE
Password Visibility Toggle in Login Page.

### ISSUE THREAD

**Issue by Ri-Sharma** [openstreetmap/openstreetmap-website#4543]
### Problem

In the current login page implementation, users might face difficulty while entering their password due to its hidden nature. This lack of visibility can lead to errors during input. 

### Description

To enhance the user experience and facilitate accurate password entry, I propose the implementation of a password reveal functionality. This feature, commonly denoted by an eye icon, allows users to toggle between obscured and visible password states, providing user with the flexibility to verify their input. This improvement aims to contribute to a smoother login process.

### Screenshots

![image](https://github.com/openstreetmap/openstreetmap-website/assets/80570105/7e2f6790-4a88-4eba-93c0-9c76ef675be8)

**Comment by IshmeetSingh06** [comment]
I can pick this up if it's an actual requirement @gravitystorm

**Comment by sjvudp** [comment]
For me it's not an issue (on the desktop at least), because I use a password manager to either
* paste the password from the clipboard, or
* use "auto-type" to let the password manager fill in the (username and) password field

On the mobile phone with a touchscreen keyboard it might be an issue if typing the password manually, however.
