### ISSUE TITLE
Network location provider at "https://www.googleapis.com/”: ERR CONNECTION TIMED OUT.

### ISSUE THREAD

**Issue by KKJava1** [openstreetmap/openstreetmap-website#4611]
### How to reproduce the issue?

When trying to use the browser's geolocation feature with navigator.geolocation.getCurrentPosition(), I encounter an error message: "Network location provider at 'https://www.googleapis.com/': ERR CONNECTION TIMED OUT." How can I resolve this issue?

### Screenshot(s) or anything else?

<img width="552" alt="33a5c47ec388659a0d57545939c00a7" src="https://github.com/openstreetmap/openstreetmap-website/assets/116629035/a43f94a8-f7db-4dff-87e2-1654611517e0">

**Comment by tomhughes** [comment]
That's a matter to take up with the provider of your browser - we do not make any calls to googleapis.com ourselves we just ask the browser for a location and if it chooses to consult google then that is up to them.

Given that it looks like you may be in China I suspect the real problem is that your browser's attempt to ask Google for location information my be being blocked by the great firewall so it's not something that anybody is going to be able to do anything about.
