### ISSUE TITLE
missing en.javascript translation

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/openstreetmap-website#4618]
From Thursday (March 21) evening:

![OSM_website_missing_translation](https://github.com/openstreetmap/openstreetmap-website/assets/57260466/71045595-2a19-4fc3-8eeb-634949212032)

If the Polish translation is missing, it should display the English one, as it always was. But I see that the Polish translations are there, so something is messed up.

**Comment by AntonKhorev** [comment]
Are there any messages in your javascript console (F12 > console)?

**Comment by mmd-osm** [comment]
Polish translation looks fine over here. Maybe you (or some other tool) have blocked some of the language asset files.

**Comment by tomhughes** [comment]
I agree - as far as I can see https://www.openstreetmap.org/?locale=pl is fine so this must be some client side issue.

**Comment by AntonKhorev** [comment]
The biggest recent change on the js side was Turbo.

**Comment by gravitystorm** [comment]
Another report: https://www.openstreetmap.org/user/Kanoxitu_zh/diary/403741

**Comment by tordans** [comment]
@maro-21 can you check the developer console and network tab to see if anything is red or yellow that might be related. And share your browser and system versions.

**Comment by mmd-osm** [comment]
> Another report: https://www.openstreetmap.org/user/Kanoxitu_zh/diary/403741

It would be good to have a bit more details. The user mentioned that they had to switch to another browser, otherwise the report lacks quite some details.

Maybe @LaoshuBaby could help us a bit with communication, so we would at least be able to find out which browser the user is using, and other things which could help us reproducing the issue. Many thanks in advance.

**Comment by LaoshuBaby** [comment]
> Maybe @LaoshuBaby could help us a bit with communication, so we would at least be able to find out which browser the user is using, and other things which could help us reproducing the issue. Many thanks in advance.

I have encountered this problem from time to time since I registered OSM five or six years ago. The solution is to force refresh the browser, **Ctrl+F5**
Unfortunately, I haven't been able to find a stable reproduction method, and I sometimes encounter similar translation missing in other downstream sites (such as OpenGeofiction). I just encountered this problem once in the past few days.

_Similar problems sometimes occur in the iD editor, but I think it may be different from the technical problems encountered by this rails site._

**Comment by systemed** [comment]
> > Another report: https://www.openstreetmap.org/user/Kanoxitu_zh/diary/403741
> 
> It would be good to have a bit more details. The user mentioned that they had to switch to another browser, otherwise the report lacks quite some details.
> 
> Maybe @LaoshuBaby could help us a bit with communication, so we would at least be able to find out which browser the user is using, and other things which could help us reproducing the issue. Many thanks in advance.

This happens in a couple of old browsers I have around - both Safari 14 and Firefox 78 - while not logged in. A handful of not very illuminating JS errors in the console:

> [Error] SyntaxError: The string did not match the expected pattern.
>	matches (vendors-node_modules_github_file-attachment-element_dist_index_js-node_modules_primer_view-co-3959a9-134c7fee9431.js:1:19860)
> [...]
> [Error] Unhandled Promise Rejection: TypeError: this.parseInputValue().at is not a function. (In 'this.parseInputValue().at(-1)', 'this.parseInputValue().at' is undefined)

Logging in fixes it.

**Comment by dex2000** [comment]
> Logging in fixes it.

not at 
    User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) (Seamonkey/Firefox)

Konsole says:
   jQuery.Deferred exception: Turbo is not defined [...]
