### ISSUE TITLE
Please add option to open website of modeled object

### ISSUE THREAD

**Issue by BertMule** [openstreetmap/openstreetmap-website#4754]
### Description

I often add the website of an organisation/business as a property to the model.
Think of museums, campings, hotels, restaurants, shops, marinas, locks, ...

I only recently discovered in the website one can open various information from a context menu.
Among those not so obvious technical information like surrounding map-objects.

More useful to the average user is the address, if filled in.

But lacking is the ability to open the most obvious and useful property of all: its website.
That usually would provide the most up to date and complete  information, like address, business hours, phone-number, menu, or whatever other information they have put in.

So far I haven't even seen any way of reaching that information, except through an editor!

So please add that to the website.

**Comment by tomhughes** [comment]
The right click menu does not have access to that sort of information because the map you are looking at is just a picture and doesn't have any rich data of that sort.

If you use "query features" which I think is what you are referring to when you talk about technical information about surrounding objects then that will query a different service which does have access to rich data and if you then click on the relevant feature that any web links should be shown in the feature details.

Given that the target audience of the web site is map editors this seems reasonable to me - if our target audience was end users (which it specifically is not) then direct access to web site links might be more important.

**Comment by BertMule** [comment]
I don't agree at ALL.

I regularly use the site for what it is, a map.
And if one can access and display various data in a context menu, that could, and SHOULD, also include basic and useful data like the website.

This would be a simple additional feature.
This discussion takes more than an implementation.

Please reopen this issue..

**Comment by tomhughes** [comment]
Whether you agree is not really relevant - it is the stated policy of the site that it is targeted at map editors and is specifically not intended to provide an end user replacement for the likes of google maps.

We prefer that role to be undertaken by other site and services using our data downstream.

**Comment by Dimitar5555** [comment]
@BertMule [Qwant Maps](https://map.qwant.com) has such functionality.
