### ISSUE TITLE
Improve the text of a mail about comments to a changeset

### ISSUE THREAD

**Issue by deevroman** [openstreetmap/openstreetmap-website#4806]
### Problem

Inspired by [comment](https://t.me/ruosm/816094) in the community chat: 

> It took me 2 months and a block before I found how to reply. I see the comments on the mail, I take note, but how to reply is unclear.

<img width="784" alt="Снимок экрана 2024-05-17 в 10 35 11" src="https://github.com/openstreetmap/openstreetmap-website/assets/25708359/89493797-fc44-4562-bf3e-cd924114cef8">

What if the text "More details about the changeset can be found at %{url}." is replaced with: "Reply or learn more about the changeset at %{url}"?

**Comment by HolgerJeromin** [comment]
The text is defined here:

https://github.com/openstreetmap/openstreetmap-website/blob/41ed1f8e528406c47b6a0afe3b6deef2de34f411/config/locales/en.yml#L1692

**Comment by AntonKhorev** [comment]
Currently it's similar to note notifications that also don't say how to reply.

**Comment by kleenkanteen** [comment]
@HolgerJeromin How does one test sending an email locally?

**Comment by AntonKhorev** [comment]
> Why is the text duplicated on lines 1692-1693 in the file you quoted?

Emails contain both html and plaintext.

**Comment by AntonKhorev** [comment]
> How does one test sending an email locally?

If you want to test the mailer output, see for example https://github.com/openstreetmap/openstreetmap-website/blob/master/test/mailers/user_mailer_test.rb

**Comment by AntonKhorev** [comment]
> Also is there a script that allows one make edits to a text, say for this sentence for example, in all languages using a translation API?

https://github.com/openstreetmap/openstreetmap-website/blob/master/CONTRIBUTING.md#i18n

**Comment by sjvudp** [comment]
Sorry, if this is not exactly on-topic, but:
I frequently get messages about responses to an OSM note (hint). As it lacks the original note, I can only guess from the mail message what it might refer to. To find out, I'll have to follow the link.
Working on a desktop, but reading mail on the mobile (while on the road), I cannot easily reply to the comments I still would have to log in to OSM from the mobile phone (but I don't have the credentials there, because I use a random passwords only my password manager on the desktop can remember.
So it would be nice if the link in the mail message had some magic access token embedded that does not require login, just to respond to a comment.
In general I think having a "worklist" with all the comments that were sent by mail when being logged in to OSM would be very helpful. Switching between the E-Mail browser tab and the OSM browser tab to work on the messages one-by-one is not very efficient (and it is little fun).

**Comment by kleenkanteen** [comment]
@sjvudp Are you asking for these 3 things?:

1. Having the original note as well as the reply in the email.
2. Having a magic access token when clicking on the the email's view changeset link.
3. A easier way to reply to comments on OSM (I am not sure what you mean by this exactly).

Feel free to clarify any

**Comment by sjvudp** [comment]
#1 and #2 are correct.
#3 is when you have something like 30 comments on 25 different notes, and you want to review them all (independently from the email messages received). I agree that this item is not directly related to sending out mail messages. Instead it's about an efficient workflow.

**Comment by tordans** [comment]
Ping also to https://github.com/openstreetmap/openstreetmap-website/issues/4047 which would improve the situation with very little change IMO.

**Comment by tomhughes** [comment]
Fixed in #4812.
