### ISSUE TITLE
API: List IDs of hidden notes

### ISSUE THREAD

**Issue by qugebert** [openstreetmap/openstreetmap-website#4817]
### Problem

Background: Notes can be reported via the web interface, for example, if they contain personal data or are offensive. After review by the moderators (DWG?), they are then hidden.
However, there are also other websites that display these notes and have already saved them in their databases at the time of moderation. An example of such a website is https://resultmaps.neis-one.org/osm-notes.
Notes moderated by the DWG currently continue to be displayed on these websites.

### Description

I would therefore like to suggest that a way be created to generate a list of hidden notes. A list of the note IDs should be sufficient for this purpose. This would allow the operators of external sites to also hide the notes that have been hidden by the DWG after careful review

**Comment by tomhughes** [comment]
Third party sites are generally consuming the notes dump from https://planet.openstreetmap.org/notes/ and you can already kind of tell what has been hidden by the fact that it's no longer present in the dump.

We could add an explicit record of hidden notes to that dump, but that would be a matter for https://github.com/openstreetmap/planet-notes-dump/issues rather than here.

**Comment by qugebert** [comment]
neis-one lists a few hundreds of notes that have been hidden on osm over the last days
