### ISSUE TITLE
The response is /changeset/:id.json endpoint is different for Ruby API and CGImap

### ISSUE THREAD

**Issue by deevroman** [openstreetmap/openstreetmap-website#5047]
### URL

https://api.openstreetmap.org/api/0.6/changeset/70.json

### How to reproduce the issue?

CGImap returns in the response to /changeset/:id.json array of elements with a single element-meta information about changeset

I deployed the OSM API locally without CGImap, and the Ruby implementation immediately returns a changeset object in the response (probably based on the XML response)

----

CGImap also calls the bbox borders differently for the JSON response: minlat vs min_lat. In the case of an XML response, the results are the same.

Is this behavior worth documenting, or is it a bug that can still be fixed?

### Screenshot(s) or anything else?

<table>

<tr>

<td>

<img width="602" src="https://github.com/user-attachments/assets/179067ad-cba1-4796-a450-6bf277f2b05d">

<td>

<img width="587" src="https://github.com/user-attachments/assets/b790f115-34f5-4247-82cd-40902255d212">

</table>

**Comment by mmd-osm** [comment]
Thank you for reporting the issue. I think it's a bug, but I'm undecided if we should change the Rails or CGImap implementation. Usually, we say that Rails is the leading imlementation. However, since we're using the CGImap version in production already, we might have to adjust the Rails version.

Any opinions?

**Comment by deevroman** [comment]
Are there any projects forks osm.org what does the Ruby implementation use in production? I see that OpenHistoricalMap, OpenGeofiction use CGImap

https://api.openhistoricalmap.org/api/0.6/changeset/7.json
https://www.opengeofiction.net/api/0.6/changeset/6.json

It seems that the bug only affects users of the local version of the API, so if you change anything, you need to do it in the Ruby implementation. But you can simply add a warning about this in the documentation

**Comment by gravitystorm** [comment]
I think we need to first decide what we *want* the output to be, and then figure out what is practical. For example, either one of them could be changed to include the output from the other, while retaining backwards compatibility, since the `changeset` and `elements` keys don't conflict. Similarly, the `maxlat` and `max_lat` keys don't conflict, so one of the outputs could contain both, depending on which one we want to standardise on.

**Comment by mmd-osm** [comment]
It seems that both Rapid and iD aren't using the json version of the endpoint (and neither the XML version). TBC by maintainers. 

* https://github.com/openstreetmap/iD/blob/develop/modules/services/osm.js
* https://github.com/facebook/Rapid/blob/main/modules/services/OsmService.js

JOSM doesn't use OSM API JSON endpoints at all, to be knowledge.

I'd prefer not to create a superset version that includes a mix of both variants. I also find the Rails version cleaner.

My proposal would be:
* Check log files for current users the JSON endpoint
* Change Apache redirect and point changeset/{n}.json endpoint to Rails instead
* Change CGImap implementation
* Change Apache config back to CGImap after deployment of new version

**Comment by deevroman** [comment]
Note that at least osmapiR supports receiving data via the json api. Как я вижу не это влияет на поведение по умолчанию, однако влияет на документацию библиотеки (the library is young, so there may not be any users of this method at all)

https://github.com/ropensci/osmapiR/blob/790e35139d8ae1b5c47169d1a0fe4243fa3bc8ab/R/osmapi_changesets.R#L276

**Comment by bhousel** [comment]
> It seems that both Rapid and iD aren't using the json version of the endpoint (and neither the XML version). TBC by maintainers.

I agree, it doesn't look like we are using this endpoint.

**Comment by AntonKhorev** [comment]
It would be surprising if these differences are not documented anywhere. API users have to write code expecting either response, like this:

https://github.com/AntonKhorev/osm-note-viewer/blob/67185792b458d5a1c6a7f886c281b107f02be0be/src/osm/changeset.ts#L61-L69

If you rush to fix the issue by changing one of the implementations, API users would still have to write code expecting either response because they can't force all of the deployed osm-website/cgimap servers to be updated.

**Comment by AntonKhorev** [comment]
@mmd-osm Why do you label this issue as a bug here? If you think there's a bug, the bug is in CGImap. Returning changeset data inside the `elements` array is wring because a changeset is not an osm element. But of course you can't fix this bug without breaking compatibility with everything using that endpoint.

**Comment by mmd-osm** [comment]
Well, it's labeled as a bug because the title says that the two responses are different, which they shouldn't.  

It's clear that we haven't decided yet, how exactly the output should look like (like @gravitystorm mentioned), and where and how we want to fix the bug.  I will for sure open a separate  issue on the CGImap repo, if that's the conclusion of our discussion here.

**Comment by mmd-osm** [comment]
For some reason, the changeset discussions (`/api/0.6/changeset/nnn.json?include_discussion=true`) also differs across implementations. Are we ok with the current Rails JSON format as a baseline?

**Comment by mmd-osm** [comment]
I just merged the updated json format in CGImap, which means it will be ready for testing on the dev instance in the next 10 mins or so. Please do some testing and let me know if there are any issues left.

**Comment by mmd-osm** [comment]
Apparently, there are either no further issues.  The fix will be shipped in next CGImap release. Closing here.

**Comment by pietervdvn** [comment]
I was using this endpoint with MapComplete, and this breaking change caused me quite some troubles!

Luckily, I have error reports and could (manually) salvage all the changes that people wanted to make, so no information got lost.

**Comment by mmd-osm** [comment]
Yes, this was really an exceptional case. As a general recommendation, I would encourage more developers to run unit tests on the dev instance from time to time (maybe once a week or so), to discover issues early on. As you can see in the discussion above (and also the OAuth 2.0 discussion), it's sometimes rather difficult to find out which apps are impacted by a given change.
