### ISSUE TITLE
"Tracestrack Topo" name too long for space given

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/openstreetmap-website#5066]
### Problem

"Tracestrack Topo" doesn't fully fit in the window, here in the Map Layers panel. The second word gets chopped at its waist.

### Description

Everything fits fine on my laptop (Chromebook) screen, except this one item.

### Screenshots

![Screenshot 2024-08-11 19 20 38](https://github.com/user-attachments/assets/a72b848d-c2ba-4b56-9375-660d7a48c5f9)

CTRL++++, CTRL+--- don't help.

**Comment by tomhughes** [comment]
Well the nature of the web is that it's generally impossible to make things fit everywhere all the time.

It definitely fits in a reasonably standard desktop window so are you magnifying fonts or do you have a particularly narrow window or something?

**Comment by tomhughes** [comment]
The only way I can get it to go to two lines is with a window less that 175 pixels wide and even then it isn't cut off because there is space for two lines:

![image](https://github.com/user-attachments/assets/9657ced5-7bee-4653-8d5d-4968bace6d7f)

So I'm guessing you must be using text zoom to increase the font size without changing the size of anything else?

**Comment by jidanni** [comment]
Tom, I don't get notification of your questions to me because you are blocking me.

All I know is I was using a standard Chromebook. I'm glad others have already found the problem.
