### ISSUE TITLE
Implement `geo:` URLs for sharing

### ISSUE THREAD

**Issue by t-8ch** [openstreetmap/openstreetmap-website#799]
It would be nice to be able to directly copy a [Geo URL](https://en.wikipedia.org/wiki/GeoURL) from the share sidebar.

Geo URLs have several advantages:
* Directly handled by a special application as configured by the receiver
* Usable without connection to `osm.org` (No internet connection, or `osm.org` is down)
* Privacy conserving

The Geo URL could also be made clickable to the initial user (the *sharing* one), as they could follow the link and have their favourite application open.
This is for example useful if their favourite routing application has a crappy search function, for which they then could use `osm.org`

**Comment by eighthave** [comment]
I just installed as many Android map apps as I could find, and it looks like they all respond to `geo:`:
![view-geo-in-android](https://cloud.githubusercontent.com/assets/143465/5708552/69bc5634-9a92-11e4-9fb9-4dc825464c91.png)

**Comment by HolgerJeromin** [comment]
So basically we have the android world. Every geo application register them self at the system for geo: and mobile browser calls the correct system call for that. 
I don't know if a similar thing is supported on iOS, but even without that the easy jump from the webpage to an app would be a benefit for many users.

**Comment by mtmail** [comment]
On iOS you can use URLs like maps://?ll=<lat>,<lng> which open in the default maps app. It's more or less undocumented and I can't find official documentation. The official reference lists the long URLs only (which also open the maps app) http://maps.apple.com/?ll=<lat>,<lng>

**Comment by HolgerJeromin** [comment]
Ok, every map application seems to use an own urlscheme on iOS:
The Google maps uses [comgooglemaps://](https://developers.google.com/maps/documentation/ios/urlscheme) and comgooglemaps-x-callback.
Apple maps supports but does not document maps:// and catches [http://maps.apple.com](https://developer.apple.com/library/ios/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html)

The same is valid for Windows Phone on nokia phones. I just checked this. Clicking a geo: url triggers a search in the app store which gives google maps or so. But the installed offline navigation app "here" is not called.
So some desktop environments and all android would be able to use a geo url.

**Comment by eighthave** [comment]
@tomhughes to answer your question about preversing privacy, most map apps share location using an HTTP link, so that leaks the info to anyone who can see the network traffic (anyone on the same wifi, wifi AP owner, ISP, government observer, telecom, etc). Using a link also requires that the user access the network to find the information in the link (especially if it is a non-OSM shortlink).  A `geo:` link does not require network connectivity to work.

**Comment by eighthave** [comment]
Also, since I'm in the process of auditing lots of map apps for Android, I'll mention a couple more I've found that work with `geo:` URIs:

* BaiduMap
* Nokia HERE
* Glympse
* Offline Maps

So it seems basically all Android map apps support `geo:`.

**Comment by erictheise** [comment]
The geo uri in this implementation activates [OsmAnd](http://osmand.net/) on my loaner Android tablet and, somewhat to my surprise, activates [Galileo](https://galileo-app.com/) on my iPhone.

**Comment by simonpoole** [comment]
@erictheise osmand on android: thats because it is either the sole app on the device that has registered itsself for for view intents with a intent-filter that includes geo: (unlikely) or it has been set as the "standard application" for duch intents. In other words check the settings, which should include a way of resetting default applications.

**Comment by erictheise** [comment]
@simonpoole, sorry if I gave the wrong impression. OsmAnd is the only app I installed on this borrowed tablet–it was highlighted in @eighthave's screenshot above–so the behavior is as expected. Less expected, since this discussion has been so Android-focused, was that Galileo would launch on the iPhone. Good news all around.
