### ISSUE TITLE
Mention that it is necessary to visit https://127.0.0.1:8112/ and accept invalid certificate to have a working remote control

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/openstreetmap-website#803]
Remote control from https version of website is not working correctly in FF 28 (JOSM was target of messages).

Commands from http://127.0.0.1:8111/ were working correctly

But from osm website edits attempts were resulting in "Editing failed - make sure JOSM or Merkaartor is loaded and the remote control option is enabled"

To have it working it is necessary to visit https://127.0.0.1:8112/ and accept invalid certificate.

I think that it should be mentioned in warning message (the problem cannot be fixed properly, see  #740).

**Comment by stefanb** [comment]
[Current code only has error message fallback](https://github.com/openstreetmap/openstreetmap-website/blob/e2aef40437767e779f97a7447de69b4540839ff5/app/assets/javascripts/index.js#L211). 
That can be extended to either:
* instead of just using an iframe it can first fallback to open a new tab/window (then possibly close it) with 
 * http (no mixed content problem, as it cannot affect current document) or 
 * https (allows the user to accept the invalid certificate)
* instead of using iframe tag it can use img tag to call remote editors on plain http as that kind of passive (harmless) mixed content is currently still [allowed by all browsers](https://community.qualys.com/blogs/securitylabs/2014/03/19/https-mixed-content-still-the-easiest-way-to-break-ssl). Editors don't have to serve images, but that functionality can also be added to them if needed.
* use ajax to trigger mixed content calls, but that would only work on Chrome
* maybe use [content security policy](https://w3c.github.io/webappsec/specs/content-security-policy/) to allow [mixed content](http://www.w3.org/TR/mixed-content/) (not sure if this is possible. By common sense it shouldn't be allowed, but maybe there are some exceptions or bugs in there)

There is [some initiative, to make localhost an exception](https://bugzilla.mozilla.org/show_bug.cgi?id=9039667), but it isn't getting much attention.

You can [test your browser](https://www.ssllabs.com/ssltest/viewMyClient.html) to see what kind of mixed content it blocks (scroll down on that test page).

I can help with this once we agree on design.

**Comment by richlv** [comment]
for now, asked to mention this in the josm remotecontrol settings page : https://josm.openstreetmap.de/ticket/12230

**Comment by don-vip** [comment]
The mixed contents rules have changed, see https://josm.openstreetmap.de/ticket/10033#comment:38 and https://github.com/openstreetmap/operations/issues/117#issuecomment-352150065
I plan to completely remove support of HTTPS remote control from JOSM on port 8112 to go back to plain HTTP as before on port 8111.

**Comment by tomhughes** [comment]
This is redundant now that #1707 is merged.
