### ISSUE TITLE
Installation instructions should also install btree for osm-test

### ISSUE THREAD

**Issue by math1985** [openstreetmap/openstreetmap-website#878]
In `INSTALL.md`, the section "PostgreSQL Btree-gist Extension" should also be applied to the `osm-test` rather than only `openstreetmap`. Possibly the same holds for "PostgreSQL Functions".

If this is not done, `bundle exec rake test` will fail, see #47.

**Comment by tomhughes** [comment]
See #869 but basically the answer is that sometimes you need to do it to the test database as well and sometimes rails copies that from the main one and nobody knows how it decides which to do.

**Comment by gravitystorm** [comment]
I suspect the difference will be with running "rake db:test:migrate" and "rake db:test:prepare", but that needs investigating.

**Comment by tomhughes** [comment]
I guess it probably doesn't matter in any case, because when it decides to clone the schema from the main database it will effectively drop everything in the test database first anyway. So adding this line to INSTALL.md won't hurt, it just might not always be needed.

**Comment by hopfkons** [comment]
I would also support adding this info to the *Install.md* -- I just spend some time to resolve this issue for me, too. Thanks!

**Comment by tomhughes** [comment]
So having read rather too many rake tasks, and actually tried the instructions out, here's the story...

As given the instruction correctly configure the dev database, and dump it's schema (because migrate does that when it completes) but then then suggest running `rake test` and the problem is that when you do that, with the test database still empty, this is what you see:

```
rake aborted!
ActiveRecord::PendingMigrationError: 

Migrations are pending. To resolve this issue, run:

	bin/rake db:migrate RAILS_ENV=test

...
```
But of course if you actually do what it suggests and migrate the test database then the extra steps like btree_gist and the 3GL functions will be missing from the test database.

In fact the correct thing to do at that point is to run `rake db:test:prepare` to load the schema into the test database, or just `rake test:db` which will reset the database before running the tests.

I suspect that in the past resetting the database before running the tests was the default, but that at some point that changed.
