### ISSUE TITLE
Generate tile set for osm.org with English (or Latin-based) place names

### ISSUE THREAD

**Issue by greatvovan** [openstreetmap/openstreetmap-website#917]
[enhancement]
English street names and city names is higly demanded feature for people who use maps of territories with non-Latin-based local language. Assuming Latin is world most-known alphabet we must have a straihforward ability to view toponyms directly on osm.org, without redirecting to other services and without suggesting to generate "your own tiles" to user.

I suppose osm site should have a switch "Local <—> Latin" to select approprite tile set.

I suggest the following order for resolving place names with multilingual names:
* English (most preferable)
* Deutch
* Spanish
* French
* ...
* the rest European languages with Latin-based alphabet
* ...
* Local name

This will make toponyms at least recognizable for most users worldwide.

**Comment by pnorman** [comment]
This would require multi-lingual rendering and a whole bunch of things outside the scope of the rails port. The switch itself would be in scope, but that's a simple part.

**Comment by greatvovan** [comment]
What is the appropriate project for this proposal?

**Comment by tomhughes** [comment]
Well I'm not sure there is one - generating such a tile set would be a whole new project in itself.

**Comment by greatvovan** [comment]
To make things clear.
Now tiles are generated based on map data and style logic. This is the functionality we already have. What I suggest is just the same but names are taken not from name= but from name:en=, name:de= and so on. It looks like slightly modified copy of existing functionaliy. Is it really so hard to implement?

**Comment by tomhughes** [comment]
Well if you want to change the current map style then https://github.com/gravitystorm/openstreetmap-carto is the place to go, but that's not what you want, because you want to support both.

So now you have two major problems:

* You need to fork openstreetmap-carto and find a way to do location sensitive selection of what names to use (possibly best done at database import time)
* You need somebody to provide the (significant) infrastructure to render and serve these tiles

Neither of those is a problem with the openstreetmap web site frontend code, which is what is in this repository.

The first involves starting a new project to develop and maintain the technology to do the multilingual rendering.

The second involves finding a sugar daddy to provide the infrastructure, or petitioning OSMF to provide the funds for the existing operations team to purchase the necessary extra hardware.

**Comment by greatvovan** [comment]
Thank you for the explaination.
I thought it's not a problem to double up tile set on existing infrastructure because it just size of storage, not an extra load. Now it's clear that rendering itself is also significant load.
