### ISSUE TITLE
Hidden notes still appear to all users (including anonymous ones) in /user/blah/notes list

### ISSUE THREAD

**Issue by SomeoneElseOSM** [openstreetmap/openstreetmap-website#921]
For example, have a look at the notes currently at the end of

http://www.openstreetmap.org/user/SomeoneElse/notes?page=3

specifically http://www.openstreetmap.org/note/323124 and a couple of immediately earlier ones.

It appears in the list as an ordinary note (though if you click on it it'll say "hidden") and the text is visible when you do so.

**Comment by tomhughes** [comment]
I'm not sure this is a bad thing - the goal is to stop spam appearing to user's browsing notes on the map. If you actually go and look at the notes a user has raised is it not reasonable to show that they have just posted a load of spam?

**Comment by danstowell** [comment]
@tomhughes I agree when you're thinking about the user who posted the spam. But if you look at @SomeoneElseOSM 's example, it shows that spam from an *anonymous* user is showing up in SomeoneElse's userpage (because he's moderating it, not because he's posting it), so the argument is a little bit different. On the one hand it's useful to see the trail of his moderation work, but on the other hand it's potentially frustrating to have his moderation work lead to spammy notes piling up on his own userpage!

**Comment by SomeoneElseOSM** [comment]
and also (for completeness) notes that have been hidden appear to anonymous site users in the feeds of users who closed them before they were hidden:

http://www.openstreetmap.org/user/EdLoach/notes?page=1

**Comment by pnorman** [comment]
We use hiding not just for spam, but also for notes which have legal problems which prevent us from showing them, so we need some tool for preventing notes from being viewed by non-moderators.

**Comment by rickmastfan67** [comment]
Thanks for getting this fixed @tomhughes.

One suggestion though.  Instead of "Sorry, #323118 could not be found.", maybe say "Sorry, Note #323118 could not be found."?  I think that would be better.
