### ISSUE TITLE
Subway/metro lines are marked as "Subway Station" in Search and Query

### ISSUE THREAD

**Issue by jc86035** [openstreetmap/openstreetmap-website#934]
See https://www.openstreetmap.org/query?lat=51.50827&lon=-0.12452 and https://www.openstreetmap.org/search?query=Northern%20Line. For some reason what should be marked as "metro lines" or "subway lines" are marked as "subway stations".

**Comment by tomhughes** [comment]
It's no great mystery - that is just the outcome of the heuristics we apply. It's the same basic rules that nominatim uses because we leverage the same strings in the locale file. As I say, they are only heuristics and are unlikely to be 100% accurate, something that is pretty much impossible anyway given we are trying to interpret free form tagging.

I think the main problem is that the heuristics work within a single namespace and don't distinguish between point features and linear features, so there can only be one name for all `railway=subway` features.

**Comment by jc86035** [comment]
I'm not sure what you're talking about, actually. The <a href="https://wiki.openstreetmap.org/wiki/Tag:railway%3Dsubway">page on the wiki</a> says the tag can only be added to ways, and not nodes, areas or relations. I've never seen it used for stations.

**Comment by lonvia** [comment]
Actually looks like an error in the locales [here](https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/en.yml#L762). That should just be "Subway".

**Comment by tomhughes** [comment]
Well I didn't actually look at the wiki (not that the wiki should be taken as authoritative anyway) rather I just guessed that there might be conflicting meaning.
