### ISSUE TITLE
for IE editors, display warning

### ISSUE THREAD

**Issue by mikelmaron** [openstreetmap/openstreetmap-website#941]
Folks are confused by difference between editing in Chrome/Firefox vs IE. Lots of features for HOT editing depend on iD. Perhaps a warning when editing in IE? These folks are unlikely to intentionally be using Potlatch, and likely have Chrome as another option.

**Comment by tomhughes** [comment]
So in order to stop a small number of presumably fairly advanced users who routinely use different browsers getting confused we  present lots of IE users who probably have no choice to use anything else with a big fat warning?

As much as I may hate IE that really doesn't sound like a good trade off, but then it all depends on knowing who our "typical IE user" is and you and I appear to have different visions of that person ;-)

My assumption is that they are likely to either be in a corporate or governmental option whether they have no choice, or a technically unsophisticated home user. Your assumption seems to be that they have Chrome lying around and no how to use it.

The question is, how do we decide which is correct?

**Comment by bhousel** [comment]
Last time I tried, iD worked mostly ok with IE10 and up.  IE9 does not work because of something D3 needs (but could be shimmed if we really cared, I guess). 

Maybe we can just support IE10+ with a little effort and then this issue goes away?

**Comment by tomhughes** [comment]
Oh, last time I asked I was told (by @jfirebaugh most likely) that it still didn't work even in IE11.

If we can make it work in 10 and 11 then that would be great.

**Comment by tomhughes** [comment]
Currently IE is 13.6% of visits but that breaks down as:

* IE11 10.4%
* IE10 0.9%
* IE9 1.1%
* IE8 1.1%

So IE11 is really the most significant issue by far.

**Comment by jfirebaugh** [comment]
> Maybe we can just support IE10+ with a little effort and then this issue goes away?

Famous last works, but: I think so.

**Comment by mikelmaron** [comment]
:muscle:

**Comment by bhousel** [comment]
Hey this can be closed!  🎉
