### ISSUE TITLE
Accessing object info by hovering

### ISSUE THREAD

**Issue by pmailkeey** [openstreetmap/openstreetmap-website#961]
Hi,

It's been suggested I post this here:

Can we have it so that hovering over an object reveals the object type and name - and then if clicked on, opens up full data disclosure like currently selecting ? and clicking on/near an object ?

**Comment by tomhughes** [comment]
You mean over a rendered object in the map view?

**Comment by pmailkeey** [comment]
Yup - where the ? symbol is down the RH side of the screen - as an alternative to using that.

**Comment by tomhughes** [comment]
Don't think that's going to be possible - the load on overpass if we were constantly polling it as people moved around the map would be enormous. Plus at any given times there might be many different things "under the pointer" depending on exactly what your value of "under" is.

That's really why it is built the way it is, so that we can present a list of likely candidates. Early versions did try to use a (manually triggered) popup but it really doesn't work very well in an area with rich, dense data.
