### ISSUE TITLE
Implement optional two-factor authentication

### ISSUE THREAD

**Issue by tommorris** [openstreetmap/openstreetmap-website#979]
There are a wide variety of web services now that allow you to set two-factor authentication on your account. It'd be good to be able to add a [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm) two-factor authentication option for users who wish to protect the security of their account.

**Comment by tomhughes** [comment]
Unless we actually have a volunteer to do the work then I can't see this happening in the near future. I also worry about the extra support load it would inevitably create - we just don't have the resources to build and run such a system.

Yes actually adding TOTP might (I haven't looked into it so I don't know) be easy, but once you have that you also need to build a vastly more sophisticated account recovery system, otherwise you might as well not have it because the account recovery will be far weaker than the actual login. There's a reason other sites won't let you setup two factor until you've setup things like SMS for recovery.

People that want it can already get it anyway, by using an external authentication provider that supports it.
