### ISSUE TITLE
Can't register with ipflood

### ISSUE THREAD

**Issue by misterhat** [openstreetmap/openstreetmap-website#984]
Setting both the X-FORWARDED-FOR and CLIENT-IP at the same time (which [ipFlood](https://addons.mozilla.org/en-US/firefox/addon/ipflood/) does) results in an HTTP 500.

Here is a demonstration with curl:
```
$ curl -I -H "X-FORWARDED-FOR: 235.83.227.142" -H "CLIENT-IP: 253.83.227.142" https://www.openstreetmap.org/user/new?cookie_test=true | head -n1
HTTP/1.1 500 Internal Server Error

$ curl -I -H "CLIENT-IP: 253.83.227.142" https://www.openstreetmap.org/user/new?cookie_test=true | head -n1
HTTP/1.1 200 OK

$ curl -I -H "X-FORWARDED-FOR: 253.83.227.142" https://www.openstreetmap.org/user/new?cookie_test=true | head -n1
HTTP/1.1 200 OK
```

**Comment by tomhughes** [comment]
Sounds excellent to me, but in any case any bug here is in apache or passenger (most likely passenger) and not in our code.

**Comment by misterhat** [comment]
Is there a reason this only occurs on the registration? Any tips on reporting it to passenger?

**Comment by tomhughes** [comment]
Probably because our registration code will attempt to record the IP address - we don't look at any of those headers directly but we ask for the IP of the request which may cause the rack or passenger to do so.

I don't know what you think you're achieving with this ridiculous extension though - no sane site will pay any attention to those headers unless they are ones added by it's own reverse proxies.

**Comment by misterhat** [comment]
You'd be surprised :-P. Thank you.
