### ISSUE TITLE
Faulty links in messages

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#995]
(via a report received by OWG)

The "added you as a friend" messages are formatted so it puts a full stop at the end of links this makes it fail to reach the intended page.

> 제목: [OpenStreetMap] IknowJoseph added you as a friend
> IknowJoseph has added you as a friend on OpenStreetMap.

> You can see their profile at http://www.openstreetmap.org/user/IknowJoseph.

> You can also add them as a friend at http://www.openstreetmap.org/user/IknowJoseph/make_friend.

(In the forwarded email, the links included the final periods, although github appears to be more clever. So this issue is how do we format the emails to reduce the likelihood of the email client misinterpreting them).

**Comment by tomhughes** [comment]
This is really out of our control as there is no way of knowing how a given mail client will decide that the end of a URL has been reached for a plain text message - it's a heuristic operation and every mail client has it's own heuristic, witness what @gravitystorm saw when he pasted it into github.

The only thing we can do is to add an HTML version of that email (it's the only one now that doesn't have one it seems) so that at least clients which choose the HTML version will be able to accurately find the end of the link.

**Comment by danstowell** [comment]
Many email clients understand URLs in chevrons <http://www.like_this.com/>. Easy fix?

**Comment by danstowell** [comment]
(Of course github over-interpreted my example - the URL had been wrapped in < and > )

**Comment by tomhughes** [comment]
Your point may have worked better if github had displayed the "chevrons" by which I assume you meant less than/greater than?

It's true there was once an RFC that suggested that as a means of delimiting URLs in plain text emails, (actually I think it was something like `<URL:http://www.example.com/>`) but it never really caught on. To the extent that it works now it is probably mostly accidental in that an email client is unlikely to consider those valid URL characters so will stop when it hits them.

**Comment by HolgerJeromin** [comment]
always adding a space after a URL is probably not the nicest thing, but could be an easy fix.
