### ISSUE TITLE
Directions, read "to" location in URL (feature request)

### ISSUE THREAD

**Issue by nomoregrapes** [openstreetmap/openstreetmap-website#998]
Currently the directions part of the website reads a "from" field in the URL, e.g.
http://www.openstreetmap.org/directions?from=Durham%20Cathedral%2C%20Durham#map=18/54.77326/-1.57577

It does not seem to notice a "to" field.
It would be great to add such a feature, so that people can provide links for directions to their business or other POI while leaving the start location blank for the user to fill in.

**Comment by M1dgard** [comment]
This seems like a bug to me. I'm not all too familiar with the code, but in /app/views/layouts/_search.html.erb I see
```erb
 <span class="force_width"><%= text_field_tag "route_from", params[:from], :placeholder => t('site.search.from') %></span>
(...)
 <span class="force_width"><%= text_field_tag "route_to" , params[:to] , :placeholder => t('site.search.to') %></span>
```

I don't know Ruby so please don't shoot me, but could it have to do with the space after `params[:to]`?

**Comment by danstowell** [comment]
Oh that's interesting. I only noticed this feature request because of the PR. Meanwhile, I was happily using URLs of the form:

http://openstreetmap.org/directions?route=%3B51.0957%2C-1.2990

This works, but it works by affecting the `route` parameter (which puts from and to into one parameter) rather than `from` or `to`. Also it seems to require explicit co-ordinates rather than search terms.

It seems kinda funny that we have these two parallel schemes. I have no idea if there's a reason for each. But the URL scheme I describe seems to satisfy the motivation for the original request, even though it may be desirable to fix the asymmetry between `from` and `to`.
